HypothesisWorks/hypothesis

hypothesis-python/tests/numpy/test_gen_data.py
The element-already-seen branch for unique arrays seems remarkably stubborn about coverage...  extracted from #2207.
=> Really deflake test this time

hypothesis-python/RELEASE.rst, hypothesis-python/docs/changes.rst, hypothesis-python/src/hypothesis/_strategies.py, hypothesis-python/src/hypothesis/control.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/extra/dpcontracts.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/floats.py, hypothesis-python/src/hypothesis/internal/conjecture/utils.py, hypothesis-python/tests/django/toystore/forms.py
Hej, I was reading docs on the targeted PBT and noticed a typo, so I looked for some more typos as well
=> Fix various typos in docstrings & comments

.flake8, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/_strategies.py, hypothesis-python/src/hypothesis/extra/pandas/impl.py, hypothesis-python/src/hypothesis/extra/pytestplugin.py, hypothesis-python/src/hypothesis/internal/compat.py, hypothesis-python/src/hypothesis/internal/conjecture/datatree.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/floats.py, hypothesis-python/src/hypothesis/searchstrategy/collections.py, hypothesis-python/tests/cover/test_conjecture_test_data.py, hypothesis-python/tests/cover/test_pretty.py, hypothesis-python/tests/cover/test_regex.py, hypothesis-python/tests/cover/test_simple_collections.py, hypothesis-python/tests/nocover/test_flatmap.py, hypothesis-python/tests/nocover/test_pretty_repr.py, hypothesis-python/tests/quality/test_shrink_quality.py, requirements/tools.in, requirements/tools.txt, tooling/src/hypothesistooling/__main__.py
Turns out that the only warning we were using pylint for is covered by flake8's `F811`, if we simply avoid disabling it!
And while simplifying our linter setup, I discovered that we had some indirection in `compat.py` that hasn't been needed since Python 2.6, and decided to get an early start on the great refactoring :smile:
=> Adjust flake8 config and drop pylint

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/errors.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/escalation.py, hypothesis-python/tests/common/debug.py, hypothesis-python/tests/cover/test_find.py, hypothesis-python/tests/cover/test_verbosity.py
As part of repeatedly running the coverage job in order to get it stable, I found a rare failure of coverage in the `find` code. This fixes that by deleting the relevant code and rebuilding `find` on top of `given` like our `minimal` helper is already done.
=> Rebuild find on top of given

hypothesis-python/tests/cover/test_find.py
Whoops. Because the build for #2239 ran before #2235 was merged, this test wasn't caught in the purge of deprecation annotations, so the build on master will now fail. This fixes that.
=> Remove deprecation from find test

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/datatree.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py, hypothesis-python/src/hypothesis/internal/entropy.py, hypothesis-python/tests/common/setup.py, hypothesis-python/tests/cover/test_conjecture_junkdrawer.py, hypothesis-python/tests/cover/test_health_checks.py, hypothesis-python/tests/quality/test_discovery_ability.py
Fixes #2195 (which is closed but shouldn't have been - this was a real issue).
The problem is basically that #2137 introduced a low but non-negligible probability event of generating *much* larger examples than we previously would have. This means for those examples we call `draw_bits` a lot more than we would previously have, and on sufficiently slow computers this would trigger a health check failure. This was impossible to reproduce on fast computers (because the `draw_bits` code was fast enough that it wasn't an issue) or on our CI (because time was fake) but was hitting a lot of users on Travis's rather creaky VM infrastructure on a ~weekly basis.
The solution is to spend some of our initial budget on trying to generate small test cases. This potentially has other advantages, mostly …
=> Bias initial data generation towards small test cases

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/searchstrategy/featureflags.py, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/tests/cover/test_feature_flags.py, hypothesis-python/tests/cover/test_stateful.py, hypothesis-python/tests/cover/test_statistical_events.py
I have marking to do today, which is why I decided to suddenly do a thing I've been meaning to do for years and implement proper swarm testing in Hypothesis. Currently this is only used for stateful testing, because it's the place where it's most obviously a win.
Closes #1637 though we should open some new tickets for actually making use of it more broadly and including it in our public API. I will do that after this has been merged.
=> Implement swarm testing and use it for rule based stateful tests

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/tests/cover/test_validation.py
I discovered by accident that if you use a strategy inside `flatmap` it doesn't ever get validated. This isn't ideal!
Due to the way most of our strategies are defined this *mostly* doesn't matter, but strategies with custom `do_validate` methods would have been missing out.
This fixes the problem my making it impossible and calling `validate()` in every `draw()`. This is cheap because `validate()` remembers its answer and is only run once.
=> Validate strategies before drawing from them

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/tests/common/utils.py, hypothesis-python/tests/cover/test_deadline.py, hypothesis-python/tests/cover/test_explicit_examples.py, hypothesis-python/tests/cover/test_falsifying_example_output.py, hypothesis-python/tests/cover/test_reporting.py, hypothesis-python/tests/cover/test_slippage.py, hypothesis-python/tests/cover/test_stateful.py, hypothesis-python/tests/cover/test_testdecorators.py, hypothesis-python/tests/py3/test_falsifying_example_output.py
This changes our printing logic to use the pretty printing library. This is partially to give nicer output, partially to give us a bit more control over how things are printed as setup for some later features...
While here I noted that the stateful testing library outputs a bunch of garbage from `@given` that is totally irrelevant to the user, and it was easier to fix that behaviour than fix the tests to assert the right things about its format, so I did that too.
=> Improve formatting of Hypothesis example output

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/_settings.py, hypothesis-python/tests/cover/test_settings.py
While messing around with some other things, I noticed that if you accidentally pass something to `@settings` without a keyword, it gets treated as default settings to inherit from.
This results in confusing error messages when that object isn't actually a `settings` instance, and the implementation tries to copy settings from it.
This PR therefore adds an explicit `isinstance` check with a more helpful error message.
=> Explicitly check that @settings(parent) received a settings instance

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/searchstrategy/collections.py, hypothesis-python/tests/cover/test_sampled_from.py
Closes #2247, which in turn dates to #2031.
=> Fix UniqueSampledListStrategy bug

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/tests/numpy/test_argument_validation.py, hypothesis-python/tests/numpy/test_gen_data.py
As proposed in https://github.com/HypothesisWorks/hypothesis/issues/2229#issuecomment-558352718, we now do *another* little dance to get around Numpy's premature (in this case) allocation for strings of length one only.  Closes #2229.
=> Generate longer strings for unsized dtypes

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/tests/numpy/test_argument_validation.py
I, uh, left a `print` in #2245 which slipped through review, and while checking for similar problems noticed that we had a tricky helper that was obseleted by #1963.  This PR removes both.
=> Remove old debug helpers

hypothesis-python/tests/nocover/test_database_usage.py
I haven't tracked down the exact cause of #2251, but this should hopefully get rid of it by making the setup phase of the test deterministic.
Fixes #2251 (fingers crossed).
=> Hopefully make test_respects_max_examples_in_database_usage less flaky

hypothesis-python/tests/cover/test_setup_teardown.py
This test delibearetly fails its assumption with high probability, to test how teardown handles that scenario. Occasionally it fails the assumption so many times that `HealthCheck.filter_too_much` kicks in, causing flaky failures if not suppressed.
Spotted in <https://dev.azure.com/HypothesisWorks/Hypothesis/_build/results?buildId=3077>.
=> Suppress flaky health check in test_still_tears_down_on_failed_assume

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py, hypothesis-python/tests/cover/test_conjecture_engine.py, hypothesis-python/tests/quality/test_poisoned_lists.py, hypothesis-python/tests/quality/test_poisoned_trees.py
This removes a lot of the flexibility from the `ConjectureData` interface and moves the `GenerationParameters` class into the `data` module.
This isn't a particularly important change, but it sets the scene for some things I want to do later and cleans up the code a bit.
=> Internal refactoring for ConjectureData

azure-pipelines.yml, hypothesis-python/tox.ini, tooling/src/hypothesistooling/__main__.py
The latter has been out of support since April: https://www.djangoproject.com/download/
I just know Hypothesis users are keen to upgrade, and get those [sweet, sweet furlongs](https://docs.djangoproject.com/en/dev/releases/3.0/#django-contrib-gis).
=> Start testing in CI with Django 3.0; drop Django 2.0 testing

CONTRIBUTING.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/pytestplugin.py, hypothesis-python/tests/cover/test_reproduce_failure.py, hypothesis-python/tests/pytest/test_checks.py
This replaces #2233 by @NickAnyos - because it turns out that `master` interacts weirdly with 'allow edits from maintainers' - and thus closes #2164, which wasn't an easy issue after all.
=> Warn when other decorators are used without `@given`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py
This is another slimming down of `GenerationParameters`. Slightly alarmingly we can remove it and our tests seem to still pass. I could have sworn it was necessary when I added it but either something has changed since or I was hallucinating that.
=> Remove max_chance and zero_chance from GenerationParameters

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/_settings.py, hypothesis-python/tests/cover/test_stateful.py
@Zac-HD  pointed out in https://github.com/HypothesisWorks/hypothesis/pull/2262#discussion_r355367530 that we were incorrectly validating this setting and that a `0` value was permitted but didn't work. This PR fixes that by making a `0` value an error.
=> Don't allow stateful_step_count to be zero

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/control.py, hypothesis-python/src/hypothesis/statistics.py, hypothesis-python/tests/cover/test_statistical_events.py
This is designed to help with the "threshold problem" where minimal examples can make serious problems look trivial.  If you're running with `--hypothesis-show-statistics` it should help with #2180.
@aarchiba: I *don't* think this solves your UX problem, but I think it's a generally useful thing to make visible - and we can do it much sooner than the ambitious stuff in #2192.  Comments most welcome.
=> Include highest `target` scores of failing tests in statistics

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/tests/cover/test_stateful.py
One of the tests that was failing as a result of #2261 was an erratic failure in stateful tests that was the result of not always running enough steps.
The root cause of this is that even though we set the average size to be the maximum number of steps, our `many` function doesn't really handle that very well and actually generates things quite a lot smaller than that.
This release introduces a new trick, which is to generate the full list of steps with probability tantamount to one but *just* low enough to allow steps to be deleted during shrinking. This should allow all those tests to pass more reliably.
=> By default always run the maximum number of stateful test steps

azure-pipelines.yml
Main things:
* We're not using the Rust code, so it makes no sense to keep running the tests
* There are a bunch of expensive categories of test that it doesn't really make sense to run on every windows build, so this subsets our test to a reasonable set that it's worth testing across multiple OSes.
=> Remove some tasks that take up time on CI 

CONTRIBUTING.rst, RELEASE.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/py3/test_lookup.py
this is a little fix for https://github.com/HypothesisWorks/hypothesis/issues/2272
this is my first pr to the project so please let me know if there's anything i'm missing  in the PR there is or anything you'd like changed.... I've tried to keep with the style as much as possible.
I ended up handling it directly in the `from_typing_type`... was hoping not to but given subclass checks later down the line and the fact that so many container types covered later are virtual subclass of collections.abc.Hashable, or Sized it it seemed like a fools mission.
=> Hashable from type bug

hypothesis-python/RELEASE.rst, hypothesis-python/docs/settings.rst, hypothesis-python/src/hypothesis/_settings.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py, hypothesis-python/tests/cover/test_conjecture_engine.py, hypothesis-python/tests/cover/test_targeting.py
The next thing that is broken by my ongoing total gut of generation: It turns out that generation parameters help with optimisation a *bit*, and the targeting tests go slightly flaky on their removal. This PR pulls out optimisation into its own phase and doubles down on the fact that we're just hill climbing, so spends half of our example budget running hill climbing from the best points we've found so far.
For things where pure hill climbing is a good strategy this will improve our targeting. For things where it's a bad strategy, it will hurt it, but currently we're rubbish at those anyway and we need a better algorithm before we get good at that so I'd rather we reliably succeed at things where hill climbing works
=> Add dedicated phase for targeted testing

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_optimiser.py, hypothesis-python/tests/conjecture/test_test_data.py
Towards the end of #2266 I wrote a bunch of extra tests for the optimiser, only to find out that they failed. Sad face.
The basic problem this solves is that the optimiser hasn't *really* been doing hill climbing so far, in that it hasn't actually had a specific direction to go in, it just kinda bimbled around and hoped to improve the score by randomly perturbing bits. This PR makes a first step towards fixing that by turning it into an actual hill climb. As a result it can now:
1. More reliably find local optima because it's capable of determining what a sensible "direction" is for it to move in and reliably moving in that direction.
2. Making small steps when small steps are necessary rather than just generating random stuff
This is still far from perfect but it's able to do a lot …
=> Improve optimiser algorithm

.travis.yml
We already removed these from azure, and this should speed up our deploys a bit.
=> Remove rust tests from travis

hypothesis-python/RELEASE.rst, hypothesis-python/docs/index.rst, hypothesis-python/docs/packaging.rst, hypothesis-python/setup.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py, hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py, hypothesis-python/src/hypothesis/internal/conjecture/pareto.py, hypothesis-python/tests/common/utils.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_pareto.py, hypothesis-python/tests/cover/test_phases.py, hypothesis-python/tests/py3/test_lookup.py, hypothesis-python/tests/pytest/test_parametrized_db_keys.py, requirements/test.in, requirements/test.txt, requirements/tools.in, requirements/tools.txt, tooling/setup.py
This adds a data structure that lets us track an approximate pareto front. It doesn't do much with this at present - just stores it in the example database - but this lays the groundwork for potential other future work that makes better use of it.
=> Track the pareto front in the example database

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/py3/test_lookup.py
This bug turned out to be surprisingly subtle: it turns on the fact that `typing.ByteString` has a registered strategy (namely `st.binary()`), is a subclass of `typing.Sequence`, but is *not* a generic type.
The solution is an inelegant hack, like everything else in the ~~`typing` module~~ `from_type` backend, but has the considerable advantage of working.
We still consider `bytes` to be a subclass of `Sequence[int]` though, or any `Sequence[Union[int, ...]]` - it wouldn't do to let people relax *too* much :grin: 
Fixes #2257, cc @mvaled
=> Fix from_type bytestring/sequence issues

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/pareto.py, hypothesis-python/tests/conjecture/test_pareto.py, hypothesis-python/tests/conjecture/test_test_data.py
This gives `ConjectureData` and `ConjectureResult` a notion of *tags* - binary labels which distinguish them in some way. A test case only pareto dominates another if it has a superset of its tags. Functionally, tags are "just" targeting scores that only take the values 0 or 1, but they're worth treating separately because this allows for a more efficient and natural implementation.
In this PR the only tags introduced are structural coverage ones, which indicate that a particular strategy has drawn a non-discarded result.
Currently this isn't *very* useful, and is mostly a set up for two pieces of future work:
1. Once we start doing pareto optimisation, having tags should help us find more interesting corners of the search space.
2. tags are the natural hook point for getting back to to …
=> Add notion of "tagging" to test cases and use it in pareto front calculations

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py, hypothesis-python/tests/conjecture/test_test_data.py, hypothesis-python/tests/cover/test_feature_flags.py, hypothesis-python/tests/cover/test_targeting.py, hypothesis-python/tests/quality/test_discovery_ability.py, hypothesis-python/tests/quality/test_shrink_quality.py
I'm trying to slim down `GenerationParameters` a bit because it's rather too mysterious in operation (despite being an improvement on what came before!), so I wanted to get rid of the `alphabet` code. This caused a small number of tests to fail, more or less as expected.
The only major benefit of the alphabet code is that it helps us generate duplicates. So this PR adds a smol mutation step to generation that introduces duplication. This works *better* than the alphabet for creating duplicates because it also works for larger examples.
This did cause one test to fail which I just deleted, which was that it was possible to have all feature flags disabled. I thought about fixing that, and then I asked myself why that was a thing that we actually ever wanted to be possible, so I just deleted …
=> Improve ability to generate duplicated values

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/_settings.py, hypothesis-python/tests/cover/test_settings.py
And encourage use of the stdlib `warnings` module (and command line flags, and env vars, etc.) to control warnings.  This is extracted from #2282 and aimed at preparing any users it will affect, as well as generally refactoring for simplicity.
=> Emit deprecations in quiet mode

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py, hypothesis-python/tests/conjecture/test_optimiser.py, hypothesis-python/tests/cover/test_targeting.py, hypothesis-python/tests/nocover/test_targeting.py
Fixes #2286. In fact fixes #2286 *so* hard that it revealed a bug in the existing code, which is that if you have a test which will fail for sufficiently large targets and the target score is unbounded, you'll get caught in a (technically not, but practically) infinite loop as the optimiser tries to drive the score to infininity - this will not happen if you don't have any interesting examples because you'll hit `max_examples`. We fix this by bounding the amount of improvement the optimiser is allowed to make on any given run.
Basic idea of this patch: Rather than trying to run the optimiser at the example level, we run it at the block level, and patch up any examples we screw up thereby. We use `find_integer` to scale it up and down in an efficient manner, and we allow a certain amount …
=> More improvements to optimiser algorithm

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/tests/conjecture/test_test_data.py, hypothesis-python/tests/cover/test_statistical_events.py
We have a heuristic in `ConjectureData` which turns long sequences of discards into invalid test cases. This PR removes that heuristic.
This heuristic was introduced in #2030 as a workaround to performance problems. Since #2185 we no longer hit those performance problems because we mark parts of the tree with discards in them as not worth exploring, and `generate_novel_prefix` will steer us clear of there. This is a better solution: We don't artificially make some discards invalid, but we don't spend ages trying to draw many equivalent tests.
Meanwhile, leaving it in is a bit of a footgun - I lost about 20 minutes earlier to debugging something that turned out to be the result of triggering this (and in that case I was perfectly fine with long series of discards).
=> Remove consecutive discards heuristic

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
This fixes two small bugs in `pass_to_descendant`: One which could cause it to try shrinks that weren't actually to descendants if the example picked was a block and so had no descendants (which is wrong, though harmless), and another which could pick descendants of the same length (which is useless).
=> Fix boundary condition error in pass_to_descendant

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/py3/test_lookup.py, hypothesis-python/tox.ini
this adds improvements for the ``SupportsOp`` protocols from the typing library when used with `from_type` as discussed in  https://github.com/HypothesisWorks/hypothesis/issues/2292.
=> Better from type supports op

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/cover/test_lookup.py
Currently, `from_type(datetime.tzinfo)` *may or may not work*, depending on whether you have `pytz` installed.  This kinda sucks, not least for people who don't want to use `pytz` but have it installed as a dependency of something else.
[`datetime.timezone`](https://docs.python.org/3/library/datetime.html#timezone-objects) to the rescue!  This is a standard-library type since Python 3.2, so it's always available and plays well with third-party libraries.  And registering a strategy is all we need to do for `from_type()` to work as expected for both `timezone` and its parent class `tzinfo`!
Note that the UTC offset is only required to be a whole number of minutes on Python <= 3.6, but I've left it that way for everything - `from_type()` gives *simple and valid* examples, not the full range …
=> Improve `from_type(datetime.tzinfo)`

CONTRIBUTING.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/escalation.py, hypothesis-python/tests/cover/test_escalation.py
This function used to incorrectly return `True` for files belonging to modules of the form `hypothesis{suffix}`. It now returns `False` for such files.
=> Fix is_hypothesis_file internal function

.readthedocs.yml, guides/api-style.rst, hypothesis-python/.coveragerc, hypothesis-python/RELEASE.rst, hypothesis-python/docs/changes.rst, hypothesis-python/src/hypothesis/_settings.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/extra/django/_fields.py, hypothesis-python/src/hypothesis/extra/pandas/impl.py, hypothesis-python/src/hypothesis/internal/escalation.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/regex.py, hypothesis-python/src/hypothesis/utils/conventions.py, hypothesis-python/tests/cover/test_escalation.py, tooling/src/hypothesistooling/__main__.py
The common thread here is that these small refactorings didn't fit into the big changes from #2218... and since there's no user-visible change I haven't tried to split them out further.
Also fixes #2318 and fixes #2319.
=> Minor cleanups to docs formatting, coverage pragmas, and release automation

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/tests/numpy/test_gen_data.py
Another small but pleasant\* feature that is much easier now that we're Python-3-only :grin: 
\*assuming you want to find bugs, of course
Replaces #2246.
=> Generate non-UTF-8 strings for Numpy unicode datatype

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/tests/numpy/test_gen_data.py
Because https://github.com/numpy/numpy/issues/15363.
=> Roll back 5.2.0 (numpy unicode fun) for now

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/django/_fields.py, hypothesis-python/src/hypothesis/provisional.py, hypothesis-python/src/hypothesis/strategies/__init__.py, hypothesis-python/src/hypothesis/strategies/_internal/ipaddress.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/cover/test_direct_strategies.py, hypothesis-python/tests/cover/test_provisional_strategies.py, hypothesis-python/tests/cover/test_type_lookup.py
Now that Hypothesis is Python-3-only (:tada:), there are some useful things we can rely on having available - like [the `ipaddress` module](https://docs.python.org/3/library/ipaddress.html)!  This patch:
- Adds a strategy `ip_addresses(*, v=None, network=None)`.  `v` may be either `4` or `6`; `network` may be an `IPv4Network` or `IPv6Network` object (or string - the ergonomics justify handling the cast internally).
- Deprecates `hypothesis.provisional.ip{4,6}_addr_strings()` in favor of `ip_addresses(v=...).map(str)`
- Registers strategies for `IPv{4,6}{Address,Network,Interface}` by entering them in the `_global_type_lookup` mapping in `hypothesis.strategies._internal.types`
Closes #2306.
=> New core strategies for IP addresses

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/collections.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, requirements/coverage.txt, requirements/test.in, requirements/test.txt, requirements/tools.txt
My experiments with making strategies hashable - to upgrade the de-duplication in `one_of` from avoiding unrolling recursive strategies forever to actual de-duplication - both concluded that while this was probably possible, it wasn't worth the effort.
This PR adds a comment to the source explaining what's happening and why, for the benefit of future investigators, along with some minor cleanups I made along the way which seemed worth keeping.
Closes #2327 (as wontfix).
=> Tiny internal refactorings

hypothesis-python/RELEASE.rst, hypothesis-python/setup.py, hypothesis-python/src/hypothesis/_error_if_old.py, hypothesis-python/src/hypothesis/extra/django/_fields.py, hypothesis-python/src/hypothesis/internal/compat.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py
This is designed to prevent problems like #2318 - in #2315 I tried to to add a CI job for Python 3.5.1, but it turns out that `tox` doesn't support patch versions... and so I thought the best option was to explicitly drop 3.5.0 and 3.5.1 and get ahead of the cleanups.
We're not the only project to be thinking about this: e.g. there's https://github.com/pytest-dev/pytest/pull/6470, https://github.com/python-trio/trio/issues/880, and https://github.com/python/mypy/issues/7420.  Ubuntu has shipped Python >= 3.5.2 since their 16.04.05, and [PyPI stats](https://pypistats.org/packages/hypothesis) show low 3.5 usage (much lower than 2.7), of which we think only a small portion will be affected.
=> Block install on Python < 3.5.2

azure-pipelines.yml, hypothesis-python/tox.ini, tooling/src/hypothesistooling/__main__.py
[Pandas 1.0 has just been released](https://pandas.pydata.org/pandas-docs/version/1.0.0/whatsnew/v1.0.0.html), so this PR adds it to our CI.
=> Test against Pandas 1.0

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/lazy.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/tests/cover/test_lookup.py, hypothesis-python/tests/cover/test_one_of.py
So that `repr(from_type(int))` == `integers()`, rather than `from_type(int)` - the latter is *correct*, but it's not particularly helpful!
=> Improve repr of `from_type(...)` strategies

.flake8, guides/api-style.rst, hypothesis-python/RELEASE.rst, hypothesis-python/docs/conf.py, hypothesis-python/src/hypothesis/control.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/extra/lark.py, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/src/hypothesis/extra/pandas/impl.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/provisional.py, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/src/hypothesis/strategies/__init__.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/ipaddress.py, hypothesis-python/tests/cover/test_core.py, hypothesis-python/tests/cover/test_functions.py, hypothesis-python/tests/cover/test_lookup.py, hypothesis-python/tests/cover/test_numerics.py, hypothesis-python/tests/cover/test_reflection.py, hypothesis-python/tests/cover/test_runner_strategy.py, hypothesis-python/tests/cover/test_stateful.py, hypothesis-python/tests/cover/test_targeting.py, hypothesis-python/tests/cover/test_type_lookup.py, hypothesis-python/tests/nocover/test_argument_validation.py, hypothesis-python/tests/numpy/test_fill_values.py, hypothesis-python/tests/numpy/test_gen_data.py
Keyword-only arguments are great, because - assuming you have sensible names - they make complicated function signatures readable at the call site *without* needing to check the definition for e.g. the order of all the boolean flags.  This PR:
- Converts all arguments with default values into keyword-only arguments, with only a few exceptions
- `min_value` and `max_value`, because call sites are still clear with positional arguments.
- `alphabet` in `st.text()`, `subdtype_strategy` in the Numpy extra, and `columns` in the Pandas extra.  The first argument in these cases has a clear interpretation, so positional is fine.
- `extra.pandas.range_indices()`, where min_size and max_size are obvious even by position
- Adds the `@deprecated_posargs` decorator, which inserts a …
=> Migrate to keyword-only arguments

hypothesis-python/RELEASE.rst, hypothesis-python/docs/numpy.rst, hypothesis-python/src/hypothesis/_settings.py, hypothesis-python/src/hypothesis/database.py, hypothesis-python/src/hypothesis/vendor/pretty.py
A rollup of tiny fixes I've spotted lately; the "big one" is either a one-line docs change for Pandas compat, or using the Python 3 syntax for metaclasses in the places remaining after #2332.
So this should be very easy to review!
=> Misc little cleanups

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/engine.py
This quick-fix eliminates a big chunk of the performance loss that was reported in #2308.
The mutator loop was previously recalculating `groups` for each iteration, even when nothing had changed since the previous iteration. These redundant calculations took up a surprisingly large percentage of the increased runtime since 4.51.0, so avoiding them is quite helpful.
---
I have some more ambitious/vague ideas about how to speed up the mutator, but for now this is a quick and easy win.
=> Don't recreate example groups for mutation, except when necessary

.readthedocs.yml, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py
Using real positional-only parameters is sadly out of scope at least for now, but assigning to `__signature__` for the benefit of docs is easy!
=> Patch `builds()` signature on py38 for pos-only `target` in docs

.readthedocs.yml
#2345 failed because of readthedocs/readthedocs.org#6324; I've subscribed to the relevant issues.
Once their Python 3.8 image is out of beta, we'll revert this and get the signature we want in our docs (without #1104 problems) at last!
=> Python 3.8 not yet available on readthedocs

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/tests/numpy/test_argument_validation.py, hypothesis-python/tests/numpy/test_gen_data.py
Closes #2351. 
Contrary to my suggestion in that issue, I didn't add any validation logic to `from_dtype()` - generating scalars with varied units is at least potentially useful.  Improving `arrays()` so that we no longer infer such inconsistent strategies, and give a better error message if one is explicitly passed, is IMO sufficient.
=> Handle `datetime64`, `timedelta64` dtypes without time units

.readthedocs.yml
So we can revert #2355 and get the signature improvement I wanted from #2345 :grin: 
To verify that's it's *actually* working this time, you can view a working readthedocs [build log here](https://readthedocs.org/projects/hypothesis-test-zhd/builds/10466332/) and [resulting signature here](https://hypothesis-test-zhd.readthedocs.io/en/readthedocs-config/data.html#hypothesis.strategies.builds)!
=> Python 3.8 is now available on readthedocs

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/tests/cover/test_stateful.py
This PR finalises the removal of `GenericStateMachine`, and inlines various pieces of the rule-based implementation directly into `run_state_machine_as_test` to remove needless indirection.  As the last significant refactoring after dropping Py2 / releasing Hypothesis 5, this closes #2218.
Vive l'hypothèse nouvelle!
=> Refactoring stateful testing: rule-based all the way down

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/pytestplugin.py, hypothesis-python/tests/cover/test_mock.py, hypothesis-python/tests/pytest/test_fixtures.py
Closes #377 by automating our response of "don't do that then".
Skips the warning for `autouse=True` fixtures purely because it's usually much more difficult to fix those.  For example [you can have fixtures skip tests with a mark](https://stackoverflow.com/a/38763328/9297601) (and all `@given()` tests are marked `hypothesis` by our plugin), but this wouldn't support our own time-mocking system which inherits function-scoped-ness from `monkeypatch` and *should* apply to `@given()` tests.
So I'd call this two parts education, one part enforcement of good practice, and one part pragmatic non-enforcement.
=> Warn on `@given` + function-scoped fixtures

.travis.yml, azure-pipelines.yml, build.sh, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/django/_impl.py, hypothesis-python/tests/django/toystore/models.py, hypothesis-python/tests/django/toystore/test_given_models.py
Well, as much as possible before Python 3.8 anyway.  Closes #2369.
=> Give `from_model` a positional-only argument

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/tests/numpy/test_gen_data.py
This PR closes #2275, where I noted that
> when reading [the SciPy docs on structured arrays](https://docs.scipy.org/doc/numpy/user/basics.rec.html#field-titles), I discovered that array dtypes / record dtypes / structured dtypes (we should probably mention those other terms in the docs...) can have a *title* as well as a field name.  This title is *also included in the `.fields` attribute*, which I doubt much existing code is prepared to handle.  We should generate fields with titles.
Fortunately Numpy explicitly rejects titles which are also field names, but I expect this to expose latent bugs even so - there's a lot of code that doesn't handle field titles at all.
=> Allow `array_dtypes()` to generate titles, as well as names, for fields

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/pytestplugin.py, hypothesis-python/tests/pytest/test_fixtures.py
(where the original fixture was function-scope)
Solves the build issues in https://github.com/pytest-dev/pytest-asyncio/pull/148
=> Added support and unittest for overridden fixtures, solving #2375.

hypothesis-python/RELEASE.rst, hypothesis-python/docs/details.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/tests/cover/test_fuzz_one_input.py
For integration with `pythonfuzz`, or `python-afl`, or the `fuzzbuzz` service, etc.  
This isn't perfect, but the ergonomics of "just run your test suite to reproduce, minimise, and deduplicate everything" are fantastic.  And of course there's the advantage of already having tens or thousands of targets available which check meaningful properties beyond "does it crash"!
Closes #171 and closes #2374.
=> Add `fuzz_one_input` attribute

azure-pipelines.yml, hypothesis-python/setup.py, hypothesis-python/tox.ini, tooling/src/hypothesistooling/__main__.py
Because it's end-of-life upstream, per our policy we no longer support it either.  Since I can't see any compatibility code in our implementation, this is a test-only change.
=> Stop testing against EOL Django 1.11

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/__init__.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/datetime.py, hypothesis-python/tests/cover/test_lookup.py, hypothesis-python/tests/datetime/test_dateutil_timezones.py, hypothesis-python/tests/datetime/test_pytz_timezones.py
This PR contains some preliminary refactoring for #2273, which will be much easier to review separately and is still worth merging on it's own.  Best to review commit-by-commit:
- New tests to check that we respect naive bounds correctly.  These aren't related to the other changes here, but we don't actually have any tests for this important property yet!
- Move `dates()`, `times()`, `datetimes()`, and `timedeltas()` to the `strategies._internal.datetime` module.  No actual change here, they just don't belong in `strategies._internal.core`.
- Small change to `DateStrategy` to match the shrinking behaviour of `DatetimeStrategy`.
=> Refactoring for date and time strategies

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py
My profiling of #2308 found that Hypothesis currently spends a lot of time generating the example groupings that the mutator uses to insert duplicate values.
I found that by switching to a dedicated `@calculated_example_property` implementation, I could speed up those calculations by a decent amount.
In my informal testing, this cuts about 10 seconds out of a 50 second test run, which is a nice improvement.
=> Speed up calculation of example groups used by the mutator

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/compat.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/nocover/test_build_signature.py
I had hoped that https://github.com/samuelcolvin/pydantic/pull/1034 would be sufficient for Hypothesis to infer strategies for Pydantic models (meaning, among other things, the whole FastAPI ecosystem).  However https://github.com/timothycrosley/hypothesis-auto/issues/10#issuecomment-612015106 suggests otherwise, and so this PR disables our inspect-`__init__`-for-classes logic when the class has an explicit `__signature__` attribute.
@HypothesisWorks/hypothesis-python-contributors if you have review bandwidth I'd like to get this one merged soon, so that it's out when the (overdue? https://github.com/samuelcolvin/pydantic/issues/1341) release of Pydantic 1.5 happens :slightly_smiling_face:
=> Inspect `__signature__` attribute of classes in `builds()`

README.rst, hypothesis-python/README.rst, hypothesis-python/docs/index.rst
Hello! I'm having a look through the Hypothesis documentation files to think about ways to make them friendlier.
I've made a list of things I'd like to fix (some of which I already have). If you can think of any other things you've been meaning to bring up in the documentation feel free to mention it and I'm happy to have a look :grinning: 
- hypothesis-python/README.rst:
Cheers
Caitlin
=> Changes to documentation files to make them friendlier

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/pareto.py, hypothesis-python/tests/cover/test_targeting.py
Fixes #2395 
Because our pareto front data structure is only approximate, we could (rarely) hit an infinite loop when we do pareto optimisation but it fails to evict the original target even though the target is (either as a result of optimisation or always was) dominated. The result was that we would pareto optimise a test case, then we would loop back and try again and again with the same initial test case.
This PR fixes this by:
1. Adding an assertion that would have caught this problem.
2. Explicitly evicting the original test case when this would happen.
This is surprisingly hard to trigger reliably, so I've not added dedicated tests for it beyond the regression test.
=> Fix infinite loop in pareto optimisation

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/pareto.py, hypothesis-python/tests/conjecture/test_pareto.py
While I was in the area I thought I'd also fix the other pareto optimisation issue that @Zalathar and I discussed in #2395. 
We currently deliberately don't run pareto optimisation in the presence of interesting examples, but there's some possibility that pareto optimisation itself will discover an interesting example. If this happens then pareto optimisation can potentially take a very long time, because once we have interesting examples we no longer limit how many valid test cases we see before stopping the run.
This PR fixes that problem by stopping the pareto optimisation loop once there are interesting examples.
=> Stop pareto optimisation once interesting examples have been found

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/statistics.py, hypothesis-python/tests/nocover/test_targeting.py
Here's an idea that closes #2180  (cc @aarchiba): consider a test which asserts that the largest integer is `100`.  Obviously this will fail, but shrinking will make it look like an off-by-one error!
```python
@given(st.integers(min_value=0))
def test_threshold_problem(x):
target(float(x))
assert x <= 100
```
Fortunately, reporting the highest observation seen by `target` makes it easy to tell that while `x=101` was the minimal counterexample, much larger errors exist:
```python-traceback
Highest target score: 9.14676e+08  (label='')
Falsifying example: test_threshold_problem(
x=101,
)
Traceback (most recent call last): ...
```
And if we un-comment our other `target` calls and assertions, we can see that this works smoothly with multi-objective optimisation and reporting of multiple …
=> Report targets with falsifying example(s)

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py
=> Fix binary() docstring backticks

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/dateutil.py, hypothesis-python/src/hypothesis/strategies/_internal/datetime.py, hypothesis-python/tests/cover/test_datetimes.py, hypothesis-python/tests/cover/test_direct_strategies.py, hypothesis-python/tests/datetime/test_dateutil_timezones.py, hypothesis-python/tests/datetime/test_pytz_timezones.py
Closes #2273, so a review from @pganssle would be welcome.
Particular decisions:
- We unconditionally generate a `fold` attribute of either `0` or `1`, *regardless* of other constraints.  This matches the equality and comparison semantics of naive datetimes, and therefore our bounds.
- Previously, imaginary datetimes (i.e. the hours skipped over when DST 'springs forward') were generated *unless* the timezone was supplied by `pytz`.  This has been made consistent by allowing `pytz` timezones to generate imaginary times too.
- A new `allow_imaginary=True` argument to `datetimes()` which when `False` is equivalent to `datetimes(...).filter(dateutil.tz.datetime_exists)`.  This may be inefficient if the bounds mostly span an imaginary period and has some boundary issues near `datetime.min` …
=> Datetime improvements: generate `fold=1` and consistent treatment of imaginary times

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/pareto.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
This is a small refactoring following on from #2396 that moves the logic that was a little hacky into the shrinker, so we can constrain shrinking by restriction what transitions we allow rather than always accepting transitions to a smaller interesting test case.
=> Move transition logic into shrinker

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/datetime.py, hypothesis-python/tests/pandas/test_argument_validation.py
Notably `pandas.Timestamp`, which we now also have a test for.  Fixes #2406.
=> Allow datetime subclasses as bounds for `st.datetimes()`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/choicetree.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/common/debug.py, hypothesis-python/tests/conjecture/test_choice_tree.py, hypothesis-python/tests/conjecture/test_shrinker.py, hypothesis-python/tests/quality/test_shrink_quality.py
Previously in reduction we iterated over the choice tree from left to right. Now we iterate over it from right to left.
The reasoning behind the change is basically that reductions near the end of the test case are more likely to work because there's less dependent on them. The downside is that reductions towards the left are more likely to have large impacts because there's more dependent on them, but it seems that (at least in our shrink quality test suite) this is a minor performance win.
This is loosely motivated by trying to improve shrink performance in #2340 but it's a relatively minor improvement. I was trying a number of more sweeping changes but this is the only one I found that was convincingly an improvement.
Unrelated test changes in this PR:
* It was annoying me that …
=> Reverse order of steps in individual reduction passes

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/compat.py, hypothesis-python/tests/conftest.py, hypothesis-python/tests/cover/test_lookup_py36.py, hypothesis-python/tests/cover/test_lookup_py38.py
This was prompted by some work on https://github.com/Zac-HD/hypothesmith/issues/2.  Happily, it also fixes #1004 - since I last prodded at that issue the typing ecosystem has improved and we're *mostly* 3.6+ and so a fairly simple approach now works :tada:
=> Improved `get_type_hints()` for classes with forward references

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/compat.py
This is a small but easy performance improvement - and in this case small means avoiding `import django.test` for some users, around 400ms on my machine, using [this one weird trick](1130983439862181888).  You can get your own numbers with `time python -c "import hypothesis"`.
We use the same trick elsewhere to check for Numpy arrays, and for that we wrote an explicit test that `import hypothesis` does not import numpy as a side-effect.  I've skipped that here, because it's much more annoying to write that with the Django test runner than with pytest, and because I think we're at much lower risk of regressions.
=> Avoid importing Django if not needed

hypothesis-python/tests/conjecture/test_engine.py
While trying out some experimental changes to the engine, I noticed that I was able to accidentally break the max-examples checks when finding multiple examples, in a way that wasn't explicitly caught by our `tests/conjecture/` suite.
This PR adds two specially-crafted tests to verify that if we reach the example limits after finding an interesting example, then we still proceed to shrinking and don't just halt immediately.
(These tests pass as-is, because that property is thankfully true at the moment.)
=> Test that we still shrink after hitting the example limit

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/types.py
https://github.com/HypothesisWorks/hypothesis/pull/2344#issuecomment-623386133 prompted me to look at whether our internal `_can_hash` filter was really necessary.  It's a small performance overhead, but whitelisting a few builtins wins most of that back with minimal complications to the code.
=> Small `from_type()` performance upgrade

hypothesis-python/RELEASE.rst, hypothesis-python/docs/details.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/extra/pytestplugin.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/statistics.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/cover/test_statistical_events.py
Fixes #1555.
I've also gone for a more substantial refactoring than the bare minimum.  Where the old scheme converted attributes directly into report lines, this PR prefers to ship around a blob of JSON and provide a function for converting it to report lines.
Having a machine-readable form that we can dump out makes analysis (c.f. https://github.com/HypothesisWorks/hypothesis/issues/437#issuecomment-288549657) much easier, whether that's to assess a test suite, compare fuzzers, or decide if a proposed change is robustly better than the status quo.  There's no public or supported interface in this PR, but it makes experimentation much easier - for example, I'm planning to use this to assess the effectiveness of targeted PBT and/or swarm testing vs. a baseline :slightly_smiling_face:
To …
=> Per-phase statistics reporting

CONTRIBUTING.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/compat.py
In Python 3.9, NamedTuples no longer have a `_field_type` attribute;
it has been deprecated since Python 3.8 and the `__annotations__`
attribute has identical information:
```
>>> from typing import NamedTuple
>>> class MyNT(NamedTuple):
...     x: int
...     y: int = 1
...
...
>>> issubclass(P, tuple)
True
>>> issubclass(P, NamedTuple)
False
>>> hasattr(MyNT, "_fields")
True
>>> hasattr(MyNT, "_field_types")
True
>>> hasattr(MyNT, "__annotations__")
True
>>> MyNT._field_types
{'x': <class 'int'>, 'y': <class 'int'>}
>>> MyNT.__annotations__
{'x': <class 'int'>, 'y': <class 'int'>}
```
see https://bugs.python.org/issue40182
Testing for the existence of *either* `_field_types` or
`__annotations__` fixes the four failing tests on Python 3.9:
``` …
```
=> Add support for Python 3.9's NamedTuple changes

CONTRIBUTING.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/validation.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/cover/test_complex_numbers.py
Closes #2424 by removing the explicit `Optional` from the `complex_numbers` strategy. Replaces the default `min_magnitude=0` with `min_magnitude=None` since these are equivalent and the latter allows you to use implicit `Optional`
=> Deprecate min_magnitude=None

azure-pipelines.yml
This line of the windows script is either a weird Azure workaround I don't know about, in which case disregard, or a typo.
`pip install setuptools -r requirements/test.txt`
setuptools was upgraded to the latest version in the previous line so installing it here should be a no-op?
(I know about the requirement to update the changelog but can someone confirm this is right first?)
=> Rm 'setuptools' from azure script line

CONTRIBUTING.rst, azure-pipelines.yml, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/cover/test_lookup.py, hypothesis-python/tox.ini, tooling/src/hypothesistooling/__main__.py
In Python 3.9, the `__args__` attribute is unset rather than set to None on types that aren't specialized.
See:
- https://docs.python.org/3.9/whatsnew/changelog.html?highlight=__args__#id2 (search `__args__`)
- https://bugs.python.org/issue40397
Closes #2444.
=> Python 3.9: Treat missing __args__ on generic types as None

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/src/hypothesis/extra/pandas/impl.py, hypothesis-python/src/hypothesis/internal/validation.py, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/flatmapped.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/tests/cover/test_validation.py
During the [PyCon mentored sprints](https://us.pycon.org/2020/hatchery/mentoredsprints/), two of the people I was working with wrote variations on `st.lists(elements=[1, 2, 3])`, and then had to look up `st.sampled_from()`.  So:
1. if passed a list or tuple when expecting a strategy, the error message is e.g `Expected a SearchStrategy, such as st.sampled_from(elements), but got elements=[1, 2, 3] (type=list)`
2. If we `check_type` with a strategy instead of using our `check_strategy` helper, that's now an internal error.
=> Hint about `sampled_from()` when passed a sequence instead of a strategy

hypothesis-python/RELEASE.rst, hypothesis-python/docs/details.rst, hypothesis-python/src/hypothesis/core.py
...well, if it's hardly doing anything - the two tricks consist of doing less setup, and sharing the cost of creating `StateForActualGivenExecution` across invocations (or moving it before the fork point).
```python
from time import perf_counter
from hypothesis import given, strategies as st
@given(st.none())  # or something more complicated
def test(_):
pass
loops = 10000
start = perf_counter()
fuzz_one_input = test.hypothesis.fuzz_one_input  # fewer attribute lookups = faster
for _ in range(loops):
fuzz_one_input(b"look, it's trying to talk to us...  \0\0\0\0\0\0")
end = perf_counter()
print(f"{loops} iterations in {end-start:.3f} seconds, {loops/(end-start):.0f} it/s")
```
On my machine this test script goes from ~3,800 it/s on master to ~10,300 it/s, saving 170 microseconds on each …
=> Make `fuzz_one_input` ~2.5x times faster

azure-pipelines.yml, hypothesis-python/RELEASE.rst, hypothesis-python/scripts/basic-test.sh, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/typing_extensions/__init__.py, hypothesis-python/tests/typing_extensions/test_backported_types.py
While working on Hypothesmith, I noticed that `LibCST` was using `typing_extensions.Literal` in their type annotations, rather than `typing.Literal`.  As the latter was added in Python 3.8, using a backport is perfectly sensible - but `st.from_type()` had no idea what to do.  After this PR, it will "just work".
Fixes #2413.
=> Infer strategies from `typing_extensions` types

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/choicetree.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/conjecture/test_choice_tree.py
This is just a pull request of small refactoring of the logic involved in running a single step of a shrink pass. In particularly it:
* Abstracts out the logic of how we decide what choice to make a bit
* Removes the logic for computing the next prefix because we implicitly find it anyway through the logic for avoiding exhausted subtrees
* Removes some redundant information on shrink passes that we no longer need
It has no user visible impact.
I was working on a new shrink pass selection algorithm. Part of this was that I had to be able to run shrink passes where choices were made randomly instead of deterministically, which prompted the refactoring for how we pick individual choices.
I couldn't actually make this work convincingly, but I thought some of the refactoring that happened as …
=> Some small refactoring of choice tree logic in shrinker

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/ghostwriter.py, hypothesis-python/tests/cover/test_ghostwriter.py
While I'm fond of #2344 and intend to do everything in it eventually, it's also been open for more than three months because it's an _enormous_ chunk of code to review.  I've therefore split out this PR, as the first of three stages which are small enough to actually review:
I hope you find this easier to review!
=> Internal-only ghostwriter core

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/utils.py, hypothesis-python/src/hypothesis/strategies/_internal/featureflags.py, hypothesis-python/tests/conjecture/test_utils.py
Part of why #2483 was so fiddly was that it turns out that our feature flags implementation shrinks very badly. On the one hand this was good in that it revealed problems with the pass that it was useful to catch, on the other hand it'd be nicer if it just didn't shrink badly.
The problem is basically that it leaves high bytes in the choice sequence as an intrinsic feature, so the shrinker potentially has to do a lot of work repeatedly checking if it can lower those. Ideally all bytes would be 0 or 1 after a successful shrink. This is easy to achieve by swapping over the implementation to `biased_coin`, which already has optimisations for this.
In order to enable this more elegantly this caused me to add a feature to `biased_coin` which allows you to force the value it returns. Once I'd …
=> Use biased_coin in FeatureFlags

CONTRIBUTING.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/tests/cover/test_health_checks.py
Tried to fix https://github.com/HypothesisWorks/hypothesis/issues/2487, let me know if it was the correct intended behavior or if I missed anything :slightly_smiling_face:
=> Make `forced` a kw-only arg

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/pytestplugin.py
Fixes #2490.  This is not a particularly elegant patch, but it *does* mean that we won't need to touch this again regardless of what happens to `setuptools` and `distutils`.
CC @HypothesisWorks/hypothesis-python-contributors - I'd like to ship this ASAP for affected users.
=> Patch out distutils

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/tests/numpy/test_gen_data.py
Not sure it's the best way to do it, but here is a first attempt to fix https://github.com/HypothesisWorks/hypothesis/issues/2486
=> Generate non-tuples if length == 1 from `npst.basic_indices()`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py, hypothesis-python/tests/conjecture/test_engine.py
I noticed that the `extend` parameter that I added to `cached_test_function` had a bit of a problem with it: Once you'd extended a buffer it would deterministically always extend it with the same thing. This turns out to be a trivial bug in our caching (we put the original buffer in as a cache key).
~My guess is that we were never hitting this in the wild but it tripped me up in some experimental code and seems worth fixing.~
It turns out that fixing this bug caused massive performance problems in optimisation, so I've also changed the optimiser to only extend the buffer with zeroes rather than randomly. This seems to pass all our tests and should be a lot faster even than the version with the caching bug.
=> Don't use a buffer we've extended as a cache key

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/conftest.py, hypothesis-python/tests/conjecture/test_engine.py
Fixes #2497.
The reason it was often failing was that it was hitting the time limit on shrinks. The reason it was hitting the time limit on shrinks is that our mocking for `perf_counter` wasn't doing anything, which is why this was flaky on CI but not locally - it was timing dependent.
I'm not 100% clear on why this was happening, but I adopted the simpler approach of replacing it with just doing `import time` and calling methods on it, as that's significantly less brittle.
=> Don't import time methods

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/utils.py, hypothesis-python/src/hypothesis/strategies/_internal/random.py, hypothesis-python/tests/conjecture/test_utils.py, hypothesis-python/tests/cover/test_randoms.py
This improves the performance of sampling mostly by making it fail when the stream is being manipulated in a way that works against it, which happens e.g. when passing all zeroes to a non-zero sample, and can trigger a health check.
This was prompted by #2503 failing due to flaky coverage of this method, and noticing this problem when I went to try to write more precise tests for it. This yak stack is so deep right now...
=> Improve performance of Random.sample when use_true_random=False

hypothesis-python/docs/conf.py, requirements/tools.in, requirements/tools.txt
Via https://sphinx-hoverxref.readthedocs.io/en/latest/index.html
(hopefully this also does readthedocs preview builds for the PR...)
=> Hover-tooltips for xrefs in docs

CONTRIBUTING.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/_settings.py, hypothesis-python/tests/cover/test_reproduce_failure.py, hypothesis-python/tests/cover/test_verbosity.py
Fixes https://github.com/HypothesisWorks/hypothesis/issues/2451.
For https://github.com/HypothesisWorks/hypothesis/issues/2510.
=> Enable print_blob for CIs, disable for local

CONTRIBUTING.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/tests/cover/test_unittest.py
Fix: #2462
fixed as part of #europython sprints
=> unittest.subTest wrapper should be handled as method

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/tests/cover/test_custom_reprs.py, hypothesis-python/tests/cover/test_sampled_from.py, hypothesis-python/tests/cover/test_type_lookup.py, hypothesis-python/tests/nocover/test_sampled_from.py
Closes #2507.  This is kinda fiddly, but not as bad as I expected... all we really lose is the "repr preserves sequence type" thing and there's no good way to do that without storing a shallow copy of whatever we're sampling just for the repr.
=> Make `sampled_from()` non-lazy

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/quality/test_shrink_quality.py
We don't currently reduce tests that look like the following well:
```python
@given(st.integers(0, 1000), st.integers(0, 1000))
def test(m, n):
assert m + n <= 1000
```
In that we might end up with basically any pair `(m, n)` with `m + n == 1001`, when ideally we'd always end up with `m = 1, n = 1000`.
It'd be nice to normalise such a simple test. This PR adds a special case shrinking pass for tests that have sum lower bounds like this.
Full disclosure: This is me cheating at a benchmark. https://github.com/jlink/shrinking-challenge/blob/main/challenges/bound5.md
=> Add special case shrink pass for sums of integers

hypothesis-python/tests/cover/test_randoms.py
Our tests are occasionally hitting (and discovered) [Python bug 41421](https://bugs.python.org/issue41421?@ok_message=msg%20374517%20created%0Aissue%2041421%20message_count%2C%20messages%20edited%20ok&@template=item).
It's unclear what the correct behaviour here is but given that our tests exposed a bug in the code that is old enough to drink (outside the USA anyway) it's also clear that nobody uses this code so it's better to just shrug and stick to the known good region.
=> Don't test paretovariate with alpha < 1

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/dfa/lstar.py, hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py, hypothesis-python/tests/conjecture/test_lstar.py
So, bytes, there are a lot of them, right? 256, in fact.
In many cases we'll find that most of them don't matter very much. In those cases we would like to be able to treat them as basically the same so as to avoid making quite so many membership queries.
This PR adds a preliminary attempt at this, by maintaining a very basic partition of the integers into contiguous intervals, and splitting that partition up as we discover new inequivalent integers.
How much does this help? Hard to say. It definitely speeds up the scenario where we have a single block whose value we're ignoring, which is currently really unneccessarily slow. Beyond that, I suspect the heuristics will need tinkering with a bit more as we come across specific practical scenarios.
=> Normalise bytes to common canonical values in L*

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/choicetree.py, hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/conjecture/test_choice_tree.py, hypothesis-python/tests/conjecture/test_shrinker.py, hypothesis-python/tests/quality/test_shrink_quality.py
Supplants #2478 - I picked up the code again to try to use it to fix the flaky large union shrink test, and then pulled on a thread and it turned that the more time was spent in selecting the shrink passes the better the code ran.
Causes a modest speedup on our shrink quality tests. Not huge - around 10% maybe - but it's enough to get the union list rnning reliably.
Basic idea is to use a hybrid approach where when nothing seems to be working we randomly bounce a shrink pass around until we find a good point to run from and then go back to running backwards. The large union test actually works best in purely random mode, but some of the other tests work less well and this seems to be an adequate compromise.
I'm not sure how convincingly I can justify this PR other than "ad hoc …
=> Run individual shrink pass steps in a semi-random order

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/conjecture/test_shrinker.py, hypothesis-python/tests/cover/test_debug_information.py, hypothesis-python/tests/nocover/test_conjecture_engine.py
Fixes #2523. 
Basic logic: If it's been at least `N` calls since our last successful shrink, we're probably done. Initially `N = 200` but we raise it if we're still shrinking but getting near to that limit.
I also included an unrelated change in this that just tidies up the debug output a bit because I was finding it really hard to figure out what was going on - we no longer print the shrink pass before a cached test function call, only an actual call.
=> Add heuristic for detecting finished shrinks

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/dfa/__init__.py, hypothesis-python/tests/conjecture/test_dfa.py, hypothesis-python/tests/conjecture/test_lstar.py
So we're iterating over a regular language in shortlex order as part of our tests. That's fine, right? It's just breadth first search. The whole internet loves this adorable Computer Science 101 algorithm. (five minutes pass) we regret to inform you that breadth first search has exponential complexity on this problem.
The problem is this: In order to explore all strings of length `n`, we first need to explore all *paths* of length `n - 1`. For certain easy to generate DFAs that would be all strings of length `n - 1` which is, you know, a lot.
This PR switches us over to an as-far-as-I-know novel (i.e. probably an independent reinvention) algorithm for iterating over a DFA's language which uses a memoized calculation of the number of strings of length `k` accepted from each state `i`. We …
=> Speed up DFA with new iteration algorithm

requirements/tools.txt
We're getting regular `RuntimeError`s in CI right now because of https://github.com/jazzband/pip-tools/issues/1192 - updating will supposedly fix this problem.
=> Update pip-tools version

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/conjecture/test_shrinker.py, hypothesis-python/tests/quality/test_shrink_quality.py
Currently we only simultaneously lower blocks if they have the same value, and we do so for all blocks of the same value. This modifies our shrinking to subtract from any nearby pair of non-zero blocks at once.
This is another shrink pass that, while reasonably general purpose and justifiable, is mostly motivated to do better on a benchmark.
Specifically this is for the [calculator benchmark](https://github.com/jlink/shrinking-challenge/blob/f21a9633892c748622cd5ff3e270d46584ecde78/pbt-libraries/hypothesis/challenges/calculator.md), where this change allows us to shrink the expression `('/', 0, 1)` to `('+', 0, 0)`, which requires us to lower two nearby blocks by one. I've included a test based on this in the shrink quality tests.
=> Allow simultaneously lowering two nearby blocks

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/dfa/lstar.py, hypothesis-python/tests/conjecture/test_lstar.py
The new integer partition code introduce a bug where sometimes after learning the DFA would be changed but the generation would not, because we were just using the number of experiments as a counter for the number of changes made, which is inaccurate now that we also have the integer partition. This would mean that sometimes code that was supposed to iterate until it was no longer making changes to the DFA would stop early. This PR fixes that.
=> Update generation counter even when just changing the integer partition

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_shrinker.py
It turns out that our test suite passes without a number of the shrink passes, saving only for some hyper-specific tests that tested specific behaviour of those passes. So I deleted them. The Hypothesis shrinker: Now with less code.
Partly this is just because deleting code that we don't actually need is good and I encourage it, but I had some specific goals in mind for targeting these shrink passes: I have a low-key goal of removing the concept of `examples` from `ConjectureData` and making our code  work purely based on integer values of blocks. Removing things that we don't need that rely on these features is a great first step towards that.
1. We have too many uses of the word "example" in our code and doing a large scale refactoring which requires significant technical research is …
=> I heard you like shrinking, so I shrunk the shrinker

CONTRIBUTING.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/functions.py, hypothesis-python/tests/cover/test_functions.py
Adds some tests for pure functions. Needs further work.
Closes #2538 
Questions right now (https://github.com/HypothesisWorks/hypothesis/issues/2538#issuecomment-671288387 for the context):
> passing kwargs in different orders, or an arg positionally vs by keyword, does not affect the caching
How can I test this? Didn't find any `cache` references in `test_cover`
> can generate non-identical return value for non-identical arguments
I have a problem with this one. Because my code `assert r1 != r2 or r1 == r2` does not really make much sence.
What is the best way to handle it?
> arg1=numbers()
I can probably improve this part:
```python
@given(
f=functions(like=pure_func, pure=True),
arg1=integers(),
arg2=integers()
)
```
Currently `arg1` and `arg2` are just numbers. I can use `.one_of` and …
=> Adds `pure` argument to `functions` strategy

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/dfa/__init__.py, hypothesis-python/tests/conjecture/test_dfa.py
In which @DRMacIver is reminded that having single letter variable names might be fine but single variable function arguments are the worst. Possibly this should be in our style guide to prevent me from having to learn this again? Not sure.
Anyway, this fixes a bug where we may get the wrong answer the first time we call `transition` on a state on `ConcreteDFA` because I accidentally changed the character we were reading in a loop.
=> Fix bug caused by variable name reuse in DFA transitions

hypothesis-python/RELEASE.rst, hypothesis-python/scripts/basic-test.sh, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/tests/ghostwriter/recorded/base64_magic.txt, hypothesis-python/tests/ghostwriter/recorded/fuzz_classmethod.txt, hypothesis-python/tests/ghostwriter/recorded/fuzz_sorted.txt, hypothesis-python/tests/ghostwriter/recorded/fuzz_ufunc.txt, hypothesis-python/tests/ghostwriter/recorded/magic_gufunc.txt, hypothesis-python/tests/ghostwriter/recorded/re_compile.txt, hypothesis-python/tests/ghostwriter/recorded/re_compile_except.txt, hypothesis-python/tests/ghostwriter/recorded/re_compile_unittest.txt, hypothesis-python/tests/ghostwriter/test_expected_output.py, hypothesis-python/tests/ghostwriter/test_ghostwriter.py
Part of #2344 split out for easier review; follows #2449 and #2501.  In this installment, we have (commit-by-commit):
- Using qualified names so that we correctly handle non-module-scoped objects like classmethods
- Avoiding catching any redundant exceptions (i.e. subclasses of others we catch), like flake8-bugbear
- Guess a strategy for well-known argument names if there is no annotation or default value
- A `magic()` ghostwriter which can write a test for every function in a module with one pass, without duplicated imports or header comments
Good luck @rsokl!
=> Upgrade draft ghostwriter, part 3/4

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/dfa/__init__.py, hypothesis-python/tests/conjecture/test_dfa.py
In a previous review @Zalathar asked if there was something clever we could do to update all of the cached `is_dead` values at once. We semi-agreed that there probably was and it probably wasn't worth it.
Anyway my experience with trying to get #2525 working on hypothesis-csmith showed just how bad our DFA method performance was on large DFAs and pointed out that for even quite small DFAs `max_length` could easily raise a `RecursionError`.
So, this is that something clever. Non-recursive (Well, explicit recursion in the `max_length` case) implementations which more efficiently calculate `is_dead` and `max_length` for a large swathe of the DFA at once.
Still WIP because some of the changes seem to interact badly with the testing of #2525 and I haven't got to the bottom of that yet, but the …
=> Improve performance of DFA methods

azure-pipelines.yml, hypothesis-python/RELEASE.rst, hypothesis-python/docs/conf.py, hypothesis-python/src/hypothesis/extra/cli.py, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/tests/ghostwriter/recorded/addition_op_magic.txt, hypothesis-python/tests/ghostwriter/recorded/division_operator.txt, hypothesis-python/tests/ghostwriter/recorded/magic_gufunc.txt, hypothesis-python/tests/ghostwriter/recorded/multiplication_operator.txt, hypothesis-python/tests/ghostwriter/recorded/multiplication_operator_unittest.txt, hypothesis-python/tests/ghostwriter/test_expected_output.py
As a follow-up to #2118 and #2344, this PR adds ghostwriters for less common but still useful patterns:
- binary operations demonstrate most of the 'classic' properties - associative, commutative, identity element, and distributive.  While these are rarer in Python than roundtrips and IMO less useful, they're still nice to have.
- Numpy-compatible (generalised) universal array functions.  These have surprisingly complex behaviour around the allowed shapes and dtypes of input and output arrays, and provide a lovely chance to show off our high-level strategies for testing numeric code.
=> Add ghostwriter functions for binary ops and Numpy (g)ufuncs

hypothesis-python/RELEASE.rst, hypothesis-python/docs/strategies.rst, hypothesis-python/src/hypothesis/__init__.py, hypothesis-python/src/hypothesis/entry_points.py
[Entry points](https://amir.rachum.com/blog/2017/07/28/python-entry-points/) are a nice way for downstream extensions to have Hypothesis run some of their code on import.
The most common uses of this are probably to set up `console_scripts` - followed by pytest plugins - but in our case it's really just a way to get the side effect of `st.register_type_strategy` without requiring upstream libraries to speculatively import Hypothesis.  More docs in the PR, which you can see has a *very* simple implementation!
Possible users include projects like `hypothesis-networkx` registering a strategy for various graph types, or `xarray` registering strategies for their own types from an unimported-by-default submodule.
=> Add "hypothesis" entry point

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/tests/cover/test_fuzz_one_input.py
This is the last integration point I need to get an external fuzzing engine working.
Having run it in my local fork for a fortnight or so now, after a fairly wide range of failed designs, I'm also confident that this will serve well for the long term and is not too specialised to my particular use-case.  The main thing to note is that unlike our existing [`fuzz_one_input()` hook](https://hypothesis.readthedocs.io/en/latest/details.html#use-with-external-fuzzers), this will allow for some arguments to come from strategies and others from e.g. `@pytest.mark.parametrize(...)`.
=> Add a way to get the strategy used for an `@given`-wrapped test

hypothesis-python/RELEASE.rst, hypothesis-python/docs/database.rst, hypothesis-python/src/hypothesis/database.py, hypothesis-python/tests/cover/test_database_backend.py, hypothesis-python/tests/nocover/test_database_agreement.py, hypothesis-python/tests/nocover/test_strategy_state.py
I've been looking at the database code lately with a view to various fuzzing workflows, and thought that we could make it a lot easier for downstream users to write their own.  To that end, this PR:
- Turns `ExampleDatabase` into an abstract base class, so that subclasses cannot be instantiated unless they define all three of the `save`, `delete`, and `fetch` methods
- Removes the `.close()` method, which we no longer call anywhere
(I think this was dropped in 4.0, with the SQLite database format)
- Adds some API documentation - [read it here](https://hypothesis--2568.org.readthedocs.build/en/2568/database.html)
- Adds the trivial type annotations (`bytes` and `Iterable[bytes]` only)
If you have e.g. a team who would like to use some networked non-file-system data store to implement a …
=> Document and type-annotate database code

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/shrinking/dfas.py, hypothesis-python/tests/conjecture/test_shrinking_dfas.py
When we're learning a new DFA from a pair of choice sequences that fail to normalise to the same value under shrinking, we split off the common prefix and suffix and only learn the core bit in the middle. Unfortunately, there were a bunch of corner cases that meant we were doing this wrong. This PR adds tests for and fixes those corner cases.
=> Correctly handle some edge cases in learning DFAs

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/cover/test_lookup.py
Closes #2572 
Things to review:
=> Changes how TypeVar is registered, refs #2572

hypothesis-python/docs/strategies.rst, hypothesis-python/docs/usage.rst
Since https://github.com/dry-python/returns/pull/543 is merged, it is now official!
=> Adds dry-python/returns to the list of open-source projects

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/cli.py, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/src/hypothesis/internal/compat.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/ghostwriter/recorded/addition_op_multimagic.txt, hypothesis-python/tests/ghostwriter/test_expected_output.py, hypothesis-python/tests/ghostwriter/test_ghostwriter.py, hypothesis-python/tests/ghostwriter/test_ghostwriter_cli.py, hypothesis-python/tests/ghostwriter/try-writing-for-installed.py
As the final stage of the ghostwriter saga, I decided that we should really be able to infer that functions with the same qualname and set of args are probably equivalent - unless they have incompatible return type annotations.
Then I ran `hypothesis write` on a wide range of modules to check that it worked reasonably well - and fixed a couple of weird issues for `pandas`... and then got suspicious and [wrote this script](https://github.com/Zac-HD/hypothesis/blob/anyghost/hypothesis-python/tests/ghostwriter/try-writing-for-installed.py) to run it against every Python module I have installed.
As the list of commits might indicate, this revealed *many* odd little issues.  
The general theme is "give decent output for strange modules instead of crashing", and *everything* here occurs in a …
=> Ghostwriter upgrade: equivalence heuristic and lots of edge cases

hypothesis-python/docs/data.rst, hypothesis-python/docs/database.rst, hypothesis-python/docs/details.rst, hypothesis-python/docs/development.rst, hypothesis-python/docs/examples.rst, hypothesis-python/docs/manifesto.rst, hypothesis-python/docs/numpy.rst, hypothesis-python/docs/packaging.rst, hypothesis-python/docs/reproducing.rst, hypothesis-python/docs/settings.rst, hypothesis-python/docs/stateful.rst, hypothesis-python/docs/strategies.rst, hypothesis-python/docs/support.rst, hypothesis-python/docs/supported.rst, hypothesis-python/docs/usage.rst
A majority of section headings in the Python documentation used "Sentence Case" i.e. capitalise the first word, proper nouns and initials.
A minority used Title Case (i.e. capitalise all major words).
This edit made them all conform to the former style, which makes the Table of Contents look much neater.
=> Make all sections use consistent case style.

hypothesis-python/docs/details.rst
If using len(xs)> 2 or 10 or anythign greater than 1, it will return lists with a greater likelihood to contain negative numbers, which will fail in the next line.  Fixes #2479.
=> modified example test_sum_is_positive_pyconau20

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/dateutil.py, hypothesis-python/src/hypothesis/extra/django/_impl.py, hypothesis-python/src/hypothesis/extra/lark.py, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/src/hypothesis/extra/pandas/impl.py, hypothesis-python/src/hypothesis/extra/pytz.py, hypothesis-python/src/hypothesis/provisional.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/datetime.py, hypothesis-python/src/hypothesis/strategies/_internal/ipaddress.py, hypothesis-python/tests/nocover/test_deferred_errors.py
Tidied up internal defines_strategy decorators code. Fixes #2516.
The `defines_strategy` decorator now has optional named parameters instead of using a set of decorators with
different options "preset".
`base_defines_strategy` was renamed to `defines_strategy`, which means the decorator is used as `@defines_strategy()`.
Possibly leaving one "overload" in place, `defines_strategy = base_defines_strategy()`, would have allowed the decorator to be `@defines_strategy` but the thinking there is that explicitly indicating that the optional parameters are not wanted is a good thing.
=> Tidy defines_strategy decorators (#2516)

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/docs/changes.rst, hypothesis-python/src/hypothesis/_settings.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/extra/django/_impl.py, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/src/hypothesis/extra/lark.py, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/src/hypothesis/extra/pandas/impl.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/ipaddress.py, mypy.ini
When using `mypy` with `--strict` flag and `hypothesis` together I stumbled upon a problem where defining custom composite strategies with optional parameters which will be later passed to other `hypothesis` strategies makes `mypy` raise errors because `hypothesis` does not have `no_implicit_optional` option set to `True`.
```python
from hypothesis import strategies as st
@st.composite
def st_value(
draw: Callable[[st.SearchStrategy[int]], int],
max_value: Optional[int] = None,
) -> int:
return draw(st.integers(max_value=max_value))
```
Enabling `no_implicit_optional` does not break anything for users that does not use `--strict` flag but it also makes it work for those who do use it. So I prepared a quick PR which does enable `no_implicit_optional` option and fixes all typehints.
Please …
=> Set no_implicit_optional to True for mypy and align typehints

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/floats.py
the struct module is documented as accepting only "format strings" and only happens to implement "format bytes", which can cause Warnings when run with `python -bb` in some cases
see https://docs.python.org/3/library/struct.html#struct-format-strings
and https://bugs.python.org/issue41777
and https://github.com/pytest-dev/pytest-xdist/issues/596
and https://bugs.python.org/issue21071#msg292409
=> use strings for struct formats

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_pareto.py
=> Reuse up to `max_examples` from database when `Phase.generate` is disabled

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/cover/test_direct_strategies.py, hypothesis-python/tests/cover/test_explicit_examples.py, hypothesis-python/tests/cover/test_one_of.py
While not all problems admit a technical solution, helpful error messages have a complementary role to documentation.  This PR adds two context-specific messages that can help with certain confusions I've seen lately - closing #2611 and pointing `one_of(1, 2, 3)` to `sampled_from(1, 2, 3)`.
=> Improve error messages for misused APIs

azure-pipelines.yml, hypothesis-python/RELEASE.rst, hypothesis-python/docs/conf.py, hypothesis-python/docs/database.rst, hypothesis-python/scripts/basic-test.sh, hypothesis-python/setup.py, hypothesis-python/src/hypothesis/database.py, hypothesis-python/src/hypothesis/extra/redis.py, hypothesis-python/tests/cover/test_database_backend.py, hypothesis-python/tests/redis/__init__.py, hypothesis-python/tests/redis/test_redis_exampledatabase.py
Our `ExampleDatabase` is a lovely thing - and persisting failing examples is great - but our story for *sharing* them is historically not amazing.  "Sync files or put them in version control" does *work*, but gets painful to set up or very noisy, respectively.  This PR is because after sketching out my ideal fuzzing workflow for teams, I realised it was just as useful for CI .  In short:
- The CI server (and/or fuzz server) saves any failing examples to a *network* datastore.
- Developer machines read from the shared datastore, maintain a local copy, and may or may not write to it.
- To reproduce failing examples locally, *just run the tests*.
And while of course this is optional and doesn't change the default directory-based DB, if you have a Redis server it's now ~ten lines of setup …
=> New `RedisExampleDatabase`, `MultiplexedDatabase`, and `ReadOnlyDatabase` for team workflows

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/compat.py, hypothesis-python/tests/nocover/test_build_signature.py
The code #2580 was taken from existing code that was intended for an older Python version which didn't take the `typing` module into account. This patch removes the check for `type` instance, to allow the `typing` types such as `Literal`, `Union`, etc.
As the signature is only manually created, I don't see an issue with the complete removal of the check. The alternative is to ensure it is from the `typing` module but I can't find an easy way to do this without using the private types.
=> remove instanceof type check for signature hints

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/cover/test_lookup.py, hypothesis-python/tests/ghostwriter/recorded/timsort_idempotent.txt, hypothesis-python/tests/ghostwriter/test_ghostwriter.py, tooling/src/hypothesistooling/__main__.py
This *mostly* worked before, by resolving to subclasses, but it didn't handle the parametrised generic properly.  This tiny but important patch fixes #2645.
CC @HypothesisWorks/hypothesis-python-contributors; review should be quick!
=> Bugfix for `st.from_type(typing.Iterable[T])`

hypothesis-python/RELEASE.rst, hypothesis-python/docs/data.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/cover/test_composite.py, hypothesis-python/tests/cover/test_lookup.py
=> Improve support for `@st.composite` with `@classmethod` or `@staticmethod`

hypothesis-python/RELEASE.rst, hypothesis-python/docs/changes.rst, hypothesis-python/docs/conf.py, hypothesis-python/src/hypothesis/internal/compat.py, hypothesis-python/tests/cover/test_lookup.py, requirements/tools.in, requirements/tools.txt
The typing.get_type_hints function has equivalent logic, and since this has bitten people in the wild we'd better add it to ours.
Fixes #2648, related to or follows #2388, #2580, #2606, #2640.  CC @rcarriga FYI :slightly_smiling_face: 
----------
And `RELEASE.rst` is now [included in the changelog for PR docs builds](https://hypothesis--2649.org.readthedocs.build/en/2649/changes.html#current-pull-request) if it exists, so you can see how it renders.
=> None-aware signature override

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/conftest.py, hypothesis-python/tests/cover/test_lookup_py37.py
[PEP 585](https://www.python.org/dev/peps/pep-0585/), the new-in-Python 3.9 feature that enables type annotations like `list[int]` rather than `typing.List[int]`,  turns out to require some minor patches in `st.from_type()`.  
This PR makes those changes, and closes #2629 by adding all the tests needed to prove it.  
CC @sobolevn for another typing review :grin:
=> Support PEP 585 parametrized standard types

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/escalation.py, hypothesis-python/tests/cover/test_escalation.py
Since b8e837ef42ce2e5faba2dfb7504143fd790f9444, [version 3.37](https://hypothesis.readthedocs.io/en/latest/changes.html#v3-37-0) in 2017, we've had special handling for exceptions raised while drawing from a strategy and don't attempt to minimise them.
I've opened this PR because I think that we *should* shrink them, just like we shrink everything else and for basically the same reasons: it makes debugging immeasurably easier.  As a concrete example, the lack of in-strategy shrinking has been really really painful while working on Hypothesmith - my "is this source code valid" oracle is built on top of `compile()`.  When the bug is inside the reference compiler, getting long high-unicode strings as a failing input *which doesn't replicate after copy-paste* is not much fun.
CC @DRMacIver - …
=> Remove shrinking exemption for errors inside strategies

hypothesis-python/docs/reproducing.rst
There has been a minor misname of the decorator in the documentation's text.
=> Fix reproduce_failure name in docs text

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/regex.py, hypothesis-python/tests/cover/test_regex.py, hypothesis-python/tests/nocover/test_regex.py
Closes #2657 - turns out we weren't quite careful enough about `.swapcase()` on unicode characters: it turns out there there's at least one character where this changes the length, but still matches the longer string in case-insensitive mode.  So now we check for length as well as a match.
=> Fix regex case bug

hypothesis-python/RELEASE.rst, hypothesis-python/docs/details.rst, hypothesis-python/docs/settings.rst, hypothesis-python/src/hypothesis/_settings.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/tests/cover/test_fuzz_one_input.py, hypothesis-python/tests/cover/test_settings.py
The core idea here is that if we've previously seen some buffer that produces a particular failure, we only want to save the new buffer if it is shortlex smaller.  In practice this means that long fuzzing runs saturate and saves a lot of time clearing out irrelevant entries from the database later.
Inspired by fiddling with [Atheris](https://github.com/google/atheris), Google's new fuzzer for Python, and realising that we didn't already have this logic :sweat_smile:
=> Cache fewer inputs when fuzzing

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/ghostwriter.py
This is a totally trivial patch, because a friend tried ghostwriting tests for encrypt/decrypt functions and it didn't work.  But after this PR it will :rocket:
=> Recognise en/de function pairs in the ghostwriter

guides/api-style.rst
I've spent a lot of time implementing `from_xxx()` functions over the last few months, and I thought it was worth writing up some short notes for our API style guide.  I'm implicitly guided by my own earlier mistakes with `from_type()` among others, as well as some of the [jarring APIs](https://github.com/hchasestevens/hypothesis-protobuf/blob/master/README.md#simple-example) I've seen in other Hypothesis extensions.
=> Expand API style guide

hypothesis-python/.coveragerc, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/_settings.py, hypothesis-python/tests/cover/test_settings.py
The highlight of this PR is improving the signature of the `settings()` class, to use explicit and type-annotated arguments instead of `**kwargs` - and therefore support all the nice developer tooling people use.  Personally I'm more excited about tab-completion working, but type checkers and Sphinx understanding it is nice too :wink:
Best reviewed commit-by-commit, as there's some initial tidying up (this is some of our oldest code) before getting to the main event.
=> Improve signature of `settings()`, for tab-completion and type checking

hypothesis-python/RELEASE.rst, hypothesis-python/docs/conf.py, hypothesis-python/scripts/basic-test.sh, hypothesis-python/setup.py, hypothesis-python/src/hypothesis/strategies/__init__.py, hypothesis-python/src/hypothesis/strategies/_internal/datetime.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/cover/test_lookup.py, hypothesis-python/tests/cover/test_type_lookup.py, hypothesis-python/tests/datetime/test_zoneinfo_timezones.py, hypothesis-python/tox.ini
From one perspective, this is a pretty standard PR adding a new strategy - it's almost identical to the `hypothesis.extra.{dateutil,pytz}.timezones()` strategies, but in the `hypothesis.strategies` namespace because the timezones in question come from the standard library.
On the other hand, they're *only in the latest stdlib*, so we also have some logic to manage backports - mostly through a new `hypothesis[zoneinfo]` extra which has only conditional dependencies.  This is clearly documented and raises nice errors if you don't have the deps; and since it'll be standard eventually I'd prefer to put it in the right place to start with.
Implementation of `allow_aliases` and `allow_deprecated` arguments for `timezone_keys()` has been left to a future PR, along with #2414 - this is just the …
=> `st.timezones()` strategy using the stdlib `zoneinfo` module

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/cover/test_direct_strategies.py
This improved error message closes #2693, and is designed to avoid any slowdown if the target to build does not raise a `TypeError`.
=> Recommend using `sampled_from()` when `builds(Enum)` raises an error

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/pandas/impl.py, hypothesis-python/tests/pandas/test_argument_validation.py
This PR fixes #2678: generating [`pdst.data_frames()`](https://hypothesis.readthedocs.io/en/latest/numpy.html#hypothesis.extra.pandas.data_frames) with interacting `rows` and `columns` arguments gave a very confusing error message because one of the columns was missing a `fill` value:
```python-traceback
hypothesis.errors.FailedHealthCheck: It looks like your strategy is filtering out a lot of data.
Health check found 50 filtered examples but only 0 good ones. ...
```
After this patch, you instead get:
```python-traceback
hypothesis.errors.InvalidArgument: Empty fill strategy in 
column(name='b', elements=text().map(convert_element), dtype=dtype('<U'), fill=nothing(), unique=False)
cannot complete row {'a': 'x'}
```
which I think is a *lot* more helpful than the staus quo …
=> Improve error when generating a dataframe from `rows` and `columns` with `fill=None`

hypothesis-python/RELEASE.rst, hypothesis-python/scripts/basic-test.sh, hypothesis-python/src/hypothesis/_settings.py, hypothesis-python/src/hypothesis/extra/cli.py, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/tests/cover/test_settings.py
This docstring suggests that callers can pass a database path string or the special string `":memory:"`, but those arguments are not actually permitted by the implementation.
It seems that an early draft of #1196 did allow string arguments (to match the now-removed `database_file` setting). The feature was then removed after review feedback, but unfortunately the docstring was not
updated.
In-memory DBs and custom DB paths can still be specified by explicitly instantiating a subclass of `ExampleDatabase`, or by calling `ExampleDatabase` with a string argument (currently under-documented?).
=> Doc fix: The database setting doesn't actually allow string values

CONTRIBUTING.rst, tooling/src/hypothesistooling/__main__.py
I always found it slightly annoying to have to look through `.travis.yml` or `__main__.py` to figure out which tasks are supported by `./build.sh`, especially since some of the task names don't appear directly in the source. So I added a new task that just directly prints a list of all known task names.
I also added a helpful suggestion to the error message that appears when no task is specified.
=> Add a "tasks" task to print the list of tasks supported by the build system

hypothesis-python/tests/cover/test_intervalset.py
Otherwise, the next line with `assume` is useless as it is always `True` in this case
=> Fix typo in `test_subtraction_of_intervals`

.github/workflows/main.yml, AUTHORS.rst, build.sh, requirements/tools.in, requirements/tools.txt, tooling/src/hypothesistooling/__main__.py
As you may know, Travis CI was acquired by private equity a few months ago, and it appears that they are proceeding to the "strip-mine the company" phase - in particular, their open-source offering is slower, flaky, delayed, and now imposes a tight monthly cap.  The Travis blog has [more info here](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) and [an update here](https://blog.travis-ci.com/oss-announcement).  While legitimate, we therefore want to move to a different CI provider.
GitHub Actions runs on the same infrastructure as Azure Pipelines (see #2043), with somewhat cleaner configuration and much better UI integration with GitHub.  In particular secrets management and build status reporting are nice.  So let's transfer everything over to a single provider!
With deep …
=> Move our all our CI to GitHub Actions

guides/api-style.rst, guides/strategies-that-shrink.rst, hypothesis-python/docs/changes.rst, hypothesis-python/tests/cover/test_unittest.py
- Fixes #2716 (which we'll encounter as soon as we move to GitHub Actions, #2674, and re-enable dependency updates).
- Adds a line to the changelog that I discovered was missing while working on #2705.
- Our shrinking guide now [links to the published paper](https://2020.ecoop.org/details/ecoop-2020-papers/13/Test-Case-Reduction-via-Test-Case-Generation-Insights-From-the-Hypothesis-Reducer) instead of suggesting you ask David for a draft.
- Our API style guide notes that 
- `min_value` and `max_value` need not be keyword-only despite having default values,
- their default values should be None only for unbounded types (integers yes, datetimes no), and
- `floats()` is special because of `inf` and `nan` interactions.
=> Fix test issue, add missing changelog line

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/collections.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/cover/test_sampled_from.py
This is related to #2036, in that it extends our special-casing of unique lists of elements=sampled_from(), but not strictly part of that issue.  Fortunately it also stands quite nicely alone, to be reviewed and merged separately :grin:
=> Make `dictionaries(keys=sampled_from(...), ...)` more efficient

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/typing_extensions/test_backported_types.py
This turns out to be essential for the Pydantic plugin I'm working on (https://github.com/samuelcolvin/pydantic/pull/2097), so here we go.
=> Support `Literal` on py36

guides/review.rst, hypothesis-python/RELEASE.rst, hypothesis-python/docs/extras.rst, hypothesis-python/scripts/basic-test.sh, hypothesis-python/setup.py, hypothesis-python/src/hypothesis/_settings.py, hypothesis-python/src/hypothesis/extra/cli.py, hypothesis-python/src/hypothesis/extra/codemods.py, hypothesis-python/src/hypothesis/extra/django/_impl.py, hypothesis-python/src/hypothesis/extra/pytestplugin.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/internal/validation.py, hypothesis-python/src/hypothesis/provisional.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/codemods/test_codemod_cli.py, hypothesis-python/tests/codemods/test_codemods.py, hypothesis-python/tests/cover/test_settings.py, hypothesis-python/tests/nocover/test_regressions.py, requirements/tools.in, requirements/tools.txt
This is an MVP pull request to get us started on #2705 🎉 
It creates the extra dependency, tests, docs,... and uses that for the smallest possible refactoring: robustly replacing the deprecated `st.complex_numbers(min_magnitude=None)` with the non-deprecated equivalent `st.complex_numbers(min_magnitude=0)` (correctly handling shadowed names, importing as an alias, multiple arguments in any order, etc.).
I thought it would be easiest to review if I posted this as-is, and then had a follow-up (TBA) which handles our positional-or-keyword to keyword-only deprecation pathway.  However the latter part turned out to be easier than I expected, so I've included that as well 😎
=> First codemods: fix positional arguments for keyword-only parameters

build.sh
According to https://github.com/HypothesisWorks/hypothesis/issues/2734#issuecomment-754002321, this installation line was accidentally introduced in e2e0cf9 (#2656), and does not appear to be needed for anything. It had the undesired effect of causing `./build.sh documentation` to use a stale installed copy of the Hypothesis source, instead of the current source.
Fixes #2734.
=> Don't `pip install hypothesis-python/` in build.sh

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/ghostwriter/recorded/hypothesis_module_magic.txt, hypothesis-python/tests/ghostwriter/test_expected_output.py, hypothesis-python/tests/ghostwriter/test_ghostwriter.py
This patch fixes #2703, along with some smaller isssues I noticed while working on [a draft paper about the ghostwriter](https://zhd.dev/phd/ghostwriter.html).
The main point is to improve the importing logic: if we ghostwrite tests for functions in `foo.__all__`, we now import them from `foo` instead of e.g. `foo._internal.bar` where they were defined; and we import functions or classes used in `builds(Thing)`, `.map(foo)`, `.filter(bar)`, or `.flatmap(baz)`.
As minor associated patches the `magic()` ghostwriter no longer collects `Enum` subclasses from modules, `lambda: <unknown>` is replaced with `lambda: ...` for `functions(like=lambda: ...)`, and `@reproduce_failure` is properly type-annotated.  I've bundled these in to avoid conflicts with the `hypothesis write hypothesis` test, but …
=> Improve results from `hypothesis write hypothesis`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/control.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/extra/codemods.py, hypothesis-python/src/hypothesis/extra/django/_impl.py, hypothesis-python/src/hypothesis/extra/lark.py, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/src/hypothesis/extra/pandas/impl.py, hypothesis-python/src/hypothesis/extra/pytestplugin.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/internal/validation.py, hypothesis-python/src/hypothesis/provisional.py, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/datetime.py, hypothesis-python/tests/cover/test_complex_numbers.py, hypothesis-python/tests/cover/test_direct_strategies.py, hypothesis-python/tests/cover/test_provisional_strategies.py, hypothesis-python/tests/cover/test_randoms.py, hypothesis-python/tests/cover/test_reflection.py, hypothesis-python/tests/cover/test_settings.py, hypothesis-python/tests/cover/test_type_lookup.py, hypothesis-python/tests/django/toystore/test_given_models.py, hypothesis-python/tests/pytest/test_fixtures.py
Heya @HypothesisWorks/hypothesis-python-contributors!  I present for your review our smallest major release since 3.0.0:  enforcing keyword-only arguments and finalising six smaller deprecations.
It should also be pretty easy to update - most changes are small, and for the calling convention change we've already shipped a "codemod" which can automatically update user code.  Nonetheless, as per #2709 I think it's worth shipping this now to give users and their tools the nicest interface and learning experience we can.
=> Hypothesis 6.0: starting 2021 as we mean to go on

hypothesis-ruby/Gemfile, hypothesis-ruby/Gemfile.lock, hypothesis-ruby/README.markdown, hypothesis-ruby/RELEASE.md, hypothesis-ruby/Rakefile, hypothesis-ruby/docs/debt.md, hypothesis-ruby/lib/hypothesis/engine.rb, tooling/src/hypothesistooling/__main__.py
It doesn't look like any RSpec code is actually invoked in the codebase, and requiring these files prevents using hypothesis-ruby with different test runners (i.e. Minitest).
Minitest is the default test runner with Rails, and supporting it would be great. I don't see a compelling reason to limit hypothesis-ruby to RSpec alone.
=> Remove references to RSpec.

conjecture-rust/src/engine.rs, hypothesis-ruby/docs/debt.md
As per docs:
> Can be removed when: That issue is fixed, or an alternative workaround is suggested.
Now we don't use `helix` at all, and `rutie` doesn't require `Clone` to be implemented.
=> Remove `Clone` trait impl from `Engine`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/pytestplugin.py, hypothesis-python/src/hypothesis/internal/conjecture/dfa/__init__.py, hypothesis-python/tests/conjecture/test_dfa.py, hypothesis-python/tests/pytest/test_statistics.py
Closes #1975, by the inelegant but effective expedient of using a valid-for-junitxml if the `--junit-xml` argument has been passed, and base64-encoding everything to avoid XML escaping problems with arbitrary user-supplied events, `target` labels, etc.
Ping @danilomendesdias @tadeu @arthursoprana @ggrbill @prusse-martin @thisch - you each 👍'd the issue and I'd appreciate any feedback you might have on this PR, especially confirming whether or not it fixes the problem for you!
=> Refactor pytest plugin statistics handling for strict JUnit xml validation

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/tests/cover/test_filtered_strategy.py
Hey, you know how we have the `remove_discarded` shrink pass specifically designed for e.g. improving the shrinking performance of filtered strategies by removing early iterations in the rejection sampling loop? Neat feature, right?
I was writing a short blog post explaining it and then thought I'd double check the code and discovered we weren't actually marking discarded iterations in filtered strategies as discarded, so they were never actually triggering this shrink pass. Whoops. 😳 
Anyway, this PR fixes that.
=> Actually mark filter iterations as discarded

CODEOWNERS, guides/review.rst
As discussed in https://github.com/HypothesisWorks/hypothesis/pull/2761, it sounds like we're ok with removing the blocking codeowner for Rust code.
=> Remove dependency on DRMacIver for Rust reviews

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/tests/cover/test_searchstrategy.py, whole-repo-tests/test_type_hints.py
=> Improve type annotations for `one_of` and `SearchStrategy.__or__`

.github/workflows/main.yml, conjecture-rust/src/data.rs, conjecture-rust/src/distributions.rs, conjecture-rust/src/engine.rs, conjecture-rust/src/lib.rs, tooling/src/hypothesistooling/__main__.py
This PR implements a CI job for running `cargo clippy` on `conjecture-rust` source code and fixes some reported issues.
Details:
- Disabled the `many_single_char_names` lint globally because I am not sure if it is needed for cases when multiple indices are involved. Let me know if you think it is better to disable it locally for specific code blocks
- `to_result` -> `into_result`. In this part, I also changed `mut self` to `self` because there is no need to call `drain` that mutates the `draws` vector - it is dropped anyway at the end of this function (as we have `self` by value)
- Added `DataStreamSlice` type alias that is used in `Shrinker.execute` and `Shrinker.incorporate`. 
Let me know what do you think! :) 
At this stage, the build should be green. For the next steps, we can …
=> Add linting for conjecture rust

conjecture-rust/src/engine.rs, hypothesis-ruby/RELEASE.md, hypothesis-ruby/lib/hypothesis.rb, hypothesis-ruby/lib/hypothesis/engine.rb, hypothesis-ruby/spec/example_shrinking_spec.rb, hypothesis-ruby/spec/phase_specification_spec.rb, hypothesis-ruby/spec/spec_helper.rb, hypothesis-ruby/src/lib.rs
From the `RELEASE.rst`:
Adds support for skipping shrinking. While shrinking is extremely helpful and important in general, it has the potential to be quite time consuming. It can be useful to observe a raw failure before choosing to allow the engine to try to shrink. [hypothesis-python](https://hypothesis.readthedocs.io/en/latest/settings.html#phases) already provides the ability to skip shrinking, so there is precedent for this being useful. While `hypothesis-ruby` does not have the concept of other "Phases" yet, we can still start off the API by using this concept.
Usage:
```
hypothesis(phases: Phase.excluding(:shrink)) do
end
```
=> Support skipping shrinking

conjecture-rust/src/engine.rs
An easy fix for the failing test. I am not entirely happy with that since the variants in `Phase` and inside `all` should be synced manually :(
=> Fix the failing `minimizes_all_examples` test in conjecture rust

conjecture-rust/Cargo.toml, conjecture-rust/RELEASE.md
Documentation here: https://doc.rust-lang.org/cargo/reference/manifest.html#the-keywords-field
=> Adhere to the 20-char limit to cargo keywords.

.github/workflows/main.yml, hypothesis-ruby/src/lib.rs, tooling/src/hypothesistooling/__main__.py, tooling/src/hypothesistooling/projects/hypothesisruby.py
Resolves #2746 
This PR adds `cargo audit` and applies all Rust tooling we have to the Rust code inside Hypothesis-Ruby.
Note that running `cargo install cargo-audit` updates `cargo-audit` to the latest installed version if it is installed. If it is already the latest one, it skips the installation.
=> Finalize CI for Rust code

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/recursive.py, hypothesis-python/tests/nocover/test_recursive.py
Fixes #2717.
In the end, I chose thread-local storage for solving the issue as proposed in the linked issue. Here are my thoughts on why I implemented it this way & comparing how it changes the status quo.
**Single thread**
At the moment, a recursive strategy may fail on this assertion if it calls itself in `do_draw` [here](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/strategies/_internal/recursive.py#L99):
```python
with self.limited_base.capped(self.max_leaves):
return data.draw(self.strategy)
```
The strategy may look like this:
```python
from hypothesis import strategies as st
SELF_REF = st.recursive(
st.deferred(lambda: SELF_REF | st.booleans()),
lambda s: st.lists(s, min_size=1)
)
```
I am not sure how meaningful such a strategy is, but …
=> Fix race condition inside recursive strategies

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/escalation.py, hypothesis-python/tests/nocover/test_interesting_origin.py
=> Distinguish exceptions by `__cause__` or `__context__`

conjecture-rust/RELEASE.md, conjecture-rust/src/distributions.rs, hypothesis-ruby/RELEASE.md
It is a minor change that slightly improves the flexibility of `Sampler::new`.
The `weights` value is not moved, so the callee can use it again after `Sampler::new` is called without cloning. It also positively affects the performance side (very minor though) - `weights` inside `good_bitlengths` becomes stack-allocated + the size of `&[f32]` is less than `Vec<f32>`, so the call is cheaper. There is only one usage, though, but it doesn't bring any restrictions (except if moving `weights` is intentional from the API point of view, which I doubt is the case).
=> Use a slice in `Sampler::new` instead of a vector

hypothesis-python/RELEASE.rst, hypothesis-python/docs/extras.rst, hypothesis-python/docs/strategies.rst, hypothesis-python/src/hypothesis/extra/pytestplugin.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, pytest.ini, tooling/src/hypothesistooling/__main__.py
A tiny always-on integration with pytest-html, where reporting our statistics summary doesn't take up space like it would on the command-line.
Note that this PR does not include automated tests, because there's only one very simple line of code, and it would be painful to check anything meaningful even if we set up another virtualenv and CI job with `pytest-html` installed.  Assuming you have `pytest-html` installed locally, you can run e.g. `pytest hypothesis-python/tests/cover/test_complex_numbers.py --html=report.html` in the repo root, and see that the report now has stats in the previously-empty "links" column, which open as a plain-text document:
I imagine that this will be more interesting when the tests are *failing*, and you don't need to re-run any tests to get the statistics. …
=> Report statistics summary via `pytest-html`

.github/workflows/main.yml, hypothesis-python/RELEASE.rst, hypothesis-python/setup.py, hypothesis-python/src/hypothesis/extra/pytestplugin.py, hypothesis-python/tests/pytest/test_skipping.py, hypothesis-python/tests/pytest/test_statistics.py, hypothesis-python/tox.ini, tooling/src/hypothesistooling/__main__.py
Motivated by #2863, but also a fine idea in general since 4.6 is the earliest version semi-supported by the pytest maintainers.
=> Bump required pytest version to 4.6

hypothesis-python/tests/pytest/test_mark.py, hypothesis-python/tests/pytest/test_seeding.py, hypothesis-python/tests/pytest/test_skipping.py, hypothesis-python/tox.ini, pytest.ini
(New version of #2862; fixes #2863.)
=> Resolve pytest warnings about the deprecated --strict flag

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/filtering.py, hypothesis-python/src/hypothesis/strategies/_internal/lazy.py, hypothesis-python/src/hypothesis/strategies/_internal/numbers.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/tests/cover/test_direct_strategies.py, hypothesis-python/tests/cover/test_filter_rewriting.py, hypothesis-python/tests/cover/test_filtered_strategy.py
This pull request is the first piece of #2701.
It demonstrates that the concept works, handles the tricky interactions with LazyStrategy and chained filters (though `one_of()` is left for future work), and provides obvious locations for future contributions - such as copying this logic for `floats()`.  Further discussion of how the overall plan can be broken down into pull requests can be found at #2701, along with next steps.
=> Rewrite simple filters for bounded `integers()`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/__init__.py, hypothesis-python/src/hypothesis/strategies/_internal/collections.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/misc.py, hypothesis-python/src/hypothesis/strategies/_internal/numbers.py, hypothesis-python/src/hypothesis/strategies/_internal/regex.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/src/hypothesis/strategies/_internal/utils.py, hypothesis-python/tests/cover/test_type_lookup.py, hypothesis-python/tests/nocover/test_argument_validation.py
This patch is pure code-movement - reducing the size of `core.py` by moving strategy functions to other modules, and reducing the number of current import cycles.  For the same reason, it's important setup for future work on #2701.
=> Refactoring: move strategies out of `core.py`

hypothesis-python/RELEASE.rst, hypothesis-python/docs/stateful.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/extra/lark.py, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/tests/cover/test_stateful.py, requirements/coverage.txt, requirements/tools.txt
This PR contains the docs suggested in #2860, along with some refactoring of `RuleBasedStateMachine`, intended to make it easier to work on e.g. the issues discussed in #2861.
(the `define_*` classmethods were a holdover from `GenericStateMachine`, which was removed in Hypothesis 5.0.0)
=> Tidying up stateful testing

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/typing_extensions/test_backported_types.py
The test case in the first commit demonstrates the exception.
Thanks!
=> Fixes an exception in from_type(Union[Literal["a"], Literal["b"]]).example() in Python 3.6

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/recursive.py, hypothesis-python/tests/nocover/test_recursive.py
Fixes #2794 in the obvious way.
=> Improve handling of self-referential `recursive()` strategies

hypothesis-python/.coveragerc, hypothesis-python/RELEASE.rst, hypothesis-python/docs/details.rst, hypothesis-python/docs/settings.rst, hypothesis-python/src/hypothesis/_settings.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/extra/pytestplugin.py, hypothesis-python/src/hypothesis/internal/scrutineer.py, hypothesis-python/tests/cover/test_phases.py, hypothesis-python/tests/cover/test_scrutineer.py
I'm currently working on [a paper about integrating fault localisation with property-based testing](https://zhd.dev/phd/scrutineer.html) - TLDR, it's pretty easy for PBT libraries to suggest where to start debugging test failures.
It turns out that my simple baseline version is also reliable, useful, and easy to interpret.  On that basis I thought it makes sense to ship it, albeit disabled-by-default.  I've tried this on a variety of toy examples and some real bugs in `black`; reviews and/or feedback on how this works for your problems would be most welcome 🙂 
------------
Future plans for other PRs: adding fancier techniques, if they're reliable and fast and actually work better; and integration with generalised examples (#2192).  As currently planned, all of these would go in a single …
=> Scrutineer: integrating opportunistic fault-localisation with PBT

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/tests/cover/test_stateful.py
In stateful testing, it doesn't make much sense to apply both these decorators, and if you did anyway there were weird interactions with preconditions.  See #2861.
=> Allow `@rule()` xor `@invariant()` decorators on rule-based state machine methods.

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/cover/test_lookup.py, hypothesis-python/tests/cover/test_type_lookup_forward_ref.py
Sadly this closes #2565, because `Type` objects don't track the module they were defined in - and we therefore can't get the globals in which to look up the forward reference.
Upside, at least I managed to improve the error message and write a covering test :confused:
=> Improve error message for `from_type(Type["int"])`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/tests/cover/test_stateful.py
Per #2860, it's possible but awkward to give all invariants a precondition of "all initialize rules have been run" - but this is almost always the desired behaviour.
This PR therefore makes that the default behaviour, and adds an argument `@invariant(check_during_init=True)` to restore the previous behaviour of unconditionally checking invariants, which fixes #2868.
=> Default to checking stateful invariants only after initialization

hypothesis-python/tests/nocover/test_interesting_origin.py
This would fail when the retry decorator kicked in (rarely, as expected), because the settings decorator would have assigned to an attribute of `function`.  Using a fresh wrapper each time avoids the problem.
Fixes #2888.
=> De-flake test

hypothesis-python/tests/common/setup.py, hypothesis-python/tests/cover/test_type_lookup.py
If you have pydantic 1.8+ installed, with the Hypothesis plugin, our selftests will now pass again.  See code comments for details.  Fixes #2898.
=> Support testing with plugins

hypothesis-python/.coveragerc, hypothesis-python/RELEASE.rst, hypothesis-python/docs/details.rst, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/numbers.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/cover/test_lookup.py
While working on #2892 and #2896, it occurred to me that (absent a registered strategy to the contrary) it's safe to assume that forward-references to the name of a builtin type does in fact refer to that builtin.  This PR implements exactly that logic... and registers all the remaining builtin types, so that we can write the obvious tests.
=> Handle all builtin types in `st.from_type()`, including via `Type[...]` and `ForwardRef(...)`

hypothesis-ruby/RELEASE.md, tooling/src/hypothesistooling/projects/hypothesisruby.py
This also makes sure that changes to the gemspec will be required to have a release file in the future. I wrote one for https://github.com/HypothesisWorks/hypothesis/pull/2903 but didn't commit it by mistake. This will catch such a mistake.
=> Release rake dependency change

CODEOWNERS, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/src/hypothesis/internal/conjecture/pareto.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/src/hypothesis/internal/conjecture/utils.py, hypothesis-python/src/hypothesis/internal/filtering.py, hypothesis-python/src/hypothesis/strategies/_internal/ipaddress.py, hypothesis-python/src/hypothesis/strategies/_internal/numbers.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/src/hypothesis/vendor/pretty.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/cover/test_direct_strategies.py, hypothesis-python/tests/cover/test_filter_rewriting.py, hypothesis-python/tests/numpy/test_gen_data.py, hypothesis-python/tests/quality/test_discovery_ability.py, hypothesis-python/tests/quality/test_integers.py, requirements/coverage.txt, requirements/tools.txt
This PR refactors the implementation of `integers()`, so that it consists only of an `IntegersStrategy` class instead of various combinations, maps, and filters over separate classes for bounded and unbounded integers.
Data-generation is logically unchanged, with negligible performance changes in runtime and memory usage - the real motivation here is to empower runtime introspection for filter-rewriting (#2701) and prototyping symbolic execution.
=> Upgrade `integers()` backend and filter rewriting

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/ghostwriter/recorded/magic_gufunc.txt, hypothesis-python/tests/ghostwriter/test_ghostwriter.py
This is a collection of tiny patches to improve the output of `hypothesis write black`.
- Improved magic detection of which module contents to test (based on `__module__` and `__package__`)
- Fixed `st.`-rewriting bug (`frozensets()` -> `st.frozensets()`, not `st.frozenst.sets()`)
- Improved detection of required imports - of `sampled_from(...)` values, extras strategies, etc.
```diff
--- before.py
+++ after.py
@@ -2,16 +2,18 @@
import black
+import re
import typing
from asyncio.events import AbstractEventLoop
-from black import BracketTracker, Line, Mode, PathSpec, Report
+from black import BracketTracker, Line, Mode, Report
from blib2to3.pytree import Leaf, Node
from click.core import Context, Option, Parameter
from collections import ChainMap
from concurrent.futures._base import …
```
=> Tiny ghostwriter fixes

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/cli.py, hypothesis-python/src/hypothesis/extra/ghostwriter.py
Because if you're using unittest and don't even have pytest installed, life is easier (which is the whole point!) if the ghostwriter can guess that you want unittest style by default.  Of course you can still pass `--style=pytest` if you want to.
Also tunes the binary-operator detection heuristic a little, adding a check that the argument names are short and of equal length, based on my experiments with type-annotated codebases such as `black`.
=> Auto-configuration of default ghostwriter style - pytest if installed, else unittest

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/strategies/_internal/collections.py, hypothesis-python/tests/nocover/test_testdecorators.py
=> Preserve iteration order in `st.fixed_dictionaries()` and `@given()` kwargs

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/tests/ghostwriter/recorded/magic_base64_roundtrip.txt, hypothesis-python/tests/ghostwriter/recorded/magic_gufunc.txt, hypothesis-python/tests/ghostwriter/test_expected_output.py, hypothesis-python/tests/ghostwriter/test_ghostwriter.py
Specifically, if looking at a function `f` check the module that defined it for an inverse function `g`, plus some more regex patterns for `socket`-like APIs, and a performance boost for gufunc tests.
A follow-up PR based on https://github.com/Zac-HD/hypothesis/compare/ghostwriter...ghost2 will add docstring-based detection of allowed exceptions and move assertions outside the `except` clauses we generate.
=> Teach the Ghostwriter to look for more roundtrips

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/cover/test_type_lookup.py
This is a pair of a subtle bug and some smarter behaviour:
- if we had an abstract type with required-and-unannotated parameters, we'd incorrectly raise `ResolutionFailed` as if we were about to use `st.builds()` (which we, correctly, only try for non-abstract types)
- `return sampled_from(subclasses).flatmap(from_type)` is suboptimal - we can check which subclasses can be resolved and just use those... but maintain it as a fallback in case we can't resolve any now but will be able to when we actually draw values.
This is definitely a rare combination of cases to hit, but if we're going to support it let's do it *right*.
=> Fix abstract type bug

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/numpy.py
Closes #2935 
Also `flake8` was mad that we used `l` as a variable name, so I fixed that too.
=> Updates type hint for arrays(..., shape)

.github/workflows/main.yml, hypothesis-python/tox.ini, tooling/src/hypothesistooling/__main__.py
And drop tests on the now-EOL Django 3.0; closes #2928.
=> Test against Django 3.2

hypothesis-python/RELEASE.rst, hypothesis-python/setup.py, hypothesis-python/src/hypothesis/extra/cli.py
Because syntax-highlighting makes a much better first impression, like the modern and usable tool that the Ghostwriter is.
[Rich](https://rich.readthedocs.io/en/stable/) is smart enough to work across essentially all of the various terminals and operating systems that people might be using, and also disables the highlighting if you redirect output into a file.  I've added an optional dependency on Rich, but also ensured that the CLI will gracefully degrade (to builtin `print()`) if it isn't available.
=> Syntax-highlight ghostwritten code in the terminal using Rich 

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/conftest.py, hypothesis-python/tests/cover/test_lookup_py38.py, hypothesis-python/tests/cover/test_lookup_py39.py, hypothesis-python/tests/typing_extensions/test_backported_types.py
This update enables `hypothesis` to generate data for types wrapped in `typing_extension.Annotated` and `typing.Annotated`. It fixes #2919.
I have some concerns about the testing part, mainly the fact that I'm using `repr` to compare the strategies returned by `st.from_type` and the expected one. I'm guessing there should be a better way, but I couldn't find it quickly. Any suggestions @Zac-HD?
=> Add support for `Annotated` types

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/tests/ghostwriter/recorded/division_binop_error_handler.txt, hypothesis-python/tests/ghostwriter/recorded/division_fuzz_error_handler.txt, hypothesis-python/tests/ghostwriter/recorded/division_roundtrip_arithmeticerror_handler.txt, hypothesis-python/tests/ghostwriter/recorded/division_roundtrip_error_handler.txt, hypothesis-python/tests/ghostwriter/recorded/division_roundtrip_typeerror_handler.txt, hypothesis-python/tests/ghostwriter/recorded/hypothesis_module_magic.txt, hypothesis-python/tests/ghostwriter/recorded/timsort_idempotent_asserts.txt, hypothesis-python/tests/ghostwriter/test_expected_output.py
This patch has two related features.  The smaller one is to move any test assertions we write *outside* of any `except`-blocks, so that we don't e.g. raise and then immediately catch and discard an AssertionError.  Hopefully this would be fairly obvious, but better to avoid it entirely.
The larger feature is to exploit the RST `:raises Exception: ...` syntax in function docstrings - if we're calling a function with such docs, we can catch those exceptions and try a different input.  Non-builtin exceptions aren't supported because remembering to import them is a huge pain, but we're clever enough to avoid writing one exception handler inside another which subsumes it.  Support for Google-style and Numpy-style docstrings is planned for a future PR.
=> Improve exception handling in ghostwritten tests

.github/workflows/main.yml, build.sh, hypothesis-python/docs/development.rst, hypothesis-python/docs/support.rst, hypothesis-python/setup.py, hypothesis-python/tests/cover/test_annotations.py, hypothesis-python/tests/cover/test_lookup.py, hypothesis-python/tests/cover/test_lookup_py38.py, requirements/coverage.txt, requirements/test.txt, requirements/tools.txt, tooling/src/hypothesistooling/__main__.py
=> Update pinned dependencies

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/control.py, hypothesis-python/tests/nocover/test_targeting.py
Sometimes the test is simple enough that inlining the call to `target()` is nicer than needing three lines and a variable name; and it's trivial to support:
```python
assert target(abs(a - b)) < error_threshold
```
now works, because `target(x, label=...)` returns `x`.
Prompted by trying to write such code, and being a little surprised that we didn't already support it.
=> Allow `target()` inline in expressions

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/filtering.py, hypothesis-python/tests/cover/test_filter_rewriting.py, hypothesis-python/tests/cover/test_filtered_strategy.py
This is the last big step for rewriting numeric scalar filters (see #2701); after this and the early parts of #2907 Pandera checks will be a lot more efficient for free :tada:
=> AST-based filter rewriting for lambdas

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/misc.py, hypothesis-python/tests/nocover/test_pretty_repr.py
=> Ensure `filter` appears in repr of `just(...).filter(...)`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/__init__.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/misc.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/src/hypothesis/strategies/_internal/utils.py, hypothesis-python/tests/cover/test_type_lookup.py
We have some assertions and tests that assume all of our strategy functions were decorated with `@defines_strategy`, which has the side-effect of adding their names to a global `_strategies` dict. However, not all of our exported strategies actually end up in that dict.
In particular, the current version of the decorator always applies a layer of `LazyStrategy` indirection. There are several strategy functions that don't use that lazy-wrapping layer (whether deliberately or accidentally), so they also aren't registered in `_strategies`.
This PR therefore adds a `never_lazy` flag to `@defines_strategy`, and adds `@defines_strategy(never_lazy=True)` to all of the core strategy functions that are currently unregistered.
In practice, the biggest effect of this change is that …
=> Register all core strategy functions through `@defines_strategy`

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/tests/cover/test_fuzz_one_input.py, hypothesis-python/tests/nocover/test_modify_inner_test.py
adds `.hypothesis` to invalid tests.
this fixes #2966
I'm not quite sure where (or how) I should test it, I couldn't find any tests using .hypothesis other than the ones swapping the test function and that won't work here without making the invalid tests far more complicated...
all existing tests seem to pass.
=> add .hypothesis to invalid tests

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/tests/ghostwriter/test_ghostwriter_cli.py
Because printing "You can use seed() to reproduce..." doesn't really fit with the test code.
=> Quiet identity element search in binary-operation ghostwriter

hypothesis-python/tests/common/utils.py, hypothesis-python/tests/cover/test_arbitrary_data.py, hypothesis-python/tests/cover/test_explicit_examples.py, hypothesis-python/tests/cover/test_reflection.py, hypothesis-python/tests/cover/test_simple_strings.py, hypothesis-python/tests/cover/test_stateful.py, hypothesis-python/tests/cover/test_testdecorators.py, hypothesis-python/tests/nocover/test_floating.py, hypothesis-python/tests/nocover/test_testdecorators.py, hypothesis-python/tests/quality/test_discovery_ability.py
From https://github.com/HypothesisWorks/hypothesis/pull/2970#discussion_r637558955 I noticed that our own `raises` context manager is unnecessary, and indeed most of our tests already use `pytest.raises`.
This PR converts the few remaining holdouts.
We're a little bit inconsistent about `pytest.raises` vs `from pytest import raises`, but that was already the case in a few places, so I decided to keep the patch relatively slim and not change every single call site.
=> Replace our own `raises` test helper with `pytest.raises`

hypothesis-python/tests/conjecture/test_lstar.py, hypothesis-python/tests/cover/test_stateful.py, hypothesis-python/tests/cover/test_targeting.py, hypothesis-python/tests/nocover/test_lstar.py, hypothesis-python/tests/nocover/test_stateful.py, hypothesis-python/tests/nocover/test_targeting.py
These tests don't appear to be needed for coverage, and moving them out of the coverage suite reduces test time by several *minutes*.
=> Move some slow tests into `nocover/`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/utils.py, hypothesis-python/tests/cover/test_testdecorators.py, hypothesis-python/tests/nocover/test_integer_ranges.py, hypothesis-python/tests/quality/test_shrink_quality.py
Our docs say that `integers` should shrink towards positive values, but currently that isn't actually true for instances that have lower+upper bounds that span across zero.
Double bounded `integers` delegates to `integer_range`, which detects ranges that cross the designated centre value and draws a “sign bit” to determine whether to generate values upwards or downwards from the centre.
But the code in question interprets a drawn value of 0 as “below” instead of “above”, so shrinking tends to produce values below the centre if possible.
This patch negates the above/below flag, so that a drawn value 0 is treated as “above”, giving the intended behaviour.
=> Bounded `integers` should shrink towards positive values

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/regex.py, hypothesis-python/tests/cover/test_regex.py
Fixes #2982.
Most of `regex_strategy` is dedicated to figuring out how to apply leading/trailing padding, which is not relevant to `fullmatch` strategies. So it ended up being much cleaner to handle the full-match case as an early-exit that delegates to `base_regex_strategy`.
=> `from_regex("", fullmatch=True)` should only produce empty strings

hypothesis-python/tests/numpy/test_gen_data.py
```
=============================== warnings summary ===============================
hypothesis-python/tests/numpy/test_gen_data.py::test_can_minimize_float_arrays
/home/runner/work/hypothesis/hypothesis/hypothesis-python/.tox/coverage/lib/python3.8/site-packages/numpy/core/_methods.py:47: RuntimeWarning: invalid value encountered in reduce
return umr_sum(a, axis, dtype, out, keepdims, initial, where)
hypothesis-python/tests/numpy/test_gen_data.py::test_can_minimize_float_arrays
/home/runner/work/hypothesis/hypothesis/hypothesis-python/.tox/coverage/lib/python3.8/site-packages/numpy/core/_methods.py:47: RuntimeWarning: overflow encountered in reduce
return umr_sum(a, axis, dtype, out, keepdims, initial, where)
-- Docs: https://docs.pytest.org/en/stable/warnings.html
```
These warnings …
=> Avoid/ignore unhelpful numpy warnings in `test_can_minimize_float_arrays`

hypothesis-python/tests/nocover/test_database_usage.py, hypothesis-python/tests/nocover/test_imports.py, hypothesis-python/tests/nocover/test_lstar.py, hypothesis-python/tests/nocover/test_type_lookup_forward_ref.py
I took a look at the list of longest-running tests in the `nocover/` suite, and found quite a bit of low-hanging fruit.
Some of these tests went from ~20–30 seconds to ~1 second or less, with no loss of quality that I'm aware of.
=> Speed up some slow `nocover/` tests

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/utils.py
Setting up a `Sampler` is somewhat non-trivial, and there's no reason to do it every time we want to choose an integer width.
=> Use a single `Sampler` instance for all wide-range integer draws

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/collections.py, hypothesis-python/src/hypothesis/strategies/_internal/lazy.py, hypothesis-python/src/hypothesis/strategies/_internal/misc.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/tests/cover/test_sampled_from.py, hypothesis-python/tests/cover/test_searchstrategy.py, hypothesis-python/tests/cover/test_stateful.py
This is a small piece of cleanup that I've been meaning to do for a while.
Originally, the `do_filtered_draw` hook was added as a lightweight way for individual strategies to make filtering more efficient (specifically `sampled_from` in #1904), without having to fully override `.filter` with a custom strategy.
(At the time, no non-trivial strategy had a custom `.filter` implementation, so this was worthwhile.)
Over time, a few things changed:
- The hook was also used by `UniqueListStrategy` (#1891)
- Unique lists of `sampled_from` were further specialized to `UniqueSampledListStrategy` (#2031), bypassing the generic code in `UniqueListStrategy`
- More non-trivial implementations of `.filter` were added to rewrite simple filters on `integers()` into bounds updates (#2853)
All together, …
=> Simplify the `do_filtered_draw` hook

.github/workflows/main.yml
Quality tests are slow enough that we exclude them from our normal Linux/Mac builds, and instead rely on a dedicated `check-quality` task that runs as a separate CI action (on Linux only).
Windows builds sidestep `./build.sh` and invoke `pytest hypothesis-python/tests/` directly to run all of the tests. In doing so, they implicitly include the quality suite, which greatly increases build times.
We should be able to get away with testing them only in the `check-quality` CI action, so excluding quality tests from Windows builds should give us a significant speedup to some of our slowest actions.
=> Exclude `tests/quality/` from Windows CI builds

.github/workflows/main.yml
According to https://github.com/HypothesisWorks/hypothesis/pull/2736#issuecomment-754582115, CI caching was originally not enabled on MacOS because it wasn't one of the slowest tasks, so the extra effort to get it working would not have improved build times.
Well, now it is one of the slowest tasks! So here's an attempt to fix that.
=> Enable CI caching on MacOS

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/django/_fields.py, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/src/hypothesis/internal/filtering.py, hypothesis-python/src/hypothesis/provisional.py, hypothesis-python/src/hypothesis/strategies/_internal/collections.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/tests/common/utils.py, hypothesis-python/tests/cover/test_provisional_strategies.py, requirements/test.txt, requirements/tools.txt, tooling/src/hypothesistooling/__main__.py, whole-repo-tests/test_rst_is_valid.py
We are occasionally seeing flaky coverage in `provisional.py`. According to https://github.com/HypothesisWorks/hypothesis/pull/2992#issuecomment-850978280 this is because we are not reliably generating URLs that contain a fragment component.
=> Fix flaky coverage of fragments in the `urls` strategy

.github/workflows/main.yml, hypothesis-python/tox.ini
This should make CI log output easier to navigate.
=> Enable coloured terminal output in CI logs via `PY_COLORS=1` 🌈

hypothesis-python/tests/common/utils.py, hypothesis-python/tests/conjecture/test_utils.py, hypothesis-python/tests/cover/test_scrutineer.py, hypothesis-python/tests/nocover/test_explore_arbitrary_languages.py, hypothesis-python/tests/nocover/test_lstar.py
As noted in #2989, we should not be using `set(Phase) - {...}` to disable specific phases, because this has the side-effect of accidentally enabling the off-by-default `Phase.explain`.
I've changed the offending code to use `set(settings.default.phase)`, which should be more reliable.
=> Fix existing tests that accidentally enable `Phase.explain`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/pytestplugin.py, hypothesis-python/src/hypothesis/internal/compat.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinking/dfas.py, hypothesis-python/src/hypothesis/internal/conjecture/utils.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/reporting.py, hypothesis-python/tests/cover/test_float_nastiness.py, hypothesis-python/tests/cover/test_simple_strings.py, hypothesis-python/tests/nocover/test_regex.py, hypothesis-python/tests/nocover/test_strategy_state.py, hypothesis-python/tests/numpy/test_from_dtype.py, tooling/scripts/tool-hash.py, tooling/src/hypothesistooling/__main__.py
Most of these are left over from the Python 2 days, and never attracted enough attention to be cleaned up since then.
=> Remove various obsolete helper functions from `compat.py`

.github/workflows/main.yml, hypothesis-python/tox.ini
It's annoying to wait for a coverage build to complete, only to find that you don't get a report because one of the tests is failing (or flaky).
This PR tells tox to keep running subsequent tasks even if the test suite itself fails, so that we always get a coverage report.
(I've also tried adding the `.coverage` file as a build artifact, so that we can download it for local inspection if desired.)
=> Produce a coverage report even if the test suite fails

pytest.ini, tooling/src/hypothesistooling/__main__.py
When an `xfail` test unexpectedly passes, pytest switches to yellow output and includes the number of xpassing tests in its result line. However, by default it doesn't tell you which tests xpassed, making them difficult to track down from build logs.
=> Include xpassing tests in the pytest test summary

hypothesis-python/scripts/basic-test.sh
This is mainly intended to speed up Mac builds on CI, since GitHub's runners apparently have 3 cores allocated.
It should also speed up local builds on most machines.
(I'm not sure where the original `-n2` came from, but it predates the move to GitHub Actions for CI.)
=> Run the main non-coverage tests with `-nauto` instead of `-n2`

hypothesis-python/.coveragerc, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/compat.py, hypothesis-python/src/hypothesis/internal/coverage.py, hypothesis-python/tests/cover/test_compat.py, hypothesis-python/tests/nocover/test_compat.py, hypothesis-python/tests/numpy/test_floor_ceil.py
Follow-up to #3001, which removed some dead code but didn't manage to get far enough to be able to update the blocklist.
Most of the new annotations should be pretty uncontroversial.
=> Remove `compat.py` and other files from the coverage blocklist

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/src/hypothesis/internal/compat.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/utils.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/tests/cover/test_reflection.py, hypothesis-python/tests/nocover/test_compat.py
Almost all of this PR is the qualname cleanup I promised in https://github.com/HypothesisWorks/hypothesis/pull/3004#discussion_r644062244 - it turned out to be pretty easy, because `full_qualified_name()` had no callers outside of our tests (!!), and every other use of `x.__qualname__` is in a context where I could verify by inspection that the attribute would always be present.  (in Python 2 there might only be a `__name__` on types; in Python 3 that only happens for weird things like Numpy ufuncs and we only see those in the ghostwriter)
Then after reviewing all the ghostwriter logic about qualified names, I found two small user-visible changes which became the changelog for this release: avoiding treading `safe_load`/`unsafe_load` as a roundtrip, and looking on *any* module for ufuncs …
=> Clean up qualname logic (plus a user-visible ghostwriter tweak)

hypothesis-python/scripts/validate_branch_check.py, whole-repo-tests/test_validate_branch_check.py
This makes a few related improvements to our custom branch-coverage checker:
- When checking succeeds, we now print an explicit message that includes the number of branches checked.
- When the `branch-check` file is empty, we now fail with a message instead of silently succeeding.
- Line breaks are now a little nicer when reporting failures.
- Tests!
=> Produce more helpful output from `validate_branch_check.py`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/collections.py, whole-repo-tests/test_type_hints.py
See https://github.com/HypothesisWorks/hypothesis/issues/3005#issuecomment-854417951 - until [a planned extension](https://mail.python.org/archives/list/typing-sig@python.org/thread/LOQFV3IIWGFDB7F5BDX746EZJG4VVBI3/) to [PEP-646](https://www.python.org/dev/peps/pep-0646/) (i.e. type-level operators over variadic generics), this is the best we can do.  And it's been good enough in `one_of()` for years - it turns out that `n` is *usually* pretty small.
=> Annotate `tuples()` elements using overloads

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/scrutineer.py, hypothesis-python/tests/cover/test_scrutineer.py, hypothesis-python/tests/nocover/test_scrutineer.py
This set of patches makes a few related changes to [explain-mode](https://hypothesis.readthedocs.io/en/latest/settings.html#controlling-what-runs), aimed at improving the test-time and user-facing performance.  I think this is the best fix #2989 is going to get.
- Move all the not-run-under-coverage tests to `nocover` (duh)
- Use `__slots__` and some micro-optimisations in the `Tracer` class
- Only run the tracer if shrinking is enabled, though still starting immediately after the first failure (i.e. often in keep-generating mode)
- Disable the tracer immediately if a `DeadlineExceeded` error is raised.  The performance overhead of tracing interacts badly with deadlines, and "explaining" it in terms of some line of code is almost certainly wrong anyway.
=> Improve explain-mode performance

hypothesis-python/tests/nocover/test_recursive.py
I've noticed that we occasionally see a warning about an uncaught exception thrown on one of the worker threads in `test_drawing_from_recursive_strategy_is_thread_safe`.
Unfortunately I don't have an example handy, but from memory at least one of the exceptions involved was due to threads not being able to access the database file. Since the database isn't relevant to this test, I've disabled it in the hopes that it will get rid of the warning.
=> Avoid a flaky warning caused by multi-threaded DB access

hypothesis-python/docs/data.rst, hypothesis-python/tests/conftest.py
Closes #3042 - `min_size` is now a keyword-only argument.
Closes #3041 - to make running Hypothesis' selftest suite easier for external contributors, we now skip our random-seed checks if `pytest-randomly` is installed.  To ensure that we don't inadvertently disable those checks, crash if running our self-tests in CI with `pytest-randomly` installed.
=> Fix docs, and selftest compatibility with `pytest-randomly`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/cover/test_lookup_py39.py
Closes #3016; we'll need [CPython changes](https://bugs.python.org/issue41370) to actually get this working instead of just improving the error message.
I think what happened is that the builtin generics changes assumed that annotations would always be stored as strings, and the runtime introspection use-case just didn't arise until now.
=> Improve error message for recursive forward references with PEP585 builtin generics

conjecture-rust/.gitignore
=> Adds `Cargo.lock` to `.gitignore` in `rust/`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/tests/cover/test_given_error_conditions.py, tooling/src/hypothesistooling/__main__.py
This should prevent future confusion like #3054. 
While in the area, I also converted some `%`-formatting to f-strings, and made our build script print out the list of known tasks if you ask for an unknown task (so e.g. `make docs` will tell you that `make documentation` would work).
=> Improve error message when `@given()` is applied to an `async def` function

hypothesis-python/RELEASE.rst, hypothesis-python/scripts/basic-test.sh, hypothesis-python/src/hypothesis/extra/numpy.py
In #3067 @Zac-HD commented that mutating the helper methods docstrings should not effect the original method. I had used `copy.deepcopy` for this and thought I had tested it... but clearly not, as Sphinx generation in #3065 demonstrates :facepalm: 
This PR simply wraps the `valid_tuple_axes` and `mutually_broadcastable_shapes` strategies in `@proxies` before mutating their `__doc__`, replacing the use of `deepcopy`. I've tested this works when `extra.array_api` also interfaces with the array helpers.
=> Use @proxies instead of deepcopy for mutated array helpers

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/_array_helpers.py
For #3067  I wrapped all the strategies in `array_helpers.py` in `@defines_strategy()`... except `array_shapes` :man_facepalming: :woman_facepalming: :facepalm: 
I would write a test for this, but if the idea is to only have one place testing `array_helpers.py` stuff then this is covered in #3065 (how I caught this).
=> Wrap array_shapes in @defines_strategy

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/numpy/test_gen_data.py
Closes #3066.
Note that this *doesn't* change the behaviour for arrays which have a `fill` strategy; in those cases there's a tricky three-way tradeoff between speed, shrinking quality, and ability to assign elements to almost all indices (due to birthday paradox considerations).  Since performance is a real concern for array strategies and we typically *want* to be sparse anyway, I've kept the existing behaviour for that branch.
=> Faster strategy for `arrays(..., unique=True)` 

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/compat.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/cover/test_compat.py, hypothesis-python/tests/cover/test_lookup_py39.py, hypothesis-python/tests/typing_extensions/test_backported_types.py
=> Resolves strategies from `Annotated` type

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/control.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/errors.py, hypothesis-python/src/hypothesis/extra/pytestplugin.py, hypothesis-python/src/hypothesis/internal/conjecture/datatree.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinking/dfas.py, hypothesis-python/src/hypothesis/internal/conjecture/utils.py, hypothesis-python/src/hypothesis/internal/coverage.py, hypothesis-python/src/hypothesis/internal/escalation.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/internal/validation.py, hypothesis-python/src/hypothesis/provisional.py, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/src/hypothesis/statistics.py, hypothesis-python/src/hypothesis/strategies/_internal/attrs.py, hypothesis-python/src/hypothesis/strategies/_internal/collections.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/datetime.py, hypothesis-python/src/hypothesis/vendor/pretty.py, hypothesis-python/tests/cover/test_health_checks.py, hypothesis-python/tests/cover/test_stateful.py, requirements/tools.in, requirements/tools.txt
Closes #3070, and adds `FailedHealthCheck` to our list of exception types where we might say "even though this was raised inside Hypothesis, it's OK to trim the traceback" (with some refactoring).
Also closes #3072, because they were inspired by the same digging session and are easier to communicate as a set.
=> Implement `return_value` healthcheck in stateful testing

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/cover/test_slices.py
The motivation here is that we discovered in  https://github.com/HypothesisWorks/hypothesis/pull/3065#issuecomment-915346847 that the `.start` index could be *equal* to the `size` argument, which isn't a valid index.  Python and Numpy collections are fine with this - an out-of-range slice just selects no elements - but it's undefined behaviour in the Array API standard and therefore an `IndexError` in `numpy.array_api`.
And then while poking at `slices()` I made it generate a wider variety of `step` arguments too.
=> Fix off-by-one error in `st.slices()`, and allow `step=None`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/tests/cover/test_reflection.py
=> Fix for inline `given()` on bound methods

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/ghostwriter/recorded/magic_builtins.txt, hypothesis-python/tests/ghostwriter/test_expected_output.py
Closes #2977:  `$ hypothesis write max` used to produce:
```python
```
but now writes a test with correct handling of positional and keyword-only arguments:
```python
from hypothesis import given, strategies as st
@given(
iterable=st.one_of(st.iterables(st.integers()), st.iterables(st.text())),
default=st.nothing(),
key=st.nothing(),
)
def test_fuzz_max(iterable, default, key):
max(iterable, default=default, key=key)
```
=> Ghostwriter support for more builtins

AUTHORS.rst, guides/documentation.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py
Async functions are Callables that return a Coroutine, so to support a proper annotation in this particular case I added to the decorated Callable type hint the possible return of a `Coroutine[Any, Any, None]`.
Please note that the returned coroutine is conforming with the same requirement as a normal Callable (it should return None as well)
Fixes: #3099
=> Fix given decorator type hint when decorating async functions

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/array_api.py, hypothesis-python/tests/array_api/test_argument_validation.py
Fixes `None` being inferred as `xp.float64` for these methods when using a NumPy strategies namespace. This happens as a result of `numpy.array_api.float64` aliasing to `np.dtype('float64')`, which awkwardly has equality with `None`. This is actually *meant* to be deprecated behaviour—see numpy/numpy#18434.
=> Ensure `dtype=None` fails in both `xps.arrays()` and `xps.from_dtype()`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/_settings.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/extra/_array_helpers.py, hypothesis-python/src/hypothesis/internal/conjecture/dfa/lstar.py, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/src/hypothesis/strategies/_internal/collections.py, hypothesis-python/src/hypothesis/strategies/_internal/deferred.py, hypothesis-python/src/hypothesis/strategies/_internal/lazy.py, hypothesis-python/src/hypothesis/strategies/_internal/numbers.py, hypothesis-python/src/hypothesis/strategies/_internal/random.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/src/hypothesis/vendor/pretty.py, hypothesis-python/tests/nocover/test_baseexception.py, hypothesis-python/tests/quality/test_poisoned_lists.py, hypothesis-python/tests/quality/test_poisoned_trees.py, requirements/test.txt, requirements/tools.txt
This matches the behaviour of `pytest`, and means we'll shrink to minimal examples, check for `Flaky` tests, etc.  This is *unlike* `KeyboardInterrupt` where we stop and reraise immediately, though it's possible that the surrounding context will treat them specially in some way.
Closes #2223, after a long wait!
=> Treat `SystemExit` and `GeneratorExit` as normal test failures

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/array_api.py, hypothesis-python/tests/array_api/test_arrays.py
Just the clean-up part of #3105 as well as the relevant review commits. I included a test for 0d arrays (already passes).
I imagine we want to just not allow multi-dimensional array elements? If that's the case, I'll note writing checks that rely on Array API behaviour (i.e. not just `numpy.array_api`) is pretty tricky (impossible?) to do efficiently... but relying on current behaviour leads to one or two obscure logical paths where we aren't raising `InvalidArgument`. Basically, I will need to think about it more, and it's something tricky enough that I don't think will be appropriate for this PR.
=> Clean up `extra.array_api.ArrayStrategy`

hypothesis-python/docs/conf.py, hypothesis-python/docs/reproducing.rst, hypothesis-python/tests/ghostwriter/test_expected_output.py, requirements/tools.in, requirements/tools.txt, tooling/src/hypothesistooling/__main__.py
See https://github.com/felix-hilden/sphinx-codeautolink/discussions/29 ; once we get a release with these features (tonight?) I'll update the requirements file with a proper pin and we can merge!
Online preview docs here: https://hypothesis--3112.org.readthedocs.build/en/3112/details.html
(todo: also `import hypothesis.strategies as st`)
=> Add `sphinx-codeautolink` for hyperlinks in code samples

hypothesis-python/setup.py
Python 3.10 was released on 2021-10-04:
* https://discuss.python.org/t/python-3-10-0-is-now-available/10955
=> Declare support for Python 3.9 and 3.10

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinking/dfas.py, hypothesis-python/tests/cover/test_fuzz_one_input.py, hypothesis-python/tests/cover/test_random_module.py, hypothesis-python/tests/nocover/test_randomization.py, hypothesis-python/tests/quality/test_normalization.py, hypothesis-python/tests/quality/test_zig_zagging.py
We're actually already great about passing around `Random` instances rather than using the global state, so this is a pretty small patch.  Closes #2135.
=> Seed off a single `Random` instance, not global state

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/entropy.py, hypothesis-python/src/hypothesis/strategies/_internal/datetime.py, hypothesis-python/tests/cover/test_example.py, hypothesis-python/tests/cover/test_lookup.py, hypothesis-python/tests/cover/test_lookup_py37.py, hypothesis-python/tests/cover/test_lookup_py38.py, hypothesis-python/tests/datetime/test_pytz_timezones.py, pytest.ini
Thanks to Paul for [reminding me that `xpass` is a pass by default](https://blog.ganssle.io/articles/2021/11/pytest-xfail.html); this PR enables strict mode so that we notice when xfail-decorated tests are not in fact failing.  I expect this to turn up a few more cases where we expect failure *if* some condition holds; in those cases we should use conditional xfails for clarity.
=> Use xfail strict mode

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/numbers.py, hypothesis-python/tests/nocover/test_floating.py
It turns out that we *can* generate subnormal values; it's just that we do so with negligible probability because they only occur for one-in-2^11 possible exponents. The obvious workaround is to just add a handful of special values to our `NASTY_FLOATS` table, and so here's a PR to do just that.  Fixes #2976.
=> Generate subnormal floats

hypothesis-python/RELEASE.rst, hypothesis-python/docs/changes.rst, hypothesis-python/src/hypothesis/strategies/_internal/numbers.py, hypothesis-python/src/hypothesis/vendor/pretty.py, hypothesis-python/tests/cover/test_pretty.py, hypothesis-python/tests/nocover/test_floating.py
"Trap on snan" bit me a while ago, and this notation would have really helped to clarify what was going on in CI logs (though it generally doesn't affect e.g. numpy array elements).  It also boosts the probability of getting the canonical `snan` with only the last mantissa bit set, since snan is otherwise very very much rarer than standard nan.
After this patch, we have the property that *either* floats bitwise-roundtrip from their pretty reprs (new for `-nan`), *or* we have a comment to note that we printed however many signaling NaNs.
=> Distinguish negative and signaling NaNs in our pretty-printer

hypothesis-python/.coveragerc, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/extra/cli.py, hypothesis-python/src/hypothesis/extra/pytestplugin.py, hypothesis-python/src/hypothesis/internal/escalation.py, hypothesis-python/src/hypothesis/utils/terminal.py
We now respect the `pytest --tb={no,short,native,auto,long}` configuration; or if you aren't using `pytest` but do have [`better-exceptions`](https://github.com/Qix-/better-exceptions) active we'll use that.  Closes #3116.
As a bonus: tries to detect light-colored terminal backgrounds, and prints ghostwritten code with light-theme syntax highlighting.  This doesn't always work, but it's a lot better than the status quo of assuming a dark background and there's a clear place for future improvements.
=> Optional `pytest` and `better-exceptions` integration for `MultipleFailures`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/entropy.py, hypothesis-python/src/hypothesis/strategies/_internal/lazy.py, hypothesis-python/tests/cover/test_random_module.py
See #3131; this is a nice performance optimization for anyone registering lots of transient `Random` instances.
I experimented with using the same technique under `register_type_strategy()` etc., but there are so many can't-be-weak caches, closures, and references involved in strategy internals that there's no practical way to make it happen without serious performance degradation.
The exception to *that* is `unwrap_cache`, where if the outer strategy is dropped we certainly don't need to remember what it wrapped; it's a small but cheap memory-use reduction.
=> Use weak references in `register_*` functions so that garbage collection still works

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/codemods.py, hypothesis-python/src/hypothesis/extra/pandas/impl.py, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/tests/codemods/test_codemods.py
This is a prerequisite for handling `allow_subnormal` properly in #3156.
(plus some repr fixes for #3144)
=> Faster, safer kwonly-arg codemods

hypothesis-python/RELEASE.rst, hypothesis-python/docs/changes.rst, hypothesis-python/docs/details.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/cover/test_lookup_py39.py
This turned out to be a much simpler fix that I feared.  Fixes #3080 for @SDesch.
=> Handle unions of builtin generics

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/utils/terminal.py, hypothesis-python/tests/cover/test_lookup.py
=> Register `builds()` of recursive types with constraints

hypothesis-python/RELEASE.rst, hypothesis-python/setup.py, hypothesis-python/src/hypothesis/extra/_array_helpers.py, hypothesis-python/src/hypothesis/strategies/_internal/datetime.py, hypothesis-python/tests/numpy/test_argument_validation.py, tooling/src/hypothesistooling/__main__.py
Closes #3167.
I also made our weekly update PR bump the minimum required version of `tzdata`: while we usually want to permit working with older versions of our dependencies, the TZ database is an exception and should always be as kept up-to-date as possible.
=> Document `st.timezones()` windows-only dependency on `tzdata`, bump min version

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/vendor/pretty.py
Fixes #3114.  Testing this turns out to be a flaky PITA due to dependencies and versions, but using the example from that issue:
```
Falsifying example: test_always_increasing(
df_a=
A
2021-01-01  1
, df_b=
A
2021-01-01  0
2021-01-02  0
,
)
```
(the annoying lack of a newline in `, df_b=` is not pandas-specific and surprisingly tricky, so we can revisit that later)
=> Break between pprinting `DataFrame`s in failing examples

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/_array_helpers.py, hypothesis-python/src/hypothesis/extra/array_api.py, hypothesis-python/src/hypothesis/internal/floats.py, hypothesis-python/tests/array_api/test_arrays.py, hypothesis-python/tests/numpy/test_gen_data.py
Addresses an issue pointed out in #3170 regarding the quality of shapes generated by `hypothesis.extra.numpy.mutually_broadcastable_shapes`
There was a bug, which prevented the strategy from generating singleton dimensions paired against non-singleton dimensions, across shapes, unless those dimensions were aligned with the provided base-shape.
=> Fix over-constrained singleton patterns from mutually broadcastable shapes

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/_array_helpers.py, hypothesis-python/src/hypothesis/extra/array_api.py, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/tests/array_api/test_argument_validation.py, hypothesis-python/tests/array_api/test_indices.py, hypothesis-python/tests/numpy/test_gen_data.py
Resolves #3166.
I opted to simply filter the base `extra._array_helpers.BasicIndexStrategy` used inside of `extra.array_api._indices()`, which seems to do the trick... I didn't want to play around the internals haha. Let me know if you'd like a solution that doesn't filter itself. I'm fairly happy with the testing situation for indices now at least.
=> Prevent `xps.indices()` from generating indices that flat index arrays

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/strategies/_internal/utils.py
The use of @proxies to help "share" strategies between `hypothesis.extra.numpy` and `hypothesis.extra.array_api` left some strategies with obfuscated signatures.
E.g. in VSCode:
This patch provides annotations for `@proxies` and thus remedies this:
=> add annotations to @proxies

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/regex.py, hypothesis-python/tests/cover/test_regex.py
Python allows a trailing newline for `...$` regex, but jsonschema doesn't - and that's the only blocker for [perfect compatibility with the recommended jsonschema regex syntax](https://json-schema.org/understanding-json-schema/reference/regular_expressions.html), which is a problem in practice (see e.g. https://github.com/schemathesis/schemathesis/issues/1241 and https://github.com/schemathesis/schemathesis/issues/1350).
I'm hardly *delighted* to carry such a patch in Hypothesis, but it's clearly the best place to solve this problem for many end-users downstream.  We already have similar patches to handle e.g. library-specific `Skip` exceptions, `numpy.random`, and a few other things, and as private internals this can be cleanly and immediately removed if a better solution becomes …
=> Private internal patch to help downstream jsonschema regex support

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/pandas/impl.py, hypothesis-python/tests/pandas/test_argument_validation.py, hypothesis-python/tests/pandas/test_data_frame.py
Closes #3133 and closes #3144.  In both cases it's either impossible or too-magical to actually support what they're trying to do, but we can give detailed and helpful error messages 😁
=> Improve error messages for Pandas when `dtype=object` is omitted

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/typing_extensions/test_backported_types.py
Refs #2978
Refs https://github.com/HypothesisWorks/hypothesis/pull/3201
I think that duplication is now pretty visible. Should I do something about it? 🤔
=> Forbid to use or register `ClassVar`

hypothesis-python/tests/pytest/test_capture.py
Yes, PyPy3.9 is coming and once again the expected line number
in test_healthcheck_traceback_is_hidden needs to be updated.  This time
PyPy3.9 aligns it with CPython 3.8, so we expect: 6 for CPython < 3.8
and PyPy < 3.9, and 7 for CPython >= 3.8 and PyPy >= 3.9.
=> Fix test_healthcheck_traceback_is_hidden for PyPy3.9

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/compat.py, hypothesis-python/src/hypothesis/internal/escalation.py
As discussed in https://github.com/HypothesisWorks/hypothesis/pull/3191#issuecomment-992533311; this is the part that has nothing at all to do with `__note__` and the draft PEP-678.
=> Distinguish multiple `ExceptionGroup`s by their inner exceptions 

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/django/_impl.py, hypothesis-python/src/hypothesis/extra/lark.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/lazy.py, hypothesis-python/src/hypothesis/strategies/_internal/random.py, hypothesis-python/tests/cover/test_annotations.py, hypothesis-python/tests/cover/test_direct_strategies.py, hypothesis-python/tests/cover/test_posonly_args_py38.py, hypothesis-python/tests/django/toystore/test_given_models.py
This patch addresses about two-thirds of #2706 - notably,
- `@st.composite` strategies may now use positional-only arguments, which were added in Python 3.8, and
- the first arguments to `st.builds()` and the Django extra's `from_model()` are now true positional-only arguments
This is basically just a nice cleanup to have; for API clarity I don't intend to support nontrivial signatures in `@given()`-wrapped tests.  That's also some scary core code, so I'm leaving the relevant no-user-impact refactoring in there for later.
=> Use `signature` so that we support positional-only arguments

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/tests/nocover/test_modify_inner_test.py
Closes #3245.
@rsokl correctly called this one as the change to `follow_wrapped`; after digging in I think we actually don't want `@proxies` to follow wrappers so the patch is simple.  Unfortunately GH Actions seem to be degraded at the moment, so I can't merge and release it tonight... we'll shoot for 36 hours instead I guess.
=> Fix regression in `@proxies`

hypothesis-python/setup.py
Many automated tools expect the license attribute in setup.py to be an SPDX
compatible identifier (even though PEP 639 has not yet been adopted), so
they can identify the licenses in use by a project.
=> Use an SPDX identifier for the Python license

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/numbers.py
Should help out any users who hit #3265-like issues more quickly, *and* without hitting our issue tracker.  Win-win!
=> Better error if Python was compiled with `-fno-signed-zeros`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/cli.py, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/tests/ghostwriter/recorded/sorted_self_error_equivalent_1error.txt, hypothesis-python/tests/ghostwriter/recorded/sorted_self_error_equivalent_2error_unittest.txt, hypothesis-python/tests/ghostwriter/recorded/sorted_self_error_equivalent_simple.txt, hypothesis-python/tests/ghostwriter/recorded/sorted_self_error_equivalent_threefuncs.txt, hypothesis-python/tests/ghostwriter/test_expected_output.py
The idea is that this is useful for cases where you (or your students, or your code synthesis tool, or whatever) are trying to replicate the behaviour of an existing function - it's actually fine to test with over-broad strategies and get an error, so long as you get *the same error from both*.  Also uses `target()` so that we aim to spend at least half our time on valid inputs, if we've seen any.
It's a large diff, but most of that is just reference-output files for the tests!  Closes #3267.
=> Add new `--errors-equivalent` Ghostwriter

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/tests/cover/test_testdecorators.py
This is obviously a rather niche use, but supporting it makes sense under the simple model of "a decorator is just application of a higher order function".  And it used to work, before I did some signature-related refactoring a few months ago.
=> Fix `given(...)(lambda x: ...)()`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/conftest.py, hypothesis-python/tests/cover/test_lookup_py310.py
=> Support PEP-604 `int | str` syntax for union types

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/array_api.py, hypothesis-python/tests/array_api/README.md, hypothesis-python/tests/array_api/common.py, hypothesis-python/tests/array_api/conftest.py, hypothesis-python/tests/array_api/test_argument_validation.py, hypothesis-python/tests/array_api/test_arrays.py, hypothesis-python/tests/array_api/test_from_dtype.py, hypothesis-python/tests/array_api/test_indices.py, hypothesis-python/tests/array_api/test_pretty.py, hypothesis-python/tests/array_api/test_scalar_dtypes.py
Should resolve #3085. Very much WIP—namely have to update the remaining tests. Just making a PR now to see if folks have any thoughts.
Per https://github.com/HypothesisWorks/hypothesis/issues/3085#issuecomment-1079552745,
> Let's define a `HYPOTHESIS_TEST_ARRAY_API` env var - if it's not set, we do the current behaviour of testing against the mock and against `numpy.array_api` (if that's available?). You can then set the var to the import name of another array API implementation to test that (erroring if it's not installed), or to the special value `all` to test everything installed via the entry point (and error if there are none).
I wrote a [readme](https://github.com/honno/hypothesis/blob/parametrize-xp-tests/hypothesis-python/tests/array_api/README.md) which should describe what I've …
=> Support testing any array module in `tests/array_api`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/strategies/_internal/functions.py, hypothesis-python/src/hypothesis/strategies/_internal/lazy.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/src/hypothesis/vendor/pretty.py, hypothesis-python/tests/cover/test_functions.py, hypothesis-python/tests/cover/test_pretty.py, hypothesis-python/tests/cover/test_reflection.py
Fixes #3253.
This includes some other function-related cleanup related to helper functions - mostly replacing the `arg_string` helper with a `repr_call` helper, since that's what we always use it for.  The new helper also knows to wrap lambdas in parens to make the call syntax valid.
=> Quieter and prettier `functions()` strategy

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/tests/cover/test_lookup.py, hypothesis-python/tests/nocover/test_type_lookup_future_annotations.py
When resolving a TypedDict in a file with `from __future__ import annotations`, we were using `thing.__annotations__`, which would return unresolved ForwardRefs.  
For simple examples, this could be handled by later code that resolves ForwardRefs of builtins.  But it would fail the moment a complex annotation was provided.
This PR switches to using [typing.get_type_hints](https://docs.python.org/3/library/typing.html#typing.get_type_hints) which evalutates the forward references for us, returning the actual type.
=> Correctly retrieve forward referenced annotations from typed dictionaries

hypothesis-python/RELEASE.rst, hypothesis-python/src/_hypothesis_pytestplugin.py, hypothesis-python/tests/pytest/test_fixtures.py
We would already fail the test nicely if you applied `@given()` to a fixture, but the reverse was not true - and in that case `pytest` would cheerfully never notify you that you had an unused fixture which looked *an awful lot like a test*.  Since [I observed this in practice lately](https://github.com/zenml-io/zenml/blob/905a60ea90a3279a019dd298114ce4b1f7a9fcc9/tests/unit/io/test_fileio.py#L150-L152), it's now an explicit error.
=> Explicit error if `@pytest.fixture()` is applied after `@given()`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/errors.py, hypothesis-python/src/hypothesis/executors.py, hypothesis-python/src/hypothesis/internal/escalation.py, hypothesis-python/src/hypothesis/internal/intervalsets.py, hypothesis-python/src/hypothesis/internal/lazyformat.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/src/hypothesis/utils/conventions.py, hypothesis-python/tests/conftest.py, hypothesis-python/tests/cover/test_lookup.py, hypothesis-python/tests/cover/test_lookup_py37.py, requirements/coverage.txt, requirements/test.txt, requirements/tools.txt, whole-repo-tests/test_mypy.py, whole-repo-tests/test_pyright.py
Now type checkers will flag cases where positional and keyword arguments are both provided as inputs to `@given`. Also removes unnecessary usage of a `TypeVar` from `@given`'s annotations. 
Closes #3294, closes #3295.
=> Update annotations for `@given`

.github/workflows/main.yml, build.sh, hypothesis-python/tox.ini, tooling/src/hypothesistooling/__main__.py, whole-repo-tests/test_ci_config.py
Most of this PR is the tooling changes, which will automatically update most of our CI config as new Python versions are released, and then fail CI as a reminder to do the last few fiddly manual bits too.  I think this is a good balance between automation and brittleness.
Oh, and adds pypy39 to our CI, since that's been released now 🥳
=> Add pypy39 to CI; add tests so we notice new releases in future

hypothesis-python/RELEASE.rst, hypothesis-python/scripts/basic-test.sh, hypothesis-python/src/hypothesis/provisional.py, hypothesis-python/src/hypothesis/strategies/_internal/datetime.py, hypothesis-python/src/hypothesis/strategies/_internal/regex.py, hypothesis-python/tests/cover/test_settings.py, hypothesis-python/tests/nocover/test_recursive.py, pytest.ini, whole-repo-tests/test_mypy.py
This would uncover various issues which otherwise pass ~silently on CI:
- #3309
- Using [deprecated](https://docs.pytest.org/en/7.1.x/deprecations.html#using-pytest-warns-none) `pytest.warns(None)`
Submitting this so that I can see a full CI run to check if there's anything else I didn't see locally. Would be happy to fix the two issues above. Should such a fix be in separate PRs, or should I add them here?
=> Turn warnings into errors for tests

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/docs/changes.rst, hypothesis-python/setup.py, hypothesis-python/src/hypothesis/provisional.py, hypothesis-python/src/hypothesis/strategies/_internal/datetime.py
`traversable.read_text` raises a ValueError in python 3.10
Sample Error with `hypothesis==6.45.1`: 
```
tests/tracer/test_http.py:3: in <module>
from hypothesis.provisional import urls
<frozen importlib._bootstrap>:1027: in _find_and_load
???
<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
???
<frozen importlib._bootstrap>:688: in _load_unlocked
???
.riot/venv_py3103_mock_pytest700_pytest-mock_coverage_pytest-cov_opentracing_hypothesis/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:170: in exec_module
exec(co, module.__dict__)
.riot/venv_py3103_mock_pytest700_pytest-mock_coverage_pytest-cov_opentracing_hypothesis/lib/python3.10/site-packages/hypothesis/provisional.py:37: in <module>
_tlds = traversable.read_text().splitlines() …
```
=> fix(provisional): traversable.read_text error handling

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/tests/ghostwriter/recorded/magic_builtins.txt, hypothesis-python/tests/ghostwriter/recorded/re_compile.txt, hypothesis-python/tests/ghostwriter/recorded/re_compile_except.txt, hypothesis-python/tests/ghostwriter/recorded/re_compile_unittest.txt
Closes #3311, which lists the tables that I worked off to write this function.  We now guess strategies for 16,758,972 (8.43%) of 198,892,807 total arguments - excluding the staggeringly common (96,322,728) `self` argument which Hypothesis should never need to generate.
I actually feel pretty good about this: almost nine percent of all arguments is a pretty big win, and I think that the table below shows these are "reasonable guesses" that users will understand, even if they're not correct in *all* cases.  
<details>
<summary>Table of all most-common arguments, with guessed strategy (if any)</summary>
| Name | Count | Percentage | Strategy |
| :---: | ---: | ---: | :--- |
|    kwargs    | `4,664,756` | `2.345%` |  |
|      x       | `4,596,739` | `2.311%` |  |
|     args     | `4,563,483` …
=> Ghostwrite for many more names

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/__init__.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/cover/test_uuids.py, hypothesis-python/tests/nocover/test_uuids.py, requirements/coverage.txt, requirements/tools.txt, whole-repo-tests/test_mypy.py
Fixes #3263
Allow `strategies.uuids` can generate nil uuids
- Contributed as a part of PyConUS2022 mentored sprint
=> strategies.uuids can generate nil uuids

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/compat.py, hypothesis-python/tests/cover/test_type_lookup.py
I noticed this via the ghostwriter when playing around with the recent keyword-related issues.  Intending to merge pretty quickly, but might be of interest to @sobolevn too.
=> Fix rare type hints issue

AUTHORS.rst, CONTRIBUTING.rst
When testing the setup for contributors, the file extensions needed to be changed from _.txt_ to _.in_. File extensions have been updated, and the installation procedures tested satisfactorily.
=> change requirement file type

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/utils.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/conjecture/test_utils.py, hypothesis-python/tests/ghostwriter/recorded/hypothesis_module_magic.txt, hypothesis-python/tests/nocover/test_conjecture_utils.py, hypothesis-python/tests/nocover/test_type_lookup.py, hypothesis-python/tests/typing_extensions/test_backported_types.py
Banning the non-runtime types in from_type. See #2978 and #3280 for more detail.
=> Banning non runtime type in from_type

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/typing_extensions/test_backported_types.py
Added handling of annotation of `Required` and `NotRequired` in `TypedDict` in `from_typed`.
Closes #3339
=> Handle TypedDict classes with PEP-655 (Not)Required keys

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/floats.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/src/hypothesis/internal/floats.py, hypothesis-python/src/hypothesis/strategies/_internal/numbers.py, hypothesis-python/tests/conjecture/test_float_encoding.py, hypothesis-python/tests/conjecture/test_shrinker.py, hypothesis-python/tests/cover/test_float_utils.py, hypothesis-python/tests/nocover/test_simple_numbers.py
=> Fold FixedBoundedFloatStrategy into FloatStrategy

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/docs/changes.rst, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/src/hypothesis/strategies/_internal/numbers.py, hypothesis-python/tests/array_api/test_from_dtype.py, hypothesis-python/tests/array_api/test_indices.py, hypothesis-python/tests/cover/test_subnormal_floats.py, hypothesis-python/tests/numpy/test_fill_values.py, hypothesis-python/tests/pytest/test_capture.py, tooling/src/hypothesistooling/projects/hypothesispython.py, whole-repo-tests/test_release_files.py
=> Better doc formatting in extra.numpy.arrays()

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/datetime.py
It took me an inordinate amount of time to realize that [`strategies.timezones`](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.timezones) exists, so I thought it would be helpful to mention it in the [`strategies.datetimes`](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.datetimes) documentation next to the other timezone strategies.
=> Reference timezone strategies from datetimes docstring

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/vendor/pretty.py, hypothesis-python/tests/cover/test_pretty.py
Order of dictionaries is now enforced in Python 3.7 and higher. This means that the original order of dictionaries matters for falsifying examples.
This PR closes #3370. 
This PR was kindly supported by [Ordina Pythoneers](https://www.ordina.nl/vakgebieden/python/).
=> Remove sorting of dictionaries in pretty.printer. #3370

hypothesis-python/RELEASE.rst, hypothesis-python/setup.py, hypothesis-python/src/hypothesis/control.py, hypothesis-python/src/hypothesis/errors.py, hypothesis-python/src/hypothesis/internal/compat.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/cover/test_control.py, hypothesis-python/tests/cover/test_float_utils.py, hypothesis-python/tests/cover/test_stateful.py, hypothesis-python/tests/cover/test_verbosity.py
Extracted from #3308 (see also #3175) for the sake of smaller and easier-to-read diffs.
I'll then try to pick up *just* the `__notes__` changes in a separate PR, and defer the replacement of `MultipleFailures` until Pytest displays `ExceptionGroup` inner exceptions.
=> Simple initial uses of `ExceptionGroup`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/extra/django/_impl.py, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, requirements/tools.txt, whole-repo-tests/test_mypy.py, whole-repo-tests/test_pyright.py
Closes #3379 
[cb05529](https://github.com/HypothesisWorks/hypothesis/pull/3382/commits/cb05529862960dfc3fb8f450fca69563e4a83f58) and [db5ed42](https://github.com/HypothesisWorks/hypothesis/pull/3382/commits/db5ed42b35328fe23a9c70ce97458e767b11ca77) should make the test suite fail. (our pyright tests *would* fail for db5ed42 if we were using the `pyright` 1.1.250 or above)
=> Fix `InferType` and improve type-checker tests

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/tests/cover/test_core.py, hypothesis-python/tests/cover/test_fuzz_one_input.py
=> Avoid silently skipped tests

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/filtering.py, hypothesis-python/src/hypothesis/strategies/_internal/numbers.py, hypothesis-python/tests/cover/test_filter_rewriting.py
One of the remaining pieces of #2701, following the `integers()` support in https://github.com/HypothesisWorks/hypothesis/pull/2853 and https://github.com/HypothesisWorks/hypothesis/pull/2878.  
Thanks to @pschanely for https://github.com/HypothesisWorks/hypothesis/pull/3327 which made this possible!
=> Filter-rewriting for `st.floats()`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/extra/django/_impl.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/random.py, hypothesis-python/tests/cover/test_annotations.py, hypothesis-python/tests/cover/test_functions.py, hypothesis-python/tests/cover/test_lookup_py38.py, hypothesis-python/tests/cover/test_reflection.py
This is a good chunk of the remaining work on #2706.
I'd suggest reviewing commit-by-commit, and TBH leaning pretty heavily on all the tests passing.
=> Use `inspect.signature()` for argument conversion and `define_function_signature()`

hypothesis-python/RELEASE.rst, hypothesis-python/src/_hypothesis_pytestplugin.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/cover/test_statistical_events.py, hypothesis-python/tests/pytest/test_checks.py
Inspired by https://stackoverflow.com/q/72843753 and the extremely verbose traceback shown in https://stackoverflow.com/q/72792829.
=> Improve pytest error tracebacks and fix weakref error in `event()`

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/_settings.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/compat.py, hypothesis-python/src/hypothesis/internal/conjecture/choicetree.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/filtering.py, hypothesis-python/src/hypothesis/internal/floats.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/cover/test_internal_helpers.py, hypothesis-python/tests/cover/test_randoms.py, hypothesis-python/tests/nocover/test_database_usage.py, mypy.ini, whole-repo-tests/test_mypy.py
Being a follow-up to https://github.com/HypothesisWorks/hypothesis/pull/3219, now that [Mypy support for `Concatenate`](https://mypy-lang.blogspot.com/2022/04/mypy-0950-released.html) has been out for long enough for most users to pick up - since 0.950, April 2022.
(We explictly *don't* promise any degree of compatibility with anything but a best-effort attempt to support the latest state of the static-type-checking ecosystem, but giving people more than a few days to update like this seems reasonable to me.  The whole *point* of this is to provide a better user experience, after all!)
=> Use `ParamSpec` to precisely annotate `@st.composite` and `st.functions()`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/tests/numpy/test_from_dtype.py
This has been a saga:
- First implemented in https://github.com/HypothesisWorks/hypothesis/pull/2307/ (Jan 2020)
- Reverted in https://github.com/HypothesisWorks/hypothesis/pull/2329 because of https://github.com/numpy/numpy/issues/15363
- Retried in https://github.com/HypothesisWorks/hypothesis/pull/2455, abandoned due to more upstream errors
I retried again hoping that we could get everything working by the end of the Scipy sprints, but it turns out to *just work<sup>TM</sup>*; so here we go.  I've manually tested it on 1.19.0, 1.20.0, 1.21.0, 1.22.0, and in CI for the latest version of Numpy.
=> Generate non-UTF-8 unicode for Numpy arrays

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/cover/test_annotations.py, hypothesis-python/tests/cover/test_composite.py, hypothesis-python/tests/cover/test_reflection.py, hypothesis-python/tests/cover/test_statistical_events.py, hypothesis-python/tests/nocover/test_baseexception.py, hypothesis-python/tests/nocover/test_labels.py, hypothesis-python/tests/pytest/test_capture.py, hypothesis-python/tests/pytest/test_checks.py, hypothesis-python/tests/typing_extensions/test_backported_types.py
Work by @bomtall, @gzaxel, and me, to issue a deprecation warning when people misuse `st.composite` in a function that does not use the first argument `draw`. This closes #3384.
The original (messy) history and discussion can be found in #3405.
=> Fix issue 3384

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/cover/test_complex_numbers.py, tooling/ignore-list.txt
Fixes #3390.
Adds the `allow_subnormal` argument to `complex_numbers` by applying it to both the real and imaginary parts separately.
=> Allow subnormal in complex_numbers

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
Fixes #3403.
This PR proposes changes to achieve the following behavior:
> wherever user code leads `hypothesis` to raise a warning, that warning should point back to a file and line number in the user's code, instead of in `hypothesis`'s internals.
Creating a test script which causes most of the warnings mentioned in https://github.com/HypothesisWorks/hypothesis/issues/3403#issuecomment-1186549745 to be raised.
<details><summary>test_warnings.py (click me)</summary>
The warning from `database._db_for_path()` is only raised when you try to point the example database at a path with limited permissions, so I created one like this:
```shell
```
Then put the following in a file `test_warnings.py`
```python
from hypothesis import given, example, strategies as st
from hypothesis.configuration …
```
=> ensure warnings point to non-hypothesis code (fixes #3403)

hypothesis-python/RELEASE.rst, hypothesis-python/src/_hypothesis_pytestplugin.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/errors.py, hypothesis-python/src/hypothesis/internal/escalation.py, hypothesis-python/src/hypothesis/reporting.py, hypothesis-python/tests/cover/test_arbitrary_data.py, hypothesis-python/tests/cover/test_deadline.py, hypothesis-python/tests/cover/test_error_in_draw.py, hypothesis-python/tests/cover/test_escalation.py, hypothesis-python/tests/cover/test_explicit_examples.py, hypothesis-python/tests/cover/test_falsifying_example_output.py, hypothesis-python/tests/cover/test_random_module.py, hypothesis-python/tests/cover/test_randoms.py, hypothesis-python/tests/cover/test_reporting.py, hypothesis-python/tests/cover/test_reproduce_failure.py, hypothesis-python/tests/cover/test_slippage.py, hypothesis-python/tests/cover/test_stateful.py, hypothesis-python/tests/cover/test_testdecorators.py, hypothesis-python/tests/ghostwriter/test_ghostwriter.py, hypothesis-python/tests/nocover/test_interesting_origin.py, hypothesis-python/tests/nocover/test_scrutineer.py, hypothesis-python/tests/nocover/test_stateful.py, hypothesis-python/tests/nocover/test_targeting.py, hypothesis-python/tests/pytest/test_skipping.py
Using the new features from PEP-654 and PEP-678, exception groups and enriching exceptions with notes.
Draft because I'm not quite done updating tests yet - and will want to do some further manual confirmation that the output *looks* good too - but this will close #3175 when merged.
=> Switch from `MultipleFailures` to PEP-654 `ExceptionGroup`

hypothesis-python/RELEASE.rst, hypothesis-python/src/_hypothesis_pytestplugin.py, hypothesis-python/tests/pytest/test_reporting.py
Fixes #3430, and adds a test to ensure it can't reoccur.
=> Fix pytest workaround for `ExceptionGroup` display

hypothesis-python/setup.py
The `license_files` key is supported since setuptools 42.0.0, so update the version check accordingly.
This is a followup to #3483.
=> Update setuptools version check for license_files change

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/compat.py, hypothesis-python/tests/cover/test_compat.py
=> Improve handling of forward references in get_type_hints

hypothesis-python/.coveragerc, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/utils/terminal.py, hypothesis-python/tests/cover/test_reflection.py, hypothesis-python/tests/quality/test_float_shrinking.py, hypothesis-python/tox.ini
Complements https://github.com/HypothesisWorks/hypothesis/issues/3506 - this is independently useful, but https://github.com/Zac-HD/hypofuzz/issues/13 motivated me to do it *now* rather than *eventually*.
Also includes some test performance fixes, and improved `DJANGO_COLORS` handling because the Sphinx link stopped working.
=> Improve database keys by ignoring decorators, comments, etc.

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/control.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/vendor/pretty.py, hypothesis-python/tests/cover/test_falsifying_example_output.py, hypothesis-python/tests/cover/test_pretty.py
This is a pretty large diff, but it's mostly mechanical refactorings to make our pretty-printer (borrowed from IPython in ~2015 and still compatible) feel Python-3-native, and a few small fixes and bits of interface sugar.
The motivation is that I've got a working implementation of #3529 on top of this, and I'm prototyping #3411 too - so getting these parts out of the way will make those diffs much easier to deal with 🙂
=> Refactor pretty-printer to unlock future upgrades

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/compat.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/tests/cover/test_compat.py
=> `get_type_hints()` support for `partial()`

hypothesis-python/RELEASE.rst, hypothesis-python/docs/reproducing.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/tests/common/utils.py, hypothesis-python/tests/cover/test_example.py, hypothesis-python/tests/nocover/test_integer_ranges.py
Closes #3530, as @rsokl and I discussed a few weeks ago.  
Plus a small fix so that `KeyboardInterrupt` (and other exceptions not treated as test failure) interrupt immediately as they do for generated examples.
=> New method: `@example(...).xfail()`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/array_api.py, hypothesis-python/tests/array_api/test_partial_adoptors.py
We can't currently use `xps.arrays()` as-is with `torch` due to [`torch.full()`](https://pytorch.org/docs/stable/generated/torch.full.html#torch.full) not supporting integers (i.e. shorthands for 1-D shapes with the size of the integer) in its `size` argument (or what we treat as the `shape` argument). This PR simply makes it so we're always passing tuples for the `shape`/`size` argument here.
This non-compliance with the Array API has been noted as something to fix (https://github.com/pytorch/pytorch/issues/70906), so could very well see movement at some point. It feels icky for me to make such a change when we're already correctly assuming behaviour, but seems like the kind of simple change that gets us a nice win immediately. Selfishly it's useful in `array-api-tests` to better support …
=> Pass tuple shape to `xp.full()` in `xps.arrays()` for improved PyTorch support

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/pandas/impl.py, hypothesis-python/tests/pandas/test_argument_validation.py, hypothesis-python/tests/pandas/test_indexes.py
I had some tests where I had to add the index name as part of the actual test when using `range_indexes`. This should allow this to be done from the strategy itself, which is a bit cleaner
=> add name to extra.pandas.range_indexes

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/vendor/pretty.py, hypothesis-python/tests/cover/test_pretty.py
Enums are currently pretty-printed with their raw repr rather than a useful identifier than can be used in code.
This pull request updates the pretty printing code to fix that, so that where previously an enum member would be printed as e.g. `<AnEnum.SOME_MEMBER: 1>`, it is now printed as `AnEnum.SOME_MEMBER`.
=> Define a pretty printer for enums

hypothesis-python/tests/pandas/test_data_frame.py
When the test run on big endian system, the byte order confused Pandas 1.5. Older Pandas coerced the byte order to the native one anyway.
See https://github.com/HypothesisWorks/hypothesis/issues/2894 and https://github.com/pandas-dev/pandas/issues/51041
=> Tests: Don't force endianness of Pandas timestamp columns

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py
Previously, it was not clear from the documentation how these values are treated. Although the actual implementation is more complicated, I think this description (referring the users to `hypothesis.strategies.floats`) is sufficient.
=> Improve the documentation of `hypothesis.strategies.complex_numbers()`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/tests/numpy/test_from_dtype.py
I think this was just forgotten.
Related to  #3468.
=> Add `allow_subnormal` passthrough to `strategies.numpy.from_dtype()` for complex values

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/numpy/test_from_dtype.py
=> Add `min_magnitude` & `max_magnitude` passthrough in complex-valued `from_dtype()`

hypothesis-python/RELEASE.rst, hypothesis-python/docs/numpy.rst, hypothesis-python/src/hypothesis/extra/array_api.py, hypothesis-python/tests/array_api/common.py, hypothesis-python/tests/pandas/test_data_frame.py
This PR updates refs of `api_version` from `draft` to `2022.12`, and allows one to specify the new release i.e. `make_strategies_namespace(xp, api_version=2022.12)`. I also updated our complex branch in `xps.from_dtype()` to use the now-specified behaviour of `xp.finfo()` working with complex dtypes (getting the component float's info).
Additionally, this PR removes the beware-breaking-changes note in the respective docs—I think that's fine at this point right?
I was going to do min/max magnitude passthrough to `xps.from_dtype()`, but given https://github.com/HypothesisWorks/hypothesis/issues/3573 I think it can wait :sweat_smile:
=> Officially support `api_version=2022.12` in `extra.array_api`

.readthedocs.yml, AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/provisional.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/nocover/test_emails.py
Fixes #3567, closes #3582.
@Zac-HD this is a Draft PR for now because we need to discuss a few things:
- turns out that the list of default top-level domain names did not contain [special-use domain names](https://www.iana.org/assignments/special-use-domain-names/special-use-domain-names.txt), except `arpa`: https://github.com/HypothesisWorks/hypothesis/blob/600fc8a5da217778bc4e9bba8c9a71ca3116147a/hypothesis-python/src/hypothesis/provisional.py#L44 Should I add them?
- Alternatively we’d remove `arpa` from that list and inverse the logic when creating the list to draw from in the PR.
- Hardwire the special-use domain names, or use a vendor file?
- I wasn’t sure about your preference re import naming.
Things to do for me:
=> Exclude `.arpa` tld names from `domains()` strategy

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/statistics.py, hypothesis-python/tests/cover/test_statistical_events.py
A simple mean of the percentage of time taken in data generation can be misleading: "1-100 ms, ~50% in data generation" can mean:
- generation always takes 1ms, rest of the test takes 0-99 ms
- generation takes 1-50 ms, rest of the test takes 1-50 ms
Specifying a range the same way as the runtime prevents confusing these cases.
Fixes https://github.com/HypothesisWorks/hypothesis/issues/3598.
=> Clarify time spent in data generation

hypothesis-python/tests/codemods/test_codemod_cli.py, hypothesis-python/tests/cover/test_lazy_import.py, hypothesis-python/tests/cover/test_settings.py, hypothesis-python/tests/ghostwriter/test_ghostwriter_cli.py, hypothesis-python/tests/ghostwriter/try-writing-for-installed.py, hypothesis-python/tests/pytest/test_pytest_detection.py, hypothesis-python/tox.ini
Adds the `PYTHONWARNDEFAULTENCODING=1` to tox.ini as an env variable to enable warnings for encodings.  See also https://peps.python.org/pep-0597/
=> fix: enables default encoding warning to ensure users set encoding

AUTHORS.rst, CONTRIBUTING.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/numpy.py
Given the following example
```python
import numpy as np
from hypothesis.extra.numpy import arrays
a = arrays(np.int32, shape=2)
reveal_type(a)
```
On master running the typechecker the ndarray dtype is unkown
```
```
If my understanding is correct, after this pr the dtype parameter will be taken into account.
```
```
=> [TYP] return array dtype is always unkown but it's actually specified as parameter

hypothesis-python/RELEASE.rst, hypothesis-python/docs/settings.rst, hypothesis-python/src/hypothesis/control.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/src/hypothesis/vendor/pretty.py, hypothesis-python/tests/conjecture/test_inquisitor.py, hypothesis-python/tests/cover/test_random_module.py, hypothesis-python/tests/cover/test_slippage.py, hypothesis-python/tests/nocover/test_collective_minimization.py, hypothesis-python/tox.ini
Closes #3411.  Excitingly, this is also the last big new feature I'm writing for my PhD - from here it's all maintainance and thesis-writing ✍️:tada: 
Remaining things to do:
After merge,
- follow-up PR to add support for tuple elements and fixed-dict elements - I have a proof-of-concept branch
- open an issue about explain-mode for stateful tests, and possible hooks for Schemathesis
- #3551 and then consider enabling the `explain` phase by default
=> "Inquisitor": annotate parts of a minimal failing example which may vary

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/pandas/impl.py, hypothesis-python/tests/common/arguments.py, hypothesis-python/tests/pandas/test_argument_validation.py, hypothesis-python/tests/pandas/test_data_frame.py, hypothesis-python/tests/pandas/test_series.py
Support the new Pandas nullable dtypes ([see here](https://pandas.pydata.org/docs/user_guide/integer_na.html)).
Closes #3604
=> Support nullable pandas dtypes

hypothesis-python/RELEASE.rst, hypothesis-python/docs/changes.rst, hypothesis-python/src/hypothesis/extra/pandas/impl.py, hypothesis-python/src/hypothesis/version.py, hypothesis-python/tests/pandas/test_argument_validation.py, tooling/src/hypothesistooling/projects/hypothesispython.py
This fixes #3518. It picks up where the previous PR left off, and so closes #3580.
=> Improved error messages for incompatible datetime & timedelta dtypes

hypothesis-python/.coveragerc, hypothesis-python/RELEASE.rst, hypothesis-python/docs/changes.rst, hypothesis-python/docs/settings.rst, hypothesis-python/scripts/other-tests.sh, hypothesis-python/src/_hypothesis_pytestplugin.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/extra/_patching.py, hypothesis-python/src/hypothesis/extra/codemods.py, hypothesis-python/src/hypothesis/internal/charmap.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/src/hypothesis/strategies/_internal/numbers.py, hypothesis-python/src/hypothesis/vendor/pretty.py, hypothesis-python/tests/conjecture/test_inquisitor.py, hypothesis-python/tests/patching/__init__.py, hypothesis-python/tests/patching/callables.py, hypothesis-python/tests/patching/test_patching.py, hypothesis-python/tox.ini, requirements/coverage.txt, requirements/tools.txt
See https://blog.nelhage.com/post/property-testing-like-afl/ and https://github.com/Zac-HD/hypofuzz/issues/13.  I've tried it out locally and it's rather nice 🙂 
Also cherrypicked: fixes #3629, fixes #3632.
=> Write `.patch` files to add `@example()` decorators for failing test cases

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/errors.py, hypothesis-python/tests/cover/test_escalation.py
Previously, `hypothesis.errors` would return `None` when any arbitrary attribute was accessed.
This should fix the issue we are seeing in [running CPython's test suite](https://github.com/python/cpython/pull/22863#issuecomment-1529085181).
=> Raise AttributeError in errors module

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/database.py
As a follow-up on #3576, I've added some improvements to the artifacts database:
For now, I've decided to only exemplify basic workflows that enable sharing the example database of normal hypothesis runs (essentially making replication of CI failures a little faster). 
Hypofuzz isn't supported yet, as we still need to figure out the data race, plus update Hypofuzz to support changes in Hypothesis's internal API.
=> Improve Github Artifacts database

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/cover/test_complex_numbers.py, hypothesis-python/tests/cover/test_direct_strategies.py, hypothesis-python/tests/nocover/test_complex_numbers.py, hypothesis-python/tests/numpy/test_from_dtype.py
Should resolve #3573, where we used the builtin width (i.e. 64) results of `cathetus()`, which don't validate in `floats()` for any width but `64`. Currently this PR downcasts the output of `cathetus()`, but I wonder if some of those downcasts would need clipping... EDIT: yeah somethings wrong
=> Downcast numbers passed to `floats()` internally in `constrained_complex()`

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/utils.py, hypothesis-python/src/hypothesis/strategies/_internal/collections.py, hypothesis-python/src/hypothesis/strategies/_internal/datetime.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/tests/conjecture/test_test_data.py
This PR adds a `why` argument to `ConjectureData.mark_invalid()` (and `many.reject()` which can call through to it), which can optionally take a string description of the reason for the data to be marked as invalid, and will record an event.
I didn't try to ensure that every single callsite now provides these arguments (there can always be follow-up PRs to add more where it seems useful), but I covered the ones where I felt able to provide something (hopefully) sensible.
The specific case I wanted to cover was `MAX_DEPTH` invalidation, since I have a use case where I'm getting >99% invalidation due to that, and prior to this PR it was invisible in the statistics, making me dive into internals to understand what was happening. With this PR I now see:
```
- Events:
* 99.29%, max depth …
```
=> events for more mark_invalid() cases

.flake8, hypothesis-python/RELEASE.rst, hypothesis-python/src/_hypothesis_ftz_detector.py, hypothesis-python/src/_hypothesis_pytestplugin.py, hypothesis-python/src/hypothesis/_settings.py, hypothesis-python/src/hypothesis/internal/compat.py, hypothesis-python/src/hypothesis/internal/conjecture/dfa/lstar.py, hypothesis-python/tests/array_api/common.py, hypothesis-python/tests/cover/test_reflection.py, hypothesis-python/tests/ghostwriter/example_code/future_annotations.py, hypothesis-python/tests/ghostwriter/test_ghostwriter_cli.py, hypothesis-python/tests/nocover/test_baseexception.py, hypothesis-python/tests/numpy/test_from_dtype.py, pyproject.toml, requirements/tools.txt, tooling/src/hypothesistooling/__main__.py, whole-repo-tests/test_rst_is_valid.py
Closes #3650
[Ruff](https://beta.ruff.rs/) supports [over 500 lint rules](https://beta.ruff.rs/docs/rules) and can be used to replace [Flake8](https://pypi.org/project/flake8/) (plus dozens of plugins), [isort](https://pypi.org/project/isort/), [pydocstyle](https://pypi.org/project/pydocstyle/), [yesqa](https://github.com/asottile/yesqa), [eradicate](https://pypi.org/project/eradicate/), [pyupgrade](https://pypi.org/project/pyupgrade/), and [autoflake](https://pypi.org/project/autoflake/), all while executing (in Rust) tens or hundreds of times faster than any individual tool.
This PR could have replaced `autoflake` but it might be better to get used to `ruff --fix` before throwing that switch.
=> Replace flake8 and its plugins with ruff

.github/workflows/main.yml, hypothesis-python/RELEASE.rst, hypothesis-python/scripts/other-tests.sh, hypothesis-python/src/_hypothesis_pytestplugin.py, hypothesis-python/src/hypothesis/extra/_patching.py, hypothesis-python/tests/conftest.py, hypothesis-python/tests/patching/callables.py, hypothesis-python/tests/patching/test_patching.py, hypothesis-python/tests/patching/toplevel.py, tooling/src/hypothesistooling/__main__.py
Bugfixes and enhancements following https://github.com/HypothesisWorks/hypothesis/pull/3631, along with the remaining features for https://github.com/Zac-HD/hypofuzz/issues/13 downstream 😁
Notably we now detect and handle modules that just `import hypothesis` by writing `@hypothesis.example(...)` (CPython, you're welcome), have the ability to _remove_ obsolete examples with known `.via(...)` tags (the core motivation for that method!), and skip the timestamp when computing the file hash, so that we write otherwise-identical patches to the same location instead of exploding the directory with repeated runs.
=> Improved patch files for failing examples

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/array_api.py, hypothesis-python/tests/array_api/conftest.py, hypothesis-python/tests/array_api/test_arrays.py, hypothesis-python/tests/array_api/test_partial_adoptors.py, hypothesis-python/tests/array_api/test_pretty.py
Currently we can't generate arrays for JAX, because we assign values to arrays but JAX arrays are immutable.
https://github.com/HypothesisWorks/hypothesis/blob/661af850bbfcb091a820eb16c84f56048c8e21c8/hypothesis-python/src/hypothesis/extra/array_api.py#L449
This PR has `array_api.ArrayStrategy` instead prepare a builtin list `result_obj` to be passed to `xp.asarray`. Makes it kinda annoying to still do our sanity checks (e.g. see introduction and usage of `fill_mask`), but seems quite palatable if it lets us support JAX. I'll mull over the implementation details anywho.
Running https://github.com/google/jax/pull/16099 on `tests/array_api/` via `HYPOTHESIS_TEST_ARRAY_API=jax.experimental.array_api pytest tests/array_api/` gets some errors, which I'll need to explore. FWIW it's okay if …
=> Support immutable arrays (i.e. JAX) in `extra.array_api`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/errors.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/cover/test_lookup.py, hypothesis-python/tests/cover/test_regressions.py, hypothesis-python/tests/cover/test_type_lookup.py
Fixes https://github.com/HypothesisWorks/hypothesis/issues/3655.
This PR adds a parameter to `_from_type` in order to keep track of (some) already-seen types, and rewind if recursion is spotted.
Only type arguments are tracked, since this is where types become recursive - and where the bug was, since this was protected effectively only when the recursive type did not have default arguments. See first commit, which adds just a failing test for this.
=> Fix recursives

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/numpy/test_from_dtype.py, hypothesis-python/tests/numpy/test_from_type.py
A follow-up on https://github.com/HypothesisWorks/hypothesis/pull/3668, addressing https://github.com/HypothesisWorks/hypothesis/issues/3150 (draft, for discussion).
I believe something like this is the easiest way to support arbitrary and parameterized special types such as `np.ndarray[int]`. Allowing the numpy extra to inspect the type before other partial resolutions means we can compare directly with e.g. `np.typing.ArrayLike`, which is (IMO) much easier than digesting the inner types of the union. Mind, if the union is not consumed by the specialized resolver then it will get another crack at the inner types later.
I did try to make it sort-of-generic by adding a lookup table for specialized resolvers. The lookup table only considers installed modules though, not the actual module of …
=> Implement support for parameterized numpy types - np.ndarray[int] etc

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/tests/ghostwriter/recorded/sequence_from_collections.txt, hypothesis-python/tests/ghostwriter/test_expected_output.py
`collections` contains deprecated aliases for `collections.abc` classes. This commit ensures that those are not used anymore.
I've ignored the tests for Python versions < 3.9, because there the `collections.abc` classes were no generics.
Plus: I've changed my name after marrying :slightly_smiling_face:
=> ensured that ghostwriter does not use deprecated aliases

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/cover/test_lookup.py, hypothesis-python/tests/cover/test_lookup_py39.py, hypothesis-python/tests/ghostwriter/recorded/merge_dicts.txt
This is a work in progress - at time of writing it fixes #3635, but breaks the special cases we have for bytestrings.
Once that's fixed it looks pretty good, but... arguably this bugfix is also a breaking change 😬.  Not entirely sure what we want to do about that, there's no real deprecation pathway possible so our options are probably either (a) ship it now, or (b) wait until the next major version - which I'd pull forward to the 3.7 EOL at the end of this month, I guess.
Thoughts?
=> Single registration for builtin and `typing.` generic types

.github/workflows/main.yml, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/cover/test_lookup.py, hypothesis-python/tests/cover/test_type_lookup.py, hypothesis-python/tests/cover/test_type_lookup_forward_ref.py, hypothesis-python/tests/datetime/test_dateutil_timezones.py, hypothesis-python/tests/datetime/test_pytz_timezones.py, hypothesis-python/tests/nocover/test_from_type_recipe.py
Fixes #3663.  Let's see how well this works...
=> Run Python 3.12 beta in CI

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/cover/test_lookup.py, hypothesis-python/tests/ghostwriter/recorded/hypothesis_module_magic.txt
Currently the representation of lazy `st.from_type(MyClass)` were `from_type(<class 'some_module.MyClass'>)`. This patch changes it to do the following:
1. If a `__repr__` is defined on the type that is different to `object.__repr__` it just uses the representation. This is for example the case for `Optional[...]`.
2. If `__module__` and `__qualname__` are not defined also use the representation of the object.
3. ~If `__module__` is `"builtins"` just use the `__qualname__`.~ I could not find an object that would fallback to this lazy from_type, therefore I've omitted this.
4. Otherwise, use `f"{__module__}.{___qualname__}"`.
I did consider using `_get_qualname` from Ghostwriter, but this would either need to be made public and referenced or extracted, which is both a bit suboptimal.
=> improve type rendering in st.from_type

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py, hypothesis-python/tests/cover/test_lookup.py, hypothesis-python/tests/nocover/test_recursive.py
This fixes #3671 by applying the `ConjectureData` trick of extending the stack limit by the current stack depth also upon strategy validation and draw.
The implementation is slightly complicated by "best-effort thread safety", but acceptably so IMO.
=> Fix flaky recursionerror

.github/workflows/fuzz.yml, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/_patching.py, hypothesis-python/src/hypothesis/extra/codemods.py, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/tests/common/setup.py, hypothesis-python/tests/cover/test_example.py, hypothesis-python/tests/cover/test_reflection.py, hypothesis-python/tests/patching/test_patching.py
- The `.patch` files weren't showing up because the dashboard process is responsible for writing them (since that's where all the examples are reported); fixed by removing `--no-dashboard`.
- The database _also_ wasn't showing up, because eight years ago we set that to a random location (in such a way that it only sometimes took effect).  Removed this so we'll use the default location from now on.
=> Fix fuzzing artifact saving

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py, hypothesis-python/src/hypothesis/internal/conjecture/utils.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/strategies/_internal/collections.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/lazy.py, hypothesis-python/tests/cover/test_lookup.py, hypothesis-python/tests/nocover/test_recursive.py
Trying to finally kill that recursion zombie.
`from_type` didn't properly detect recursion on types that went through `types.from_typing_type`. Fixed by moving the recurse-guard list to a `ContextVar`. (yep, I should have taken your advice on that in the first place @Zac-HD)
Additionally:
- ~~when `nicerepr` encounters an error (RecursionError for example), convert it to a warning and return a string anyway. This is what made it easy to identify the problem in the first place,~~
- hard-code the stack depth increment as 2000 to avoid inconsistency between test runners (pytest seems to bump it from 1000 to 3000 during test execution, for example, and other packages may interfere),
- some other minor stuff which I'll comment in the code.
Closes: #3525
=> Fix recursion issues

hypothesis-python/RELEASE.rst, hypothesis-python/docs/strategies.rst, hypothesis-python/src/hypothesis/entry_points.py, hypothesis-python/tests/cover/test_lazy_import.py
Closes #3686. The test_lazy_import test would fail depending on which other packages happened to be installed.
Trivial code change, but you may have an opinion on the env var name.
=> Env var to skip loading of entrypoints.

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/shrinking/floats.py, hypothesis-python/tests/conjecture/test_float_encoding.py, hypothesis-python/tests/nocover/test_simple_numbers.py
Ref #3357.
Adds nearby reduced-precision shrink candidates in `Float` shrinker.
=> Consider reduced precision candidates for float shrinking

hypothesis-python/RELEASE.rst, hypothesis-python/setup.py, hypothesis-python/src/hypothesis/vendor/pretty.py, hypothesis-python/tests/cover/test_pretty.py
Closes #3709.
And since I was pushing some commits, also fixes #3707.
=> Implement pretty-printing of combined `enum.Flag` instances

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/cli.py
If you copy paste the current message in bash / zsh it will error out with:
```
» pip install --upgrade hypothesis[cli]
zsh: no matches found: hypothesis[cli]
```
=> Improve error message for missin `[cli]` extra

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/cover/test_core.py, hypothesis-python/tests/cover/test_direct_strategies.py
Attempt to add two options of `codec=`: `ascii` and `utf-8` to `st.characters()` to limit the character generated.
See #1664
=> Adding `codec=` option to `st.characters()`

.github/workflows/main.yml, hypothesis-python/.coveragerc, hypothesis-python/RELEASE.rst, hypothesis-python/docs/conf.py, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/src/hypothesis/extra/pandas/impl.py, hypothesis-python/src/hypothesis/internal/escalation.py, hypothesis-python/src/hypothesis/vendor/pretty.py, hypothesis-python/tests/conftest.py, hypothesis-python/tests/cover/test_pretty.py, requirements/coverage.in, requirements/coverage.txt, requirements/fuzzing.txt, requirements/test.txt, requirements/tools.txt
Fixes https://github.com/HypothesisWorks/hypothesis/issues/3721 and adds new access to the IPython type-to-prettyprinter registry, which should be a nice enhancement to people using complicated datastructures which have been registered with IPython.  Admittedly I expect this to be rare, but so are many of the quality of life features we have - they still add up 🙂 
Also fixes https://github.com/HypothesisWorks/hypothesis/issues/3642 because I was there anyway, and closes https://github.com/HypothesisWorks/hypothesis/pull/3727 by inclusion and a tiny patch.
=> Improve compatibility with `IPython.lib.pretty` for pretty-printing

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/_settings.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/tests/cover/test_health_checks.py, hypothesis-python/tests/cover/test_setup_teardown.py, hypothesis-python/tests/django/toystore/test_basic_configuration.py
Addresses #3446 by adding a health check for this usage.
A follow-up PR will disable health checks during database replay, which will close it.
=> Add health check for different selfs

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/array_api.py, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/ipaddress.py, hypothesis-python/src/hypothesis/strategies/_internal/numbers.py, hypothesis-python/tests/array_api/common.py, hypothesis-python/tests/cover/test_charmap.py
I happened to think of category names while working on #3742, and it turns out that we have several APIs which can be more precisely typed with `Literal`.
=> Use Literal type annotations

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
Closes #3747.  @rsokl I've checked locally that this fixes the `mygrad` failure and and so I'm shipping this asap, but please do confirm the fix at your leisure.
=> Fix explain-mode bug

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/conjecture/test_inquisitor.py
Fixes https://github.com/HypothesisWorks/hypothesis/issues/3755, by deleting some defensive code which I wrote to defend against implementation bugs and thought was unreachable in normal use.  Obviously that turned out to be wrong!  So, how _can_ you reach that?
The relevant loop is replacing an infix of our test buffer, for example taking `AA XX BB` and trying `AA YY BB`.  However, the length can vary by contents, so the test might try to read off the end of the buffer: `AA YYB B-`.  In this case, we'll try fixing it up as `AA YYB BB` - and my incorrect assert was that we'd have exactly this buffer from the rerun.  _However_, it's possible for the infix to first overflow, and then have part of the infix dropped by the canonicalisation logic (e.g. because of a filter) - so the final …
=> Remove explain-phase assertion which is in fact reachable

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/configuration.py, hypothesis-python/src/hypothesis/database.py, hypothesis-python/src/hypothesis/extra/cli.py, hypothesis-python/src/hypothesis/internal/charmap.py, hypothesis-python/src/hypothesis/strategies/_internal/datetime.py, hypothesis-python/tests/cover/test_charmap.py, hypothesis-python/tests/cover/test_filestorage.py, hypothesis-python/tests/cover/test_phases.py, hypothesis-python/tests/cover/test_settings.py, hypothesis-python/tests/nocover/test_database_usage.py, pyproject.toml
=> Warn and continue codemodding on `SyntaxError`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/random.py, hypothesis-python/tests/cover/test_randoms.py
This special cases the case where we request `0` elements from a sequence so as to not error even if the sequence is empty.
Arguably this could be fixed at the `st.sampled_from` level, which I think is something we've gone back and forth on (i.e. should `st.sampled_from([])` be equivalent to `st.nothing()` - it's arguably correct behaviour, but it's likely to silently cover errors), so I went for the minimal change that would get the correct behaviour.
=> Fix #3765 (Random.sample errors with empty sequences)

hypothesis-python/src/hypothesis/extra/django/_impl.py
Fixes https://github.com/HypothesisWorks/hypothesis/issues/3771
=> Make return type of `from_model` parameterized with respect to `model`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/cover/test_lookup_py39.py
If this works (🤞), it'll fix #3750 and close #3782.
The underlying problem here is that old versions of the `typing` module had some really weird implementation details; happily they've been steadily cleaned up and with Python 3.7 now end of life we can simplify our handling considerably.
=> Allow registration of tuples

hypothesis-python/docs/packaging.rst, tooling/src/hypothesistooling/__main__.py
=> Update Arch Linux package URL in packaging.rst

hypothesis-python/RELEASE.rst, hypothesis-python/setup.py, hypothesis-python/src/hypothesis/strategies/_internal/attrs.py, hypothesis-python/tests/cover/test_attrs_inference.py
Closes #3791.
More generally, adds support for attr's [alias parameter](https://www.attrs.org/en/stable/api-attr.html#attr.ib). On master, the following errors, for instance:
```python
@attr.s
class HasAliasedAttribute:
x: int = attr.ib(alias="crazyname")
st.builds(HasAliasedAttribute)
```
Attrs also helpfully fills in `alias` with the correctly-stripped version of private attributes, which is why this fixes the linked issue.
attrs only [added `alias`](https://github.com/python-attrs/attrs/pull/950) in `22.2.0`. I probably could have thrown a `if attrs.__version__` in here and made things backwards compatible, but it would have complicated things, so I've taken the easier option of bumping the dependency. [There is precedence for …
=> Support attrs `alias` and private attributes in `st.builds`

CODEOWNERS, hypothesis-python/RELEASE.rst, hypothesis-python/docs/_static/wrap-in-tables.css, hypothesis-python/docs/changes.rst, hypothesis-python/docs/conf.py, hypothesis-python/docs/index.rst, hypothesis-python/docs/observability.rst, hypothesis-python/docs/schema_observations.json, hypothesis-python/src/_hypothesis_pytestplugin.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/observability.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/internal/scrutineer.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/utils.py, hypothesis-python/tests/cover/test_observability.py, hypothesis-python/tests/cover/test_searchstrategy.py, mypy.ini, requirements/tools.in, requirements/tools.txt
I've been corresponding with @hgoldstein95 for a while now, and last week we met up in person too.  After talking about and hacking on https://github.com/tyche-pbt/ ([paper](https://harrisongoldste.in/papers/uist23.pdf)) - a neat in-editor frontend to see what Hypothesis is doing - we hit on the concept of [observability](https://en.wikipedia.org/wiki/Observability_(software)) for PBT.
As well as reporting the minimal failing example, let's log _every_ test case - including argument values, test outcome, runtimes, code coverage, events and target values, etc.  If all you need is the minimal example, great - but if you need more, you can treat (more of) debugging as a data analysis problem!
In a future version, we're aiming for automatic integration with [the Tyche vs code …
=> Observability features to support deeper understanding + future Tyche integration

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/compat.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/utils.py, hypothesis-python/tests/cover/test_compat.py, hypothesis-python/tests/cover/test_searchstrategy.py
closes #3812.
A pair of related questions: how heavily should this vendored implementation be tested, and how much (if any) of it can be `# pragma: no cover`'d? There are currently a number of uncovered lines in `_asdict_inner`.
=> Vendor `dataclasses.asdict`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/observability.py
Fixes an error when using observability without a .hypothesis dir. To reproduce, delete `.hypothesis` and run pytest with `HYPOTHESIS_EXPERIMENTAL_OBSERVABILITY=1`.
This matches how we do things elsewhere: https://github.com/HypothesisWorks/hypothesis/blob/6da7c6f9b7f8b838fcc83e3c4274cc4b1a56896b/hypothesis-python/src/hypothesis/internal/charmap.py#L72-L73
To be honest, this seems like a bit of a footgun with `storage_directory`. Maybe we should have a `mkdir: bool` param?
I didn't write a regression test for this because it seemed slightly annoying and not that useful. I'm happy to write one on request 🙂
=> Create parent dir in `_deliver_to_file`

hypothesis-python/docs/observability.rst
closes #3831.
(do docs updates need a release/changelog?)
=> Add note about nonstandard observability json

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/filtering.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/strategies/_internal/collections.py, hypothesis-python/src/hypothesis/strategies/_internal/strings.py, hypothesis-python/tests/cover/test_filter_rewriting.py, hypothesis-python/tests/cover/test_searchstrategy.py
Resolves part of #3795
> in this case we'll want to apply the rewrite for efficiency, and apply the predicate as a filter in case the name len has been rebound in the enclosing scope
So we take the components of the lambda and re-write with them. However, how would we keep in mind the case that the `len` function has been rebound/redefined? Or do you mean falling back to rejection sampling in this case?
=> Filter-rewriting for length filters

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/control.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/errors.py, hypothesis-python/tests/cover/test_control.py, hypothesis-python/tests/cover/test_observability.py, hypothesis-python/tests/cover/test_regressions.py, hypothesis-python/tests/cover/test_statistical_events.py
closes https://github.com/HypothesisWorks/hypothesis/issues/3827.
Note that what we originally discussed in the issue has the knock-on effect of adding to the events of that test case, which shows up in e.g. [statistics mode](https://hypothesis.readthedocs.io/en/latest/details.html#test-statistics) reporting:
```
from hypothesis import *
from hypothesis.strategies import *
@given(integers())
def test_f(n):
assume(n > 2)
```
```
sandbox.py::test_f:
- during reuse phase (0.00 seconds):
- Typical runtimes: < 1ms, of which < 1ms in data generation
- 1 passing examples, 0 failing examples, 0 invalid examples
- during generate phase (0.04 seconds):
- Typical runtimes: < 1ms, of which < 1ms in data generation
- 99 passing examples, 0 failing examples, 96 invalid examples
- Events:
* 49.23%, …
```
=> add status reason to UnsatisfiedAssumption rejections

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/utils.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/tests/common/debug.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_float_encoding.py, hypothesis-python/tests/conjecture/test_optimiser.py, hypothesis-python/tests/conjecture/test_pareto.py, hypothesis-python/tests/conjecture/test_shrinker.py, hypothesis-python/tests/conjecture/test_shrinking_dfas.py, hypothesis-python/tests/conjecture/test_test_data.py, hypothesis-python/tests/conjecture/test_utils.py, hypothesis-python/tests/nocover/test_conjecture_engine.py, hypothesis-python/tests/quality/test_integers.py, hypothesis-python/tests/quality/test_poisoned_trees.py, hypothesis-python/tests/quality/test_zig_zagging.py
Split from #3818. I could split this further if desired, with all the `draw_bits` changes in a single PR.
Changes:
* [move cu.choice to ConjectureData](https://github.com/HypothesisWorks/hypothesis/commit/0690201688cc7024ddebc70ef237791d5cbe5e1c)
* [improve minimal readability with nonlocal](https://github.com/HypothesisWorks/hypothesis/commit/f6b7349c9520b3c08baf698084541b08d9db9ebc)
* migrate away from `draw_bits` in various test files in preparation for its removal. Or at least, taking a back seat relative to the ir.
There were some test changes where the extra boolean draw from > 24 bit integers caused the test to fail.
https://github.com/HypothesisWorks/hypothesis/blob/980042e4018069cf24f6c161434378a353586a76/hypothesis-python/src/hypothesis/internal/conjecture/data.py#L1260-L1262
I …
=> Various core and test changes

hypothesis-python/RELEASE.rst, hypothesis-python/tests/conjecture/test_shrinking_dfas.py
follow-up to https://github.com/HypothesisWorks/hypothesis/pull/3839#issuecomment-1890255785.
We have a fine line to walk here. Here's my understanding. `normalize` has a budget of 100 calls, and at least once within those 100 calls, the following needs to happen:
- We run into some failure A.
- While shrinking A, we run into a different failure B.
These two items are in contention. We explore generation *upwards* towards larger examples, so we are likely to run into the minimal counterexample first. But we explore shrinking *downwards* towards smaller examples, so shrinking the minimal counterexample is unlikely to find a new counterexample (or that would have been the one found during generation).
Of course, these are heuristics, and the very need for dfa normalization is proof of that. …
=> De-flake `non_normalized_test_function` (again)

hypothesis-python/tests/quality/test_discovery_ability.py
Closes #3829. See also https://github.com/HypothesisWorks/hypothesis/issues/3829#issuecomment-1890756072 for an explanatory comment.
=> Decrease pass probability for `test_can_produce_multi_line_strings`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/tests/conjecture/test_data_tree.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_shrinker.py, hypothesis-python/tests/conjecture/test_test_data.py, hypothesis-python/tests/nocover/test_conjecture_engine.py, hypothesis-python/tests/nocover/test_explore_arbitrary_languages.py, hypothesis-python/tests/numpy/test_gen_data.py
Split from #3818. Follow-up to #3835.
Contains the simpler changes I could split out, including some test changes I missed last time. I'll also open another PR shortly (tomorrow, likely) with more substantive changes, but I've intentionally split them so they can be considered independently. 
Hopefully these are the last pulls necessary before the main event!
=> Test touchups in preparation for ir migration

build.sh, hypothesis-python/RELEASE.rst, hypothesis-python/docs/schema_observations.json, hypothesis-python/src/hypothesis/control.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/observability.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/utils.py, hypothesis-python/tests/common/strategies.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/cover/test_observability.py, hypothesis-python/tests/pytest/test_capture.py, tooling/scripts/ensure-python.sh
Plus a note in the docs inspired by discussion on https://github.com/tyche-pbt/tyche-extension/issues/3.  
Cc @hgoldstein95 for timing metadata per your email.
=> Pull out timing observations, more jsonable arguments

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/control.py, hypothesis-python/tests/cover/test_control.py, hypothesis-python/tests/ghostwriter/recorded/hypothesis_module_magic.txt
=> Pretty-print objects in `note()`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/tests/cover/test_reflection.py, hypothesis-python/tests/nocover/test_pretty_repr.py
For consideration, and submitted for the test runs.
A warning like this would have saved some development time lately, on #3820 and #3837.
=> Warn when generating overly large repr

hypothesis-python/RELEASE.rst, hypothesis-python/src/_hypothesis_globals.py, hypothesis-python/src/_hypothesis_pytestplugin.py, hypothesis-python/src/hypothesis/configuration.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/cover/test_sideeffect_warnings.py, hypothesis-python/tests/nocover/test_sampled_from.py, hypothesis-python/tests/pytest/test_sideeffect_warnings.py
See https://github.com/HypothesisWorks/hypothesis/pull/3837#issuecomment-1894791471
This fixes the spurious warning in pytest's tests by not incrementing the `in_initialization` counter in the `pytest_configure` hook, only at import time. The decrement in `pytest_sessionstart` is called as normal before every test session, so we allow the variable to go negative.
=> Fix pytest plugin issue

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/observability.py
=> Avoid side effect warning when `HYPOTHESIS_EXPERIMENTAL_OBSERVABILITY` is set

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/floats.py, hypothesis-python/src/hypothesis/internal/intervalsets.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_float_encoding.py, hypothesis-python/tests/cover/test_intervalset.py, hypothesis-python/tests/nocover/test_conjecture_engine.py, hypothesis-python/tests/quality/test_poisoned_trees.py, hypothesis-python/tests/quality/test_zig_zagging.py
The last simple bits I could squeeze out of #3818.
The last remaining test I'd like to migrate off `draw_bits` is `test_avoids_zig_zag_trap`. But I spent a fair amount of time trying to make that work, and wasn't able to get it to cooperate, likely because I don't fully understand when `lower_common_block_offset` fires. Any changes to `draw_bits` I made in the zigzag test caused `lower_common_block_offset` to be passed over as a result of this conditional being false: https://github.com/HypothesisWorks/hypothesis/blob/775ed9125f8429b6a92912c723d0cefee8b664cf/hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py#L1011-L1013
but I don't really understand why this conditional is there or the circumstances that cause it to be true.
=> More small IR-related improvements

hypothesis-python/tests/cover/test_stateful.py, hypothesis-python/tests/nocover/test_stateful.py
Ignore for now, submitted for the test run
This just moves one slow test from cover/ to nocover/. Since `check-coverage` succeeds, it should be fine.
=> Move slow stateful test from cover to nocover

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/compat.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/conjecture/test_float_encoding.py, hypothesis-python/tests/cover/test_compat.py, hypothesis-python/tests/cover/test_composite.py, hypothesis-python/tests/cover/test_lookup.py, hypothesis-python/tests/cover/test_sampled_from.py, hypothesis-python/tests/nocover/test_regex.py, hypothesis-python/tests/nocover/test_sampled_from.py
We should sample empty enum.Flag examples by default. They are valid instances after all, representing no flag bits set.
True, a user could opt-in by for example `one_of(sampled_from(Flags), just(Flags(0)))`. But it's better to have complete coverage by default, and if necessary opt-out by adding `.filter(bool)` or similar.
We *might* want to lessen visible impact by shrinking towards first non-empty flag instead of empty. I don't know how best to achieve this, I expected the first (opt-in) example to do exactly that but it doesn't. Anyway, I added a provisional test to modify to whatever shrinking behaviour we desire.
=> Generate empty flag enums

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/pareto.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
*This problem was jointly identified in discussion of #3827 with @tybug  and @hgoldstein95.  Finding this kind of performance issue without knowing to look for it is a great illustration of the value of observability!*
It turns out that we're spuriously aborting many test cases with status=Overrun, due to `ConjectureData.from_buffer()` limiting the max length to the length of the provided bytestring unless `extend=...` is passed.  This makes sense in the `shrink` phase - any longer buffer cannot be a successful shrink, so we may as well abort early - but *not* in the `reuse` or `target` phases.
- The `reuse` phase is easy to fix: simply add the relevant argument to allow extending buffers replayed from the database - we'll get different behaviour, but get a performance gain (and maybe …
=> Avoid pointless discards during the `reuse` and `target` phases

hypothesis-python/RELEASE.rst, hypothesis-python/docs/_static/better-signatures.css, hypothesis-python/docs/changes.rst, hypothesis-python/docs/conf.py, hypothesis-python/docs/settings.rst, hypothesis-python/src/hypothesis/database.py, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, tooling/src/hypothesistooling/projects/hypothesispython.py
Got nerdsniped, closes #3860.
This doesn't actually show type annotations in the signature, because I'm not sure it's net-positive without a bit more filtering than I could easily work out how to do... but all the styling and nitpick fixes I made while trying do seem useful.
Live preview: https://hypothesis--3868.org.readthedocs.build/en/3868/data.html#hypothesis.strategies.builds
=> Update some Sphinx config for docs

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/control.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/observability.py, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/tests/cover/test_observability.py
This is part of #3845, which will enable downstream tools to resolve #213 for good.  Also includes some extra metadata to fix #3861, since it looked easy.
@hgoldstein95, let me know what you think - will this be useful for Tyche?
=> Observability - count sat/unsat calls to `assume()` and stateful `@precondition()`s

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/control.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/cover/test_searchstrategy.py
Fixes https://github.com/HypothesisWorks/hypothesis/issues/3810.
=> Deprecate use of global PRNG in strategies

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/datatree.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/misc.py
I don't think this has a meaningful impact yet, but directly interfacing with the IR will provide benefits in the future (e.g. better/faster shrinking). Also shamelessly snuck in a comment about the IR, since I missed doing it before we merged #3818.
A general question: is there a difference between `@defines_strategy(force_reusable_values=True)` and stating so at the strategy level?
```python
class BooleansStrategy(SearchStrategy):
...
def calc_has_reusable_values(self, recur):
return True
```
Both seemed to work; I used the former here in order to match existing strategies, even though the latter seems more explicit.
=> Directly use `ConjectureData.draw_boolean()` in `booleans()`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py, hypothesis-python/src/hypothesis/strategies/_internal/utils.py, hypothesis-python/tests/conjecture/test_data_tree.py, hypothesis-python/tests/cover/test_searchstrategy.py
Noticed when investigating https://github.com/HypothesisWorks/hypothesis/issues/3874.
Can reproduce with:
```python
@given(st.integers(0, 1<<10000))
def test_f(n):
pass
test_f()
```
```
...
File "/Users/tybug/Desktop/Liam/coding/hypothesis/hypothesis-python/src/hypothesis/strategies/_internal/utils.py", line 163, in to_jsonable
return float(obj)
^^^^^^^^^^
OverflowError: int too large to convert to float
```
=> Fix error with very large ints in `to_jsonable`

hypothesis-python/RELEASE.rst, hypothesis-python/docs/ghostwriter.rst, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/tests/ghostwriter/recorded/addition_op_magic.txt, hypothesis-python/tests/ghostwriter/recorded/addition_op_multimagic.txt, hypothesis-python/tests/ghostwriter/recorded/division_binop_error_handler.txt, hypothesis-python/tests/ghostwriter/recorded/division_operator.txt, hypothesis-python/tests/ghostwriter/recorded/division_operator_with_annotations.txt, hypothesis-python/tests/ghostwriter/recorded/division_roundtrip_arithmeticerror_handler.txt, hypothesis-python/tests/ghostwriter/recorded/division_roundtrip_error_handler.txt, hypothesis-python/tests/ghostwriter/recorded/division_roundtrip_error_handler_without_annotations.txt, hypothesis-python/tests/ghostwriter/recorded/division_roundtrip_typeerror_handler.txt, hypothesis-python/tests/ghostwriter/recorded/matmul_magic.txt, hypothesis-python/tests/ghostwriter/recorded/multiplication_magic.txt, hypothesis-python/tests/ghostwriter/recorded/multiplication_operator.txt, hypothesis-python/tests/ghostwriter/recorded/multiplication_operator_unittest.txt, hypothesis-python/tests/ghostwriter/test_expected_output.py, website/content/2017-04-05-how-not-to-die-hard-with-hypothesis.md
I just found [this excellent competition](https://arxiv.org/abs/2401.15189) ([repo](https://github.com/ThunderKey/python-tool-competition-2024)) by @ThunderKey et al, and decided to add a note explaining that the Ghostwriter is trying to do something different.
Then I went to add a link to my demo page for `hypothesis write operator.mul`, and got nerdsniped into upgrading the Ghostwriter... so I guess it's turned out to be relevant after all 😅 
Bonus bits: fixes https://github.com/HypothesisWorks/hypothesis/issues/3875 and adds a non-public hook for https://github.com/nchammas (https://github.com/HypothesisWorks/hypothesis/pull/3400#issuecomment-1950839734).
=> Add a research note on the Ghostwriter + improve binop test generation

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/cover/test_error_in_draw.py, hypothesis-python/tests/test_annotated_types.py
First commit inspired by https://github.com/HypothesisWorks/hypothesis/issues/3739#issuecomment-1954952599.  Second fixes https://github.com/HypothesisWorks/hypothesis/issues/3891 (along with https://github.com/annotated-types/annotated-types/pull/62 upstream).
I sometimes wonder what the world would be like if everyone cared this much about error messages...
=> Add note to errors from strategies

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/src/hypothesis/internal/filtering.py, hypothesis-python/src/hypothesis/strategies/_internal/collections.py, hypothesis-python/src/hypothesis/strategies/_internal/lazy.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/tests/conjecture/test_test_data.py, hypothesis-python/tests/cover/test_custom_reprs.py, hypothesis-python/tests/cover/test_filter_rewriting.py
See https://github.com/HypothesisWorks/hypothesis/issues/3795; implementing rewriting for `st.lists(...).map(<some type>).filter(<length check>)` covers all the common cases with pretty reasonable code.  I suppose we'll learn from users, eventually, if there's something this doesn't cover.
The known gaps are `st.from_type(bytearray)` and `memoryview`, because they can only operate on bytestrings and therefore require a `st.lists(...).map(bytes).map(memoryview)` and this branch only sees through one layer of mapping.  We could generalize MappedStrategy to have a tuple of pack functions, analogously to FilteredStrategy?  But tbh I'm inclined to ship without them and revisit later.
let's see what CI thinks...
=> Rewrite length filters for diverse collection types

.gitignore, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/strings.py, hypothesis-python/src/hypothesis/vendor/pretty.py, hypothesis-python/tests/cover/test_filter_rewriting.py, hypothesis-python/tests/cover/test_health_checks.py
Turns out that all the hard parts were handled in https://github.com/HypothesisWorks/hypothesis/pull/3730 and https://github.com/HypothesisWorks/hypothesis/pull/3839, which is pretty convenient!
Closes https://github.com/HypothesisWorks/hypothesis/issues/3795; length bounds are already done and I don't think any of the other listed-as-optional ideas are worth the trouble.
=> Rewrite regex filters on `text()` and `binary()`

hypothesis-python/RELEASE.rst, hypothesis-python/docs/numpy.rst, hypothesis-python/src/hypothesis/extra/array_api.py, hypothesis-python/tests/array_api/README.md
The array API has just had its `2023.12` release (https://github.com/data-apis/array-api/pull/755)... in Feb 2024 :sweat_smile: This PR simply accepts `api_version="2023.12"` for `extra.array_api.make_strategies_namespace()`.
---
I believe there aren't any changes that should necessitate what the strategies namespace is doing for `2023.12`! I assume this will be an on-going trend, as I can't think of any existing discussions that would either shake-up the existing strategies or want us to add news ones.
I did have the idea to maybe just warn instead of erroring when `api_version` is greater than the last item of `RELEASED_VERSIONS` (and not `draft`), so we don't "annoy" libraries by asking them to use an older `api_version` kwarg for `make_strategies_namespace()` whilst they wait on us to …
=> Support `2023.12` version of the array API

hypothesis-python/tests/pandas/test_indexes.py
The [sys.maxsize](https://docs.python.org/3/library/sys.html#sys.maxsize) attribute stores the maximum size of the *signed* size type, so `is_32bit` is never `True`. Fixing this may also make the special-casing for windows obsolete (but I have no windows machine to verify that).
=> Fix 32-bit architecture detection in pandas index test

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/src/hypothesis/strategies/_internal/collections.py, hypothesis-python/tests/numpy/test_gen_data.py
Closes #3900.
Also includes the error-message fix for https://github.com/data-apis/array-api-tests/issues/238.
=> Fix missing-`fill` problem in `arrays()`

.github/workflows/main.yml, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/tests/conjecture/test_data_tree.py, hypothesis-python/tests/cover/test_filter_rewriting.py, hypothesis-python/tests/cover/test_lambda_formatting.py
- Fix #3916
- The regression was introduced by #3915
- PEP 696 was accepted but is not currently implemented python/cpython#116129
also closes #3918 by cherry-picking
=> Fix unimplemented default TypeVar argument in 3.13a4

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/tests/cover/test_stateful.py
Fixes #3618; it turns out this wasn't about filtering at all.
=> Fix performance of `RuleBasedStateMachine` with data-hungry rules

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/datatree.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinking/common.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinking/floats.py, hypothesis-python/tests/conjecture/common.py, hypothesis-python/tests/conjecture/test_float_encoding.py, hypothesis-python/tests/conjecture/test_ir.py
I had originally tried writing a `shrinker_v2.py` from scratch...and quickly abandoned it as infeasible. I think my current plan is to convert shrinking passes one by one (where possible, which may or may not be all of them). `minimize_floats` is one of the more directly applicable ones. 
Definitely open to feedback on the details of the migration approach here. 
There is overlap in the `IRTree` definition with #3806, though it's not exactly the same. Either is fine to merge before the other; I'll handle conflict resolution whichever way.
=> migrate `Float` shrinker to the ir

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/conjecture/common.py, hypothesis-python/tests/conjecture/test_dfa.py, hypothesis-python/tests/conjecture/test_ir.py, hypothesis-python/tests/conjecture/test_junkdrawer.py, hypothesis-python/tests/conjecture/test_shrinker.py, hypothesis-python/tests/cover/test_direct_strategies.py
Part of #3921.
There's a failure on `test_optimises_the_pareto_front`:
```
...
File "/Users/tybug/Desktop/Liam/coding/hypothesis/hypothesis-python/tests/conjecture/test_pareto.py", line 206, in test_optimises_the_pareto_front
assert len(runner.pareto_front) == 6
AssertionError: assert 26 == 6
+  where 26 = len(<hypothesis.internal.conjecture.pareto.ParetoFront object at 0x13b9c68d0>)
+    where <hypothesis.internal.conjecture.pareto.ParetoFront object at 0x13b9c68d0> = <hypothesis.internal.conjecture.engine.ConjectureRunner object at 0x13b9c6bd0>.pareto_front
```
I am still fuzzy on the purpose of the pareto front for cases when `target()` is not involved. With `target()`, it's clear to me that we want to keep the pareto front of all distinct target keys. But what metric are we optimizing …
=> Migrate `reorder_examples` to the IR

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/conjecture/test_ir.py, hypothesis-python/tests/conjecture/test_shrinker.py
I think these are the last remaining directly translatable passes. The remaining two groups are "block programs" (roughly corresponding to new "node programs" with a single instruction `X`, no `-`) and "everything else".
=> Migrate `pass_to_descendant` and `redistribute_block_pairs` shrinker passes

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/conjecture/test_ir.py
Forgot that float shrinking is more complicated than just "closest to 0". 
Full disclosure, I'm hoping to defer some of this work to later because it would substantially complicate things for probably little benefit (maybe we save one or two shrink calls here and there). I just got it to a point where it's not *wrong* anymore.
When we redefine ordering for the ir, we can probably simplify this function to "is first in ordering", like we do for buffers (first in ordering == zero buffer)
=> Fix `trivial` computation for floats

hypothesis-python/docs/strategies.rst
Hello!
I implemented strategies to generate random molecules based on hypothesis and I would be super happy if it was listed on the extensions page of the hypothesis docs! :)
Best,
Steffen
=> Add hypothesis-rdkit to list of extensions in docs

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/tests/cover/test_filter_rewriting.py, hypothesis-python/tests/cover/test_lambda_formatting.py
Closes https://github.com/HypothesisWorks/hypothesis/issues/3919.  This _wasn't_ fixed upstream, but turns out to be an easy workaround, and I've reported https://github.com/python/cpython/issues/117174.
=> Work around weird lambda issue by popping entry from `linecache`

.github/workflows/main.yml, .gitignore, build.sh, hypothesis-python/RELEASE.rst, hypothesis-python/scripts/validate_branch_check.py, hypothesis-python/setup.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/extra/_patching.py, hypothesis-python/src/hypothesis/extra/array_api.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/coverage.py, hypothesis-python/src/hypothesis/internal/observability.py, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/src/hypothesis/strategies/_internal/datetime.py, hypothesis-python/tests/common/setup.py, hypothesis-python/tox.ini, pytest.ini, requirements/coverage.in, requirements/coverage.txt, requirements/fuzzing.txt, requirements/tools.txt, tooling/src/hypothesistooling/__main__.py
I think this is enough of a speedup to close https://github.com/HypothesisWorks/hypothesis/issues/3524.
=> Parallel coverage tests

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/datatree.py, hypothesis-python/src/hypothesis/internal/conjecture/pareto.py, hypothesis-python/tests/conjecture/test_utils.py, hypothesis-python/tests/nocover/test_integer_ranges.py
This fixes https://github.com/HypothesisWorks/hypothesis/issues/3921#issuecomment-2008569274 by always drawing the integer value from the full range.
Also closes https://github.com/HypothesisWorks/hypothesis/issues/3940 by improving the error message.
(worked on irl with @Zac-HD 😄)
=> Improve integer weight draw and flaky error message

.github/workflows/main.yml, AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/array_api.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/tests/array_api/conftest.py, hypothesis-python/tests/array_api/test_arrays.py, hypothesis-python/tests/array_api/test_partial_adoptors.py, hypothesis-python/tests/numpy/test_from_dtype.py, hypothesis-python/tests/numpy/test_gen_data.py, hypothesis-python/tox.ini, tooling/src/hypothesistooling/__main__.py
This also replaces a couple of top-level `pytest.warns` with ignores, which was the simplest way I found to silence the errors caused by the change in behavior of `numpy>=2`.
Still missing: a way to actually test this with a nightly build of `numpy`, but since I don't know your CI well enough I'll need help with that.
With `numpy>=2`, I'm getting a bunch of other failures locally, mostly concerning the removal of `numpy.asfarray`.
=> compatibility with `numpy>=2.0`

hypothesis-python/src/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/datatree.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinking/common.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinking/lexical.py, hypothesis-python/tests/conjecture/test_data_tree.py, hypothesis-python/tests/conjecture/test_minimizer.py, hypothesis-python/tests/conjecture/test_order_shrinking.py, hypothesis-python/tests/cover/test_complex_numbers.py, hypothesis-python/tests/cover/test_composite.py, hypothesis-python/tests/cover/test_direct_strategies.py, hypothesis-python/tests/cover/test_shrink_budgeting.py, hypothesis-python/tests/cover/test_simple_characters.py, hypothesis-python/tests/cover/test_simple_collections.py, hypothesis-python/tests/nocover/test_find.py, hypothesis-python/tests/nocover/test_simple_numbers.py
No user-facing changes, just (1) some cleanups, (2) changes in preparation for the shrinker ir migration, and (3) a pretty printer for `DataTree`.
=> Small cleanups, add a `DataTree` pretty printer

hypothesis-python/RELEASE.rst, hypothesis-python/src/RELEASE.rst, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/tests/cover/test_reflection.py
Addresses the performance part of #3963. Have not profiled memory. It should also be significantly reduced as we're calling `ast.parse` less now, but this will not address any underlying memory leak, if one exists.
=> cache extract_lambda_source

hypothesis-python/tests/common/strategies.py, hypothesis-python/tests/conjecture/common.py, hypothesis-python/tests/conjecture/test_ir.py
got tired of seeing this fail 😅 https://github.com/HypothesisWorks/hypothesis/actions/runs/8946209326/job/24576465627
possibly *too* aggressive with removing `HealthCheck.too_slow`? ah well, let's run it through the ci wringer and we can revert some if necessary.
=> Improve `draw_string_kwargs` efficiency

hypothesis-python/RELEASE.rst, hypothesis-python/docs/strategies.rst, hypothesis-python/src/hypothesis/internal/coverage.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/cover/test_composite.py
Closes https://github.com/HypothesisWorks/hypothesis/issues/3970, and fixes https://github.com/HypothesisWorks/hypothesis/issues/3968 too since I worked out what was happening.
=> Don't warn on typing overloads for a composite function

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/datatree.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/conjecture/common.py, hypothesis-python/tests/conjecture/test_alt_backend.py, hypothesis-python/tests/conjecture/test_data_tree.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_ir.py
I was not expecting to go this deep into the caching logic, but it became more and more clear to me while working on #3962 that our internal `mark_invalid` for misaligned datas actually requires some more thought, and we were only getting away with it before by luck.
The issue goes something like this. Say a test function draws an integer then a boolean. That means a data with an ir prefix of `[0, True]` is valid and a data of `[0, 2]` is misaligned. The latter hits an internal `mark_invalid` and has `Status.INVALID`. Now, how should `[0, 2]` be cached? Its resulting ir tree is  just `[0]`, since it was invalid "between" 0 and 2 and we don't know what value the test function would have drawn in this scenario. But mapping `[0]: invalid` in our cache would be incorrect! In this case `[0]` …
=> Improve caching for misaligned `ConjectureData`s

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/datatree.py, hypothesis-python/tests/conjecture/test_ir.py
closes #3974. Turns out this definitely can happen in practice! 
The reproducer in the issue is actually the worst case for this bug. Conditions for triggering are a strategy with a single unbounded `st.integers` strategy as the heaviest (or only) branching point in its choice tree. I'm guessing we're saturating the 8 and/or 16 bit integer buckets and then getting unlucky by trying to draw from said buckets 10 times in a row, triggering our deduplication fallback to exhaustive enumeration.
=> Implement `all_children` for unbounded integers

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/pandas/impl.py, hypothesis-python/src/hypothesis/internal/compat.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/cover/test_composite.py
In an attempt to help with https://github.com/HypothesisWorks/hypothesis/issues/3074, I have added type annotations to `hypothesis/internal/conjecture/engine.py`. I have checked these type hints with both `mypy` and `pyright`, and verified a few of the trickier-to-statically-determine types by checking their runtime types in the tests.
There are three things that I'm still confused about.
1. Can `Overrun` be a valid `value` for `self.interesting_examples`?
In all places but this one sample (lines 389 in this PR), all of the keys for `self.interesting_examples` are `ConjectureResult`. However, this assignment may possibly be `Overrun`. Indeed, in one test, `test_backend_can_shrink_bytes`, this does occur. This seems (to me) to be the only place in the tests where this `Overrun` assignment …
=> Add type annotations to `hypothesis/internal/conjecture/engine.py`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/django/_impl.py, hypothesis-python/tests/django/toystore/models.py, hypothesis-python/tests/django/toystore/test_given_models.py
the docs say `from_model()` won't try to create a strategy for any `AutoField`s, but the code only does that for `AutoField`s that have `auto_created` set to `True.  this updates the code to match the docs.
this resolves issue #3978.
=> extra/django: fix from_model for non-auto-created AutoFields

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/cover/test_lookup_py39.py, hypothesis-python/tests/test_annotated_types.py
Fixes https://github.com/HypothesisWorks/hypothesis/issues/3980, closes https://github.com/HypothesisWorks/hypothesis/pull/3981.  
Motivated by https://github.com/pydantic/pydantic/issues/4682#issuecomment-2105327657; supporting nested-`GroupedMetadata` and short-circuiting if such an item contains an `st.SearchStrategy` will allow for extensive control purely from downstream code.
=> Improve handling of GroupedMetadata

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/engine.py
Regressed in #3961. See recent failure https://github.com/HypothesisWorks/hypothesis/actions/runs/9066538054/job/24909659955 on https://github.com/HypothesisWorks/hypothesis/commit/5983af0b284b7c30cea15d68cba89972977ad402.
`new_data` can in fact be `Overrun`, though it is still safe to set `data = new_data` because `data` starts as `>= OVERRUN` and we maintain a `new_data.status >= data.status` invariant.
Some annoying duplicated code here for the `failed_mutations` case to make the type checker happy...cleanest way I could find to do it, but possibly a better way exists.
=> Fix overly strict type assertion

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/datatree.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/nocover/test_regressions.py
closes #3874. Also includes a test case for recent coverage flakes in eg #3987.
=> Handle overruns in `generate_novel_prefix`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/compat.py, hypothesis-python/src/hypothesis/internal/conjecture/choicetree.py, hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py, hypothesis-python/src/hypothesis/internal/conjecture/pareto.py, hypothesis-python/src/hypothesis/strategies/_internal/collections.py, hypothesis-python/tests/conjecture/test_junkdrawer.py, hypothesis-python/tests/nocover/test_sampled_from.py, hypothesis-python/tests/quality/test_shrink_quality.py
`UniqueSampledListStrategy` uses `LazySequenceCopy` to pop elements from the list. Because `LazySequenceCopy` only implemented pop-from-end, we swapped the element we wanted to pop to the end before popping. But this leaves the list in a bad state for shrinking: if `i = 0`, we just swapped the last element, which is the most complicated in shrinking order, to the front of the list, leaving it there for future passes. This means an ir tree of `[0, 0, 0]` indicating the first three elements of the sequence corresponds to `{0, 8, 9}` for `sets(range(10))`.
The solution is properly implementing `.pop(i)`. I've applied this in other places we use the swap trick, though I'm less confident than `UniqueSampledListStrategy` that this is not a behavioral change.
=> Implement `LazySequenceCopy.pop(i)`

CONTRIBUTING.rst, hypothesis-python/RELEASE-sample.rst, hypothesis-python/RELEASE.rst, tooling/src/hypothesistooling/projects/hypothesispython.py, whole_repo_tests/test_release_files.py, whole_repo_tests/test_rst_is_valid.py
I've always missed a sample `RELEASE.rst` to start with, so I wouldn't have to search for examples in recent "good" PRs.
I think something like this would be useful! Ideally with examples of all relevant (for us) Sphinx roles, which I was hoping you could help with :tulip:
=> Sample RELEASE.rst

guides/internals.rst
PR #2278 moved the location of the `test_conjecture_engine.py` file. This PR adjusts sources to changes.
=> Update `test_conjecture_engine.py` reference

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/cache.py
The issue is when multiple tests share the same cache kwargs, it may lead to an error like the one reported in https://github.com/schemathesis/schemathesis/issues/2269
Hopefully, the performance impact is negligible. At the moment I can't come up with a reasonably small test to reproduce the issue.
=> fix: Race condition inside internal cache implementation

hypothesis-python/tests/nocover/test_recursive.py
This PR changes the flaky gc-hook test to run in a subprocess (https://github.com/HypothesisWorks/hypothesis/pull/4007#issuecomment-2168759932)
=> Test tweaks

hypothesis-python/.coveragerc, hypothesis-python/RELEASE.rst, hypothesis-python/docs/strategies.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/extra/_patching.py, hypothesis-python/src/hypothesis/internal/entropy.py, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/src/hypothesis/statistics.py, hypothesis-python/tests/cover/test_composite.py, hypothesis-python/tox.ini
Fixes #4003 
Since late March, we haven't had coverage checks active outside of `internal.conjecture`. We should plug this hole as soon as possible, so it doesn't grow more.
The before-state is of significant size. I will likely just add `#pragma: no cover  # FIXME` to anything that is not immediately obvious, so that we can at least get the configuration change in quickly.
```
Name                                                      Stmts   Miss Branch BrPart  Cover   Missing
-------------------------------------------------------------------------------------------------------
[elided]
-------------------------------------------------------------------------------------------------------
TOTAL                                                       12917    809   5202     75    93%
``` …
=> Reinstate coverage

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/tests/conjecture/test_alt_backend.py
Move `post_test_case_hook` higher up so it correctly handles symbolic lifetimes. Reported in https://github.com/pschanely/CrossHair/issues/263, regressed in https://github.com/HypothesisWorks/hypothesis/pull/3977.
Also includes a bandaid for flakiness when replaying interesting non-hypothesis backend examples. I ran into this when we flakily raised `DeadlineExceeded` with the crosshair backend. I think probably we want to raise `Flaky` here instead of silently exiting though.
=> Adjust `post_test_case_hook` scope

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/cache.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/tests/cover/test_cache_implementation.py, hypothesis-python/tests/nocover/test_cache_implementation.py
Fix some issues with the cache implementation. ~~No actual bugs, only latent issues and cleanup.~~
- The cache docs were were not in sync with the code: it was documented that `on_access` should return the updated score, but the code expected the score to be modified in-place. Code changed to match docs.
- Simplify by removing the unnecessary count of pinned entries.
- "ignore `pin()` on expired keys" is unsafe: if we later insert the key, the pin-state of the key is unknown. This can be observed "in the wild" in our current usage — by adding artificial cache pressure before `pin()` we fail when calling `unpin()` on a not-pinned key.
- `max_size=0` (ignoring new entries) is no longer allowed, as that violates the handy (for atomicity) "last entry successfully set is present in cache" …
=> Cache fixes

.github/workflows/main.yml, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/django/_fields.py, hypothesis-python/src/hypothesis/extra/django/_impl.py, hypothesis-python/tests/django/manage.py, hypothesis-python/tests/django/toys/settings.py, hypothesis-python/tests/django/toystore/models.py, hypothesis-python/tests/django/toystore/test_given_models.py, hypothesis-python/tox.ini, tooling/src/hypothesistooling/__main__.py
This PR adds support for Django 5.0, and drops support for Django < 4.2 as 4.2 is the [oldest currently supported version](https://endoflife.date/django).
Upgrade considerations:
- from 5.0 support for pytz in Django is [dropped](https://docs.djangoproject.com/en/5.0/releases/5.0/#features-removed-in-5-0) — use of pytz was [deprecated in 4.0](https://docs.djangoproject.com/en/5.0/releases/4.0/#zoneinfo-default-timezone-implementation) in favour of Python's built-in `zoneinfo`; and
- a transitional setting, [FORMS_URLFIELD_ASSUME_HTTPS](https://docs.djangoproject.com/en/5.0/ref/settings/#std-setting-FORMS_URLFIELD_ASSUME_HTTPS) is added until 6.0, when the default for [URLField.assume_scheme](https://docs.djangoproject.com/en/5.0/ref/forms/fields/#django.forms.URLField.assume_scheme) will …
=> Support Django 5.0

hypothesis-python/RELEASE.rst, hypothesis-python/setup.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/provisional.py, hypothesis-python/src/hypothesis/strategies/_internal/utils.py, hypothesis-python/tests/conjecture/test_alt_backend.py
* `post_test_case_hook` has been renamed to `realize` and is used in more places where we want to realize symbolic values
* `avoid_realization` backend class variable added, which backends can set to disable features that would cause premature realization
* I've tentatively exposed `hypothesis.provisional.realize` as part of our unstable-but-public api, to address https://github.com/pschanely/hypothesis-crosshair/issues/7 among others. If we want to make this less public, we can put it in `hypothesis.internal.conjecture.data` for now.
@pschanely here are the local modifications I made to hypothesis-crosshair:
```python
class CrossHairPrimitiveProvider(PrimitiveProvider):
avoid_realization = True
...
def realize(self, value):
return self.export_value(value)
```
This includes a fix for …
=> Add and use `realize` and `avoid_realization` backend hooks

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/scrutineer.py, hypothesis-python/tests/common/utils.py, hypothesis-python/tests/conftest.py, hypothesis-python/tests/cover/test_flakiness.py, hypothesis-python/tests/cover/test_monitoring.py
Fixes #4021 
When a warning is raised (due to `-Werror`) during test execution, it may cause the test to raise `Flaky` from `StopTest`. This makes the error message less informative.
~~This PR makes `HypothesisWarning` fatal, not only `HypothesisDeprecationWarning`. Because the warnings are meant to be seen.~~
=> Improve internal warning tests

hypothesis-python/setup.py, hypothesis-python/tests/array_api/test_arrays.py, hypothesis-python/tests/common/debug.py, hypothesis-python/tests/common/setup.py, hypothesis-python/tests/cover/test_datetimes.py, hypothesis-python/tests/cover/test_direct_strategies.py, hypothesis-python/tests/cover/test_slices.py, hypothesis-python/tests/numpy/test_gen_data.py, hypothesis-python/tests/numpy/test_gufunc.py
Mostly but not exclusively aimed at #3914 / extracted from #4034 to make that smaller and easier to work with.
=> Test-only improvements

hypothesis-python/RELEASE.rst, hypothesis-python/scripts/other-tests.sh, hypothesis-python/setup.py, hypothesis-python/tests/cover/test_draw_example.py, hypothesis-python/tests/cover/test_explicit_examples.py, hypothesis-python/tests/ghostwriter/test_ghostwriter.py, hypothesis-python/tests/nocover/test_collective_minimization.py, pyproject.toml
Before creating the temporary functions, moves the local directory to a clean temporary directory; this should guarantee that the files to be created don't exist, and handles cleanup automatically.
This also works when the local directory that the tests are executed from is not writable, but the temporary directory is.
I have tested that the way fixture resolution works, it seems that `in_temp_file` will only be executed once if you include both of the file-creating fixtures.
=> Use tmp_path in ghostwriter tests

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py, hypothesis-python/tests/conftest.py
=> Store reference to time.perf_counter for gc accounting

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/datatree.py, hypothesis-python/tests/conjecture/test_forced.py, hypothesis-python/tests/conjecture/test_ir.py
The range for semibounded integers changes subtly based on `shrink_towards`(and therefore certain min/max value params). Correctly take that into account when computing `all_children`, and when validating `forced` in `draw_integer`.
Here's a reproducer after ~10s:
```python
from hypothesis import *
from hypothesis import strategies as st
@given(st.integers(min_value=2**128))
@settings(max_examples=1000000)
def f(n):
pass
f()
```
=> Fix semi-bounded `all_children` computation

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/control.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/functions.py, hypothesis-python/tests/cover/test_pretty.py
Found while investigating #4014. This manually hoists the `should_note` call up a level to avoid computation when not necessary. 
This is particularly bad for `@given(st.data())`, which reprs each draw, and also `fixed_dictionaries`, which incurred lambda source extractions in `record_call` via `MappedStrategy.map`.
This takes https://github.com/HypothesisWorks/hypothesis/issues/4014#issuecomment-2257127814 from 5s -> 4.5s.
=> Avoid pretty printing overhead in most cases

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/cache.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/tests/cover/test_cache_implementation.py
Introduces a new, more performant, "pure LRU" cache in place of our scan resistant one. 
I'm unsure how desirable scan resistance here is. I imagine it was introduced back when this cache was being used purely for `ConjectureData` caches. We pay a pretty hefty price for it in the heap rebalancing, though, so I think the tradeoff here is worthwhile.
Should mostly address #4014. This takes https://github.com/HypothesisWorks/hypothesis/issues/4014#issuecomment-2257127814 from 5s -> 3.9s (#4063 not included)
=> Use a more performant `LRUCache` for ir kwargs caches

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/engine.py
Fixes a pathological bug I stumbled across while playing around with #3999:
```python
from hypothesis import *
from hypothesis import strategies as st
@given(st.data())
@settings(suppress_health_check=HealthCheck.all())
def f(data):
data.conjecture_data.draw_integer(0, 1 << 30_000)
data.conjecture_data.draw_integer(0, 1 << 30_000)
data.conjecture_data.draw_integer(0, 1 << 30_000)
f()
```
```python
File "/Users/tybug/Desktop/Liam/coding/hypothesis/hypothesis-python/src/hypothesis/internal/conjecture/engine.py", line 1241, in _run
self.generate_new_examples()
File "/Users/tybug/Desktop/Liam/coding/hypothesis/hypothesis-python/src/hypothesis/internal/conjecture/engine.py", line 1002, in generate_new_examples
assert len(prefix) <= BUFFER_SIZE
^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```
I …
=> Truncate novel prefixes

.github/workflows/main.yml, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/django/_impl.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinking/collection.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinking/ordering.py, hypothesis-python/src/hypothesis/internal/conjecture/utils.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/cover/test_attrs_inference.py, hypothesis-python/tests/cover/test_example.py, hypothesis-python/tests/cover/test_lambda_formatting.py, hypothesis-python/tests/dpcontracts/test_contracts.py, requirements/coverage.txt, requirements/fuzzing.txt, requirements/test.txt, requirements/tools.in, requirements/tools.txt, tooling/scripts/ensure-python.sh, tooling/src/hypothesistooling/__main__.py
Fixes https://github.com/HypothesisWorks/hypothesis/issues/4067.
Manually ran this because [`types-pkg-resources` got yanked](https://pypi.org/project/types-pkg-resources/), and so [our cronjob failed](https://github.com/HypothesisWorks/hypothesis/actions/runs/10256597580/job/28376009901).  I also adjusted our python version upgrade logic to pick the `.0rc1` over `-dev`.
=> Upgrade pinned dependencies

hypothesis-python/RELEASE.rst, hypothesis-python/docs/schema_observations.json, hypothesis-python/scripts/other-tests.sh, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/observability.py, hypothesis-python/tests/common/utils.py, hypothesis-python/tests/conjecture/test_alt_backend.py, hypothesis-python/tests/cover/test_observability.py
@pschanely you can put whatever (json-encodable) stuff in here that you might want 😁 
@hgoldstein95 fyi, you might be interested in https://github.com/pschanely/hypothesis-crosshair/issues/22 too.
=> Allow alternative backends to provide observability metadata

hypothesis-python/RELEASE.rst, hypothesis-python/setup.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/tests/array_api/test_arrays.py, hypothesis-python/tests/common/debug.py, hypothesis-python/tests/conjecture/test_alt_backend.py, hypothesis-python/tests/cover/test_core.py, hypothesis-python/tests/cover/test_datetimes.py, hypothesis-python/tests/cover/test_deadline.py, hypothesis-python/tests/cover/test_health_checks.py, hypothesis-python/tests/cover/test_targeting.py, hypothesis-python/tests/nocover/test_randomization.py, hypothesis-python/tests/nocover/test_recursive.py, hypothesis-python/tests/nocover/test_simple_numbers.py, hypothesis-python/tests/numpy/test_gen_data.py, hypothesis-python/tests/quality/test_shrink_quality.py
Extracted from https://github.com/HypothesisWorks/hypothesis/pull/4034 to make that smaller + easier to review again 🙂
=> Various test cleanups for Crosshair integration

hypothesis-python/tests/conjecture/common.py
This probably doesn't matter too much, but saves a few cycles not running the explain phase in tests.
=> Don't run explain phase unnecessarily

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/datatree.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinking/bytes.py, hypothesis-python/src/hypothesis/strategies/_internal/strings.py, hypothesis-python/tests/common/strategies.py, hypothesis-python/tests/conjecture/common.py, hypothesis-python/tests/conjecture/test_alt_backend.py, hypothesis-python/tests/conjecture/test_data_tree.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_ir.py, hypothesis-python/tests/conjecture/test_minimizer.py, hypothesis-python/tests/conjecture/test_shrinker.py, hypothesis-python/tests/conjecture/test_test_data.py, hypothesis-python/tests/cover/test_filter_rewriting.py, hypothesis-python/tests/cover/test_health_checks.py, hypothesis-python/tests/nocover/test_conjecture_engine.py, hypothesis-python/tests/nocover/test_duplication.py, hypothesis-python/tests/nocover/test_explore_arbitrary_languages.py, hypothesis-python/tests/quality/test_poisoned_trees.py, hypothesis-python/tests/quality/test_zig_zagging.py
Many changes here were analogous to strings, and I've unified approaches where it made sense.
=> Add support for variable-width bytes in the IR

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/numpy.py
Failed on numpy nightlies: closes https://github.com/HypothesisWorks/hypothesis/issues/4102. 
This is in `src/`, so actual users will start hitting this once the numpy nightly becomes not nightly.
(possibly this was the root cause of the other #4102 errors, we'll see what ci says.)
=> Remove now-incorrect numpy assertion

hypothesis-python/docs/details.rst
Given snippet doesn't find any satisfying examples anymore. Not sure if it can be fixed through tweaking some settings but it is misleading in its current state. I don't know what changed since the original documentation was added, maybe @DRMacIver can comment.
See the relevant PR:
https://github.com/HypothesisWorks/hypothesis/pull/2600
which was mistakenly reverted in:
https://github.com/HypothesisWorks/hypothesis/pull/3238
=> Remove misleading assume example.

hypothesis-python/RELEASE.rst, hypothesis-python/scripts/other-tests.sh, hypothesis-python/src/_hypothesis_ftz_detector.py, hypothesis-python/src/hypothesis/configuration.py, hypothesis-python/src/hypothesis/errors.py, hypothesis-python/src/hypothesis/extra/_patching.py, hypothesis-python/src/hypothesis/internal/cache.py, hypothesis-python/src/hypothesis/internal/cathetus.py, hypothesis-python/src/hypothesis/internal/compat.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/detection.py, hypothesis-python/src/hypothesis/internal/filtering.py, hypothesis-python/src/hypothesis/internal/scrutineer.py, hypothesis-python/src/hypothesis/provisional.py, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/src/hypothesis/statistics.py, hypothesis-python/src/hypothesis/strategies/_internal/random.py, hypothesis-python/src/hypothesis/strategies/_internal/regex.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/src/hypothesis/utils/dynamicvariables.py, hypothesis-python/tests/conjecture/test_alt_backend.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_utils.py, hypothesis-python/tests/patching/callables.py, hypothesis-python/tests/patching/test_patching.py, hypothesis-python/tox.ini, tooling/src/hypothesistooling/__init__.py
The general theme here is trying to make it easier to review and hopefully merge other PRs by pulling out some easy stuff to shrink them.
Plus a performance improvement for stateful testing while I was looking at it, and more-compatible paths in patch headers.
Fixes https://github.com/HypothesisWorks/hypothesis/issues/4116.
=> Various cleanups

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/errors.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/tests/conjecture/test_alt_backend.py, hypothesis-python/tests/cover/test_regressions.py
Sometimes, an alternative backend will just be done, and this new exception (and handlers) provides an interface to communicate that.  There are several reasons this could happen, including:
- `not_realizable`: e.g. hitting a timeout while attempting to `.realize()` some value, as in https://github.com/pschanely/hypothesis-crosshair/issues/21
- if we hit more than ten of these, we switch to the Hypothesis backend to preserve good performance.
- `exhausted`: running out of useful work to do, e.g. if the test function immediately invokes compiled code then Crosshair doesn't have much to do, and can hand back to the Hypothesis backend
- `verified`: for the cases where we've estabilished that the test will _never fail_, similar to Hypothesis' own `ExitReason.finished` if the datatree is …
=> Add `BackendCannotProceed` to improve integration

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/vendor/pretty.py, hypothesis-python/tests/cover/test_pretty.py
This PR adds logic so that attrs and dataclass defined classes get pretty printed directly via their repr.
Use case: They mostly pretty print fine with reprs, but I wanted to define custom pretty printing for a type that was contained in a dataclass, which doesn't work if you rely on repr printing.
I've made this a minor release because it changes user visible behaviour in a way that we have no compatibility requirements on but that is arguably undesirable in some cases. In particular if a type is defined this way but has a custom repr, we will now ignore that repr. There's plenty of precedent for us doing that, and the logic of when we should use the repr after all is quite fiddly, so I think this is OK.
=> Add better support for pretty-printing record types

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/filtering.py, hypothesis-python/src/hypothesis/provisional.py, hypothesis-python/src/hypothesis/strategies/_internal/datetime.py, hypothesis-python/tests/cover/test_filter_rewriting.py
Closes #4000; dealing with timezones makes datetimes and times not worth the trouble.
=> Filter-rewriting for more efficient `from_type(pydantic.types.condate)`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/src/hypothesis/strategies/_internal/numbers.py, hypothesis-python/tests/conjecture/common.py, hypothesis-python/tests/conjecture/test_alt_backend.py, hypothesis-python/tests/conjecture/test_forced.py, hypothesis-python/tests/conjecture/test_shrinker.py, hypothesis-python/tests/conjecture/test_test_data.py, hypothesis-python/tests/conjecture/test_utils.py, hypothesis-python/tests/cover/test_filtered_strategy.py, hypothesis-python/tests/quality/test_shrink_quality.py
This makes `st.integers` map to a single `draw_integer` call in our IR, improving efficiency for shrinking, and possibly generation due to e.g. example copying (`generate_mutations_from`). Previously discussed at https://github.com/HypothesisWorks/hypothesis/pull/4101#discussion_r1753038201 and other intermittent places. 
The new interface is:
```python
@abc.abstractmethod
def draw_integer(
self,
min_value: Optional[int] = None,
max_value: Optional[int] = None,
*,
weights: Optional[dict[int, float]] = None,
shrink_towards: int = 0,
forced: Optional[int] = None,
) -> int:
```
I've made several practical compromises here to ease implementation:
- `sum(p)` must be strictly less than 1. In other words, weights cannot be a total interval. This allows the forcing implementation to force into …
=> Fold integer endpoint upweighting into `weights=`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/datatree.py, hypothesis-python/tests/conjecture/common.py, hypothesis-python/tests/conjecture/test_ir.py
Closes https://github.com/HypothesisWorks/hypothesis/issues/4140.
I forgot to update `compute_max_children` for the weights change. In particular, this block was at fault:
```python
for weight, n in zip(weights, range(min_value, max_value + 1)):
if weight == 0:
continue
yield n
```
where the zip truncates when `weights` is smaller than the range (I am eagerly awaiting `strict=True` in 3.10).
This wasn't caught in testing because all of the `weights` examples in `integer_kwargs` got filtered out due to an incorrect computation of the target sum, which unconditionally failed an `assume`. I should have checked this more carefully, especially when it touches `st.integers`, which is empirically the most used strategy in all of hypothesis (and it's not even close).
=> Fix `compute_max_children` for integer weights

hypothesis-python/docs/details.rst
In rare cases, the pytest plugin’s side effects become annoying. For an example, see https://stackoverflow.com/a/71452757/680382
=> Document how to disable pytest plugin

.github/workflows/main.yml
As per discussion here: https://github.com/HypothesisWorks/hypothesis/pull/4142#issuecomment-2422581361
=> Disable py314 builds until 3.14 is a bit more reliable

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/vendor/pretty.py, hypothesis-python/tests/cover/test_pretty.py
Someone pointed out to me that the changes from #4133 now meant some nested types they had were no longer pretty printing with their namespace (despite this being in their repr). This PR fixes that. I also noticed that we had the same problem with enum types declared nested, so I fixed that too.
=> Include namespace classes in pretty printing

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/vendor/pretty.py, hypothesis-python/tests/cover/test_pretty.py
Continuing my small tweaks to pretty printing logic...
This changes the priority order for our pretty printing logic to always prefer a user provided `_repr_pretty_` to any of our more general heuristics, on the grounds that if the user provided one they probably meant it to be used.
This is particularly relevant in scenarios where the `_repr_pretty_` is inherited from some base class defining it. I ran into this in a scenario where we had a base type that wanted to define a universal pretty printing method, but because its subtypes were dataclasses they weren't inheriting the defined method. This seems obviously wrong.
The priority order is now:
1. Singleton printers.
2. Any defined pretty printing method.
3. Everything else.
=> Always use a repr_pretty if provided

tooling/src/hypothesistooling/projects/hypothesispython.py
This pull fixes timeouts on our [`deploy`](https://github.com/HypothesisWorks/hypothesis/blob/21502bafae188563133a7fd4cbc0e512e53810a2/.github/workflows/main.yml#L273) CI job, on as seen as far back as dec 2023 ([CI job](https://github.com/HypothesisWorks/hypothesis/actions/runs/7333908116/job/19970286343)) - or [more recently, with logs](https://github.com/HypothesisWorks/hypothesis/actions/runs/11374162227/job/31643181680#step:5:667). I tracked this down to a hang on building `.. jsonschema::` in `observability.rst`, only when using text mode (as our deploy script does). We don't need to build the whole docs there, so I didn't dig further and sidestepped the issue by only building the necessary changes.
In passing, I've also removed `--keep-going`, which seems redundant as of sphinx 8.1 …
=> Fix deploy docs

hypothesis-python/RELEASE.rst, hypothesis-python/docs/settings.rst, hypothesis-python/src/hypothesis/_settings.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/tests/common/setup.py, hypothesis-python/tests/cover/test_settings.py, hypothesis-python/tests/pytest/test_capture.py, hypothesis-python/tests/pytest/test_seeding.py
After one too many complaints about Hypothesis being unsuitable for CI usage, I finally got around to making it so that the trivial configuration for making it deterministic on CI happens out of the box for you. Now if you set the `CI` environment variable it will run deterministically (as long as your test code is deterministic).
=> Default to CI-appropriate settings when running on CI

hypothesis-python/tests/common/costbounds.py, hypothesis-python/tests/conftest.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_junkdrawer.py, hypothesis-python/tests/conjecture/test_lstar.py, hypothesis-python/tests/conjecture/test_shrinker.py, hypothesis-python/tests/cover/test_cache_implementation.py, hypothesis-python/tests/cover/test_core.py, hypothesis-python/tests/cover/test_deadline.py, hypothesis-python/tests/cover/test_flakiness.py, hypothesis-python/tests/cover/test_functions.py, hypothesis-python/tests/cover/test_random_module.py, hypothesis-python/tests/cover/test_reproduce_failure.py, hypothesis-python/tests/cover/test_slippage.py, hypothesis-python/tests/cover/test_stateful.py, hypothesis-python/tests/cover/test_statistical_events.py, hypothesis-python/tests/cover/test_testdecorators.py, hypothesis-python/tests/nocover/test_baseexception.py, hypothesis-python/tests/nocover/test_cacheable.py, hypothesis-python/tests/nocover/test_conjecture_engine.py, hypothesis-python/tests/nocover/test_deferred_errors.py, hypothesis-python/tests/nocover/test_limits.py, hypothesis-python/tests/nocover/test_targeting.py, hypothesis-python/tests/nocover/test_threading.py
- use `nonlocal` rather than updating list elements, a much-delayed cleanup from the Python 2 days
- add `: ConjectureData` to get better editor support in some common cases
=> Small test cleanups

hypothesis-python/RELEASE.rst, hypothesis-python/docs/settings.rst, hypothesis-python/src/hypothesis/_settings.py, hypothesis-python/tests/cover/test_settings.py
This is me following up on my [note for later](https://github.com/HypothesisWorks/hypothesis/pull/4152#issuecomment-2450522626).
Previously if you reregistered a profile you'd need to then load it again before it came into use. This changes the logic so that's not the case.
The main motivation for this is is that if a user registers a CI profile this now ensure it will automatically be used on CI.
=> Automatically reload settings profile if it's redefined

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/control.py, hypothesis-python/src/hypothesis/database.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/conjecture/test_data_tree.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_inquisitor.py, hypothesis-python/tests/conjecture/test_ir.py, hypothesis-python/tests/conjecture/test_junkdrawer.py, hypothesis-python/tests/cover/test_database_backend.py
Closes #3864. Depends on #4159.
=> Migrate `explain` phase to the typed choice sequence

.github/workflows/main.yml, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/scrutineer.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/tests/cover/test_example.py, hypothesis-python/tests/cover/test_flakiness.py, hypothesis-python/tox.ini, tooling/src/hypothesistooling/__main__.py
- refactoring the tracer, *ala* #4164, since that doesn't really have a downside
- avoiding pprint logic to support `@example(...).xfail()` when there are no xfail examples, closing #4139 by expanding on #4063
- some Django-update logic which closes #4031 - it's not fully automated but we won't miss an update
- one more use of `nonlocal`, following #4156
=> Various small fixes

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/cover/test_debug_information.py, hypothesis-python/tests/cover/test_flakiness.py, hypothesis-python/tests/cover/test_replay_logic.py, hypothesis-python/tests/cover/test_statistical_events.py
This adds a fast path so that when you rerun a test that has previously been fully shrunk it does not attempt to shrink it again.
The logic is a bit fussy to avoid a couple of failure modes. In particular:
* We need to make sure that when we replay multiple failures we do see all of these failures
* If the test changes in a way that means that we should shrink after all, we try to do so. This impossible to detect in general without actually running the shrinker and seeing, but we can detect major test changes.
I've added corresponding tests for a bunch of the fussy different interactions this can have.
This did cause me to find a bug in the fuzzing support where it was putting the data in the primary key (which is for already shrunk examples) rather than the secondary key (which is for …
=> Add fast path for replaying already shrunk test cases

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/conjecture/test_data_tree.py, hypothesis-python/tests/conjecture/test_ir.py
The motivation for this is that we sometimes want to access the ir nodes of a `ConjectureData` that hasn't been frozen/concluded yet, similar to how we sometimes do for the buffer.
=> Move `ir_nodes` from `Examples` to `ConjectureResult`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/control.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/tests/conjecture/common.py, hypothesis-python/tests/conjecture/test_ir.py, pyproject.toml, whole_repo_tests/test_mypy.py
Split from #4172. Recommend reviewing by commit.
=> Implement `NodeTemplate` + small fixes

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/common/debug.py, hypothesis-python/tests/conjecture/common.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_float_encoding.py, hypothesis-python/tests/conjecture/test_shrinker.py, hypothesis-python/tests/cover/test_filtered_strategy.py, hypothesis-python/tests/nocover/test_conjecture_engine.py, hypothesis-python/tests/quality/test_zig_zagging.py
This will probably be one of a few pulls in this vein, to keep the migration reasonable piecewise.
The new code piece here is `data.choices`. I'm quite happy to report that in working on the full typed choice sequence migration there seems to be a decent separation between when you need just `list[IRType]` (when constructing a ConjectureData) and when you need the full nodes (after running a ConjectureData; the shrinker, and the database because of `sort_key`). Therefore an attribute for accessing the former is convenient.
To preempt a review comment: "why have some buffers changed from (0, n) to (n)?" because the first 0 represents the bounded integer weighted endpoint choice for the buffer. Only occurs for bounded integers above `2**8 - 1`.
=> Migrate some tests to the typed choice sequence

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/observability.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/cover/test_observability.py
This regressed at some point, probably when we were moving things around for alternative backends.
=> Report all generated arguments in observability

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
Ran into this in the wild myself and decided to do something about it 😄. See also https://github.com/HypothesisWorks/hypothesis/issues/3790#issuecomment-1811657344. I think the downsides to a lower batch size are small; people really shouldn't be using `.example` for large n, and even if they do the overhead of smaller batches is pretty small.
=> Reduce example generation batch size

hypothesis-python/RELEASE.rst, hypothesis-python/docs/database.rst, hypothesis-python/docs/details.rst, hypothesis-python/src/hypothesis/database.py, hypothesis-python/tests/cover/test_database_backend.py, hypothesis-python/tests/cover/test_stateful.py, hypothesis-python/tests/nocover/test_database_agreement.py
See https://github.com/Zac-HD/hypofuzz/pull/41#discussion_r1844925846; was something like this what you were thinking of? 
(I expect coverage to fail here; explicit covering test pending)
=> Add `BackgroundWriteDatabase`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/tests/cover/test_stateful.py
After reviewing, closes #4181, I realize there isn't a really "hypothesis-like" way to differentiate between the `Bundle` calls from the internal `run_state_machine` and those from other strategies, so the best way to solve this seems to be to revert most of it (there's two areas about printing but it didn't seem to affect the tests, so leaving that in). Hopefully it wasn't too much trouble for the users! At the very least there's some improvement in the testbase.
I'll also have to do a bit of refactor #4084 but I think that'll be fine.
Original PR: #4124
=> Revert Refactor of `BundleReferenceStrategy` into `Bundle`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/tests/conjecture/test_alt_backend.py
cc @pschanely 
- following #4165, the Tracer no longer branches (in a way visible to Crosshair) on whether sys.settrace() is active
- `span_start()` and `span_end()` methods to make recognising recursive strategies easier.
- not yet tested, but that's why the PR is marked experimental.
- experimental engine change which I think should let us raise `Unsatisfiable` after an alternative backend gives up.
- I'm not sure of this though, and would appreciate a pointer to the affected tests so that we can get this behavior deliberately checked by our test suite.
=> Experimental changes for Crosshair support

hypothesis-python/docs/data.rst, hypothesis-python/docs/database.rst, hypothesis-python/docs/development.rst, hypothesis-python/docs/django.rst, hypothesis-python/docs/examples.rst, hypothesis-python/docs/ghostwriter.rst, hypothesis-python/docs/index.rst, hypothesis-python/docs/numpy.rst, hypothesis-python/docs/quickstart.rst, hypothesis-python/docs/usage.rst
I've found the documentation sidebar quite confusing to navigate at times. Mostly that the titles are verbose or do not lean on hypothesis-specific terms (`strategies`), and that there is no clear delineation between the reference and the community pages. This is my subjective first pass at putting things in a more readable state 🙂 (with a lot of work on individual pages still remaining!)
| master | this pull | 
| --- | --- |
| <img width="296" alt="image" src="https://github.com/user-attachments/assets/b472d26d-45bb-4449-8b95-191ce8bc9cfe"> | <img width="279" alt="image" src="https://github.com/user-attachments/assets/d8bf68be-4686-424c-ba2a-4395638ae508"> |
=> Reorder docs pages

hypothesis-python/tests/ghostwriter/test_expected_output.py
Shaves about a second off `pytest --collect-only`.
=> Defer ghostwriter test collection

hypothesis-python/RELEASE.rst, hypothesis-python/docs/_ext/hypothesis_linkcheck.py, hypothesis-python/docs/changes.rst, hypothesis-python/docs/conf.py, hypothesis-python/docs/endorsements.rst, hypothesis-python/docs/ghostwriter.rst, hypothesis-python/docs/numpy.rst, hypothesis-python/docs/strategies.rst, hypothesis-python/docs/supported.rst, hypothesis-python/docs/usage.rst, hypothesis-python/setup.py, hypothesis-python/src/hypothesis/_settings.py, hypothesis-python/src/hypothesis/database.py, hypothesis-python/src/hypothesis/extra/ghostwriter.py, hypothesis-python/src/hypothesis/extra/lark.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py
As I was looking at adding an automated check for outdated links, I found some broken links in our documentation. This pull fixes those, and updates most 301 permanent redirects, and some 302 Found redirects.
To run locally:
```
sphinx-build --builder linkcheck hypothesis-python/docs linkcheck
```
I've also written a sphinx extension that modifies the linkcheck builder to ignore intersphinx links. I think we can rely on those being accurate.
I was thinking we could run linkcheck on each pull in the future? `linkcheck` still picks up on a few false positive request timeouts or missing section headers though, so we'll need a way to manually whitelist false positives before turning such a job on.
=> Update documentation links

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/cover/test_given_error_conditions.py, hypothesis-python/tests/cover/test_testdecorators.py, hypothesis-python/tests/cover/test_validation.py
Addresses https://github.com/HypothesisWorks/hypothesis/issues/4197, plus one which I ran into while reproducing, plus one which I've had on the back of my mind for a long time (`st.text("ascii")` has bitten me before.)
Tests for #4197 coming at a later date; I sleep now 🙂
=> Error message and warning improvements

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/provisional.py
Closes #4201. My benchmark results:
```
Field     Time:    Compared to: Time difference:
Baseline  0.000182 N/A
Text      0.353401 baseline     0.353219
Domains   3.109082 baseline     3.108901
URLs      3.952818 domains      0.843736
Emails    3.208230 domains      0.099147
Fake      0.065587 domains      -3.043495
```
```
Field     Time:    Compared to: Time difference:
Baseline  0.000170 N/A
Text      0.363252 baseline     0.363082
Domains   1.905849 baseline     1.905679
URLs      2.744583 domains      0.838734
Emails    2.032297 domains      0.126449
Fake      0.067094 domains      -1.838755
```
=> Improve performance of `st.domains()`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/nocover/test_precise_shrinking.py
For a little dose of nostalgia, this is a "@DRMacIver makes weird changes to the shrinker" pull request.
*Mostly* the actual changes are quite small, and it's just the return of an old shrink pass that I removed as seemingly unnecessary. The really important change here is the introduction of a bunch of tests that constrain the shrinker behaviour a bit more carefully that I added in the course of trying to track down the problem I was seeing. The problem turned out to be much more bounded than I thought, but the tests are I think broadly useful.
=> Add zero_examples shrink pass for better precise shrinking

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/floats.py, hypothesis-python/tests/conjecture/common.py, hypothesis-python/tests/cover/test_float_utils.py, pyproject.toml
This pull changes the float clamper to directly incorporate float kwargs. While I think this approach is cleaner, I'm really doing it because it is easier to reuse the single clamper for future typed choice sequence work I have lined up.
Also removes a rule removed in new ruff versions to silence a warning, but we'll see if CI likes that 😄
=> Use a single clamper for floats

hypothesis-python/tests/conjecture/common.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_ir.py, hypothesis-python/tests/conjecture/test_optimiser.py, hypothesis-python/tests/cover/test_float_utils.py
I love seeing -500 diffs 🙂 
Follow up to https://github.com/HypothesisWorks/hypothesis/pull/4207#discussion_r1894534362. I dropped the `make_` suffix; I originally had this to avoid confusion with the `{float, ...}_kwargs` strategies, but I think the 5 char saving is worth the minimal confusion increase, since `_kw` is singular and `_kwargs` is plural, following non-strategy and strategy conventions respectively. Let's just pretend that kw isn't short for kwargs...
=> Use convenience functions for choice sequence kwargs

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/tests/cover/test_lookup.py
Which allows the answer to [this StackOverflow question](https://stackoverflow.com/questions/79199376/hypothesis-cannot-build-from-type-when-type-is-int-subclass) to be "subclasses of `int` must have pos-only args, fix that and it'll work".
=> Teach from_type to build with posonly args

hypothesis-python/tests/conftest.py, hypothesis-python/tests/cover/test_random_module.py
I found this was adding ~50ms of overhead to every test. When multiplied by our 6500 tests, that's...a lot. Since [the commit which added this](https://github.com/HypothesisWorks/hypothesis/commit/cc8c93f21b9a46592f8d9dc943b0fc98c7ab6c9a) is 9 years old and pypy-specific, I'm hoping we can drop it without issues? @DRMacIver do you happen to remember the motivation for this change or any idea if it is still necessary?
To test, you can add the following to any test file
```python
@pytest.mark.parametrize("v", range(100))
def test_123456789(v):
print("call", v)
```
and observe that `pytest -n 1 -k test_123456789 -s` takes ~7 seconds on master but 1.5 seconds on this branch (not zero due to test collection overhead).
=> Remove `gc.collect()` before each test

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/pareto.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/cover/test_deadline.py, hypothesis-python/tests/nocover/test_duplication.py, hypothesis-python/tests/quality/test_float_shrinking.py
This uses `sort_key_ir` in place of `sort_key` for most things. We can't get rid of `sort_key` quite yet, but we're getting there.
This is a slight improvement in shrinking, probably because we've dropped the +1 shrink call per test to forced to the smallest buffer for compatibility with the buffer ordering. I think the stronger signal here is that nothing has gotten *worse*. ![shrinking](https://github.com/user-attachments/assets/9f5e1de3-5c37-464d-88ba-f7a3b06c45e9)
=> Implement and use `sort_key_ir`

CODEOWNERS
I was going to review https://github.com/HypothesisWorks/hypothesis/pull/4217 and realised I couldn't actually approve it as I'm not listed as a code owner for conjecture. Seemed appropriate to fix this given that I'm getting more involved in Hypothesis again.
=> Add DRMacIver as code owner

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_shrinker.py, hypothesis-python/tests/nocover/test_precise_shrinking.py
This adds an initial phase to shrinking that is allowed to make changes that would be bad to make as part of the main shrink pass, with the main goal of producing better results for ``one_of``.
This isn't as good a pass for this as I wanted to add. In particular it results in *no* new guarantees about shrinking, because we can't iterate this pass to a fixed point along with the others, but it should start the shrinking off from something that is much more likely to already be the minimal usable branch for this strategy.
When trying to add a more reliable pass I kept running into issues that I think will be easier to solve after we've made some of the discussed changes and generally fully moved over to the new IR.
=> Add initial coarse reduction pass for reducing alternatives

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/choice.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinking/collection.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinking/common.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_minimizer.py, hypothesis-python/tests/conjecture/test_shrinker.py
Significantly speeds up `test_draw_to_overrun`, and seems generally appropriate.
Benchmark (no change):
=> Add short-circuit for trivial collections

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/datatree.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinking/collection.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinking/common.py, hypothesis-python/tests/conjecture/test_data_tree.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_float_encoding.py, hypothesis-python/tests/conjecture/test_ir.py, hypothesis-python/tests/conjecture/test_shrinker.py, hypothesis-python/tests/cover/test_filtered_strategy.py, hypothesis-python/tests/nocover/test_conjecture_engine.py, hypothesis-python/tests/numpy/test_gen_data.py
Depends on #4217 (so `test_draw_to_overrun` finishes in a sane amount of time).
Here are three proposals for a replacement for `ConjectureData.for_buffer` on the typed choice sequence:
(1) pass the value of each choice:
```python
@classmethod
def for_choices(
cls,
choices: Sequence[NodeTemplate | IRType],
...
):
...
```
(2) pass the value of each choice and its complexity index:
```python
@classmethod
def for_choices(
cls,
choices: Sequence[NodeTemplate | tuple[IRType, int]],
...
):
...
```
(3) pass the value of each choice and its kwargs, noting that the complexity of a choice can be derived from its value + kwargs:
```python
@classmethod
def for_nodes(
cls,
nodes: Sequence[NodeTemplate | IRNode],
...
):
...
```
I am proposing we use (1) in this pull. The benefits of this is mainly a …
=> Use `ConjectureData.for_choices`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/tests/cover/test_reproduce_failure.py, hypothesis-python/tests/cover/test_stateful.py
Depends on #4219 for `ConjectureData.for_choices`. 2e01109a3c1d136e778af2faf442237ad4f05dc6 is the additional commit in this pull.
=> Use the typed choice sequence for `@reproduce_failure`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/database.py, hypothesis-python/src/hypothesis/internal/conjecture/choice.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/datatree.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py, hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py, hypothesis-python/src/hypothesis/internal/conjecture/pareto.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/tests/conjecture/common.py, hypothesis-python/tests/conjecture/test_data_tree.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_ir.py, hypothesis-python/tests/conjecture/test_pareto.py, hypothesis-python/tests/conjecture/test_shrinker.py, hypothesis-python/tests/conjecture/test_test_data.py, hypothesis-python/tests/nocover/test_explore_arbitrary_languages.py
* `IRType` -> `ChoiceT` (and move to choice.py)
* `IRKwargsType` -> `ChoiceKwargsT` (and move to choice.py)
* `ir_value_permitted` -> `choice_permitted` (and move to choice.py)
* use actual `InterestingOrigin` instances in tests
* work some more on type hints
On the topic of type hints, I've been playing around with mypyc recently, and may work towards a serious push towards it in the near future, a la https://github.com/HypothesisWorks/hypothesis/issues/3074. I think most of the remaining work there is actually in conforming to a mypyc-approved subset (no nested classes, meaning `Examples` will need to be refactored!) rather than adding more type hints. Though there will certainly be some of the latter 😄
=> More type hinting, move some things to `choice.py`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinking/floats.py, hypothesis-python/src/hypothesis/internal/floats.py, hypothesis-python/tests/conjecture/common.py, hypothesis-python/tests/conjecture/test_data_tree.py, hypothesis-python/tests/conjecture/test_shrinker.py, hypothesis-python/tests/quality/test_shrink_quality.py
also addresses a TODO in `minimize_duplicated_nodes`.
=> Extend `redistribute_integer_pairs` to floats

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/engine.py
root cause of exceptions in https://github.com/HypothesisWorks/hypothesis/pull/4034. No test because it requires taking the zero_data code path, and any test may well be obviated by imminent typed choice sequence work.
=> Freeze in `BackendCannotProceed`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/database.py
Discovered while investigating test failures in https://github.com/Zac-HD/hypofuzz/pull/47.
=> Write atomically in `DirectoryBasedExampleDatabase`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/conjecture/test_shrinker.py
Root cause of https://github.com/HypothesisWorks/hypothesis/pull/4239#issuecomment-2585843038 (shrinker was exiting with max_shrinks inside the test case, though I didn't look into why that didn't set the `stopped-because` key).
=> Early-abort `redistribute_numeric_pairs` if we become imprecise

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/tests/cover/test_flakiness.py
Closes #4183 
Closes #4228 
Two corner cases in reporting of flaky errors.
One of them is a straightforward missing handling of flakiness at `mark_interesting` time.
The other deals with a surprising aspect of how a naked exception is wrapped in an `ExceptionGroup` when caught and reraised by `except*` — the group's traceback points not to where the naked exception is raised, nor to the location of the `except*` block, but instead to the _caller_ one frame above the `except*`:
```
def wrapped():
try:
raise Exception  # innermost frame of EceptionGroup.exceptions[0]
except* Exception:
raise
def naked():
raise Exception  # innermost frame of Exception
if __name__ == "__main__":
import traceback
try:
naked()
except Exception as e:
print("naked:", traceback.format_tb(e.__traceback__)[-1]) …
```
=> Fix some flaky reporting corner cases

.readthedocs.yml, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/database.py, hypothesis-python/src/hypothesis/internal/conjecture/choice.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_forced.py, hypothesis-python/tests/conjecture/test_ir.py, hypothesis-python/tests/conjecture/test_pareto.py, hypothesis-python/tests/cover/test_database_backend.py, hypothesis-python/tests/cover/test_float_utils.py, hypothesis-python/tests/cover/test_reproduce_failure.py, hypothesis-python/tests/nocover/test_conjecture_engine.py
The database now stores entries as `(sort_key_ir(data.ir_nodes), data.choices)`, letting us sort entries by shrink ordering. If `ir_from_bytes` deserialization fails, return None. Caller is responsible for handling this case (usually by clearing the bad entry from the db). 
I think it's worth storing the choice complexity in the db, for better sorting. The case of interest is when serialization is large but the complexity is low. This happens mainly via `min_size=` or `shrink_towards`. I'm not certain how big of a problem this is - probably most issues require storing some (small + high complexity) or (large + low complexity) value, then changing the test case to add or remove a min_size, changing the relative complexity baseline. I think the worst this would manifest as is us repeatedly …
=> Use typed choice sequence in database

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/providers.py, hypothesis-python/tests/conjecture/test_alt_backend.py, hypothesis-python/tests/conjecture/test_provider_contract.py, hypothesis-python/tests/cover/test_fuzz_one_input.py
This provider is "the simplest thing that works". There is no upweighting for ascii characters or small integers. Step one is getting `fuzz_one_input` off the buffer (this pull), and so I'm not yet putting any effort into optimizing the provider for fuzzing. In fact, arguably the simplest thing will end up performing better than most more intelligent things, as fuzzers tend to do well at discovering behavior iff choice size remains constant.
=> Add and use `BytestringProvider` in `fuzz_one_input`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/pareto.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/cover/test_fuzz_one_input.py
Also moves a few more usages off the buffer.
This causes crosshair test failures, where crosshair cannot find a `!= 123456` failure. Crosshair appears to be claiming the test case is verified, due to this line:
```
zero_data = self.cached_test_function_ir(
(NodeTemplate("simplest", size=BUFFER_SIZE),)
)
```
because the `NodeTemplate` forcefully inserts a simplest-valued choice, bypassing the usual `draw_*` request logic. I believe Crosshair therefore thinks the test case requests zero choices and has an empty decision tree, which is trivially verified.
* We could add a `draw_node_template` hook or similar which backends can override, but I'm a bit nervous about committing this implementation detail to the interface when I'm not confident `NodeTemplate` will stick around in its current …
=> Fully move to the typed choice sequence cache

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/tests/conjecture/test_data_tree.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_ir.py, hypothesis-python/tests/conjecture/test_test_data.py, hypothesis-python/tests/cover/test_deadline.py, hypothesis-python/tests/cover/test_observability.py, hypothesis-python/tests/cover/test_reproduce_failure.py, hypothesis-python/tests/cover/test_stateful.py, hypothesis-python/tests/crosshair/test_crosshair.py, hypothesis-python/tests/nocover/test_conjecture_engine.py, hypothesis-python/tests/nocover/test_targeting.py
This is a bit of an RFC; I'm not sure this is the correct semantics. The argument is that the number of nodes is more often the most relevant piece of information (as e.g. the primary ordering for `sort_key`), and not the choice size, so our internal api should reflect this. In this pull, there are two ways for a `ConjectureData` to overrun: by overrunning `BUFFER_SIZE` via `ir_size` as normal, or by drawing more than `max_length` choices. If `max_length` is not passed, then the former is the only way to overrun. There is currently no way to decrease the maximum `buffer_size` for a particular data, though in principle we could add this interaction.
A secondary argument is this lets us get rid of lots of `ir_size` calls, which makes it easier (or possible at all, really) to require that …
=> Define `extend: int = 0` and `NodeTemplate` in terms of choice count

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/database.py, hypothesis-python/src/hypothesis/internal/conjecture/choice.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py, hypothesis-python/src/hypothesis/internal/conjecture/providers.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/src/hypothesis/internal/conjecture/utils.py, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/tests/array_api/test_from_dtype.py, hypothesis-python/tests/conjecture/common.py, hypothesis-python/tests/conjecture/test_alt_backend.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_ir.py, hypothesis-python/tests/conjecture/test_provider_contract.py, hypothesis-python/tests/conjecture/test_test_data.py, hypothesis-python/tests/conjecture/test_utils.py, hypothesis-python/tests/cover/test_database_backend.py, hypothesis-python/tests/nocover/test_health_checks.py, hypothesis-python/tests/nocover/test_precise_shrinking.py
It makes me very happy to be opening this pull. This is likely the zenith of the typed choice sequence migration! It's all cleanup from here.
- `ConjectureData.buffer` is no more
- `choice_permitted` can now be what it always wanted to be...that is, not limited by arbitrary internal restrictions.
-  Every `draw_*` function now uses pure `random` functions instead of `draw_bits`. I am nervous that I may have subtly (or not subtly!) changed the distribution of generated values here, as our testing in this area is rather weak. Careful reading of these changes for equivalence with the previous logic would be appreciated.
- We no longer need the `forced` and `fake_forced` parameters of the `PrimitiveProvider` interface! This is a backwards-compatible change.
- I guess it's conceivable a …
=> Remove `ConjectureData.buffer`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/stateful.py
For https://github.com/Zac-HD/hypofuzz/pull/51.
Continuing discussion from there:
> Rather than attaching a magic attribute - which could be confused by mocks or whatever - let's define a subclass of TestCase in hypothesis.stateful and then [inherit from it here](https://github.com/HypothesisWorks/hypothesis/blob/eaa0852472ff4830782bfabb9043b914ef989332/hypothesis-python/src/hypothesis/stateful.py#L428-L443), so we have a principled way to identify it on the Hypofuzz side.
I like this in principle, but hypofuzz still needs a way to access the actual defining `RuleBasedStateMachine` class, not just recognizing if it is a stateful test or not. Do you think we should *also* add the custom `TestCase` subclass, in addition to the magic attribute? And use the former for checking stateful test …
=> Refactor some stateful internals

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/_settings.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/database.py, hypothesis-python/src/hypothesis/internal/conjecture/choice.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py, hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py, hypothesis-python/src/hypothesis/internal/conjecture/providers.py, hypothesis-python/src/hypothesis/strategies/_internal/strings.py, hypothesis-python/tests/common/setup.py, hypothesis-python/tests/conjecture/common.py, hypothesis-python/tests/conjecture/test_alt_backend.py, hypothesis-python/tests/conjecture/test_data_tree.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_ir.py, hypothesis-python/tests/conjecture/test_pareto.py, hypothesis-python/tests/cover/test_database_backend.py, hypothesis-python/tests/cover/test_filter_rewriting.py, hypothesis-python/tests/cover/test_reproduce_failure.py, hypothesis-python/tests/nocover/test_conjecture_engine.py
* Move providers to `providers.py`, including `HypothesisProvider` and `PrimitiveProvider`. I'm trying to structure things better than sticking everything into `data.py`, which has become massive (2k lines)
* `AVAILABLE_PROVIDERS` has moved from `data.py` to `providers.py`, so (@pschanely) crosshair should update its registration code - or we could leave a compatibility alias in `data.py`?
* `NodeTemplate` -> `ChoiceTemplate`
* ...a few other obviously-correct renamings
* no actual behavioral changes
=> Reorganize code for the typed choice sequence

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/array_api.py
This is a bit pre-emptive: 2024.12 Array API spec is not released yet :-).
However, the story goes like this:
The 2024.12 release is in the works and is expected "soon" (tm);
We would like to release array-api-compat and array-api-strict with 2024.12 support quickly once the spec itself is finalized;
Testing of array-api-compat across Array API provider libraries (numpy, pytorch, jax.numpy, dask) relies on array-api-tests;
array-api-tests relies on hypothesis.extra.array_api module;
if hypothesis.extra.array_api does not recognize 2024.12 as an allowed version, we cannot even start testing anything against the new spec version.
<s>So I'm wondering what would you think about merging this one-line change and cutting a new hypothesis release? I fully realize it might sound a bit preposterous …
=> Add 2024.12 to allowed array API versions

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py, hypothesis-python/src/hypothesis/internal/conjecture/utils.py, hypothesis-python/src/hypothesis/internal/escalation.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/tests/conjecture/test_junkdrawer.py, hypothesis-python/tests/nocover/test_conjecture_int_list.py
I was surprised at how impactful `isinstance` is in hot loops like `__getitem__`. That hit will go away on mypyc...but we may as well make interpreted code fast too, since we'll always have that as a fallback.
Includes a few type hints to make https://github.com/Zac-HD/hypofuzz/pull/53 easier.
=> Optimizations

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/choice.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/datatree.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/src/hypothesis/internal/escalation.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/tests/conjecture/common.py, hypothesis-python/tests/conjecture/test_alt_backend.py, hypothesis-python/tests/conjecture/test_data_tree.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_forced.py, hypothesis-python/tests/conjecture/test_ir.py, hypothesis-python/tests/conjecture/test_optimiser.py, hypothesis-python/tests/conjecture/test_provider_contract.py, hypothesis-python/tests/conjecture/test_shrinker.py, hypothesis-python/tests/quality/test_poisoned_trees.py
Also renames all (?) remaining references to `ir_`. `ChoiceNode(type="integer")` is maybe a bit weird but `ChoiceNode(choice_type="integer")` felt too verbose. I think of `choice` as "a single typed value" and `ChoiceNode` as "a value plus the context in which it was drawn (kwargs/etc)".
Things were looking pretty hairy for a while when we were in the thick of the migration, api-design and naming-wise 😅 I'm pretty happy with where we've ended up in `choice.py` now though.
=> Share `belongs_to` cache

hypothesis-python/RELEASE.rst, hypothesis-python/setup.py, hypothesis-python/src/hypothesis/database.py, hypothesis-python/src/hypothesis/extra/redis.py, hypothesis-python/src/hypothesis/internal/scrutineer.py, hypothesis-python/tests/cover/test_database_backend.py, hypothesis-python/tests/redis/test_redis_exampledatabase.py, hypothesis-python/tests/watchdog/__init__.py, hypothesis-python/tests/watchdog/test_database.py, hypothesis-python/tox.ini, requirements/coverage.in, requirements/coverage.txt, requirements/tools.in, requirements/tools.txt
TODO: write real docs for this? and figure out whether to put `watchdog` in `test.in` or `tools.in`?
=> Add a pubsub database implementation

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/conftest.py, hypothesis-python/tests/cover/test_typealias_py312.py
Closes https://github.com/HypothesisWorks/hypothesis/issues/4242.
=> Add support for `TypeAliasType` to `from_type` and `register_type_strategy`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/tests/nocover/test_stateful.py
`singleton_printers` does unconditional id-based replacement, which is not always correct (see tests). `test_unrelated_rule_does_not_use_var_reference_repr` fails on master with:
```python
state = UnrelatedCall()
a_0 = state.add_a(a=0)
state.unrelated(value=a_0) # should be value=0
```
I think the main use case for the singleton printers is addressed with `VarReference`, and any remaining effects are imo net-negative, though they can sometimes be more readable even if not strictly correct.
=> Improve pprinting of stateful examples

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/database.py, hypothesis-python/tests/watchdog/test_database.py
I can't believe I left CI debugging prints in :(. Totally my fault. At least it didn't affect anyone. Unless there's a mysterious day one adopter out there - in which case I'd love to hear what you're using this for!
Also closes https://github.com/HypothesisWorks/hypothesis/issues/4274.
=> Adjust db pubsub type hints and remove print

hypothesis-python/docs/changes.rst, tooling/src/hypothesistooling/releasemanagement.py, whole_repo_tests/test_rst_is_valid.py
`.. code-block: python` is a comment; `.. code-block:: python` is a code block 😅. Affects some old changelogs as well.
=> Fix code blocks in changelog

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/choice.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinking/common.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinking/floats.py, hypothesis-python/tests/conjecture/test_float_encoding.py, hypothesis-python/tests/cover/test_shrink_budgeting.py, hypothesis-python/tests/quality/test_float_shrinking.py
Closes #4277.
The first issue (`-nan`) is a one-liner, switching from `sign_aware_lte` to `math.copysign` to detect the sign of a choice.
Second issue (`struct.unpack('d', struct.pack('Q', 0xfff8000000000001))[0]`) requires distinguishing NaNs in float shrinking, so that code is reshuffled a bit to separate out the "immutable" value for the shrinker from the "hashable" value for tracking of seen values.
=> Shrink NaN to canonical form

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/cover/test_lookup.py
Closes #4194. 
Continuing from there - we actually do support drawing from non-runtime-checkable protocols, *iff* they have a corresponding registered strategy.`IsDataclass` did have such a strategy in this case, so erroring here is a bug. 
The bug in this case was running logic involving `issubclass` on a thing which cannot be subclass-checked - but we only checked this sometimes, due to short circuiting. This explains the `int` heisenbug.
=> Fix `from_type` error on certain protocols

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
In the pareto optimiser, left dominates right if it is better in every way, including sort_key and all target scores. The optimiser shrinks by allowing transitions where left dominates right, which means it will never allow transitions where the attempt is larger than the current data in terms of sort_key. Because of this, I think allowing the target phase to extend is actually not beneficial, because ParetoOptimiser will reject these anyway. 
@Zac-HD would appreciate a sanity check if I'm correct here. We changed this in https://github.com/HypothesisWorks/hypothesis/pull/3862 (and at the time I also thought this was a good change and agreed with the reasoning, but no longer believe that). 
To go back to the original issue #3827, this isn't going to make Tyche's life any easier, because …
=> Don't extend during the target phase

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, whole_repo_tests/revealed_types.py, whole_repo_tests/test_mypy.py, whole_repo_tests/test_pyright.py
Closes #4269.
Using `PredicateT` was not correctly capturing the `Ex` TypeVar in `def filter(self, condition: PredicateT)`. I've replaced all of the type alias usages with explicit ones, which resolves this issue and probably several others we hadn't found yet.
=> More correct type hints for filter and map

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinking/collection.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_shrinker.py, hypothesis-python/tests/cover/test_debug_information.py, hypothesis-python/tests/quality/test_shrink_quality.py
Closes https://github.com/HypothesisWorks/hypothesis/issues/4286. The changes to `collection.py` are what actually addresses that issue. `lower_duplicated_characters` is a bonus which I came across while investigating.
=> Improve shrinking for collections with duplicate elements, and duplicate characters across string choices

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/datatree.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/tests/conjecture/common.py, hypothesis-python/tests/conjecture/test_alt_backend.py, hypothesis-python/tests/conjecture/test_data_tree.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_float_encoding.py, hypothesis-python/tests/conjecture/test_optimiser.py, hypothesis-python/tests/conjecture/test_pareto.py, hypothesis-python/tests/conjecture/test_shrinker.py, hypothesis-python/tests/cover/test_one_of.py, hypothesis-python/tests/ghostwriter/test_ghostwriter.py, hypothesis-python/tests/nocover/test_conjecture_engine.py, hypothesis-python/tests/nocover/test_precise_shrinking.py, hypothesis-python/tests/quality/test_poisoned_trees.py, hypothesis-python/tests/quality/test_zig_zagging.py
Purely aesthetic change I noticed when printing one_of. I'm open to this being shut down as not worthwhile / having unintended effects elsewhere - but I can't think of any.
This matches `typing`, FWIW:
```python
>>> Union[int, Union[str, bool]]
typing.Union[int, str, bool]
```
=> Unwrap nested `one_of` strategies

hypothesis-python/tests/cover/test_database_backend.py, hypothesis-python/tests/watchdog/test_database.py
I only have moderate confidence that this is going to resolve all flakes for db listener tests. If it doesn't, I'm going to try to simplify the tests rather than make them more correct. I hadn't intended to test OS-level internals when writing them!
=> Try making db listener tests more reliable

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/providers.py, hypothesis-python/tests/quality/test_discovery_ability.py, hypothesis-python/tests/quality/test_shrink_quality.py
First part of https://github.com/HypothesisWorks/hypothesis/issues/3127. I'd still like to walk the ast to extract constant strings, but that's for a future pull 😄
I'm happy to make adjustments to what values we include here. I basically just scrolled through the three linked posts and added strings that I thought were relevant. I avoided including a bunch of sections of the big list of naughty strings in particular, because I don't think we want to be actively vulnerability hunting (xss, sql injection, etc). Most everything from the other two made it in.
I also intentionally left off the EICAR string. I haven't tried it, but I think odds are good that the Hypothesis library/source code itself would be detected as malware by some users, even if we made it past pypi. We could rot13 it, but …
=> Add possibility to generate nasty strings

guides/strategies-that-shrink.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/lark.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/datatree.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py, hypothesis-python/src/hypothesis/internal/conjecture/providers.py, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/src/hypothesis/internal/conjecture/utils.py, hypothesis-python/src/hypothesis/provisional.py, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/src/hypothesis/strategies/_internal/featureflags.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/tests/conjecture/test_data_tree.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_ir.py, hypothesis-python/tests/conjecture/test_optimiser.py, hypothesis-python/tests/conjecture/test_pareto.py, hypothesis-python/tests/conjecture/test_shrinker.py, hypothesis-python/tests/conjecture/test_test_data.py
Addresses part 1 of #4166. 
I was a bit concerned about having to leave a deprecated alias for `data.{start, stop}_example()`, but [grep.app doesn't know of any other consumers](https://grep.app/search?q=.start_example%28). Which doesn't mean there aren't any, of course 😅
=> Rename `Example` to `Span`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/utils.py, hypothesis-python/src/hypothesis/strategies/_internal/misc.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/tests/conjecture/test_mutations.py, hypothesis-python/tests/conjecture/test_utils.py, hypothesis-python/tests/nocover/test_sampled_from.py, hypothesis-python/tests/quality/test_poisoned_trees.py
Adds repeated subtree mutation, in the style of [nautilus](https://wcventure.github.io/FuzzingPaper/Paper/NDSS19_Nautilus.pdf). (I didn't take this mutation from them, it's just the obvious thing to do and I noticed afterwards that they were the same. Though who knows, maybe this was only in my brain after reading that paper).
This adds a bit of unwanted mutation to `st.sampled_from(Flag)`, because that uses a recursive `sampled_from` in its own implementation. `calc_label_from_name` doesn't use strategy kwargs to distinguish labels; maybe it should? It's just the class name right now, so every `sampled_from` has the same label. Adding kwargs would make labels useful as a true marker of recursive structure. I haven't checked whether doing this breaks anything. Requiring every strategy to …
=> Add subtree mutations

hypothesis-python/RELEASE.rst, hypothesis-python/docs/strategies.rst, hypothesis-python/src/hypothesis/internal/conjecture/providers.py, hypothesis-python/tests/common/arguments.py, hypothesis-python/tests/conjecture/test_alt_backend.py, hypothesis-python/tests/conjecture/test_provider_contract.py
[Antithesis](https://antithesis.com/) is a fuzzer which uses `/dev/urandom` as its source of randomness to mutate. This pull adds a `class URandomProvider(HypothesisProvider)` which backs its random draws using `/dev/urandom`, giving Antithesis control over choices made during Hypothesis tests.
(Zac and I are attending [Antithesis' BugBash](https://bugbash.antithesis.com/#about) in April—Zac as a speaker—and would love to be able to say that Hypothesis has great integration with Antithesis!)
=> Add a `URandomProvider` for use by Antithesis

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/conjecture/test_shrinker.py
`consider_new_nodes` checks `sort_key`, but `cached_test_function` doesn't, so the shrinker does unnecessary work sometimes. This moves those checks into `cached_test_function`.
Benchmark (10% improvement):
=> Use `shrink_key` to avoid shrinking work in more places

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/errors.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/tests/cover/test_database_backend.py, hypothesis-python/tests/crosshair/test_crosshair.py
Pulling out source-code changes from https://github.com/HypothesisWorks/hypothesis/pull/4034 into its own pull, since this is an immediate improvement for users, and also the cause of one of our xfailing tests.
=> Don't pin zero data if backend cannot proceed

hypothesis-python/RELEASE.rst, hypothesis-python/docs/redirect.html.template, hypothesis-python/docs/supported.rst, hypothesis-python/src/hypothesis/strategies/_internal/utils.py, hypothesis-python/tests/crosshair/test_crosshair.py
- Adds back a missing docs section https://github.com/HypothesisWorks/hypothesis/pull/4300#issuecomment-2749046732
- Adds a test that we don't add choices to symbolics from crosshair
- crosshair makes two choices for bools, but I'm assuming that's not on our side?
- everything else is 1 choice except floats, which I expected since crosshair mimics actual f64 semantics in z3
- Adds some manual redirects for the old `details.html` page. Ideally I'd build some way to specify hash redirects in the plugin, but hacking them into the redirect template was easier.
=> Add a crosshair realization test and improve docs

hypothesis-python/benchmark/README.md, hypothesis-python/benchmark/graph.py, hypothesis-python/tests/conftest.py
I tried getting xdist to serialize this information from worker -> controller in memory, but I'm not sure it's possible. (You can do controller -> worker, though). Ended up just writing to disk.
I expect I'm about the only person who cares about this benchmark, but 8x speedup will be really nice for me! And also enables increasing the trials-per-test from 5 in the future, for tighter confidence intervals.
=> Support xdist in shrinking benchmark (via the filesystem)

hypothesis-python/tests/cover/test_lookup.py, hypothesis-python/tests/cover/test_lookup_py38.py, hypothesis-python/tests/cover/test_provisional_strategies.py, hypothesis-python/tests/cover/test_randoms.py, hypothesis-python/tests/cover/test_regex.py, hypothesis-python/tests/cover/test_sampled_from.py, hypothesis-python/tests/cover/test_stateful.py, hypothesis-python/tests/nocover/test_characters.py, hypothesis-python/tests/nocover/test_emails.py, hypothesis-python/tests/nocover/test_flatmap.py, hypothesis-python/tests/nocover/test_from_type_recipe.py, hypothesis-python/tests/nocover/test_health_checks.py, hypothesis-python/tests/nocover/test_lstar.py, hypothesis-python/tests/nocover/test_sampled_from.py, hypothesis-python/tests/nocover/test_simple_strings.py, hypothesis-python/tests/nocover/test_targeting.py, hypothesis-python/tests/nocover/test_type_lookup_forward_ref.py, hypothesis-python/tests/nocover/test_unusual_settings_configs.py
Add triage reasons & issue links for the CrossHair tests that are skipped due to poor performance.
Also removed a couple of the skips entirely.
Resolves https://github.com/pschanely/CrossHair/issues/301 (and part of #3914).
=> Triage slow crosshair tests

.github/workflows/main.yml, AUTHORS.rst, tooling/src/hypothesistooling/__main__.py
Closes https://github.com/pyodide/pyodide#5585
This PR refactors the `update_pyodide_versions()` function in `tooling/src/hypothesistooling/__main__.py` which generates the relevant versions for Pyodide and its build tooling in the `test-pyodide:` CI job. The previous logic did not account for the fact that we had unvendored `pyodide-build` and moved it to a separate package that is released separately of the Pyodide runtime during the Pyodide 0.27 release cycle.
With these changes, the logic per the periodic updates will:
- use the PyPI Simple API to find out the latest stable version of `pyodide-build`, like before
- scan [the Pyodide cross-build environments metadata file](https://github.com/pyodide/pyodide/blob/d878eb2059b877fd4d25623d162c73872cdb4530/pyodide-cross-build-environments.j …
=> Handle Pyodide and pyodide-build unvendoring, and update Pyodide CI job

hypothesis-python/RELEASE.rst, hypothesis-python/docs/conf.py, hypothesis-python/docs/reference/api.rst, hypothesis-python/src/_hypothesis_pytestplugin.py, hypothesis-python/src/hypothesis/__init__.py, hypothesis-python/src/hypothesis/internal/detection.py, hypothesis-python/tests/conftest.py, hypothesis-python/tests/cover/test_detection.py, hypothesis-python/tests/ghostwriter/recorded/hypothesis_module_magic.txt
Because this has a code interface, I put it in the API reference, instead of the Integrations reference.
=> Document `is_hypothesis_test`

hypothesis-python/RELEASE.rst, hypothesis-python/docs/compatibility.rst, hypothesis-python/src/hypothesis/internal/constants_ast.py
Minor fix to prevent an unlikely but possible `RuntimeError` when `local_modules()` is called (in `hypothesis.internal.constants_ast`).
The error occurs while looping through `sys.modules.values()`, if its size is modified during iteration, e.g. by code from another thread.  This PR addresses the issue by pulling out out a copy of `sys.modules.values()` before iterating over it.
Example traceback:
```
.0 = <dict_valueiterator object at ...>
return tuple(
module
>       for module in sys.modules.values()
if (
getattr(module, "__file__", None) is not None
and _is_local_module_file(module.__file__)
)
)
E   RuntimeError: dictionary changed size during iteration
.../site-packages/hypothesis/internal/constants_ast.py:147: RuntimeError
```
=> fix: avoid race condition during loop over `sys.modules`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/pareto.py
`self.front.front.remove` bypasses the engine listener, which removes the corresponding entry from the database. This is the cause of the historically-flaky `test_database_contains_only_pareto_front`.
=> Fix pareto listener not firing in one case

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/_settings.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/providers.py, hypothesis-python/src/hypothesis/internal/constants_ast.py, hypothesis-python/tests/conjecture/test_local_constants.py, hypothesis-python/tests/conjecture/test_pareto.py, hypothesis-python/tests/cover/test_constants_ast.py
Closes #4365 and closes #4364
Main improvement here is tracking which modules we've seen before and directly caching `ModuleType -> set[ConstantT]`. This avoids paying the overhead of `SortedSet` and computing the choice type for all local constants, which turned out to take 100ms per provider instance in sympy's case.
=> Improve constants collection speed

hypothesis-python/docs/stateful.rst
An example was obviously copy-pasted and modified, but a method retained the previous name.
Been loving hypothesis, kudos to all contributors!
=> Fixed typos in docs

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/providers.py, hypothesis-python/tests/conjecture/test_alt_backend.py, pytest.ini
Crosshair can raise `BackendCannotProceed` when realizing choices for any example - including failing examples, as seen in https://github.com/HypothesisWorks/hypothesis/actions/runs/14853721823/job/41703445166, where we don't catch `BackendCannotProceed` and it bubbles up to the user.
Failing examples are more important to fully realize than standard examples, though. This PR adds a `for_failure` parameter which backends like crosshair can use to bump up the timeout and hopefully avoid `BackendCannotProceed` for failing examples.
This doesn't yet add exception handling for `BackendCannotProceed` for failing examples; we could do so now, or we could wait to see how big of a problem this is in practice with the increased timeout.
(cc @pschanely, ~~for release coordination as a breaking …
=> Add `for_failure: bool = False` to `provider.realize`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/datatree.py, hypothesis-python/tests/conjecture/test_choice.py
Uses a closed form expression to calculate the number of distinct strings, hence improving performance.
I also bumped `MAX_CHILDREN_EFFECTIVELY_INFINITE` by a factor 100 (to 10 million). This seems like a reasonable maximum number for all practical purposes, considering possible memory limits and so on, but if it's *only* for the counting performance then it can be increased (much) more without very bad effects.
=> Improve performance of string max-children count

.github/workflows/main.yml, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/database.py, hypothesis-python/tests/cover/test_asyncio.py, hypothesis-python/tests/cover/test_database_backend.py, hypothesis-python/tests/cover/test_testdecorators.py
Closes #4393 
Collects all test files in directory by name, rather than let pytest discover them.
I had to add a couple of module-level skips to avoid failure during test collection.
=> Fix pyodide

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/_settings.py
Check for GitLab CI in addition to GitHub and other platforms.
> "`GITLAB_CI`: Available for all jobs executed in CI/CD. `true` when available."
<https://docs.gitlab.com/ci/variables/predefined_variables/>
This function doesn't seem to have/need any test coverage, but please let me know if I missed something. (I also wasn't completely sure if creating `RELEASE.rst` was appropriate for such a tiny change - please let me know if I should remove that.)
=> Include GitLab CI variable when checking if in CI

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/pandas/impl.py
`hypothesis.extra.pandas.indexes()` -- add missing `.iloc` to silence Pandas 2.X FutureWarning.
Fixes #4400
=> add explicit .iloc to silence Pandas 2.X FutureWarning

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/observability.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/cover/test_fuzz_one_input.py, hypothesis-python/tests/cover/test_observability.py
brought up in https://github.com/HypothesisWorks/hypothesis/pull/4416#discussion_r2114673657
also closes https://github.com/HypothesisWorks/hypothesis/issues/4391
=> Write observability in `fuzz_one_input`

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py
The legacy LL(1) parser cannot handle compound with-statements using grouping parentheses and the `EXPR as TARGET` syntax, because it is not LL(1)-recognizable.
This partially reverts commit f151eec1e28b07f78837c08806401cd292ff6949.
---
Fixes #4421.
With this, to the best of my knowledge[^1], there are no current LL(1) parser failures in the `src` directory of the current (6.131.32) codebase.
There are still some such non-parsable expressions left over in the tests. Should I bother with those? There should be no differences compared to running Python 3.9 with the newer PEG-based parser, save for lack of parsing errors.
[^1]: `grep -E '^ *with\b'`
=> Restore compatibility with Python 3.9's legacy LL(1) parser

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/control.py, hypothesis-python/src/hypothesis/core.py, hypothesis-python/tests/cover/test_control.py, hypothesis-python/tests/nocover/test_precise_shrinking.py, hypothesis-python/tests/quality/test_discovery_ability.py
Split from #4422, required for https://github.com/Zac-HD/hypofuzz/pull/113
Hypofuzz uses this for the following in `HypofuzzProvider`:
```python
self.database_key = function_digest(context.wrapped_test.hypothesis.inner_test)
self.nodeid = getattr(
current_pytest_item.value, "nodeid", None
) or get_pretty_function_description(context.wrapped_test)
self.worker_identity = worker_identity(
in_directory=Path(inspect.getfile(context.wrapped_test)).parent
)
```
=> Add `wrapped_test` to `BuildContext`

hypothesis-python/tests/cover/test_direct_strategies.py
Fix xfail-strict failures in `compatible_shared_strategies_do_not_raise()` test when the test suite is run without global `-Werror`.
Fixes #4428
=> Fix compatible_shared_strategies_do_not_raise() test without -Werror

AUTHORS.rst, hypothesis-python/RELEASE.rst, hypothesis-python/docs/conf.py, hypothesis-python/docs/reference/api.rst, hypothesis-python/src/hypothesis/extra/django/__init__.py, hypothesis-python/src/hypothesis/extra/django/_impl.py, hypothesis-python/tests/django/toystore/test_basic_configuration.py, requirements/tools.in, requirements/tools.txt
=> Add extra.django.SimpleTestCase

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/_patching.py
and renames `failing_examples` to `examples` internally
=> Add type hints to `_patching.py`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/cache.py
I've seen a rare failure here in CI several times over the past ~month. As far as I can remember, they are always on windows. Most recent failure: https://github.com/HypothesisWorks/hypothesis/actions/runs/15687024864/job/44192686508?pr=4388. 
The cache is threadlocal, so I'm not sure how a race condition could occur here. This makes me a bit nervous that there is an actual logic bug in `GenericCache`, and adding this condition will mask it. On the other hand, only reproducing on windows is evidence of a race condition rather than a logic error.
=> Safer cache eviction

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/src/hypothesis/stateful.py
`dataclasses.asdict` deepcopies and can be very expensive. Regressed in https://github.com/HypothesisWorks/hypothesis/pull/4395, where I copied `attrs.asdict` -> `dataclasses.asdict` (but that's no excuse!)
closes (very likely) https://github.com/HypothesisWorks/hypothesis/issues/4431.
=> Fix stateful test performance regression

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_shrinker.py, hypothesis-python/tests/nocover/test_conjecture_engine.py
Part of https://github.com/HypothesisWorks/hypothesis/issues/4451.
Running under free threading can cause race conditions with shrinking pass definitions. `pytest -k test_minimal_min_magnitude_positive --parallel-threads 2 --iterations 500` leads to:
```
File "/Users/tybug/Desktop/Liam/coding/hypothesis/hypothesis-python/src/hypothesis/internal/conjecture/engine.py", line 1550, in shrink
s.shrink()
File "/Users/tybug/Desktop/Liam/coding/hypothesis/hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py", line 440, in shrink
self.greedy_shrink()
File "/Users/tybug/Desktop/Liam/coding/hypothesis/hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py", line 634, in greedy_shrink
node_program("X" * 5),
^^^^^^^^^^^^^^^^^^^^^
File …
```
=> Refactor shrink pass definitions for threading

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/tests/cover/test_lambda_formatting.py
I have actually hit this many times over the years. I know what the reason for the failure is, so it's not too bad for me, but I can imagine this being confusing and frustrating to developers who are not familiar with hypothesis internals.
To reproduce, you can do something like run a stateful test with a one-line lambda in a precondition, then quickly delete a line at the start of the file to offset all the line numbers.
=> Remove lambda source code assertion

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/strategies/_internal/lazy.py, hypothesis-python/src/hypothesis/utils/threading.py, hypothesis-python/tests/cover/test_threading.py
Part of https://github.com/HypothesisWorks/hypothesis/issues/4451.
There are three separate fixes here, split by commit:
* https://github.com/HypothesisWorks/hypothesis/commit/dc0e5e7ed98bd612c0591388a674e9ac0096bd26
* https://github.com/HypothesisWorks/hypothesis/commit/56908301f70a29aab4ea5fbc2a335f2c17674d99 - as long as the assignment to `__wrapped_strategy` is atomic (and deterministic), I don't think we need a lock. Worst case is two threads perform the same computation and assign the same value after.
* https://github.com/HypothesisWorks/hypothesis/commit/2548924dbe3a525c6eba13c8e0331ff8458e071a - performance overhead of a lock in single-threaded seems negligible on a microbenchmark
=> Improve threading compatibility of core strategy definitions

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/charmap.py, hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py, hypothesis-python/tests/nocover/test_threading.py
This was the last blocker to actually running a multithreaded test in CI; yay! (...well, probably; I wouldn't be surprised to hit https://github.com/HypothesisWorks/hypothesis/pull/4453 here)
Previous code related to thread safety and `ensure_free_stackframes`: 
* https://github.com/HypothesisWorks/hypothesis/pull/3683
* https://github.com/jobh/hypothesis/blob/34f5ccec96019cfc30ad8593498cd30291f9e4ec/hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py (from the commit history of the above PR)
That made concurrent `__enter__` of the same `ensure_free_stackframes` object thread-safe due to the per-instance lock though, which we don't do anywhere - we use a fresh instance per call.
=> Make the `ensure_free_stackframes` warning thread-safe

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/control.py, hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py, hypothesis-python/src/hypothesis/internal/entropy.py
Part of https://github.com/HypothesisWorks/hypothesis/issues/4451
No tests, because any test I could write immediately runs into other thread-safety issues that I've temporarily hacked around locally.
=> Make `deprecate_random_in_strategy` thread safe

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
I noticed some performance pickups while investigating https://github.com/HypothesisWorks/hypothesis/issues/4465. This does not fix that issue, but it does help a bit.
---
Benchmark results from https://github.com/HypothesisWorks/hypothesis/issues/4465. That benchmark has substantial between-runs variance on my machine, so I wouldn't treat this as anything more than a sanity check.
| Master | PR |
|--------|--------|
| <img width="3568" height="2368" alt="master  hypothesis_performance_scaling" src="https://github.com/user-attachments/assets/524d0766-94bc-482c-af8e-6fcaacdf5200" /> |  <img width="3568" height="2368" alt="branch  hypothesis_performance_scaling" src="https://github.com/user-attachments/assets/173e6036-8fb9-495a-b270-8191381258a9" />  |
=> Optimize `sampled_from` and stateful performance

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py, hypothesis-python/tests/common/utils.py, hypothesis-python/tests/conjecture/test_junkdrawer.py, hypothesis-python/tests/nocover/test_recursive.py, hypothesis-python/tests/nocover/test_threading.py
Part of https://github.com/HypothesisWorks/hypothesis/issues/4451.
The old implementation still had thread-safety problems, as I discovered when testing afterwards. This is a complete and maybe slightly overkill solution which retains (almost; see refcounting comment) as much power of the warning as possible.
This also fixes an actual concurrency bug (not just to do with warnings) where the recursion limit might not be restored to its correct value. We track the original recursion limit of the first `ensure_free_stackframes` call on the stack, and reset it to that unconditionally when the last context exits (regardless of that context's initial value). Intermediate threads can still trample each other's limits, but there's nothing we can do about that.
=> Fix `ensure_free_stackframes` thread-safety

hypothesis-python/RELEASE.rst, hypothesis-python/docs/changelog.rst, hypothesis-python/src/hypothesis/control.py, hypothesis-python/src/hypothesis/internal/entropy.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py
Part of https://github.com/HypothesisWorks/hypothesis/issues/4451. We're quite close to a clean `--parallel-threads 2` run at this point.
Tracking this more concretely also lets us get rid of `_Checker` (which frees up a stackframe call on every strategy draw - that might actually be noticeable in perf! though it probably isn't).
=> Fix a remaining thread safety issue in the random deprecation warning

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/extra/_array_helpers.py, hypothesis-python/src/hypothesis/extra/array_api.py, hypothesis-python/src/hypothesis/extra/lark.py, hypothesis-python/src/hypothesis/extra/numpy.py, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/src/hypothesis/strategies/_internal/collections.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/datetime.py, hypothesis-python/src/hypothesis/strategies/_internal/numbers.py, hypothesis-python/src/hypothesis/strategies/_internal/random.py, hypothesis-python/src/hypothesis/strategies/_internal/recursive.py, hypothesis-python/src/hypothesis/strategies/_internal/shared.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/src/hypothesis/strategies/_internal/strings.py, hypothesis-python/src/hypothesis/strategies/_internal/types.py, hypothesis-python/tests/common/strategies.py, hypothesis-python/tests/nocover/test_duplication.py, hypothesis-python/tests/nocover/test_threading.py, website/content/2016-12-10-how-hypothesis-works.md
Part of https://github.com/HypothesisWorks/hypothesis/issues/4451. This one is pretty rare, only triggering about once per full test suite run under `--parallel-threads 2`. There might be a way to write `do_validate` that takes recursion into account and only tracks `validate_called = True` at the end, but that's a bigger rewrite.
I'm somewhat worried about the unconditional lock overhead in the singlethreaded case. It's ~pure lock/unlock overhead, I expect ~zero contention. Here's a claude benchmark for `.validate` for `lambda i: st.integers().map(lambda x: x + i))`, where the `lambda i` and `.map` are cache-busters so each strategy really gets `.validate` called.
```
master        : 0.000080612s per call (12405 calls/sec)
pr        : 0.000086325s per call (11584 calls/sec)
``` …
=> Fix strategy validation thread-safety

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
See https://github.com/Quansight-Labs/pytest-run-parallel/actions/runs/16373126695/job/46266326511?pr=96#step:7:178 (https://github.com/Quansight-Labs/pytest-run-parallel/pull/96). I don't have a consistent reproducer for this locally, but this is the only possible way I can see this happening.
=> Speculative fix for `strategy.label` thread safety

hypothesis-python/RELEASE.rst, hypothesis-python/docs/prolog.rst, hypothesis-python/docs/reference/api.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/errors.py, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/pareto.py, hypothesis-python/tests/conjecture/common.py, hypothesis-python/tests/conjecture/test_data_tree.py, hypothesis-python/tests/conjecture/test_engine.py, hypothesis-python/tests/conjecture/test_float_encoding.py, hypothesis-python/tests/conjecture/test_optimiser.py, hypothesis-python/tests/conjecture/test_pareto.py, hypothesis-python/tests/conjecture/test_provider.py, hypothesis-python/tests/conjecture/test_shrinker.py, hypothesis-python/tests/conjecture/test_test_data.py, hypothesis-python/tests/cover/test_exceptiongroup.py, hypothesis-python/tests/nocover/test_conjecture_engine.py, hypothesis-python/tests/nocover/test_precise_shrinking.py, hypothesis-python/tests/quality/test_discovery_ability.py, hypothesis-python/tests/quality/test_poisoned_lists.py, hypothesis-python/tests/quality/test_poisoned_trees.py, hypothesis-python/tests/quality/test_zig_zagging.py
Closes https://github.com/HypothesisWorks/hypothesis/issues/4462.
Suppressing the "failed on backend A but not backend B" note for `DeadlineExceeded` is simple enough. Once that's done, and `DeadlineExceeded` gets raised, we replay it. We're very likely to get a `FlakyFailure` report of the deadline being exceeded in the failing input but not in the replay, because we switched to the hypothesis backend for the replay. 
This would be similarly confusing to the flaky-backend report, so I've chosen to re-raise the initial failure instead of reporting a flaky failure if a backend-raised `DeadlineExceeded` does not reproduce. We have to replay an `is_final=True` input to get `should_note()` output, even if flakiness is out of the picture, so our options are (1) reraise the initial exception …
=> Re-raise `DeadlineExceeded` from backends

hypothesis-python/RELEASE.rst, hypothesis-python/src/_hypothesis_pytestplugin.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py, hypothesis-python/src/hypothesis/internal/conjecture/providers.py, hypothesis-python/src/hypothesis/vendor/pretty.py, hypothesis-python/tests/conjecture/test_provider.py, pyproject.toml
Previously `on_observation` would be called for the replayed choice sequence on the hypothesis backend
=> Fix `PrimitiveProvider.on_observation` being called incorrectly during failure replay

hypothesis-python/RELEASE.rst, hypothesis-python/docs/prolog.rst, hypothesis-python/src/hypothesis/stateful.py, hypothesis-python/src/hypothesis/strategies/_internal/featureflags.py, hypothesis-python/tests/cover/test_stateful.py
Closes https://github.com/HypothesisWorks/hypothesis/issues/4413.
Since `@precondition` can be applied either before or after `@rule`, it's easiest to raise this error at runtime, rather than definition time.
I refactored stateful initialization to make this possible / cleaner. `inspect.getmembers` makes me nervous performance-wise, so it's good to cut that down to just a single use as well.
=> Error when `@precondition` is used without `@rule`

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/conjecture/engine.py
Part of https://github.com/HypothesisWorks/hypothesis/issues/4451. Discussion in https://github.com/HypothesisWorks/hypothesis/pull/4388#issuecomment-3124748043. Untested since I don't have a consistent local reproducer, but follows the same pattern as `DeadlineExceeded`.
=> Disable `HealthCheck.too_slow` under threading

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/core.py, hypothesis-python/src/hypothesis/internal/scrutineer.py
GraalPy's next release will update to 3.12, but we didn't yet implement `sys.monitoring`. This PR will avoid failing on the next GraalPy by checking for `sys.monitoring`'s presence instead of the python version. It shouldn't change anything for CPython.
CC @timfel
=> Improve detection of sys.monitoring

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/tests/nocover/test_threading.py
Part of #4451. This previously caused `test_inference_on_generic_collections_abc_aliases` to fail under threading.
=> Add a lock to `OneOfStrategy.branches`

hypothesis-python/RELEASE-sample.rst, hypothesis-python/docs/compatibility.rst, hypothesis-python/docs/conf.py, hypothesis-python/tests/cover/test_stateful.py
Closes https://github.com/HypothesisWorks/hypothesis/issues/4451 🎉 
I also saw a `check-threading` failure on master, which I cannot reproduce locally: https://github.com/HypothesisWorks/hypothesis/actions/runs/16794763925/job/47563329138#step:6:671. One of the threads doesn't shrink. I don't see how this can happen unless we have a race inside shrinking (but then why only for `.teardown()`?). I'm adding logging for the next time it triggers.
=> Declare thread safety

hypothesis-python/tests/cover/test_database_backend.py, hypothesis-python/tests/cover/test_traceback_elision.py
Fixes a couple of annoyances in the test suite:
- Don't fail test when traceback trimming is disabled in env (and incidentally add a test for it)
- Don't leave temp dirs that are not cleanable by pytest (which it complains verbosely about)
=> Test annoyances

hypothesis-python/tests/cover/test_constants_ast.py
This test keeps failing for me locally, because I (often) have other dev-installed packages, for debugging or whatever.
This PR makes the test a non-strict XFAIL unless the CI profile is used -- if so, it is required to pass.
=> Skip constants-from-file test when not on CI

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/filtering.py, hypothesis-python/src/hypothesis/internal/lambda_sources.py, hypothesis-python/src/hypothesis/internal/reflection.py, hypothesis-python/tests/conftest.py, hypothesis-python/tests/cover/test_lambda_formatting.py, hypothesis-python/tests/cover/test_reflection.py, hypothesis-python/tests/cover/test_simple_strings.py
Closes #4457
The source compilation test for lambda is tweaked so that it has no false negatives on our test corpus. To be confirmed by CI, as (apparent) false negative is now a self-test failure.
That means the test compilation can be done on all sources, and then it's trivial and safe to expand the search to surrounding lines.
There is probably an impact on performance, but I imagine it will be fairly small in practive - given extensive caching and also that most cases will be satisfied by the same-line source match.
=> Improvements to bytecode-comparison of lambdas

hypothesis-python/RELEASE.rst, hypothesis-python/src/_hypothesis_pytestplugin.py
Noticed a typo in an error message: "cotext manager" -> "context manager"
My bad for not catching this when submitting my earlier pull request.
=> fix: typo in error message

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/internal/conjecture/data.py, hypothesis-python/src/hypothesis/internal/conjecture/utils.py, hypothesis-python/src/hypothesis/internal/lambda_sources.py, hypothesis-python/src/hypothesis/strategies/_internal/core.py, hypothesis-python/src/hypothesis/strategies/_internal/flatmapped.py, hypothesis-python/src/hypothesis/strategies/_internal/numbers.py, hypothesis-python/src/hypothesis/strategies/_internal/shared.py, hypothesis-python/src/hypothesis/strategies/_internal/strategies.py, hypothesis-python/src/hypothesis/strategies/_internal/utils.py, hypothesis-python/tests/conjecture/test_utils.py, hypothesis-python/tests/cover/test_direct_strategies.py, hypothesis-python/tests/cover/test_sampled_from.py, hypothesis-python/tests/nocover/test_labels.py
Closes #4301.
After I realized that a single strategy may be present multiple times by different keys in the strategy cache, dealing with cache revocations became untenable. So this alternative solution does not refer to the cache or singletons at all, and just compares strategy labels. This is strictly less powerful, as it it doesn't distinguish strategies with incompatible constraints; but it is reasonably clean&safe, and if the label concept grow more powerful in the future then the warning will, too.
=> Fix shared strategy warnings

hypothesis-python/RELEASE.rst, hypothesis-python/src/hypothesis/_settings.py
See https://github.com/HypothesisWorks/hypothesis/issues/4481. Untested - I'm happy to add one if someone sees an easy way to test this.
=> Respect `__TOX_ENVIRONMENT_VARIABLE_ORIGINAL_CI` under tox
