HypothesisWorks/hypothesis

- README.rst
> README.rst: fix typo in BadSetTester example

- docs/details.rst
This looks bad:
especially compared with the previous example, which uses correct formatting:
> Fix REPL formatting in example

- docs/supported.rst
They've either broken their https setup or don't intend to use it for the content site.
Login to https://ci.appveyor.com is configured correctly.
> HTTPS certificate fails for www.appveyor.com

- docs/quickstart.rst
When I look at [the quickstart docs](http://hypothesis.readthedocs.org/en/latest/quickstart.html), a few sections that should formated as code are not.
I fixed that.
> Fix code blocks in quickstart

- src/hypothesis/errors.py
This information is clearly contained in the doc string already.
> Emphasize that no examples were found

- src/hypothesis/core.py
Previously core.py included a line that artificially referenceed the
imported assume function to avoid a flake8 warning. This adds a noqa
comment to the import so it is skipped by flake8, meaning the artificial
usage is no longer required.
(This follows from my previous PR)
> Make flake8 skip "unused" assume import in core.py

- src/hypothesis/strategies.py
The type of bytes in python 3 is `bytes`, not `binary`.
> Fix documentation of `binary` to mention `bytes` instead of `binary`

- CONTRIBUTING.rst
- src/hypothesis/internal/reflection.py
Resolves #143.
This change adjusts the logic when compiling source into a module and then importing it. Previously this could race, as multiple test processes running in parallel could attempt to write the same file at roughly the same time. This change prevents that by ensuring that each process writes to a unique file (by using a UUID4 in the filename), and then atomically renaming the file to the proper name.
On Windows this is a bit tricky because `os.rename` raises an `OSError` if the destination exists, so we allow for that. Otherwise, `os.rename` is atomic so this should be fine: no file should ever be empty.
Currently there are no tests here, I'm going to think about how best to test this, but I wanted the change up for review ASAP.
Consider this change a gift from your friends at …
> Avoid races when execing source as modules.

- docs/data.rst
- src/hypothesis/strategies.py
This was rendering poorly in read the docs making it hard to read.
This is what it looks on https://hypothesis.readthedocs.org/en/latest/data.html?highlight=recursive
Here is after this change
The second commit is just fixing a sphinx build error
Which cased the docs to look like this
And now they look like this
> Fix minor quirks in docs

- scripts/basic-test.sh
Namedtuple wasn't used for sys.version_info there.
> Fix major version lookup on Python 2.6

- tests/cover/test_streams.py
Fixes coverage failure for types module on line 76. I wasn't very original in test case >_>
> Add test for Stream.map

- docs/quickstart.rst
I made a minor edit to the Quick Start example to make it more explicit what raises the bug for the parameter ``s='001'``. It's a trivial point, but I think it makes it clearer. :)
> Make RLE example more explicit in quickstart docs

- src/hypothesis/database/backend.py
This method is [used](https://github.com/DRMacIver/hypothesis/blob/e93399e2ae86951340cb39bc4658b052c85b7631/src/hypothesis/database/__init__.py#L89) by ExampleDatabase and custom backends should be aware about it.
> Add close method to Backend interface

- .gitignore
- CONTRIBUTING.rst
- docs/Makefile
- docs/extras.rst
- src/hypothesis/extra/datetime.py
- tests/datetime/test_dates.py
- tests/datetime/test_times.py
* Add `dates` and `times` strategies
* Add tests
* Add documentation, improving `datetimes` documentation
* Add `livehtml` target to `docs/Makefile` using `sphinx-autobuild` for live docs editing
* `gitignore` update with some folders that appear during tests
> Add dates() and times() strategies to hypothesis.extra.datetime

- .gitignore
- CONTRIBUTING.rst
- docs/details.rst
- docs/extras.rst
- src/hypothesis/extra/pytestplugin.py
- src/hypothesis/settings.py
- tests/cover/test_settings.py
- tests/pytest/test_profiles.py
Allows users to register settings profiles and load them
in as needed. Allowing for different defaults for different
environments
Is this kind of what you were thinking for the profile setup?
This code should enable the following pattern
```
Settings.register_profile('dev', max_examples=5, max_shrinks=10, max_iterations=100)
Settings.register_profile('ci', max_examples=1000, max_shrinks=1000, max_iterations=2000)
Settings.load_profile(os.getenv('HYPOTHESIS_PROFILE', 'default'))
```
If you think im close ill iterate with you as needed. If we get to something you like let me know and ill write up the docs.
> Create profile loading mechanism

- src/hypothesis/core.py
- tests/py2/test_destructuring.py
Instead of `TypeError: unhashable type: 'list'` when we try operate on them.
> Better error when decorating a function with destructuring args

- CONTRIBUTING.rst
- docs/database.rst
- docs/details.rst
- docs/quickstart.rst
- docs/stateful.rst
- examples/bintree.py
- src/hypothesis/errors.py
- src/hypothesis/searchstrategy/collections.py
- src/hypothesis/strategies.py
- tests/cover/test_given_error_conditions.py
- tests/cover/test_simple_numbers.py
- tests/cover/test_simple_strings.py
- tests/nocover/test_example_quality.py
@DRMacIver This pull request corrects several spelling errors I found using the [scspell](https://pypi.python.org/pypi/scspell) utility. I verified that none of the changes introduce any linting errors
The scspell utility has a fairly high false positive rate, labeling several differences between British and American English as errors. I ignored those "errors" manually. I think the corrections included here are unambiguous spelling errors or typos.  None of them have any effect on code execution, since they occurred in either documentation or test names.
I opted not to correct the following errors in `changes.rst` since immutability of changelogs is probably desirable.
- simplificaiton
- implemnetation
- suitee
- parametrizing
- remaing
- Mozila
- stratagies
- embarassing
Thanks for all …
> Correct several spelling errors discovered with scspell

- tests/cover/test_recursive.py
- tests/cover/test_testdecorators.py
- tests/nocover/test_example_quality.py
- tests/numpy/test_gen_data.py
- tox.ini
This adds "flaky" as a dependency. I've tagged all tests which failed in my
previous pull requests.
> Retry flaky tests on fail

- .travis.yml
This avoids taking up resources when we're going to fail the build anyway, see
http://docs.travis-ci.com/user/customizing-the-build/#Fast-Finishing.
> Fail Travis build quickly if a worker fails

- docs/manifesto.rst
Because hyperlinks exist to make the world more serendipitous.
> Linking to tef's talk

- docs/stateful.rst
I was playing with the stateful api and ran into a few warnings
> Avoid using deprecated apis in stateful testing docs

- docs/stateful.rst
- src/hypothesis/stateful.py
- tests/cover/test_stateful.py
This adds a `@precondition` decorator that you can use on your `@rule`-decorated functions to add preconditions to them. Rules that don't match preconditions will not be considered as a "step" in the state machine.
TODO:
> preconditions for RuleBasedStateMachine

- src/hypothesis/internal/charstree.py
- src/hypothesis/searchstrategy/strings.py
- src/hypothesis/strategies.py
- tests/cover/test_charstree.py
- tests/cover/test_simple_characters.py
This strategy allows to produce single unicode characters by specified rules: you may have exact characters or characters that belongs some [Unicode Category](http://www.unicode.org/reports/tr44/#General_Category_Values). Additionally, you may reverse your rule to specify which characters you don't want to get.
characters strategy preserved existed OneCharStringStrategy behaviour when with no arguments it produces all the characters except surrogates.
characters with exact only argument converted into sampled_from strategy implicitly.
Generally tests passed, but travis fails due to irrelevant reasons. What I can fix will send with additional PRs. 
Feedback is welcome (:
> Implement characters strategy

- Makefile
`make check` runs the full battery of tests, including the format check.
However before running any test suites the `check-format` target runs, to
enforce code style - including that there are no uncommitted changes.
As a consequence `make check` is awkward to run before a commit.
`make check-noformat` is intended to remedy that.
> Allows test suite to be run, with a dirty checkout

- src/hypothesis/types.py
- tests/cover/test_health_checks.py
This warning happens in 3.5+ due to PEP-479 that aims to distinguish
stop iteration from generator exit. Eventually, StopIteration exception
happens inside __iter__ method (assuming iteration) on picking next item
from generator what violates the new rules.
While this change marked as backward incompatible, the fix is quite
trivial to work with all Python versions and not introduce any
workarounds.
The well known trigger of this warning are composite strategies, but
there may be others.
Notice: nose and py.test keeps silent on this warning, so you may notice
it if use stdlib unittest runner or similar.
> Fix PendingDeprecationWarning: generator '__iter__' raised StopIteration

- setup.py
Given that `python setup.py test` doesn't work, we probably don't need this.
> Remove vestigial tests_require.

- setup.py
This fixes a [reproducibility issue](https://tests.reproducible-builds.org/dbd/unstable/amd64/python-hypothesis_3.0.0-1.diffoscope.html#python3-hypothesis_3.0.0-1_all.deb/data.tar.xz/data.tar/./usr/lib/python3/dist-packages/hypothesis-3.0.0.egg-info/requires.txt) with building Hypothesis.
> Sort dependencies for stable ordering.

- CONTRIBUTING.rst
- setup.py
I understand that this version is not really supported, but I thought it'd be trivial enough to add.
> Also depend on enum34 for Python 3.3

- docs/packaging.rst
The README says that the only supported versions are 2.7, 3.4 and 3.5.
> Fix supported versions in packaging guidelines

- docs/settings.rst
The default settings are immutable, so to change verbosity you need to pass
your own instance instead of direct assignment.
> Fix settings example

- src/hypothesis/extra/pytestplugin.py
py.test has dev versions of the format `1.2.3.dev1`. `dev1` is not a
valid integer.
> Don't crash on pytest dev version

- src/hypothesis/strategies.py
These seem to have been introduced accidentally in 2d195a0,
and seem to cause Sphinx to duplicate their automodule documentation,
as can be seen here:
http://hypothesis.readthedocs.org/en/3.1.0/data.html#hypothesis.strategies.recursive
http://hypothesis.readthedocs.org/en/3.1.0/data.html#hypothesis.strategies.composite
> Remove duplicated __all__ exports

- docs/usage.rst
According to this blog post (http://morepypy.blogspot.com.es/2016/03/pypy-50-released.html) PyPy 5.0 uses hypothesis for his tests.
> Add PyPy to Open Sources projects.

- src/hypothesis/core.py
Current state:
```
If you want to disable just this health check, add HealthCheck.exception_in_generationto the suppress_health_check settings for this test.
```
I have not tested this change
> Add space between words

- docs/extras.rst
As pointed out in #259 (Documentation for hypothesis.extra.numpy) there is currently no documentation for `extra.numpy` and I would like to contribute a few basic examples.
> DOC: added basic doc for extra.numpy

- CONTRIBUTING.rst
- src/hypothesis/searchstrategy/collections.py
This kept triggering `too slow` health check failures on my tests and post-change I get a drop from ~18s to ~12s to generate my data.
I tried to run the tests locally, but they keep failing with what look like unrelated errors for python2.6:
```
Traceback (most recent call last):
File "/home/ccc/g/hypothesis/.tox/py26-full/lib/python2.6/site-packages/_pytest/config.py", line 319, in _importconftest
mod = conftestpath.pyimport()
File "/home/ccc/g/hypothesis/.tox/py26-full/lib/python2.6/site-packages/py/_path/local.py", line 650, in pyimport
__import__(modname)
File "/home/ccc/g/hypothesis/tests/conftest.py", line 25, in <module>
run()
File "/home/ccc/g/hypothesis/tests/common/setup.py", line 33, in run
charmap()
File "/home/ccc/g/hypothesis/.tox/py26-full/lib/python2.6/site-packages/hypothe …
```
> Adds a `max_size` check to the `ListStrategy` while loop.

- docs/details.rst
It is no longer raised, since: 2d48fcdb9d123871493fb8ba98088f42b974e344.
> doc: remove DefinitelyNoSuchExample error from example text

- docs/extras.rst
Seems better not to encourage new installations of this no-op legacy package.
Another option would be to leave a tombstone entry with the text from the [hypothesis-pytest package description](https://pypi.python.org/pypi/hypothesis-pytest), I suppose.
> extras.rst: remove hypothesis-pytest section

- src/hypothesis/extra/django/models.py
- tests/django/toystore/models.py
- tests/django/toystore/test_given_models.py
This pull request updates the `hypothesis.extras.django.models.models` strategy for building Django model instances from a model class.
Duplicating information from the field definitions into the construction of a strategy is tedious and makes it harder to start using `hypothesis` in a pre-existing Django application.
My goal was that `models(MyModel).example().full_clean()` should succeed to the extent possible.
- The [`max_length`](https://docs.djangoproject.com/en/1.9/ref/models/fields/#django.db.models.CharField.max_length), [`blank`](https://docs.djangoproject.com/en/1.9/ref/models/fields/#blank) and [`choices`](https://docs.djangoproject.com/en/1.9/ref/models/fields/#choices) kwargs are now respected.
- Add support for `DecimalField`. This uses a custom `decimal` strategy which …
> Use Django field definitions to ensure valid strategies

- README.rst
This just updates the README.rst with a working link to the contribution docs.
> Update README with working contributing link

- CONTRIBUTING.rst
- README.rst
- docs/changes.rst
- docs/examples.rst
- src/hypothesis/core.py
- src/hypothesis/searchstrategy/strategies.py
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs links for their .org -> .io migration for hosted projects

- docs/examples.rst
New user reading through the docs - this looks like a bug in the node example (I have not run the example code).
> Fix NodeStrategy usage in code fragment

- tox.ini
This is already handled by the "brief:" conditional in [testenv].
> Remove rendundant -brief testenv from tox.ini

- src/hypothesis/extra/pytestplugin.py
This makes the flags show under the hypothesis label rather than
`custom flags`
> Use option group in py.test plugin

- setup.py
I don't know why fake-factory's version was pinned but I hope the issue is fixed.
> Bump supported fake-factory version

- src/hypothesis/database.py
Otherwise, when running tests using hypothesis with Python's [-b/-bb option](https://docs.python.org/3/using/cmdline.html#cmdoption-b), we'd get a warning/error:
```
hypothesis/database.py:243: in save
tmpname = path + '.' + str(binascii.hexlify(os.urandom(16)))
E   BytesWarning: str() on a bytes instance
```
Not sure how to best test this, I just added `-bb` to the `brief` environment locally. Maybe a new tox environment, similar to the `unicode` one? Or add `-bb` to the full testsuite on Python 3?
> Avoid using str() on a bytes object on Python 3

- src/hypothesis/internal/conjecture/utils.py
Without this patch, drawing an integer outside the valid range marks the
data as invalid, which forces a re-draw of all other data up to that
point. After the patch, we immediately redraw the integer until it is
within the target range. In practice, this doubled the number of valid
examples found within a bounded time period.
> Speed up fair integer drawing

- tests/nocover/test_pretty_repr.py
This function doesn’t appear anywhere else in the codebase; let’s get rid of it.
> Remove an unused function from test_pretty_repr

- docs/extras.rst
- docs/settings.rst
The default `buffer_size` doesn't really support modest sized matrices that are greater than 3 dimensions (fails to find an example for shape of `(25, 25, 2)`), and the documentation/error messages are lacking in that particular area (it took quite a bit of digging to figure out that that was the root problem).  This PR updates the documentation to make that a little bit more clear, and highlight the fact that `buffer_size` is a settings option.
> Update docs for `buffer_size` setting

- src/hypothesis/_settings.py
- src/hypothesis/internal/charmap.py
- src/hypothesis/internal/conjecture/data.py
- src/hypothesis/internal/debug.py
- src/hypothesis/stateful.py
- src/hypothesis/strategies.py
- src/hypothesis/tools/mergedbs.py
- src/hypothesis/vendor/pretty.py
- tests/common/__init__.py
- tests/common/utils.py
- tests/cover/test_core.py
- tests/cover/test_database_agreement.py
- tests/cover/test_pretty.py
- tests/cover/test_runner_strategy.py
- tests/cover/test_stateful.py
- tests/nocover/test_compat.py
- tests/nocover/test_descriptortests.py
- tests/nocover/test_strategy_state.py
- tests/py3/test_asyncio.py
[flake8 3.2.0](http://flake8.pycqa.org/en/latest/release-notes/3.2.0.html) (and then 3.2.1) were released about a fortnight ago, and the new checks are breaking the tests on #396. This patch gets the lint check passing again.
(Actually, looking at the pycodestyle release notes, it looks like this was an existing check that was previously broken. Oh well, same effect on us.)
> Fix lint failures introduced by flake8 3.2.1

- README.rst
Having to bury into the 3rd or so page of the docs just to install `hypothesis` is annoying, especially if you just want to be sure that `pip install hypothesis` is the right command.
> Add install instructions

- src/hypothesis/internal/conjecture/data.py
- src/hypothesis/internal/conjecture/engine.py
- src/hypothesis/internal/conjecture/minimizer.py
- src/hypothesis/searchstrategy/flatmapped.py
- src/hypothesis/strategies.py
- tests/cover/test_composite.py
- tests/cover/test_flatmap.py
In existing Hypothesis there is a problem where often code
using these results in examples that don't shrink very well
because shrinking an earlier value results in changes to
the structure of the later value that no longer exhibits
the problematic behaviour.
This change introduces some limited ability to work past
that by allowing the later structure to be reordered in a
way that gives more flexible possibilities for producing
shrunk examples..
This is primarily focused on cases that use length prefixed
lists and similar concepts (hence the tests focusing on that),
but likely should work more generally.
This branch also contains a number of other improvements to
the Conjecture engine that turned out to be necessary to make
this work well, and one removal of an annoying shrinking pass …
> Improve shrinking of code using flatmap/composite

- scripts/basic-test.sh
- setup.py
- src/hypothesis/extra/django/models.py
- tests/django/toystore/test_email_strategies.py
- tox.ini
This creates a small internal use only email strategy that replaced hypothesis.extra.django's use of the faker based email strategy.
The strategy in question is not very good, but it is mostly better than the fake factory based one (the big limitation in comparison is that the email addresses generated only contain ascii, but I think that's probably a feature rather than a bug given handling of unicode emails).
This is partly an experiment. I want to see if people mention the fake factory integration ever again when the Django integration stops needing it. The faker integration is also really slow right now, so moving it out of the critical path for testing Django is a nice bonus.
> Remove hypothesis.extra.django's dependence on faker

- src/hypothesis/searchstrategy/deferred.py
- src/hypothesis/searchstrategy/flatmapped.py
- src/hypothesis/searchstrategy/strategies.py
- src/hypothesis/strategies.py
- tests/nocover/test_statistical_distribution.py
This replaces #383, which was getting a bit unwieldy and which Travis appears to have forgotten about.
> Flatten branches when using `one_of()`

- src/hypothesis/core.py
- src/hypothesis/errors.py
- src/hypothesis/executors.py
- src/hypothesis/internal/conjecture/data.py
- src/hypothesis/internal/conjecture/engine.py
- tests/cover/test_conjecture_engine.py
- tests/cover/test_conjecture_test_data.py
- tests/cover/test_conjecture_utils.py
- tests/cover/test_control.py
- tests/cover/test_executors.py
- tests/cover/test_integer_ranges.py
- tests/cover/test_simple_strings.py
- tests/nocover/test_statistical_distribution.py
This causes pytest warnings because they look like they're
supposed to be unittest tests, but they have an __init__ which
stops them being picked up as such.
> Rename classes whose name starts with Test

- src/hypothesis/internal/debug.py
- tests/conftest.py
- tests/nocover/test_fixtures.py
This uses some judicious monkey patching to control the passage of time during our tests.
The reason for this is that when running tests on Travis, or really any computer with slightly unreliable performance, tests can currently fail because the system is under load or took a nap mid execution, etc. A lot of the current flakiness comes from this.
If instead we just pretend time passes at a uniform rate by having time increment by 100ns every time we check (I originally tried for 1ms but that turned out to be too much and a numberof the tests in test\_example\_quality failed), the testing should become much more robust.
This doesn't remove all flakiness, because we're still at the mercy of the random seed (I'm tempted to fix this by doing a fixed seed prior to each test, but I'm a little …
> Take control of the time stream

- Makefile
- scripts/enforce_header.py
This replaces the four (!) different places we decide which files
get formatted with a single one, as a prerequisite for the actual
point of this: Formatters should not run on vendored files.
This is somewhat prompted by an intent to add another vendored
file, but it's a good change in its own right even if we don't
do that.
> Standardize which files to format. Exclude vendor

- .travis.yml
- Makefile
- tox.ini
* We had a tox environment and a Make task for Django 1.9, but it wasn’t being used anywhere.
* We didn’t have any testing for Django 1.10.
> Add CI testing for Django 1.9/1.10

- src/hypothesis/core.py
- src/hypothesis/internal/reflection.py
- src/hypothesis/strategies.py
- tests/cover/test_reflection.py
This means that when a strategy is wrapped with `@composite`, we
preserve the docstring of the original function.
Fixes #422.
> Preserve a function's docstring with copy_argspec

- Makefile
- setup.py
- tox.ini
Resolves #380.
As pointed out in the issue notes, the tests fail if you run them under pytest 2.6 and 2.7, and they’re no longer run in Travis anymore.
Dependencies should go forward – pytest 2.8 is ~18 months old, putting in the effort to get these old versions of pytest working again is a waste of time.
> Remove old versions of pytest

- src/hypothesis/_settings.py
Whilst working on the Reproducible Builds effort [0], I noticed tha
python-hypothesis could not be built reproducibly. This happens because the
current working directory is embedded into the documentation (and then into
the searchIndex.js file too):
│  in which case no storage will be used.
│ -default value: &#8216;/build/1st/python-hypothesis-3.6.1/docs/.hypothesis/examples&#8217;</p>
│ +default value: &#8216;/build/python-hypothesis-3.6.1/2nd/docs/.hypothesis/examples&#8217;</p>
│  </dd></dl>
It seems this was introduced in 23562adc2417c6c6722a56f8f22cc400c473cd59.
[0] https://reproducible-builds.org/
Signed-off-by: Chris Lamb <chris@chris-lamb.co.uk>
> Make the build reproducible

- .travis.yml
* Sort the Python versions in `matrix` into a more natural order
* Sort the excluded OS X jobs into the same order as `matrix`, for
easier comparison
* Don't bother excluding the `check-examples2` and `check-examples3`
job on OS X, as those tasks no longer exist.
---
This change brought to you by “wait, you only have a Python 3.4 Travis job… no wait, they’re just in a weird order”.
> Tidy up the Travis config and Makefile

- .travis.yml
- appveyor.yml
This is a bit of a speculative PR and I'd like to discuss it before merge.
Travis has an annoying behaviour for pull requests where it builds each pull request twice: Once for the branch, once for the merge commit.
Given Hypothesis's painfully slow builds this is rather frustrating.
As [per the Travis documentation](https://docs.travis-ci.com/user/customizing-the-build#Building-Specific-Branches) we can turn this off and only have it build master. This should still build pull requests, or at least it was the suggested fix for https://github.com/travis-ci/travis-ci/issues/1147.
Do you think this is a good idea? It solves quite an annoying problem but I don't know how annoying not having the CI builds for our branches when we're working on them will be. It would be nice to be able to …
> Restrict CI to only building the master branch

- .travis.yml
- scripts/basic-test.sh
This reduces the amount of tests we run on Python 3.4 and 3.5 to try to reduce build times. The full tests still run on 3.6.
> Reduce amount of time spent testing old Python 3 versions

- scripts/basic-test.sh
Spotted while reviewing #448.
Hypothesis no longer supports Python 2.6, and if you try to run the tests (or this script) with Python 2.6, it will crash and burn long before this runs to completion. Thus these checks are redundant, let’s make the code a bit tidier.
> Remove a bit of Python 2.6-specific build code

- .travis.yml
This has two main purposes:
* Put 3.6 earlier in the matrix now that it's the only Python 3 that we run full tests on.
* Make the important jobs / less important jobs distinction more obvious
> Reorder some travis tasks.

- tox.ini
This causes pytest to print out the durations in seconds of each of the 20 slowest tests in a run. This will hopefully be useful in trying to track down why builds sometimes randomly take four times as long as usual: It might not be a test that's doing it, but if it's not this will help rule that out.
We'll see a lot more than 20 timings out of this because we invoke pytest in a number of different times and places, but I don't really have a problem with that.
> Print durations of slowest tests

- CONTRIBUTING.rst
I’m pretty sure that “tyop” was intentional, but “Of” wasn’t. :-)
> Fix the unintentional typo

- src/hypothesis/internal/compat.py
- src/hypothesis/internal/conjecture/engine.py
- src/hypothesis/internal/conjecture/minimizer.py
- tests/cover/test_conjecture_engine.py
This is some work extracted from my ongoing work on the new backend. It makes the shrinker a fair bit faster by some more judicious choices of shrinking - there is less wasted work and bigger shrinks are achieved faster.
It has three major features:
1. A bunch of tuning of the lexicographic minimizer. In particular this removes a bunch of bulk operations that always performed a lot of attempted shrinks and rarely worked, and generalises the ddmin stuff to a set of operations that seem to do a good enough job most of the time.
2. Better duplication of blocks in the main engine - a new pass which tries many clones at once on the off chance that they'll succeed.
3. Move the whole buffer lexicographic shrink later in the process so it's not doing a lot of duplicated work.
The following is the …
> Some optimizations to the shrinker

- scripts/basic-test.sh
- src/hypothesis/searchstrategy/deferred.py
- src/hypothesis/searchstrategy/recursive.py
We use deferred strategies all over the place. Unfortunately this
means a lot of indirection. Python is not very good at optimising
indirection.
This patch allows us to transparently ignore most of that
indirection by unwrapping all strategies before we create the
"real" underlying strategy.
Informal benchmarking suggests it helps some of the example
quality tests (which run draw() a lot of times) about 10-20%, but
this is obviously not that reliable.
> Deferred strategies should unwrap their arguments

- tests/cover/test_conjecture_engine.py
This has become slightly flaky - I've seen it fail on a few recent
builds. I think this is a mix of the new timing changes and the
new improvements to the shrinker.
This makes the example slightly harder to shrink and removes the
timeout, which should make the test more reliable.
> Make test_terminates_shrinks more reliable

- tests/quality/test_shrink_quality.py
Now that we're "running time faster" this test seems to sometimes fail
at the generation stage with NoSuchExample.
Adding a min_size parameter there means that it should stop doing that.
While in the area I noticed we're now much better about shrinking this
example so I also added stronger assertions about the result.
> Make another example quality test more reliable

- scripts/basic-test.sh
The version check in #448 was wrong (missing bracket), so old Python 3 versions are still running the full suite of tests. Oops.
This should fix that. Let's double check the Travis build before merging to make sure this time.
(I have no idea how we would have tested for this except manually)
> Fix syntax in check for Python versions

- src/hypothesis/internal/conjecture/engine.py
- src/hypothesis/internal/conjecture/minimizer.py
- tests/cover/test_conjecture_engine.py
This removes two passes from the shrinker:
* the ddsub pass in the lexicographic minimizer that subtracted 1 from each byte
* the interval replacement pass
These turn out to be the source of at least one flaky test in test\_example\_quality (the large union test) - both of them would occasionally get stuck there and produce bad shrinks:
* In the ddsub pass it would suffer from a problem of too many shrinks - it would perform a lot of small shrinks instead of the more desirable few numbers of large shrinks.
* the interval replacement pass was largely useless for this test but still ended up taking up a lot of time
Moreover both of these passes appear to be unneeded. The ddsub pass is mostly redundant with the later attempts to shrink individual indices, which work better because they tend …
> Remove some problematic shrinker passes

- .travis.yml
We'd like to run as little on OSX as possible, as the Travis
builds for it are very slow. Thus it makes sense to whitelist
rather than blacklist which jobs should run on it.
(Note: I'm not 100% sure this is the right syntax and will need to see what Travis does)
> Switch to explicitly whitelisting tasks for OSX

- docs/details.rst
Otherwise ReST converts `--` to a unicode dash.
> Formatting for CLI arguments

- src/hypothesis/extra/pytestplugin.py
Otherwise running pytest with --strict (which is done by hypothesis' tests
already) with the current features branch of pytest will fail.
> pytest: Register hypothesis marker

- .gitignore
- .travis.yml
- Makefile
- setup.py
- tests/django/toys/settings.py
- tests/django/toys/urls.py
- tox.ini
This may shed light on the issues we’re having in #488. If not, it would be good to do this anyway.
On an entirely separate note, it looks like [Django 1.7 has been out of support](https://www.djangoproject.com/download/) for over a year, but we still test it in CI. Time to drop it?
> Start testing with Django 1.11

- .travis.yml
- Makefile
- tox.ini
We swapped out fakefactory for Faker a while ago, but we still have tests that pin specific versions of fakefactory.  This is a pointless test – switch to tests that pin faker instead.
> Tidy up Faker-related tests in CI

- Makefile
- scripts/install.sh
- tox.ini
Depending on the phase of the task being run and the phase of the
moon, we were previously using one of Python 3.4.3, Python 3.5.1 or
Python 3.6.0 for our Python 3. This is silly and we should stop.
This updates everything to run on Python 3.6.1.
In particular:
* We now configure the best python 3 version in a single variable in the makefile
* We use tox's default of running with the same python it was launched with so we don't have to specify it in tox.in
This could use some followup work for making sure that when new Python versions come out we update our builds to use them, but I'm not going to do that now.
> Rationalize which version of Python 3 we use

- src/hypothesis/core.py
- src/hypothesis/internal/compat.py
- src/hypothesis/internal/conjecture/engine.py
- src/hypothesis/internal/escalation.py
- src/hypothesis/internal/floats.py
- src/hypothesis/searchstrategy/numbers.py
Hey, so you know how we have that flaky test for interleaving engines?
Did you notice it was only flaky on Python 2.7? (I didn't).
It turns out that this is because shrinking doesn't work properly on Python 2.7. Oops. There are a number of mishaps where we have str where we meant to have hbytes (AKA something that actually behaves like bytes behaves on Python 3), and this was resulting in doing the wrong thing entirely.
This pulls out some of my changes from #498 which tighten up on this by raising an error when you try to mix str and compatbytes. This flushed out a few places we were doing this, which this also fixes.
> Prevent mixing str with compatbytes on Python 2.7

- tests/quality/test_discovery_ability.py
As Hypothesis evolves (e.g. with #498) the mental model of it as repeatedly drawing independent examples becomes increasingly false, and it becomes increasingly meaningless to think about "how often" an event occurs as Hypothesis seeks out new and different examples.
This makes the statistical distribution tests very finicky and a millstone around our necks, limiting the ability of the system improves. That makes them bad tests.
It's also never been *really* clear how predictive they were about Hypothesis's bug finding ability, especially with the exact probabilities.
This PR replaces with something that is still quite ad hoc but at least more intuitively corresponds to Hypothesis's capabilities: How often it finds at least one example satisfying a condition in a "standard" run. These …
> Statistics? Pah! Who needs 'em?

- Makefile
- scripts/tool-hash.py
Apparently git is very timestamp happy and keeps touching tools.txt
even if it hasn't changed (and doesn't set mtime based on commits
like I thought it did). This means that the makefile repeatedly
ends up blowing away our tools virtualenv, which takes a long time
to reinstall.
This changes that approach by giving the tools virtualenv a name
based on the hash of the current contents of requirements/tools.txt
and removing the time dependency. That means that every time the
file actually changes we'll get a new tools virtualenv, but as long
as its contents remain the same we'll keep the same stable name and
not have to rebuild.
> Give tools virtualenv a unique name per reqs

- src/hypothesis/core.py
- tests/cover/test_given_reuse.py
This allows us to reuse the given decorator for multiple calls.
I'm reasonably sure this bug dates back to 2013.
> Don't mutate arguments to given.

- src/hypothesis/internal/conjecture/utils.py
- src/hypothesis/searchstrategy/misc.py
- src/hypothesis/strategies.py
- tests/cover/test_sampled_from.py
- tests/nocover/test_descriptortests.py
Closes #423.  Closes #221.
As an implementation detail, sampled_from and choices strategies converted input values to a tuple to allow index-based selection; which did not maintain a reproducible order for sets etc.  This pull attempts to sort unordered collections by value ~~and falls back to comparing hashes before explicitly throwing if that also fails~~.  This is largely for discussion, to replace vaguer comments I was drafting on the linked issues.
> Allow reproducible examples when sampling from sets

- src/hypothesis/core.py
- tests/cover/test_random_module.py
The motivation for seeding the random module in tests (which remains)
is that this is a great source of people writing tests with
nondeterminism that is not under Hypothesis's control and then
blaming Hypothesis for the inevitable confusing behaviour. We used
to have a health check that complained about that, but it basically
just annoyed people because most of the time this was happening
deep in the bowels of something they were depending on.
On the other hand, doing this for every test causes a lot of annoyances
too - it makes examples look distinct when they're not, slows things
down, and generally is a constant small annoyance that can trip us
up.
So instead we implement a convenient halfway house: If we're not asked
to seed the random module explicitly, we just seed it to zero. This …
> Do not seed random.module from data by default

- src/hypothesis/strategies.py
Spotted that `uuids()` wasn't documented either.
Resolves #521.
> Make sure the data() and uuids() strategies are documented

- tests/cover/test_arbitrary_data.py
I haven't been able to reproduce #523 locally, but this test change should validate my hypothesis that this is occasionally triggering some sort of internal assertion error if and when it fails on CI.
> Switch test to ValueError

- src/hypothesis/core.py
- src/hypothesis/internal/conjecture/data.py
- src/hypothesis/internal/conjecture/engine.py
- src/hypothesis/internal/conjecture/utils.py
- src/hypothesis/searchstrategy/collections.py
- tests/cover/test_completion.py
- tests/cover/test_conjecture_engine.py
- tests/cover/test_duplication.py
- tests/cover/test_random_module.py
This lets us do two important things:
* We can avoid testing duplicate buffers, both during generation
and shrinking.
* When shrinking we can additionally avoid testing any buffers
that are a prefix of a buffer we've already tried (which will
result in an overrun).
This is partly intended as a performance improvement, partly intended
as a data quality improvement. The data quality improvement is
straightforward: In cases where we previously wasted our example
budget on duplicates, we now don't.
The performance improvement in our
own tests is mild to non-existent, but that's because the actual
functions under test are quite fast. For things where that's not
the case, this should be a significant improvement. I especially
expect it to be useful for stateful testing.
Another small change …
> Track a tree of where Hypothesis has explored

- .travis.yml
According to [the Travis documentation](https://docs.travis-ci.com/user/customizing-the-build#Deploying-your-Code) the condition should be something that goes in a bash \[\[ \]\].
Rather than doing that, this instead makes it a before_deploy script. If this exits with a non-zero code then the build will error (which I think is correct behaviour) and the deploy won't run.
> Use make in before_deploy instead of condition

- scripts/hypothesistooling.py
The deploy almost worked then failed at the last hurdle: https://travis-ci.org/HypothesisWorks/hypothesis-python/jobs/224103554
We're adding a deploy key that can push to github, but then we're not actually using it because this is cloned from the HTTP URL! This PR fixes that by adding a remote for the ssh URL and using that to push.
It turns out that writing software you can't test is hard.
> Push to SSH instead of HTTP

- scripts/hypothesistooling.py
The latest obstacle to getting this new deployment stuff working: ssh-agent whines about our deploy key having too generous permissions. This fixes that by chmodding it first.
> chmod the deploy_key first so we don't get yelled at

- requirements/tools.txt
The latest failure of the deployment code: https://travis-ci.org/HypothesisWorks/hypothesis-python/jobs/224246289#L274
I'm 99% certain this is because we have an old version of setuptools there. It turns out pip freeze omits packaging related packages by default, so our version of setuptools is unpinned. This fixes that.
> Add packaging deps to requirements/tools.txt

- scripts/deploy.py
Apparently I wrote --sdist-dir when I meant --dist-dir.
Additionally this moves the sdist building to happen unconditionally before we start waiting for other things. This makes it easier to spot bugs in the process.
> Fix the typo that is currently breaking the deploy

- docs/changes.rst
- scripts/check-ancient-pip.sh
- setup.py
- src/hypothesis/version.py
Apparently #495 broke install on debian stable because people use ancient system provided pip and setuptools which can't handle wildcards in extras_require. 😭 
This PR:
* Fixes our test for old versions of pip to run the same version of setuptools and pip found in current debian stable (I verified manually that this reproduces the bug)
* Reverts #495 - I really doubt anyone is install hypothesis for django with the hypothesis[django] extra who does not already have django installed, so I think this is harmless.
* Updates the version and changelog (even though there is no code change so this is not required) so we can release 3.7.2 and fix that.
> Fix install on debian stable and release 3.7.2

- .travis.yml
- Makefile
- scripts/deploy.py
First item in #551
Every time I encrypt a new file this causes Travis to change its decryption key. This means that under the recommended way of decrypting (in a before\_install) *every single job in every single branch will start failing*.
This change instead localises those failures to the deploy task by running the decryption from the makefile. This will still be slightly annoying but I think is reasonable for detecting problems in the deployment before merge.
> Move secret decryption to deploy task

- docs/changes.rst
- src/hypothesis/core.py
- src/hypothesis/internal/reflection.py
- src/hypothesis/version.py
- tests/pytest/test_fixtures.py
I couldn’t find any tests for our interactions with pytest fixtures, so I wrote a few.
This will fail, as it exposes the bug raised in #560.
> Fix interactions with pytest fixtures

- scripts/check-changelog.py
- scripts/hypothesistooling.py
This makes a couple of changes to the build which are currently blocking e.g. #565, #566 and #563.
The core theme is that things that don't make changes to source code do not require a new version, but the checks aren't always good at realising that. In particular:
* check-changelog was checking unconditionally for the date, which it only needs to do if the current version hasn't already been released! (Or, given the version check, just whether there are source changes)
* detecting source changes was just looking at the diff between this and the last version, where it should have been looking at the diff with the last common ancestor of the current branch and the last version.
It also makes some minor changes for cleanup and debugging in the area (e.g. added a default to …
> Update checks to better handle no source changes

- Makefile
- docs/conf.py
- examples/test_binary_search.py
- examples/test_rle.py
- scripts/files-to-format.py
- scripts/hypothesistooling.py
- setup.py
You've probably noticed that format has become intolerably slow. Or you may not have because it's been intolerably slow for a while, so this might just seem normal to you.
Anyway, this mostly fixes this problem by changing the logic so that format only runs on files that have been modified since the last released version (unless the header or tools.txt have changed in which case it runs on everything). You can force the old behaviour by setting a FORMAT\_ALL environment variable.
The natural way of writing this also had the knock on effect that our formatting runs on *every* tracked Python file unless it's explicitly blacklisted. I think that's the correct behaviour, but it resulted in a number of files that were previously not formatted now being. I decided to force those to format all …
> Only run format on files that have changed

- tests/pytest/test_capture.py
- tests/pytest/test_runs.py
unicode\_literals used to be part of our default future header, but they turn out to be an attractive nuisance and make it harder rather than easier to write correct cross-version code.
Apparently they'd lingered in precisely two places. I don't know why. I think our isort based import management doesn't remove futures, only adds them, so they were allowed to remain.
We could lint for this if we wanted to but I don't think it's worth the effort, so this is a simple PR removing the last two I found in the code (via git grep)
> Don't use unicode literals

- scripts/deploy.py
Fixes #561 (I think) and thus unblocks #536 I think
The problem is that the secure environment variables aren't defined when the pull request is coming from outside the main repo. [The documentation](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables) says we can test this with TRAVIS_SECURE_ENV_VARS, so that's what this change does: Have the deploy pass just skip entirely if the secure vars aren't defined.
> Don't attempt to run deploy when we don't have secure vars

- docs/changes.rst
- src/hypothesis/internal/compat.py
- src/hypothesis/strategies.py
- src/hypothesis/version.py
- tests/cover/test_custom_reprs.py
- tests/cover/test_direct_strategies.py
Adds an `iterables()` strategy to close #135.  It's basically `st.lists(...).map(iter)`, but with a nicer `repr`.  Imagine trying to debug a falsifying example from `<list_iterator at 0x7c1e567518>` instead of `iter([1, 2, 3])`!
> Simple iterables strategy

- Makefile
- docs/details.rst
- docs/extras.rst
- docs/settings.rst
- docs/stateful.rst
Turns out flake8 is perfectly happy to lint files that don’t contain any Python. This patch tells it just to look for whitespace errors, nothing else.
Resolves #559.
> Add whitespace linting to docs

- scripts/hypothesistooling.py
As we saw with [this build](https://travis-ci.org/HypothesisWorks/hypothesis-python/jobs/224911202) there's currently a race condition where if you merge a new thing to master before the old one has finished running its build, the deploy code would detect that it wasn't master and refuse to deploy!
This weakens the check to assert only that the current build is an *ancestor* of master. i.e. it has already been merged in. This should be the actual semantics we want: Everything merged (that has a source change) will deploy, everything not merged won't.
> Check only that we are an ancestor of master

- Makefile
- docs/changes.rst
- docs/conf.py
- docs/data.rst
- src/hypothesis/strategies.py
- src/hypothesis/version.py
Closes #533, closes #320.
This pull skips doctests for functionality under `extra`, because they often depend on package versions or require much more setup than is worthwhile in doctests.  I'm OK with this, because the motivation was things like people attempting `streaming(integers()).example()` - per the docs - and discovering that it raises an exception.  Also skips rectangle lists per #581, as the shrink is flaky as well as suboptimal.
I'm using Sphinx's doctest runner because it has the best control of discovery that I've found, and allows us to reseed the random module before each doctest group.  This prevents the problems with other runners where execution order means different output, or changing one group invalidated all other output too.
@DRMacIver, I'd appreciate it if you …
> Check examples in docstrings

- scripts/benchmarks.py
Two small fixes:
* Some benchmarks can produce constant data (this doesn't happen in any of the current ones with the current implementation, but I've seen it in some experiments). This currently produces a p-value of NaN. This updates it to check those benchmarks manually as having identical constant values and skipping them.
* The code was catching StopTest. I'm not sure why I thought that was a good idea, but it's certainly not necessary and is kinda naughty (I think harmless though). This removes that and adds the data in a finally block.
These are entirely independent but I'm being lazy and bundling the two line change for StopTest in with the other more interesting one. Feel free to yell at me if this bothers you and I'll split it out.
> Some small benchmarking fixes

- docs/changes.rst
- scripts/deploy.py
- scripts/hypothesistooling.py
See #589 - deploys currently think they're not on master when they are.
This updates the master check to use "git merge-base --is-ancestor", which is hopefully more correct.
It's obviously a little hard to test this without actually deploying, but this should work.
> Hopefully fix deployment

- .coveragerc
- tests/common/__init__.py
- tests/common/debug.py
- tests/quality/test_shrink_quality.py
This turns timing out in shrinking in our shrink quality tests into
an error.
Some of these tests errored. They got made either easier or just
deleted if I judged they were unimportant. In general, these tests
are a bit artificial and I think where they fail we might just want
to lower the bar on shrink quality until we see some real world
impact.
This is extracted from #580, but I thought it could use some independent review and discussion.
> Raise an error when minimal times out

- .travis.yml
This should unblock #575.
Plus it means that if isort/pyformat change, we pick up the new results immediately, rather than when we next edit those files.
> Always check-format of all files when running in CI

- tests/quality/test_shrink_quality.py
You know that thing where you get frustrated with your test suite and want to delete all of it? This is that PR.
The purpose of this PR is a *really* brutal cull of tests/quality/test_shrink_quality.py
A justification of my actions follows:
I've been doing a lot of benchmarking related work recently. It goes roughly like this:
1. I find some *really* suboptimal behaviour where Hypothesis is doing way more work than it needs to.
2. I replace it with something simple and faster and the benchmark suite thanksk me.
3. Some weird test case that I dreamed up four years ago to showcase how clever I was being fails
4. I get annoyed and try to fix it.
5. Oh god there are worms everywhere why did I even open this can?
The fact is, most of the shrinking tests in this file don't come from *anywhere* …
> Relax some of the weirder constraints on Hypothesis shrinking

- tests/cover/test_lambda_formatting.py
- tests/cover/test_reflection.py
`sed -i "" 's/  # pragma: no cover$//' tests/cover/*`
This is the follow up PR from #481
> Remove unused pragma: no cover

- docs/changes.rst
- src/hypothesis/extra/pytestplugin.py
- src/hypothesis/version.py
Fixes #611
This version check tests for a version of pytest that is > 2 years old, and the check has been a frequent source of breakage for pytest's use of Hypothesis. Lets just remove it.
> Remove pytest version check

- scripts/check-changelog.py
I just had the changelog for #508 (proposed version 3.9.0) merged to below the changelog for new release 3.8.3, so I thought our check should look at order as well as existence.  And uniqueness.  And that we didn't skip a valid version number.
> Ensure that changelog entries are ordered

- docs/changes.rst
- docs/conf.py
- src/hypothesis/internal/conjecture/utils.py
- src/hypothesis/version.py
- tests/cover/test_sampled_from.py
A tiny compatibility fix for `sampled_from`, allowing Enums without a deprecation warning.  Closes #595.
Uses the current year (in UTC) for the sphinx copyright notice.
> Sampling fix

- docs/changes.rst
- scripts/check-changelog.py
Because that only works when they all have the same number of digits between each dot.  Whoops.
Also a better error message for unsorted entries.
> Compare version numbers as Tuple[int], not strings

- docs/changes.rst
- docs/supported.rst
- src/hypothesis/_settings.py
- src/hypothesis/database.py
- src/hypothesis/version.py
Still a single import, but this way it's only attempted if you're actually using a sqlite example database.  IMO it is better to raise an import error if you attempt to use sqlite than to change the database selection logic depending on whether it is installed.  Closes #173.
> Import sqlite3 only if used; minor bugfixes

- docs/changes.rst
- src/hypothesis/core.py
- src/hypothesis/internal/compat.py
- src/hypothesis/internal/reflection.py
- src/hypothesis/searchstrategy/deferred.py
- src/hypothesis/strategies.py
- src/hypothesis/version.py
- tests/cover/test_reflection.py
- tests/nocover/test_compat.py
- tests/py3/test_annotations.py
This allows us to support keyword-only arguments and defaults in various places, as well as passing through function annotations.  Closes #290.  It's also part of the foundation for 167 and eventually 293.
Needs review by @DRMacIver, because it's scary internals stuff.  I also need to move most of the tests to a new file for Py3 reflection tests.
> Upgrade introspection to use getfullargspec

- docs/changes.rst
- src/hypothesis/core.py
- src/hypothesis/version.py
- tests/pytest/test_capture.py
Timeouts and health check failures currently generate large and
unhelpful verbose failure messages. Using tracebackhide prevents our
internal helpers from being shown in the detailed traceback view.
See http://doc.pytest.org/en/latest/example/simple.html#writing-well-integrated-assertion-helpers
> Use pytest __tracebackhide__ for better error output under pytest

- docs/changes.rst
- src/hypothesis/internal/conjecture/utils.py
- src/hypothesis/version.py
- tests/cover/test_sampled_from.py
Fairly simple patch – just extend the list of types we exclude from the warning about un-replayable collections.
Resolves #688.
> Ensure we can sample from an OrderedDict without a warning

- tests/numpy/test_gen_data.py
When building for Arch repos we are currently failing test_can_minimize_float_arrays 10 times in a row. Simply adjusting max_runs here passes the tests here. I don't know if it's acceptable to do this upstream, thanks.
> Try harder to pass test_can_minimize_float_arrays

- tests/cover/test_datetimes.py
- tests/datetime/test_dates.py
- tests/datetime/test_datetime.py
- tests/datetime/test_times.py
- tests/datetime/test_timezones.py
Several tests used `find` or `minimal` without asserting anything about the result, solely to demonstrate that such examples exist.  Using `s.filter(predicate).example()` is much more efficient, and should eliminate a common source of timeouts, especially for pypy.
> More efficient tests for datetimes

- appveyor.yml
- docs/changes.rst
- src/hypothesis/version.py
This improves our deploy process by having appveyor build wheels and upload them to pypi when it's building a tag.
Context: In the future I will want us to start shipping C extensions. This is unfortunate for Windows users who may not have a C compiler installed, so we're going to need to build wheels for them.
This is the first stage of that. We're still Python source only, but we can at least start building wheels. I doubt this will improve anyone's lives much, but it will at least make install from pypi very fractionally faster.
This also:
* makes appveyor build on tags as well as on master.
* updates and expands the range of versions we test on appveyor.
> Build wheels on appveyor

- appveyor.yml
[Apparently CMD_IN_ENV doesn't work in powershell](https://ci.appveyor.com/project/DRMacIver/hypothesis-python/build/1.0.1287/job/bl1cum9h4t143fpj#L1960).
This is somewhat speculative but should work. I have hand cranked wheels out for the release that failed, so nothing is currently on fire. I guess we'll find out if this works properly next release?
(The major concern here is I'm not really sure that Python  is on the path there, but I think it should be)
> Fix wheel building

- Makefile
See #710 for details. Basically right now doctests force a large amount of manual work that should be completely automatable on almost every change I make to data generation, or the documentation thereof.
I care about being able to actually do work on Hypothesis more than I care about having our examples be perfectly up to date (especially for things that are really just changes in which random path you happened to take), so until we come up with a fully automated solution for updating these examples, I don't want this in the build.
I am more than happy to revert this when we figure out a solution to #711, and am quite sad to remove it, but until we come up with a proper solution I think this is the best way forward.
> Don't run doctests until #711 is resolved

- appveyor.yml
This just disables Appveyor builds on every branch that isn’t master – we don’t actually have any official version branches (unless they’re hiding?), but this regex was doing builds for pushes to pyup branches, which have the form
```
pyup-update-dependency-x.y.z-to-a.b.c
```
and I think the version number was matching the regex.
No effect on Hypothesis itself, just a benefit for maintainers that we’ll have slightly less contention for Appveyor builds.
> Only build Appveyor pushes to master, not PR branches

- docs/changes.rst
- src/hypothesis/core.py
- src/hypothesis/version.py
- tests/cover/test_skipping.py
- tests/pytest/test_skipping.py
Closes #514; based on / closes #515.
This is a separate pull mostly to see if the tests pass on this one without rebasing away Alex's work.
> Honour 'skip test' exceptions

- docs/changes.rst
- docs/data.rst
- docs/details.rst
- guides/documentation.rst
- src/hypothesis/__init__.py
- src/hypothesis/core.py
- src/hypothesis/errors.py
- src/hypothesis/internal/compat.py
- src/hypothesis/internal/reflection.py
- src/hypothesis/searchstrategy/types.py
- src/hypothesis/strategies.py
- src/hypothesis/utils/conventions.py
- src/hypothesis/version.py
- tests/cover/test_given_error_conditions.py
- tests/cover/test_type_lookup.py
- tests/py3/test_lookup.py
Closes #293.  This pull:
- adds a new function `from_type` to look up a strategy that can generate instances of the given type
- upgrades `builds()` to infer missing arguments based on type hints
- upgrades `@given` to infer missing arguments from type hints
- adds a new function `register_type_strategy` to register custom types that can't be automatically derived (based on a known child class or type hints, using `builds`)
It's been a long time coming, but I think I'm done.  (again 😉)
> Strategies from type hints, and inference of missing arguments to builds() and @given()

- docs/changes.rst
- src/hypothesis/internal/conjecture/data.py
- src/hypothesis/version.py
- tests/cover/test_regressions.py
As per title, fixes #751 
What's going on here:
In implementing the recursion support I basically picked an arbitrary number as the greatest depth it was likely to be "reasonable" to hit. Apparently I underestimated how much @mithrandi liked using `@composite`, which ends up wrapping things a lot and pushing up the depth, making it hit that `MAX_DEPTH`.
Compounding that is the fact that `min_size=1` does not currently play well with the max depth constraints, which is why it was producing an overflow in that case. I have a branch which fixes that, but it's more work and in that case we would *still* want to avoid the depth bounding case (which is what the additional test in `test_regressions` is for).
It might be good to do some better error handling in the case where the minimal example …
> Raise MAX_DEPTH to fix Issue #751

- docs/changes.rst
- docs/healthchecks.rst
- docs/settings.rst
- scripts/unicodechecker.py
- src/hypothesis/__init__.py
- src/hypothesis/_settings.py
- src/hypothesis/core.py
- src/hypothesis/version.py
- tests/common/setup.py
- tests/cover/test_conjecture_engine.py
- tests/cover/test_core.py
- tests/cover/test_database_backend.py
- tests/cover/test_database_usage.py
- tests/cover/test_datetimes.py
- tests/cover/test_find.py
- tests/cover/test_given_error_conditions.py
- tests/cover/test_health_checks.py
- tests/cover/test_integer_ranges.py
- tests/cover/test_settings.py
- tests/cover/test_testdecorators.py
- tests/cover/test_timeout.py
- tests/datetime/test_datetime.py
- tests/nocover/test_collective_minimization.py
- tests/nocover/test_git_merge.py
- tests/nocover/test_recursive.py
- tests/nocover/test_strategy_state.py
- tests/pytest/test_statistics.py
As per #534, timeout is a major source of flakiness for end users. It also significantly complicates our lives.
This pull request deprecates it as functionality.
The intended behaviour is:
* Users who are not currently running into the timeout in their tests or configuring it in any way will see no difference
* Everyone else will get deprecation warnings either when they set it or when their tests actually run into it
* People who want to default to the new functionality can do `settings(timeout=unlimited)` (unlimited being a new special value from Hypothesis which we will use in a few other places). This will not trigger a deprecation warning.
* Once timeout has been removed entirely (in some unspecified future version) `settings(timeout=unlimited)` will start emitting deprecation …
> Deprecate timeout feature

- docs/changes.rst
- src/hypothesis/database.py
- src/hypothesis/internal/compat.py
- src/hypothesis/internal/conjecture/data.py
- src/hypothesis/internal/conjecture/engine.py
- src/hypothesis/internal/conjecture/utils.py
- src/hypothesis/searchstrategy/collections.py
- src/hypothesis/strategytests.py
- src/hypothesis/version.py
- tests/common/debug.py
- tests/cover/test_database_usage.py
- tests/nocover/test_large_examples.py
This is extracted from some upcoming work of mine that I realised made sense on its own.
It fixes the issue pointed out in https://github.com/HypothesisWorks/hypothesis-python/issues/751#issuecomment-319698767 that a large `min_size` on collections is still somewhat problematic. It will loop infinitely if it's still not reached `min_size` by the time it's forced to draw only zeroes. It also fixes #724 because I was in the area.
The key idea of it is to change write so that it actually modifies the output data rather than relying on the right data being there to draw. This has a few knock on changes to the engine (`rewrite_for_novelty` now needs to detect when this has happened and fast forward accordingly, tree usage changes a bit, and sometimes we can expect to get a shrink and actually …
> Change data.write() to modify the data stream

- docs/changes.rst
- docs/settings.rst
- src/hypothesis/_settings.py
- src/hypothesis/core.py
- src/hypothesis/internal/compat.py
- src/hypothesis/internal/conjecture/engine.py
- src/hypothesis/version.py
- tests/cover/test_database_usage.py
- tests/cover/test_phases.py
This pull request contains three distinct changes, so I could split it up if you want, but they're all quite closely related and really what it contains is the one change I wanted to make and the two that got in the way of it:
1. The principle thing it does is make some major changes to how we replay examples from the database. I'll go into that below.
2. In the course of doing that I realised that the way that we handled `Phase.reuse` was completely backwards and fixed that.
3. In the course of doing *that* I realised that the phases setting was completely undocumented, so I fixed that too.
The main idea of the database changes is that currently we have a problem that saved examples can overwhelm your testing. If you e.g have more than 200 shrinks of a previous failure (which can happen …
> Better management of the example database

- docs/changes.rst
- src/hypothesis/internal/conjecture/utils.py
- src/hypothesis/version.py
- tests/cover/test_simple_collections.py
This changes the implementation of `many()` so that when we've rejected too many elements we just stop drawing instead of marking the data as invalid (unless doing so would produce too small a result). It also relaxes the threshold at which it stops slightly.
Fixes #780
> Handle sets with few elements better.

- RELEASE.rst
- src/hypothesis/internal/conjecture/engine.py
This is a rather niche patch. It serves two purposes:
* Helping some of the performance problems @mithrandi has been having since 3.13.0 (on his experiments he reports that it makes things better but still not as good as they were previously)
* To serve as a trial run of #787 
The idea here is that bytes that we explicitly wrote don't really "count" for the purposes of the permutation step: They're going to get inserted into the stream in the appropriate place anyway, so we don't really want to spread them out. This is especially true because it can result in the number of non-zero bytes increasing in this step, which leads to problems.
Sadly I have no tests for this - it's a relatively subtle change that shouldn't actually affect behaviour much (watch famous last words as everything …
> Zero forced bytes before permuting examples

- .gitignore
- CONTRIBUTING.rst
- Makefile
- RELEASE.rst
- requirements/test.in
- requirements/test.txt
- src/hypothesis/core.py
- src/hypothesis/internal/reflection.py
- tests/cover/test_reflection.py
- tests/cover/test_regressions.py
- tests/pytest/test_fixtures.py
Fix bug where mocks can be used as test runners under certain
conditions. Specifically, if a mock is injected into a test via pytest
fixtures or patch decorators, and that mock is the first argument in the
list, hypothesis will think it represents self and turns the mock
into a test runner.  If this happens, the affected test always passes
because the mock is executed instead of the test body.
Specifics:
- Add a function to check for mocks by looking for random attributes
that would be EXTREMELY unlikely to occur in an object that isn't a
mock.
- Add a check in  to determine if the argument we think is
self is really a mock.  If that's the case, don't use it.
> Fix bug where mocks can be used as test runners

- Makefile
As @Zac-HD has pointed out, running rst-lint on RELEASE.rst means we can't use any sphinx cross-referencing features on it.
This is only part of what we need to do, as we also need CI to check that this doesn't break the documentation, but it at least unblocks us from releasing for now.
> Don't run rst-lint on RELEASE.rst

- RELEASE.rst
- src/hypothesis/internal/compat.py
- src/hypothesis/strategies.py
- tests/cover/test_direct_strategies.py
- tests/nocover/test_compat.py
Extracted from #777.  Turns an assertion into an InvalidArgument error, and adds a test to make sure it doesn't come back.
> Improved validation for integers() bounds

- appveyor.yml
As @Zac-HD points out, appveyor builds are one of the slowest part of our CI, and half or more of that time is 32-bit builds. This turns them off.
It *might* be worth having a 32-bit specific build on Linux or something, but at the moment the set of things we do that could break specifically on 32-bit is extremely small. I don't think this has ever caught something useful for us.
When we start building native extensions we might have to turn this back on, sadly.
> Turn off 32-bit builds in appveyor for now

- .pyup.yml
- Makefile
- requirements/test.txt
- requirements/tools.txt
This makes the following changes:
* Updates all of our requirements
* Adds a Make task to do that
* Downgrades pyup pull requests to weekly.
check-requirements isn't sufficient on its own, because it won't actually upgrade existing libraries, so we still need pyup, but this should significantly reduce the noise level until we have a better solution.
> Partial fix for our current pyup mess

- Makefile
- scripts/build-documentation.sh
- scripts/hypothesistooling.py
- scripts/update-changelog-for-docs.py
We run just enough of the release process to update the changelog before building documentation, then clean it up afterwards.
This fixes #795.
> Update changelog with RELEASE before building docs

- CONTRIBUTING.rst
- RELEASE.rst
- docs/strategies.rst
- src/hypothesis/internal/compat.py
- src/hypothesis/internal/escalation.py
- src/hypothesis/searchstrategy/regex.py
- src/hypothesis/strategies.py
- tests/cover/test_regex.py
- tests/nocover/test_regex.py
In what is definitely our longest chaining of passing the baton yet, I'm taking over #776 from @Zac-HD who took it over from @maximkulkin.
This has the following major changes from the point at which it was left off in #776:
* Groups are now correctly supported. We create a cache object for groups that is cleared at the end of the draw for the regex.
* Group if-then-else matches are now correctly supported: We look in the group cache for whether the group has been set and pick the branch appropriately.
* I have about-faced and decided that @Zac-HD was right and hoping to match the full string is a non-starter (I shall explain in detail below), but decided given that, just returning something that starts with a match does not go far enough! The defined semantics are now that the returned …
> Upstream hypothesis-regex 3: Tokyo Drift

- scripts/hypothesistooling.py
This makes two changes in an attempt to fix #808:
* It tries to push to master first, so if that doesn't work we don't get a half-baked deploy.
* If merges the push and tag into one command. I'm speculatively guessing that running ssh-agent twice in succession might somehow be the source of our problem (given that the push command does work on its own) and that merging it might help. I've no idea why that would be and the fact that for whatever hilarious reason we're not getting any output is not helping.
> Merge and reorder deploy commands

- RELEASE.rst
- src/hypothesis/internal/renaming.py
- src/hypothesis/searchstrategy/datetime.py
- src/hypothesis/strategies.py
- tests/cover/test_datetimes.py
- tests/datetime/test_timezones.py
So as part of #811 I realised that argument naming conventions in the new date and time strategies were inconsistent with other strategies in hypothesis.strategies, and in the spirit of #812 I thought I'd fix that so that the bounds were all `min_value` and `max_value`.
This takes the slightly unprecedented for Hypothesis step of making a change to a function signature that isn't just appending something to the end, however I believe it to be fully backwards compatible.
The cases we have to worry about:
* An argument may be passed positionally. This is fine: It goes to the new, non-deprecated, argument which has an identical function to the old argument in that position.
* An argument may be passed as a keyword, in which case it is passed to the old, deprecated, argument.
> Rename strategy arguments to min/max value for consistency

- RELEASE.rst
- src/hypothesis/core.py
Apparently when an `@example` fails it prints and extra traceback for no obviously good reason. It looks like this is some debugging code I put in there two years ago in 7f0768ad4b66c4eede439754bd98b5ddb5f47f71 and nobody has complained about it since.
Note: I haven't added and tests for this, because I'm a little unsure what a meaningful test for it that would actually catch other problems is. Maybe the right test is to add a line to the review guide that suggests looking for stray debugging code? But we're pretty good at that anyway and this predates our review process by some time.
(This PR also serves as a useful demonstration of the problem with our release process for Github support staff)
> Remove debugging stack trace

- docs/changes.rst
- docs/data.rst
- guides/review.rst
- scripts/build-documentation.sh
A bunch of broken refs and funcs have snuck in over the last couple of releases (almost entirely my fault I think but I haven't checked). This PR does three things:
1. Fix the specific mistakes we've made.
2. Fix the documentation building so that it doesn't try to undo your changes while you're editing the changelog (or, rather, so that it doesn't if you don't have a release file).
3. Update the review guide to highlight this issue and recommend manual inspection.
> Fix RST errors in changelog

- RELEASE.rst
- src/hypothesis/searchstrategy/deferred.py
- src/hypothesis/searchstrategy/recursive.py
- src/hypothesis/searchstrategy/shared.py
- src/hypothesis/searchstrategy/strategies.py
- src/hypothesis/searchstrategy/wrappers.py
This is an attempt at #799. It's not a very good attempt, but I think it will work.
You will note the absence of tests. This is because based on a bunch of investigation just now, this is a *really* hard problem to reproduce. I've not been able to get a test to reliably reproduce the problem despite some trying.
Based on this I'm 99% certain that the reason for this is that this is not an infinite recursion error, just a lots recursion error, and the difficulty with reproducing comes from there being less on the stack when I try, but working around that is fiddly.
Based on further investigation of what is on the stack at the time of this happening, I came to the conclusion that the reason this was happening is that in some highly specific circumstances we call `do_draw` directly rather …
> Speculative attempt to fix recursion errors in tests

- CONTRIBUTING.rst
- RELEASE.rst
- src/hypothesis/internal/charmap.py
- src/hypothesis/internal/compat.py
- tests/cover/test_charmap.py
If the cached pickle of the charmap data was corrupted in any way
initialisation would fail.
Now if a cache file cannot be found or read, it will be
regenerated. The logic is also slightly refactored, so we do not
need to write a file to disk, only to immediately read it back.
This will also help #768 by not depending on a file being written
to disk.
> Refactor charmap caching [Fixes #767]

- RELEASE.rst
- src/hypothesis/internal/renaming.py
- tests/cover/test_renaming.py
I’m a little surprised this code doesn’t have any tests around it (or if it does, I couldn’t find any).
Anyway, resolves #822.
> Don't throw a TypeError if renaming args in a function with no docstring

- Makefile
- RELEASE.rst
- docs/conf.py
- src/hypothesis/extra/numpy.py
- tests/numpy/test_gen_data.py
As part of #785 I'm doing a bunch of work with uniqueness.  I realised it would be *much* easier if the underlying numpy strategies supported uniqueness and would let me push some complexity down a level.
So this PR implements that. It adds a `unique` flag to the arrays strategy which behaves identically to the corresponding flag for `lists`.
Things to note:
* If a user sets `unique=True` given a non-hashable type, they will see a raw `TypeError`. Given that all of the common numpy types are hashable and the same is currently true for lists, I don't have a huge problem with this.
* It doesn't currently allow `unique_by` as lists do. I figured the use case for that was much less obvious with numpy arrays, but we could easily add it if desired.
> Add unique flag to arrays

- RELEASE.rst
- src/hypothesis/searchstrategy/lazy.py
- tests/cover/test_settings.py
Our LazyStrategy definition captures the current settings object and propagates it to when it's evaluated. This is mostly a vestigial thing where settings *used* to affect the individual strategies by controlling defaults but no longer does.
I tried to do this a while ago in part of a past pull request (I forget which. One of the deprecation ones I think) and wound up in a complete mess because the strict setting mattered for what happened with deprecation warnings in strategies. But we no longer have strict mode as of #728, so that should no longer matter and we can now remove this.
> Don't propagate settings into strategy definitions

- RELEASE.rst
- src/hypothesis/core.py
- src/hypothesis/internal/conjecture/data.py
- src/hypothesis/internal/conjecture/engine.py
This finishes off something I probably should have done in #710, which is to remove the distribution parameter altogether from the ConjectureData side.
This shouldn't have any impact on behaviour. We were effectively always passing 'uniform' as this parameter, so I've now just removed the parameter and replaced its usage with uniform everywhere.
> Remove vestigial distribution parameter

- RELEASE.rst
- src/hypothesis/searchstrategy/strategies.py
- tests/common/debug.py
- tests/cover/test_datetimes.py
- tests/cover/test_example.py
- tests/cover/test_regex.py
- tests/cover/test_simple_characters.py
- tests/cover/test_simple_collections.py
- tests/datetime/test_dates.py
- tests/datetime/test_datetime.py
- tests/datetime/test_times.py
- tests/datetime/test_timezones.py
- tests/nocover/test_recursive.py
- tests/nocover/test_strategy_state.py
As per discussion in https://github.com/HypothesisWorks/hypothesis-python/issues/832, use of `example()` inside tests leads to very confusing behaviour. This is because you're not supposed to use `example()` in tests at all, but the practice is nevertheless widespread.
This PR fixes the issue by causing this use of example to emit a deprecation warning. It's arguable that we could turn this into an error without that, and I'm probably going to be willing to turn it into an error later without bumping a major version, but I figure the deprecation warning gives people some time to adjust.
> Emit deprecation warnings on misuse of example

- RELEASE.rst
- src/hypothesis/core.py
- src/hypothesis/database.py
- src/hypothesis/errors.py
- src/hypothesis/internal/conjecture/data.py
- src/hypothesis/internal/conjecture/engine.py
- tests/common/utils.py
- tests/cover/test_conjecture_engine.py
- tests/cover/test_database_backend.py
- tests/cover/test_database_usage.py
- tests/cover/test_slippage.py
- tests/cover/test_stateful.py
- tests/nocover/test_database_agreement.py
There's a phenomenon often called "slippage" where when shrinking a bug results in finding another bug. This often happens with rarer bugs shrinking to more common ones.
This isn't a huge problem in practice for Hypothesis because the example database still saves the original failures and will replay them, but it's annoying. I ran into at least one example of it in debugging #785, which reminded me that I've been meaning to do some work on trying to avoid the problem.
So this is that work. It adds a notion of `interestingness_origin` to ConjectureData and forces the engine to shrink subject to the additional constraint that the origin is preserved.
For tests we use the somewhat imprecise but probably good enough partitioning that two failures are "the same bug" if they throw the same …
> Display all slipped errors found during shrinking

- RELEASE.rst
- src/hypothesis/extra/numpy.py
- tests/numpy/test_gen_data.py
This is just a very small extraction from #826 - it doesn't contain all of the fixes, just the ones for the datetime and timedelta resolution problems, as those were causing problems in testing #785.
All the correct part of this are @Zac-HD's, but I take full blame for any the mistakes. 😉
> Extract datetime resolution fix from #826

- RELEASE.rst
- src/hypothesis/database.py
- src/hypothesis/tools/mergedbs.py
- tests/common/utils.py
- tests/cover/test_database_backend.py
- tests/nocover/test_database_agreement.py
- tests/nocover/test_git_merge.py
Followup work from #836.
It turns out that the documentation already said this was deprecated, we just weren't emitting the warnings!
> Emit deprecation warnings for use of SQLiteExampleDatabase

- tests/common/debug.py
- tests/cover/test_deferred_strategies.py
- tests/cover/test_example.py
- tests/cover/test_map.py
- tests/cover/test_nothing.py
- tests/cover/test_one_of.py
- tests/cover/test_regex.py
- tests/cover/test_searchstrategy.py
- tests/cover/test_simple_characters.py
I decided to do a trial run of the algorithm for getting coverage time down I proposed in #852, but found that the most expensive tests were ones in test_regex.py for asserting unsatisfiability of certain conditions, and rather than wanting to move these tests to nocover there was just an obvious way to make them faster.
So this is that way. It provides a single unified helper to assert that no examples (possibly of a condition) exist. The main performance improvement comes from the fact that it runs substantially fewer trials than using `example()`, but it's also just nice to have a unified helper for doing this.
> Provide a unified helper for asserting unsatisfiability

- docs/django.rst
- tests/django/toystore/test_basic_configuration.py
Closes #846 the easy way, by suppressing the relevant check and suggesting that users do the same thing.
> Suppress 'too slow' healthcheck for TransactionTest

- RELEASE.rst
- docs/settings.rst
- src/hypothesis/_settings.py
- src/hypothesis/core.py
- src/hypothesis/errors.py
- src/hypothesis/internal/escalation.py
- tests/cover/test_conjecture_engine.py
- tests/cover/test_deadline.py
- tests/cover/test_health_checks.py
- tests/cover/test_randomization.py
- tests/nocover/test_deferred_strategies.py
- tests/nocover/test_floating.py
Slow tests are a major problem for property-based testing - they both significantly limit its utility and also make us look bad (performance is high up on the list of things I hear complaints about. Some of this is legitimate - Hypothesis data generation performance is quite bad in places - but a lot of it it's actually the tests that are slow).
With the deprecation of timeout (#580) this problem is going to only get worse because it's been made more visible to the user (which was the goal! Long-run this is a clear improvement).
This change is designed to ratchet up that visibility in a way that is actually actionable to users by showing them how slow their tests are and where they are slow. In particular because the deadline participates in the normal shrinking process, users can see …
> Add deadline feature to make slow tests an error

- RELEASE.rst
- src/hypothesis/_settings.py
- src/hypothesis/core.py
- src/hypothesis/searchstrategy/collections.py
- src/hypothesis/searchstrategy/numbers.py
- src/hypothesis/searchstrategy/strategies.py
- src/hypothesis/stateful.py
- src/hypothesis/tools/mergedbs.py
This started out as a pull request to remove the various Parameter classes that haven't been used in more than a year, but I figured that while I was in the area I might as well get rid of the rest of our uses of namedtuple too! Now that we depend on attrs we might as well use it.
This also rips out some very out of date docstring contents from SearchStrategy.
> Migrate usage of nametuple to attrs

- docs/conf.py
- docs/settings.rst
Closes #349 - output capture is properly a concern for the Pytest project, but we should document this as a common source of confusion.
> Note pytest stdout capturing in verbosity docs

- RELEASE.rst
- docs/examples.rst
- scripts/install.sh
- src/hypothesis/extra/pandas/impl.py
- src/hypothesis/internal/conjecture/data.py
- src/hypothesis/internal/conjecture/engine.py
- src/hypothesis/searchstrategy/collections.py
- src/hypothesis/searchstrategy/deferred.py
- src/hypothesis/searchstrategy/flatmapped.py
- src/hypothesis/searchstrategy/lazy.py
- src/hypothesis/searchstrategy/misc.py
- src/hypothesis/searchstrategy/strategies.py
- src/hypothesis/strategies.py
- tests/common/setup.py
- tests/cover/test_argument_validation.py
- tests/cover/test_deferred_strategies.py
- tests/cover/test_nothing.py
- tests/cover/test_reusable_values.py
I managed to trigger an `AssertionError` when writing a deferred strategy for something due to an unfortunate interaction. The problem example was the following strategy:
```python
literals = st.deferred(lambda: st.one_of(
st.booleans(),
st.tuples(literals, literals),
literals.map(lambda x: [x]),
))
```
The issue with this is that we change our minds midway through the calculation here as to whether literals can have reusable values, so we end up deciding that `tuples(literals, literals)` are reusable values but `literals` aren't.
The root cause here is primarily that the way we were handling recursive calculations of fixed points was, to be honest, super dodgy. This pull request fixes that, replacing it with a more sophisticated and fully accurate approach based on value propagation - …
> Switch to a more sophisticated calculation for strategy properties

- RELEASE.rst
- src/hypothesis/core.py
- src/hypothesis/extra/pytestplugin.py
- tests/cover/test_seed_printing.py
- tests/cover/test_testdecorators.py
- tests/pytest/test_pytest_detection.py
- tests/pytest/test_seeding.py
Users often find themselves in one or more of the following scenarios:
* They have data types with very bad reprs
* They are using Hypothesis features that currently don't play well with `@example`.
* Their CI setup doesn't interact brilliantly with the Hypothesis example database.
This can make it annoying to impossible to reproduce failures from CI locally.
This PR aims to mitigate that: When a test fails, if the random seed required to reproduce that test was not already set deterministically (with `@seed` or `derandomize=True` or with the command line argument I'll mention in a moment), Hypothesis will print out the seed it used along with instructions on how to use it to reproduce the example.
In order to make that information more readily useful and allow reproducing examples …
> Print seed on test failure to aid reproduction

- RELEASE.rst
- src/hypothesis/core.py
- tests/nocover/test_coverage.py
Currently the following two facts interact poorly:
* We deliberately collect files that coverage ignores, because we're interested in more than just reporting and want to use coverage information to distinguish different states.
* We feed collected data back to coverage so that things that ran under Hypothesis contribute to its reporting.
Unfortunately, as things currently stand, we were feeding it files that it had deliberately ignored. This resulted in it including them in its report when it shouldn't have.
This PR fixes that. When running under an existing collector, every time we see a new file we ask it whether it's interested in that file (we have to do this dynamically as we run because it requires access to the frame object. This is for reasons internal to coverage that don't …
> Don't try to feed coverage files it doesn't want

- tests/pandas/test_data_frame.py
- tests/pandas/test_series.py
`pd.Series([1]).dtype` is `int64` for any integer in the valid range (and `dtype('O')` beyond it).  `np.dtype(int)` gives `np.int_`, which is defined as ['same as C `long`'](https://docs.scipy.org/doc/numpy/user/basics.types.html), and thus can be 32 or 64 bit depending on the machine.  This pull therefore fixes #876, failing test on i686, by checking that the dtype of these series is `'int64'` rather than `int`.
A similar issue to be aware of is handled by our centralised conversion functions - `np.array([int_x]).dtype` will vary with the value of `x`.  On my machine 32bit within that range, and 64bit otherwise, but the docs allow different results so long as the dtype is sufficient for the values.
> Fix over-precise assertion about Pandas dtype

- RELEASE.rst
- src/hypothesis/internal/cache.py
- src/hypothesis/internal/escalation.py
- src/hypothesis/searchstrategy/lazy.py
- src/hypothesis/searchstrategy/misc.py
- src/hypothesis/searchstrategy/strategies.py
- src/hypothesis/strategies.py
- tests/cover/test_cache_implementation.py
- tests/cover/test_cacheable.py
- tests/cover/test_escalation.py
Hypothesis historically caches all the things (ALL THE THINGS? Well, no, not quite, but most of the things doesn't have the same ring to it) in its strategy module. This is because I was lazy and didn't want to write, or find a decent cache.
Well, now I have. I wasn't very happy with any of the options, and I had this neat property-based testing library lying around that makes it easier to write your own data structures and not be worried about them being wrong, so I ended up writing my own.
The caching policy adopted is an LFLRU cache - that is, we evict the key that has been used the least often, breaking ties by evicting the one which has been used the least recently. This seems likely to be a good fit for Hypothesis's workload, though it's hard to say for sure.
Note; This is not …
> Add a sensible eviction policy for Hypothesis's strategy caching

- Makefile
- RELEASE.rst
- scripts/install.sh
- setup.py
- src/hypothesis/internal/compat.py
- tox.ini
[Python 3.3 will be end-of-life on September 29](https://www.python.org/dev/peps/pep-0398/#x-end-of-life).  Support for Python 3.3 was officially dropped in Hypothesis 2, but it still probably mostly worked for a while (with no testing, I'm actually unsure) and until now our `install_requires` setting has allowed it.
With no further security updates, it's appropriate to explicitly block this version - if anyone is still using it they should upgrade as a matter of urgency, or possibly pay for commercial support (for both Python and Hypothesis).
I also removed our tooling for [2.6 and 3.2, both past EOL](https://docs.python.org/devguide/#status-of-python-branches), and the `setup.cfg` file which [has never done anything](https://github.com/HypothesisWorks/hypothesis-python/commits/master/set …
> Block install on Python 3.3 for EOL on 29 September

- RELEASE.rst
- src/hypothesis/_settings.py
- src/hypothesis/core.py
- src/hypothesis/errors.py
- tests/cover/test_deadline.py
Deadlines currently interact poorly with shrinking in the
shrinker will try to find an example which is right on the
boundary of failing, which means that given the slightly
unreliable nature of timing, often when you replay the
example it doesn't fail! This results in a confusing user
experience.
The fix is twofold:
1. Give a better error message when this happens.
2. Try to avoid it happening in the first place by raising
the deadline temporarily during the shrinking process, so
that we stop at a boundary that is significantly above that
of the deadline.
This fixes #892.
> Improve behaviour of deadlines on the boundary

- tests/pandas/test_indexes.py
It's something about datetimes and empty indexes - whatever the underlying cause, this fixes #923 and I think that's good enough.
> Looser test for Pandas < 0.19

- tests/pandas/test_indexes.py
Turns out that #924 *didn't* fix it in general, so now we just skip that assertion entirely on Pandas 0.18
This is not what I'd planned for Hacktoberfest 😞
> Fix pandas test *again*

- RELEASE.rst
- src/hypothesis/strategies.py
- tests/py3/test_lookup.py
Which are not actually types at runtime, hence the requirement for special handling.  Closes #901.
> Infer strategies from typing.NewType instances

- RELEASE.rst
- src/hypothesis/core.py
- src/hypothesis/internal/conjecture/engine.py
- tests/cover/test_core.py
It turns out that:
* We use tag objects as hash keys a *lot* in target selections
* Our tag objects are all attrs classes and attrs has some significant problems with hashing and equality performance right now: https://github.com/python-attrs/attrs/issues/261  
This replaces our tags with hash-consed (i.e. memoized) objects, so that two value equal tags are always reference equal. This significantly speeds up their use as keys and set members.
Fixes #919.
> Address performance problems in new target selector code

- .travis.yml
- RELEASE.rst
- src/hypothesis/_settings.py
@manueljacob pointed out that performance of `use_coverage` was actually perfectly reasonable on pypy. I think some of this was because it wasn't suffering so badly from the problems fixed in #922, but even once those are fixed my limited benchmarking suggests that the performance on pypy is perfectly reasonable. 
Certainly its performance after the various recent performance fixes is a lot better than CPython performance was in 3.30.4, so we might as well make pypy users suffer and get a bunch of interesting bug reports from them too. 😁
> Enable coverage on pypy

- .pyup.yml
Based on rereading [the pyup docs](https://pyup.io/docs/bot/config/) I now see why pyup is still just as chatty as ever after turning on weekly batching - we had the format wrong and pyup wasn't telling us because who validates yaml anyway?
This should hopefully fix that.
> Fix pyup.yml format to actually batch

- RELEASE.rst
- docs/changes.rst
- src/hypothesis/strategies.py
- tests/py3/test_lookup.py
We actually already support sampling from enums, but this still adds two features:
- `from_type(an_enum)` now correctly delegates to `sampled_from(an_enum)`, rather than `builds(an_enum)` (which fails, despite being a class with no required args to `__init__`)
- When sampling from an [`enum.Flag`](https://docs.python.org/3/library/enum.html#flag) subclass, we also generate combinations of members.  Eg for `Flag('Permissions', 'READ, WRITE, EXECUTE')`, we can now generate `Permissions.READ|EXECUTE`.  This is done dynamically to avoid O(2\^n) memory blowup.
> Better sampling from Enums

- RELEASE.rst
- src/hypothesis/internal/reflection.py
- tests/cover/test_reflection.py
- tests/py3/test_lookup.py
This is a subtle but nasty bug I added when working on type inference introspection.  The root cause is that the calculation of what arguments are required assumes that the `args` tuple contains the *names* of the arguments, where it actually contains the *values*.  😕 
Closes #946, with thanks to the excellent report by @hoefling.
> Fix builds introspection with type hints

- RELEASE.rst
- src/hypothesis/core.py
- tests/cover/test_given_error_conditions.py
Report a deprecation if @given is applied to a test more than once.
Currently, a user can apply @given to a test as many times as they like.  The effect of this may not be obvious at first, but what it actually does is wrap the test multiple times: the inner most decorator will be applied first, generating a wrapped test, and then the outer decorator will be applied. Each wrapper will search the space of of possible parameters separately, which will be much more inefficient than doing it together.  I'm also concerned (but haven't investigated) that this is liable to interact badly with use of @example; if @example is used before the first decorator, the example will be tested in the outer wrapper, but if it's used before an inner decorator, the example will be tested in the inner wrapper, …
> Deprecate repeated given

- CONTRIBUTING.rst
- RELEASE.rst
- src/hypothesis/strategies.py
- tests/cover/test_direct_strategies.py
- tests/cover/test_uuids.py
Closes #721 by adding a `version` argument for `hypothesis.strategies.uuids`, which is passed through to the UUIDs constructor.
> Support version argument for uuids strategy

- RELEASE.rst
- src/hypothesis/internal/compat.py
- tests/common/setup.py
- tests/cover/test_regex.py
- tests/django/manage.py
- tests/django/toys/urls.py
- tests/django/toystore/models.py
- tests/nocover/test_compat.py
- tests/quality/test_discovery_ability.py
Motivation: [this Twitter thread](https://twitter.com/ncoghlan_dev/status/917088410162012160) where @ncoghlan pointed out that `inspect.getfullargspec` has never actually emitted a `DeprecationWarning`.  I wrote the mentioned workaround in #625, when I trusted the docs and didn't bother checking.  There's a lesson in that, I'm sure 😉
avoid if practical, emulate latest compatible interface if not 😛)
> Enable 'DeprecationWarnings as errors' for all tests

- RELEASE.rst
- docs/data.rst
- docs/healthchecks.rst
- src/hypothesis/_settings.py
- src/hypothesis/core.py
- src/hypothesis/errors.py
- src/hypothesis/extra/pandas/impl.py
- src/hypothesis/internal/conjecture/data.py
- src/hypothesis/internal/escalation.py
- src/hypothesis/internal/validation.py
- src/hypothesis/strategies.py
- tests/cover/test_escalation.py
- tests/cover/test_health_checks.py
- tests/cover/test_setup_teardown.py
As part of the Smarkets funded work I'm going to be doing a bunch of rationalisation and consolidation of the health check code. This is the first casualty of that work - getting rid of the health check which catches exceptions thrown during data generation and rethrows them as a less useful error.
Uh, yeah, I don't know why I ever thought that was a good idea either.
This turned out to be a surprisingly involved change. It has two major parts to it:
* A bunch of new deprecation warnings.
* Changes to the escalation code to always reraise errors inside draw.
Additionally:
* A bunch of refactoring in support of that (extracted the validation code from hypothesis.strategies into its own module because I wanted to use some from settings, moved StopTest into hypothesis.errors).
* I realised …
> Always escalate exceptions in data generation

- RELEASE.rst
- docs/changes.rst
- src/hypothesis/internal/cache.py
- src/hypothesis/internal/charmap.py
- src/hypothesis/internal/reflection.py
- src/hypothesis/searchstrategy/lazy.py
- src/hypothesis/searchstrategy/regex.py
Includes removing indirect imports, style fixes/clarification, fixing typos in comments, etc.
This should have no user-visible impact beyond the formatting fix in the changelog, but I'll be happier browsing certain bits of code.  For maintainers, the various parts of `charmap.py` now consistently return tuples, and importing `sre_constants` from the correct module should ease static analysis.
> Misc. minor refactoring

- RELEASE.rst
- src/hypothesis/core.py
- tests/cover/test_deadline.py
This changes the deadline feature to subtract the amount of time spent in drawing data (which we now have as a result of #973) from the run time of the test.
This was a surprisingly involved change and necessitated a bunch of refactoring. A bunch of logic got moved from top level functions to `StateForActualGivenExecution` and some of this was inlined. This was largely because the place where the deadline code was being calculated didn't have access to the data object. I've tried to make sure this refactoring makes the code better rather than worse, but core.py remains a bit of a horror show...
Fixes #911.
> Don't count interactive draw towards deadline time.

- .travis.yml
- RELEASE.rst
- docs/conf.py
- docs/data.rst
- docs/details.rst
- docs/settings.rst
- guides/documentation.rst
- scripts/fix_doctests.py
- src/hypothesis/strategies.py
Closes #711, via a series of terrible hacks that work well enough for now (see comments in source, or just read source, for details).  Notably there are some not-too-rare cases that are not covered; but as an aid to manual updates I think it's good enough - I certainly don't want to spend longer writing it than is saved by its use!
> Get doctests working again; script to fix broken doctests

- RELEASE.rst
- src/hypothesis/internal/reflection.py
- tests/cover/test_lambda_formatting.py
- tests/cover/test_statistical_events.py
Special case lambdas inside decorators using exciting regular expressions as a fallback.
I could attempt to justify myself, but I think we'd both be happier if I didn't, so I'm just going to say sorry instead.
Fixes #981.
> Special case decorators when extracting lambdas

- RELEASE.rst
- src/hypothesis/searchstrategy/regex.py
- tests/cover/test_regex.py
Turns out we should have been passing the flags through to `sre_parse.parse` along with the pattern, and failing to do so breaks things.  Obvious in hindsight!  Closes #992.
And I did a minor refactor while I was there, passing a bool `is_text` instead of checking the type of the pattern every time.
> Handle re.VERBOSE in from_regex

- tests/common/setup.py
- tests/django/manage.py
- tox.ini
Closes #969 - the Arch package has unbundled some upstream dependencies, so this option will be useful for @felixonmars 😄 
CC @DRMacIver in case this is one of those things where we have divergent taste in solutions.
> Allow downstream to disable deprecations-as-errors with environment var

- RELEASE.rst
- src/hypothesis/internal/charmap.py
- src/hypothesis/searchstrategy/strings.py
- tests/cover/test_charmap.py
- tests/cover/test_intervalset.py
- tests/nocover/test_characters.py
Instead of supporting blacklisted characters with rejection sampling, this updates the interval set we use to generate characters to remove them. This should significantly improve the efficiency in some cases, particularly when shrinking if the blacklisted characters include a bunch of small codepoints.
Extracted from #996, where this code triggered a new health check.
> Handle blacklisted characters as part of the intervals

- .travis.yml
- Makefile
- docs/extras.rst
- docs/numpy.rst
- tox.ini
- Closes #983.
- For efficiency I've also dropped Pandas 0.18 from our CI suite, though it remains available to run locally.
- Minor edit to Tox environment setup; now uses latest compatible patch version of optional packages.
- Reduced redundant docs.
> Test Pandas 0.21 in CI

- RELEASE.rst
- src/hypothesis/core.py
- src/hypothesis/internal/conjecture/engine.py
- tests/cover/test_database_seed_deprecation.py
- tests/cover/test_database_usage.py
- tests/cover/test_seed_printing.py
- tests/cover/test_settings.py
- tests/nocover/test_floating.py
Turns out that telling someone the seed isn't very helpful if they then need the entire example database to recreate it!
This is kinda an interim "just make things not broken" release. It patches a lot of little interactions, adds some deprecations, and tries to make things not terrible. A proper fix is out of scope for now - it requires us to think about example DB workflows a lot better than we currently have.
> Improve interactions between example database and seeding

- CONTRIBUTING.rst
- RELEASE.rst
- src/hypothesis/internal/conjecture/utils.py
- tests/numpy/test_sampled_from.py
Makes it so you can `hypothesis.strategies.sampled_from` an `ndarray`.
```
Python 2.7.14 (default, Sep 25 2017, 09:53:22) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import hypothesis
>>> hypothesis.strategies.sampled_from(numpy.array([1, 2, 3])).example()
.../hypothesis-3.33.0-py2.7.egg/hypothesis/strategies.py:418: HypothesisDeprecationWarning: Cannot sample from array([1, 2, 3]), not a sequence.  Hypothesis goes to some length to ensure that sampling an element from a collection (with `sampled_from` or `choices`) is replayable and can be minimised.  To replay a saved example, the sampled values must have the same iteration order on every run - ruling out sets, dicts, etc …
```
> adds numpy ndarray to the list of sampleable types

- .travis.yml
- Makefile
- RELEASE.rst
- docs/changes.rst
- docs/extras.rst
- setup.py
- src/hypothesis/extra/fakefactory.py
- tests/fakefactory/test_fake_factory.py
- tox.ini
Closes #1002 and updates the relevant docs.  I've also tested several versions of Faker locally, and given that they work I've toned down compatibility warnings, and reduced our CI tests to only check against one version for speed.
> Deprecate hypothesis[fakefactory]

- RELEASE.rst
- src/hypothesis/_settings.py
- src/hypothesis/database.py
- src/hypothesis/internal/compat.py
- src/hypothesis/internal/conjecture/engine.py
- src/hypothesis/internal/conjecture/minimizer.py
- tests/cover/test_conjecture_engine.py
- tests/cover/test_direct_strategies.py
- tests/cover/test_numerics.py
- tests/quality/test_shrink_quality.py
My yak stack was deep enough that I forget why, but I noticed that `bytes_from_list` was literally just `hbytes`.  Pulling on the thread revealed several other things that could easily be deleted from compat.py, and pulling *those* threads led to cleaning up some unidiomatic code in the conjecture engine.
There should be no change to behaviour, ~~but shrinking passes may be slightly faster in a few places - sorting once instead of twice in `minimize_duplicated_blocks`, and iterating directly over blocks instead of accessing each index in a list in `coarse_block_replacement` and `minimize_individual_blocks`.~~
For the compat changes, I took the view that if the Python 3 idiom works on Python 2, we should just use that - and therefore eg. import reduce from functools rather than compat.py.
> Internal code cleanup

- RELEASE.rst
- src/hypothesis/searchstrategy/lazy.py
- tests/cover/test_composite.py
- tests/cover/test_custom_reprs.py
Fixes #1017.
As far as I can tell from digging through the history of `lazy.py`, this function originally used a custom tuple subclass which fixed the reprs of its elements.  That didn't last, but the general tupleize function did.
~~Notably, there are *no tests* specifically for this change.  Pretty weird for Hypothesis, but the basic functionality is well covered by other tests.  As there's essentially no chance of accidental regression, I declined to write a super-specific test purely for it's own sake - and writing a test just to have written a test is rather missing the point.~~
> De-tuplize arguments to lazy strategies

- scripts/hypothesistooling.py
- scripts/run_circle.py
I noticed in #1021 that the Circle build was giving the wrong message as to why it wasn’t running tests.
After staring *really hard* at the diff for #1014, I spotted what might be the issue:
```diff
-if [ "$CIRCLE_BRANCH" != "master" ] && [ "$CI_PULL_REQUESTS" == "" ] ; then
-  exit 0;
-fi
+    if (
+        os.environ['CIRCLE_BRANCH'] != 'master' and
+        os.environ['CI_PULL_REQUEST'] == ''
+    ):
```
Looking at [the Circle docs](https://circleci.com/docs/1.0/environment-variables/#build-details), I’m struggling to see why this would make a difference:
> `CI_PULL_REQUESTS`
>
> Comma-separated list of pull requests this build is a part of.
>
> `CI_PULL_REQUEST`
>
> If this build is part of only one pull request, its URL will be populated here. If there was more than one pull request, …
> Fix a terrible pluralisation bug

- docs/changes.rst
- docs/development.rst
- docs/extras.rst
- docs/packaging.rst
- docs/quickstart.rst
Hopefully nothing controversial here.  @DRMacIver might take note though - http://www.drmaciver.com does not (yet) redirect to https.
> Docs updates - use https links, don't suggest strict mode

- RELEASE.rst
- src/hypothesis/errors.py
- tests/cover/test_timeout.py
- tox.ini
Closes #618, based on the recently accepted [PEP 565](https://www.python.org/dev/peps/pep-0565/).
Strictly speaking this may change behaviour of people's tests if they had a warnings filter configured to catch `DeprecationWarning` but not `FutureWarning`, but there's no gradual path anyway in that case -
inheriting from both gets the default, silent, behaviour of the former.
> Use FutureWarning for user-facing warnings, per PEP 565

- tests/common/strategies.py
- tests/cover/test_conjecture_engine.py
- tests/nocover/test_conjecture_engine.py
As part of debugging why #1023 is being screwy I wanted better tests for the core engine. This PR implements that.
I wanted to keep this separate from any implementation changes, so this *just* touches testing. No release is involved.
Things this implements:
1. `tests/cover/test_conjecture_engine.py` now gives 100% coverage of `src/hypothesis/internal/conjecture/engine.py`
2. Tests in there should be much faster now, partly due to some judicious use of stubbing and other poking at engine internals to put it in the right state rather than relying on chance.
3. Some tests that don't meaningfully contribute to coverage are moved into tests/nocover.
There is an xfail in the tests because I didn't want to make source changes, let alone open the can of worms that is `__rewrite_for_novelty`. I'm …
> Improve tests covering ConjectureRunner.

- RELEASE.rst
- src/hypothesis/core.py
Fixes #997.
You may note that this fix does not come with an associated test. This bug is *incredibly* fiddly to create an isolated test case for, and after about an hour trying I decided I simply didn't care enough to do so - as far as I can tell we would basically have to create a Python package in our test suite and install it into the current virtualenv, and ain't nobody got time for that.
The bug is easy to reproduce in situ in the affected projects, and I've manually done so and verified that this fix works for them.
The root issue is as described in #997 but basically when running under Hypothesis the test file doesn't "look" like part of the right package to coverage. This fixes the problem by using the fact that part of the test file must already have been loaded into coverage in …
> Use the parent collector's notion of what files it cares about where applicable

- tests/cover/test_numerics.py
This:
* Replaces use of `@fails` to assert the ability to find certain examples with the more modern `find_any` 
* Replaces all use of math functions (which convert to floats) with the corresponding decimal methods
As a result fixes #1033
> Clean up tests/cover/test_numerics.py

- tests/cover/test_float_nastiness.py
I saw a flaky failure of one of these tests in #1023 so I figured I'd fix the test.
The idea is that although we don't currently reliably generate both signed zeros (we do so with high probability but not quite high enough), anything we can minimize to we can generate, and the signed zeroes are the shrink target for floats of a given sign, so we can use minimal to assert the same property more reliably.
> Make tests for signed zero less flaky

- guides/testing-hypothesis.rst
- tests/README.rst
- tests/nocover/test_pretty_repr.py
> I remember the first time I opened the tests directory. I was working on my first feature to contribute, needed to write tests, and... I just stared at it for a while. The volume is really intimidating for newcomers, and I had no idea where to start!
>
> Adding a tests/README.rst describing the contents and purpose of each sub-directory would be really helpful - with the aim that reading it provides just enough info to direct a new contributor to the right place. For the tests root, this probably includes a brief note on what we try to test and our test philosophy. I'd also add another readme to each subdirectory with a note on the various files - equivalent to a short module docstring but visible in one place.
Closes #975.  The best way to review this might be to check [the branch in …
> Add README files to our tests to help new contributors

- RELEASE.rst
- src/hypothesis/core.py
- src/hypothesis/internal/conjecture/engine.py
- tests/cover/test_conjecture_engine.py
- tests/cover/test_datetimes.py
- tests/cover/test_testdecorators.py
- tests/nocover/test_conjecture_engine.py
- tests/quality/test_discovery_ability.py
This is a pure refactoring pull request.
It has two main goals:
1. I want to be able to apply the shrinker to things that aren't bugs, and so it needed to be possible to pass it an arbitrary predicate. Currently the logic of the shrink predicate was super tangled with the rest of the code, so this teases that out into its own object.
2. Once I had done that, the goal I've vaguely had for a while of killing the `last_data` property on `ConjectureRunner` was much more tractable - the property is largely legacy at this point since the multiple bugs at once functionality, so getting rid of it was desirable (the shrinker uses a similar pattern, but I think that makes sense for its role - it really *does* have a single target of interest).
One thing worth noting is that the state management in …
> Remove use of runner.last_data and factor out Shrinker state

- RELEASE.rst
- src/hypothesis/internal/conjecture/data.py
- src/hypothesis/internal/conjecture/engine.py
- tests/cover/test_conjecture_engine.py
- tests/quality/test_poisoned_lists.py
- tox.ini
(Built on top of #1023)
In doing some evaluation for my upcoming paper on the Hypothesis shrinker, I managed to find a class of examples which the shrinker does quite badly on - "poison lists", which are strategies that generate a list of elements via some slightly awkward process and try to minimize based on whether they contain a single low probability poison value. In particular in this example the poison value has the problem that it's smaller than the other elements, so it defeats the heuristic we use to detect whether we can delete intervals.
After some tinkering I've improved the shrinker so that it can detect and deal with length parameters more reliably.
The idea is this: We're currently paying the cost for attempted deletion for subsequent intervals every attempt to …
> More reliable handling of shrinking of strategies with length parameters

- CONTRIBUTING.rst
- RELEASE.rst
- src/hypothesis/internal/escalation.py
> fix caching of file-categorization logic

- CONTRIBUTING.rst
Seems to have been inadvertently broken in #917
> Fix an email address link

- RELEASE.rst
- src/hypothesis/internal/conjecture/data.py
- src/hypothesis/internal/conjecture/engine.py
- src/hypothesis/internal/conjecture/utils.py
- src/hypothesis/searchstrategy/strategies.py
- tests/cover/test_conjecture_engine.py
Context: When drawing data we sometimes do a lot of rejection sampling, where we repeatedly (at least, for a few times. In a real random generator we'd loop infinitely because we could rely on low probability events being low probability. We bound the loops more tightly because we can't guarantee that) draw a thing until we get the right sort of value.
Each of these corresponds to an interval in the data, so when the shrinker runs it will try deleting each of the rejected regions, so this is not an obstacle to shrinking. However, if there's a lot of these regions that's a lot of shrinks to try before we do anything more useful.
So this PR lets the caller annotate a region as discarded when it finishes with it. The shrinker will now try to simultaneously delete all discarded intervals on …
> More aggressively discard filtered data from the input during shrinking

- .travis.yml
- Makefile
- RELEASE.rst
- docs/django.rst
- scripts/basic-test.sh
- setup.py
- tox.ini
[Django 2.0 released](https://www.djangoproject.com/weblog/2017/dec/02/django-20-released/):
> The Django team is happy to announce the release of Django 2.0.
>
> This release starts Django’s use of a loose form of semantic versioning, but there aren’t any major backwards incompatible changes (except that support for Python 2.7 is removed). […]
This adds testing for Django 2.0 to Travis. I did a test locally; ran green with no changes or warnings.
> Add support for Django 2.0; drop support for Django 1.10

- docs/reproducing.rst
[The docs for PrintSettings](https://hypothesis.readthedocs.io/en/latest/reproducing.html#hypothesis.PrintSettings) are currently singularly useless because they don't actually document the options! This fixes that.
> Add :members: directive to autoclass for PrintSettings

- RELEASE.rst
- src/hypothesis/extra/django/models.py
- src/hypothesis/strategies.py
- tests/django/toystore/test_given_models.py
Closes #1045.  Reference django/django#8670 and [Django ticket 28201](https://code.djangoproject.com/ticket/28201).
Interestingly, these cases would be rejected inside the strategy on Django 2.0 by our validator-to-filter code, which makes this change a performance optimisation only on newer versions.
> Blacklist null byte in Django string strategies

- RELEASE.rst
- docs/data.rst
- docs/details.rst
- src/hypothesis/internal/conjecture/engine.py
- src/hypothesis/strategies.py
- tests/cover/test_conjecture_engine.py
- tests/cover/test_deferred_strategies.py
- tests/nocover/test_conjecture_engine.py
~~Update: Please review #1054 first~~.
Previously in Hypothesis development...
1. I opened a pull request (#1048) to make our default integer size smaller
2. This revealed some problems with our internal sampler implementation, so I opened a pull request (#1049) that replaced it with a more normal sampler implementation.
3. This revealed a bug in `__rewrite_for_novelty` where the change to the sampler triggered an internal assertion.
4. This pull request ended up breaking the pandas tests because one of them was more or less only working by coincidence - the test for shrinking based on two columns only worked if you got the right initial example. Previously we were, now we're not. #1054 fixed this.
`__rewrite_for_novelty` has been on my hit list for a while, so this is a pull request to …
> Generate prefixes that guarantee novelty rather than trying to rewrite on the fly

- RELEASE.rst
- docs/data.rst
- docs/reproducing.rst
- src/hypothesis/internal/conjecture/utils.py
- src/hypothesis/searchstrategy/numbers.py
- tests/cover/test_conjecture_float_encoding.py
- tests/cover/test_conjecture_utils.py
- tests/nocover/test_conjecture_utils.py
- tests/quality/test_shrink_quality.py
As part of #1048 I was working on the sampler and discovered that as well as shrinking badly the distribution of our sampler was also significantly wrong!
This PR switches us back to a more standard method of sampling - the alias method, adapted lightly for shrink quality purposes. I don't think the claimed advantages of the weird system we were using instead are borne out in practice given that it appears to shrink badly and be wrong.
> Switch back to a vose alias method sampler

- appveyor.yml
- docs/reproducing.rst
> [NOTE: AppVeyor searches for skip commit string in the commit message title only (text before first empty line) only.](https://www.appveyor.com/docs/how-to/filtering-commits/#commit-message)
Appveyor "helpfully" supports standard skip messages in a non-standard way.  Instead of making our regular message ugly, I've just told Appveyor to skip that message too.
This should avoid spurious reporting of failures in the commit list; and likewise against the repo title via [refined github](https://github.com/sindresorhus/refined-github).  (which is great, as is [issue link status](https://github.com/bfred-it/github-issue-link-status))
> Actually skip bump-commits in Appveyor

- tox.ini
This turns off verbose test reporting in pytest, so instead of seeing each test name we'll mostly see ...F... and then the failing tests printed at the end.
@Zac-HD suggested this a little while back, and I've become convinced it's a good idea, mostly because I'm incredibly annoyed by how badly Travis et al handle large test output (yes, lets take the simple text output and run it through incredibly slow javascript that locks up people's browsers, what a good idea).
> Make test output non-verbose by default

- tests/cover/test_arbitrary_data.py
- tests/cover/test_float_nastiness.py
This fixes our two current flaky tests that aren't build issues.
* I'm not totally sure why ` test_prints_on_failure` became flaky. The small ints work would have done it, but it became flaky before then! Either way it's not a very sensible place to be testing a hard to satisfy condition, so I've just fixed it by making the test easier to pass.
* `test_half_bounded_generates_endpoint` ~~OTOH is a genuine bug - it's another place where we were implicitly relying on our sampler being broken. I've rejigged the distribution of floating point numbers to be much more likely to include 0, and this makes the test non-flaky.~~ this is still a genuine regression, but for now I've just marked the test as flaky with a high enough fudge factor that it passed 100 test runs. I'm not super happy with …
> Fix flaky tests

- RELEASE.rst
- src/hypothesis/searchstrategy/types.py
- src/hypothesis/strategies.py
- tests/py3/test_lookup.py
This patch improves handling of forward references in `from_type()`, and thus fixes #1004.
- Forward references are detected in more cases, and uniformly result in errors as they're not a type
- Self-referential types (such as trees) now resolve without recursion errors.
Unfortunately the original motivating case involves a little too much magic to resolve, but if you define `__init__` manually it works.
> Handle forward references and recursion in from_type

- RELEASE.rst
- docs/details.rst
- src/hypothesis/internal/conjecture/data.py
- src/hypothesis/internal/conjecture/engine.py
- tests/cover/test_conjecture_engine.py
- tests/quality/test_poisoned_trees.py
- tests/quality/test_shrink_quality.py
More work that emerged from evaluations done while writing my paper on the shrinker: I noticed that if we have a binary tree that we're generating as leaf | branch, we actually can only "properly" shrink it to the right hand subtree. We can shrink to the left subtree only if this is the last element drawn (because then we can silently discard the bytes at the end).
This change provides a significant upgrade to how Hypothesis handles recursive data in the form of two extra passes:
* `zero_intervals` tries replacing every draw call with its natural minimum element (the one you get from an infinite series of zeroes): It first tried replacing the interval with a zero interval of the same length. If that works, great. If not but it produces a valid example, we can read off the set of possible …
> Improve support for shrinking recursive data structures

- scripts/run_travis_make_task.py
I've been finding the `CalledSubprocessError` stack traces on our build failures annoyingly distracting. This replaces them with code that just exits with the right code instead.
> Make build failures tidier

- tests/py3/test_lookup.py
Closes #1074, which was raising `TypeError` because the type hints went missing before `Tree` was passed to `builds()`, which then failed because required arguments were not provided.  If this happens, we now assert that the test is running on Python 3.5.x (which has a very early provisional typing module), and then skip the test.
I still hate debugging things I can't reproduce locally - I even installed the exact version of Python! - but I suppose reading the code is good for me :roll_eyes:
> Deal with another old-typing-module problem

- RELEASE.rst
- src/hypothesis/internal/conjecture/data.py
- src/hypothesis/internal/conjecture/engine.py
- tests/cover/test_conjecture_engine.py
In the Shrinker we have a notion of whether or not a block is "shrinking": The idea is that if we ever see lowering the block reducing the amount of data drawn next, the block is shrinking. If not, it's not.
So for example if we have:
```python
x = integers(0, 255)
t = tuples(x, x)
l = x.flatmap(lambda n: lists(booleans(), min_size=n, max_size=n))
```
Then no block in drawing t is shrinking (the data size is fixed), but the first block in drawing l is shrinking because it determines how many values are drawn afterwards.
The problem we must face is where we store this information: If we've previously determined that a block is shrinking, and then we change the shrink target, is the block at that position still shrinking? Possibly not.
Previously we stored information about which blocks …
> Change how we track whether a block is shrinking

- RELEASE.rst
- src/hypothesis/internal/conjecture/data.py
- src/hypothesis/internal/conjecture/engine.py
- tests/cover/test_conjecture_engine.py
- tests/cover/test_conjecture_test_data.py
(In which David takes a break from his wild Friday night of paper editing to implement something the paper made him realise he could do)
The way we store intervals on `ConjectureData` is kinda bad. It's relatively expensive and puts logic that should be in the shrinker in the wrong place.
This changes how we handle that code to instead track a precise list of `start_example/stop_example` boundaries, in order of when `start_example` was called. We can then calculate everything we need off that list in the shrinker as and when we need it.
This has the feature (and also necessity because of how it used intervals) that we can now be more precise in what was previously called `zero_intervals` and is now called `zero_draws` - previously we had a problem caused by the fact that we couldn't tell …
> Move interval calculations into Shrinker and track precise example locations

- RELEASE.rst
- src/hypothesis/internal/compat.py
- src/hypothesis/internal/conjecture/data.py
- src/hypothesis/searchstrategy/collections.py
- src/hypothesis/searchstrategy/deferred.py
- src/hypothesis/searchstrategy/lazy.py
- src/hypothesis/searchstrategy/strategies.py
- src/hypothesis/strategies.py
- tests/cover/test_conjecture_engine.py
- tests/cover/test_database_usage.py
- tests/cover/test_simple_numbers.py
- tests/cover/test_stateful.py
- tests/nocover/test_conjecture_engine.py
- tests/nocover/test_labels.py
There are currently two tensions in moving forward some planned Hypothesis development:
1. I want to take better advantage of coverage information.
2. I want to keep things working without coverage information
One option is basically to just fall back to something 100% naive in the latter case, but that seems a shame. We're basically just using coverage to partition the space, so perhaps we can figure out a (necessarily coarser) partition without coverage?
This PR is a first pass at doing that: The idea is to using hashing to indicate some basic structural information about the shape of the data - for example, to distinguish an empty list from a list containing an integer from a list containing a string. The tags in question are then used exactly like coverage targets, but apply whether …
> Add purely structural tags to ConjectureData

- RELEASE.rst
- src/hypothesis/internal/conjecture/engine.py
- tests/cover/test_conjecture_engine.py
- tests/quality/test_zig_zagging.py
Bad news: Hypothesis's shrinking is sometimes `O(16^n)`.
Good news: Here's a fix for that!
Bad news: This problem is intrinsic to the problem of test-case reduction and there's no escape. All is lost. We are doomed to live in exponential land forever.
(This isn't really a problem in practice because `max_shrinks` saves us, but I thought I'd spend some time figuring out how to deal with the common case and it turns out that the common case is easy to deal with).
Anyway, we can detect and fix some of the common cases as follows:
* we keep track of which bytes have changed since we last managed to reduce the size of the byte stream and as the last stage of the shrink process we try to lexically minimize them all together.
* we beef up the way the lexical minimizer makes changes to multiple …
> Add guard against exponential time pathology

- RELEASE.rst
- setup.py
In #1008, we had to add some maximum version constraints to Django - at the time, it had not set the `python_requires` tag and `pip install django` therefore failed on Python 2.  Since django/django#9413 has been released and the PyPI admins have fixed this on earlier versions, we can ditch the upper version constraint as for all our other dependencies.
While fixing this, I found [this article on conditional dependencies](https://hynek.me/articles/conditional-python-dependencies/), which pointed out that our handling of `enum34` was broken for binary wheels.  I therefore fixed this too - you now need a newish (~8 months old) version of setuptools to build a Hypothesis dist without emitting the new warning, but can install it with very old pips.
> Improve dependency version constraints for enum34, django extra

- CONTRIBUTING.rst
- RELEASE.rst
- src/hypothesis/strategies.py
- tests/cover/test_direct_strategies.py
This is my attempt to address https://github.com/HypothesisWorks/hypothesis-python/issues/1104, following the suggestion in the comment from @DRMacIver on that issue.
But I don't think it's good:
- calling `builds()` with no argument for the target no longer raises `TypeError` (`builds().example()` does), since the new code here isn't actually run when you call `builds()`
- for the same reason, the deprecation warning doesn't show when you first call `builds()`
I'm not thinking of any ways to fix this without adding a bunch of complication (I'd have to mess with `proxies()` and/or `base_defines_strategy()`?).
I'm completely new here, but it seems to me that merging this would make life worse for users and developers.
I figured I'd post it anyway, since (a) maybe I'm wrong about that or …
> rename target arg so we can use targets requiring an argument 'target'

- guides/api-style.rst
- guides/internals.rst
- guides/testing-hypothesis.rst
As part of #1093 I promised to write us an internals guide. This is a hopefully decent start at that!
> Add a guide for working on internals

- RELEASE.rst
- src/hypothesis/internal/renaming.py
- tests/cover/test_renaming.py
Fixes https://github.com/HypothesisWorks/hypothesis-python/issues/1111 (just item 1, not the rest).
Before:
```
In [1]: from hypothesis.strategies import timedeltas
In [2]: ?timedeltas
Signature: timedeltas(min_value=datetime.timedelta(-999999999), max_value=datetime.timedelta(999999999, 86399, 999999), min_delta=None, max_delta=None)
Docstring:
A strategy for timedeltas between ``min_value`` and ``max_value``.
Examples from this strategy shrink towards zero.
The following arguments have been renamed:
* min_delta has been renamed to min_value
* max_delta has been renamed to max_value
Use of the old names has been deprecated and will be removed
in a future version of Hypothesis.
File:      ~/hypothesis-python/src/hypothesis/strategies.py
Type:      function
```
After:
```
In [1]: from …
```
> fix indentation of docstrings produced by renamed_arguments

- Makefile
- RELEASE.rst
- requirements/tools.in
- requirements/tools.txt
- src/hypothesis/_settings.py
- src/hypothesis/control.py
- src/hypothesis/core.py
- src/hypothesis/database.py
- src/hypothesis/errors.py
- src/hypothesis/extra/django/models.py
- src/hypothesis/extra/pandas/impl.py
- src/hypothesis/internal/cache.py
- src/hypothesis/internal/conjecture/engine.py
- src/hypothesis/internal/conjecture/minimizer.py
- src/hypothesis/internal/conjecture/utils.py
- src/hypothesis/internal/reflection.py
- src/hypothesis/searchstrategy/collections.py
- src/hypothesis/searchstrategy/deferred.py
- src/hypothesis/searchstrategy/lazy.py
- src/hypothesis/searchstrategy/misc.py
- src/hypothesis/searchstrategy/numbers.py
- src/hypothesis/searchstrategy/strategies.py
- src/hypothesis/searchstrategy/strings.py
- src/hypothesis/stateful.py
- src/hypothesis/types.py
- tests/cover/test_conjecture_engine.py
- tests/cover/test_skipping.py
- tests/pandas/helpers.py
- tox.ini
You can see the list of possible errors [here](http://www.pydocstyle.org/en/stable/error_codes.html); but in short this ensures that we have consistent indentation, use and placement of newlines, and capitalization.
Checks also exist (but have been disabled) for presence of a docstring on all public classes and functions, single-line summaries, and trailing quotes on a new line - these might be nice, but I'm not going to add it all in this pull.
Closes #1088.
> Add flake8-docstrings as an additional style lint.

- Makefile
- scripts/install.sh
- tests/quality/test_zig_zagging.py
- tox.ini
Fixes #1087. It turns out the reason why our build didn't catch this is we only run the quality tests on Python 3!
This also:
*  updates the build to run quality tests on Python 2 so this doesn't happen again (As part of the same build job given how much of our tests are Travis startup time).
* Updates our testing version of Python to 2.7.14, though this turned out not to matter.
> Fix build on 2.7.14

- RELEASE.rst
- src/hypothesis/internal/conjecture/data.py
- src/hypothesis/internal/conjecture/floats.py
- src/hypothesis/internal/conjecture/utils.py
- src/hypothesis/searchstrategy/collections.py
- src/hypothesis/searchstrategy/numbers.py
- src/hypothesis/searchstrategy/strategies.py
- src/hypothesis/stateful.py
- src/hypothesis/strategies.py
- tests/cover/test_conjecture_engine.py
- tests/nocover/test_labels.py
This gives every `Example` a non-`None` label, as a prerequisite for (and as discussed in) https://github.com/HypothesisWorks/hypothesis-python/issues/1098.
I think previously most labels were sensitive to the substructure below them in the example tree (e.g. strategies like `ListStrategy` using `combine_labels` to combine their labels with those of the element strategies). That wasn't really available to me here (at least without bigger changes), so hopefully it's not a problem.
This will change the behavior of `TargetSelector` at least a little, since the `Example`s that previously had labels `None` are included in `TargetSelector.examples_by_tags` when they weren't before.
> give every Example a label

- scripts/hypothesistooling.py
I've been slightly annoyed that when I run `make check-release-file` spits out the whole diff, so this suppresses that. (This is often much more output than other `make ...` commands.)
I'm not too attached to this, so if anyone else prefers the status quo, I'm happy to stick to that instead.
(I confirmed that `make check-release-file` still complains if there are source changes and no RELEASE.rst.)
> don't show diff in make check-release-file

- scripts/fix_doctests.py
[`scripts/fix_doctests.py`](https://github.com/HypothesisWorks/hypothesis-python/blob/master/scripts/fix_doctests.py) is a nifty tool that replaces the expected output of failing doctests with whatever we actually got.  
As of this pull (which closes #1108), it:
- Requires Sphinx 1.7 or later, for more accurate reporting of doctest location (including "unknown"!)
- Handles indentation of other than four spaces correctly (eight spaces, no indent, etc) 
- Should work on doctests in docstrings in any file, but also retains the old workaround as a fallback in case of misreporting by Sphinx (still sadly common).
> Improve fix-doctests script

- docs/database.rst
From `git help gitignore`:
> * An optional prefix "!" which negates the pattern; any matching file excluded by a previous pattern will become included again. It is not possible to re-include a file if a parent directory of that file is excluded.
Therefore, we should exclude `.hypothesis/*`, not `.hypothesis/`.
> Fix .gitignore example excluding hypothesis examples database

- RELEASE.rst
- docs/settings.rst
- src/hypothesis/_settings.py
- tests/cover/test_settings.py
This closes #940, replacing and completing it.
As well as simplifying registration of new settings profiles, this patch requires that the name be a native or unicode string (in order to ease file- or envvar-based loading), and does some general tidying up of the formatting and documentation.
> Make settings.register_profile(...) accept kwargs as for settings(...)

- RELEASE.rst
- docs/changes.rst
- docs/healthchecks.rst
- docs/settings.rst
- docs/supported.rst
- src/hypothesis/_settings.py
- src/hypothesis/core.py
- src/hypothesis/errors.py
- src/hypothesis/internal/compat.py
- tests/cover/test_given_error_conditions.py
- tests/cover/test_unittest.py
- tests/django/toystore/test_basic_configuration.py
This is implemented via a series of terrible hacks, so I've put the whole thing in `core.py` 😜
> Improve unhappy paths using @given with unittest

- scripts/check-release-file.py
So we can have properly green builds, even without automatic deployment.
> Skip release file check for v4 pulls and non-master branches

- RELEASE.rst
- src/hypothesis/searchstrategy/collections.py
- src/hypothesis/searchstrategy/strategies.py
- src/hypothesis/stateful.py
- src/hypothesis/strategies.py
- tests/common/__init__.py
- tests/cover/test_direct_strategies.py
- tests/cover/test_flatmap.py
- tests/cover/test_one_of.py
- tests/cover/test_reusable_values.py
- tests/cover/test_sets.py
- tests/cover/test_simple_collections.py
- tests/cover/test_testdecorators.py
- tests/cover/test_type_lookup.py
- tests/numpy/test_fill_values.py
We have a [catalogue of style guide violations](https://github.com/HypothesisWorks/hypothesis-python/blob/master/guides/api-style.rst#a-catalogue-of-current-violations), of which allowing `elements=None` for empty collections is probably the most egregious (that's what the `nothing()` strategy is for!).  Part of issue #1155.
This pull deprecates passing `elements=None`, and makes the consequential changes to our test suite.
>  Deprecate elements=None in collection strategies

- RELEASE.rst
- tests/numpy/test_gen_data.py
Closes #1164 (cc @ginggs).  I've made this a patch release because while it only really affects downstream distributors, they're also going to appreciate having a version number for the fix :smile:
> Fix Numpy dtype test on big-endian platforms

- RELEASE.rst
- src/hypothesis/_settings.py
- src/hypothesis/internal/floats.py
- src/hypothesis/internal/validation.py
- src/hypothesis/strategies.py
- tests/cover/test_direct_strategies.py
- tests/cover/test_float_nastiness.py
- tests/cover/test_numerics.py
Closes #814 - see issue or release notes for details.
Notably, passing non-`Real` bounds to `integers` and `floats` has been converted to an error without any deprecation period, because this was a `TypeError` in `math.isnan` immediately below.  Otherwise, it's as planned in the issue.
> Improve validation of numeric bounds

- .gitignore
- RELEASE.rst
- src/hypothesis/internal/coverage.py
- tests/common/setup.py
- tox.ini
Closes #1175.  
The key insight is that doing this via the `PYTHONWARNING` environment variable is simply too difficult - the whole testing stack leaks warnings like crazy, and essentially can't be fixed without dropping support for older versions of Python.  Instead, we can use `warnings.filterwarnings` in `conftest.py` - which only applies to code we run *during* our tests, but not in our tools.
I'm keen to write an article about this with @dchudz to evangelize this tactic :smile:
> Use warnings-as-errors in our tests (yep, it finally works!)

- RELEASE.rst
- src/hypothesis/extra/numpy.py
- src/hypothesis/extra/pandas/impl.py
- src/hypothesis/internal/conjecture/utils.py
- src/hypothesis/internal/validation.py
- src/hypothesis/searchstrategy/collections.py
- src/hypothesis/searchstrategy/regex.py
- src/hypothesis/strategies.py
- tests/common/__init__.py
- tests/cover/test_argument_validation.py
- tests/cover/test_direct_strategies.py
- tests/cover/test_draw_example.py
- tests/cover/test_flakiness.py
- tests/cover/test_health_checks.py
- tests/cover/test_recursive.py
- tests/cover/test_sets.py
- tests/cover/test_simple_collections.py
- tests/cover/test_simple_numbers.py
- tests/cover/test_simple_strings.py
- tests/cover/test_stateful.py
- tests/cover/test_testdecorators.py
- tests/cover/test_validation.py
- tests/nocover/test_pretty_repr.py
- tests/nocover/test_recursive.py
- tests/nocover/test_strategy_state.py
- tests/quality/test_discovery_ability.py
The `average_size` argument was treated as a hint about the distribution of examples from a strategy.  In turn, this is a remnant of earlier versions of Hypothesis with a different conceptual model and much weaker engine for generating and shrinking examples.  More recent strategies simply describe what constitutes a valid example, and let the internals handle the rest.
Closes #1155.  See our API style guide or the linked issue for more details.  Notes:
- Behaviour of collection sizes has not changed if `average_size` was not specified before - the internal defaults were always overridden
- Once the argument is completely removed, backwards compatibility will remain trivial by use of keyword arguments (which are idiomatic now anyway)
> Deprecate average_size argument to lists(), sets(), etc

- tests/cover/test_testdecorators.py
Before this, `test_uses_provided_seed` uses database examples when they're there, and fails with this warning:
```
================================================================================================= FAILURES =================================================================================================
_________________________________________________________________________________________ test_uses_provided_seed __________________________________________________________________________________________
Traceback (most recent call last):
File "/Users/davidchudzicki/hypothesis-python/tests/cover/test_testdecorators.py", line 352, in test_uses_provided_seed
test_foo()
File "/Users/davidchudzicki/hypothesis-python/tests/cover/test_testdecorators.py", line 348, in test_foo …
```
> make test_uses_provided_seed stop failing on the second run

- guides/review.rst
Not specifically in response to discussion in #1190, but it prompted me to remember that a) this is something I've been thinking about recently and b) If it's a worthwhile principle it should be in the review guide!
NB. Comedy attempts to expand the scope of this pull request will be met with stern looks and eye rolling.
> Add section about scope creep to the review guide

- RELEASE.rst
- docs/stateful.rst
- src/hypothesis/stateful.py
- tests/cover/test_stateful.py
This fixes another long-standing annoyance: Almost the first thing you want to do with a stateful testing failure is turn it into a program that reproduces that failure. Why not make the computer do that for you??
Output from stateful testing now looks like:
```python
state = DatabaseComparison()
v1 = state.k(k=b'')
v2 = state.v(v=v1)
state.save(k=v1, v=v2)
state.values_agree(k=v1)
state.teardown()
```
Isn't that better?
Note: Currently we don't show invariants in this output. We probably should but there are a bunch of questions (showing them everywhere creates a lot of clutter. Do we show them only where they failed? What if there are side effects so that the invariant *should* have been checked before hand? What if the invariant has a precondition? etc.) that I decided not to try to …
> Improve printing of stateful testing

- docs/community.rst
This came up (in a fairly benign way! Nobody was threatened, and clearly no harm was meant) in a recent pull request, and I've had to ask people to similarly avoid such things on IRC a few times.
Given this is as far as I can recall the only remotely code of conduct shaped thing I've ever had to enforce, it seems worth making it explicit...
> Add Code of Conduct line against jokes about violence

- RELEASE.rst
- docs/details.rst
- docs/settings.rst
- src/hypothesis/_settings.py
- src/hypothesis/core.py
- tests/cover/test_verbosity.py
Closes #518, treating it as a docs issue (comparing arbitrary outputs is impractical, so our whole system is designed to work at the level of byte-streams).
In a similar vein, I've stopped `find()` from displaying this distinction when run in verbose mode (though of course it still happens in debug mode).  Finally, there are some more formatting and cross-reference fixes as usual.
> Improve docs for min_satisfying_examples

- .travis.yml
- Makefile
- RELEASE.rst
- docs/changes.rst
- setup.py
- tests/common/setup.py
- tox.ini
Django 1.8 will reach end of life tomorrow, so this patch removes our support for it.  Yay simpler build and install!
> Block install with EOL Django 1.8.x, as of 2018-04-01

- docs/stateful.rst
This does two things:
* Replace the introduction to stateful testing with one that doesn't claim that it's still new and experimental (this API has been basically unchanged for three years now) and explains the context and naming a bit better
* Replace the `GenericStateMachine` example with one that actually shows why on earth you might want to use this thing.
> Various improvements to documentation of stateful testing

- RELEASE.rst
- docs/database.rst
- src/hypothesis/_settings.py
- src/hypothesis/database.py
- tests/cover/test_duplication.py
- tests/cover/test_settings.py
- tests/cover/test_shrinking_limits.py
- tests/cover/test_verbosity.py
- tests/cover/test_weird_settings.py
- The `database_file` setting is deprecated in favor of the `database` setting, which is now implemented in the normal way (without otherwise changing their behavior).  Closes #175.
- From the same issue, `$HYPOTHESIS_DATABASE_FILE` is deprecated in favor of the settings profile system.
- If the `database` setting is using the default value (ie `.hypothesis/examples/`) and this directory is unusable due to e.g. permissions problems, we now issue a warning and fall back to an in-memory database (but *only* if the path was not set by the user).  Closes #242 and closes #768 - while it is still possible to have path-related problems, they will now be the user's responsibility.
- Added `settings(database=None)` to tests that fail if there are saved examples, to ease local development.
> Various improvements to the database setting

- RELEASE.rst
- appveyor.yml
- docs/changes.rst
- src/hypothesis/internal/cathetus.py
- src/hypothesis/strategies.py
- tests/cover/test_cathetus.py
Fixes #1207, non-exact results on [32-bit Windows](https://ci.appveyor.com/project/conda-forge/hypothesis-feedstock/build/1.0.172/job/wy4p8vutiirr676c).  As a library function `hypot()` is permitted epsilon relative error, I found that exact results were obtained on my 64-bit glibc machine and so imposed these more stringent requirements in the tests. Oops.
I've made the same change for calls to `cathetus()`, since that has the same permitted relative error (via `sqrt()`, _except_ for the subnormal tests, since those are essentially integer calculations.
> Allow relative error of floating-point epsilon in cathetus tests

- CODE_OF_CONDUCT.rst
- hypothesis-python/docs/community.rst
I've been thinking for a while anyway that we should move the code of conduct into [the official GitHub recognised location](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/) but in the bold new era of monorepoization it's extra important.
> The code of conduct is not just for the Python community

- hypothesis-python/RELEASE.rst
- hypothesis-python/setup.py
- scripts/hypothesistooling.py
Behold the shiny new renamed repository!
This PR updates the home page URL in the setup.py and also serves to test which of our CI systems have broken horribly by this rename.
> Update URL in setup.py

- hypothesis-python/docs/changes.rst
- scripts/hypothesistooling.py
Today is not a good day for our docs build.
Docs, yes, but not build :sob:
> Correct placement for changelog entry anchor

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/cover/test_conjecture_test_data.py
- hypothesis-python/tests/cover/test_regressions.py
Fixes #1230.
The root cause of this bug is that sometimes we would think we had data to discard as part of the fast-path for discarding values that were rejected during filter etc, but it all consisted of empty intervals so there wasn't actually any data in there. This could happen if you had something like a `sets(just(x))` that had to be non-empty in the final result.
> Don't count empty intervals as discards

- Makefile
- hypothesis-python/docs/changes.rst
- hypothesis-python/docs/settings.rst
- The `RELEASE.rst` for v3.56.1 had trailing whitespace; which the linter didn't catch because the paths hadn't been updated in the monorepoisation.
- A suggestion to use `HYPOTHESIS_VERBOSITY_LEVEL` was removed, and the previous changelog ammended to reflect the fact that it had existed.
- Fixed broken cross-reference syntax for a version link target (needs a `:ref:` before the backtick)
- Linkified other version numbers, discovering a typo in the process (3.28.4 does not exist; it now refers to 3.30.4 where we reduced the perf impact of coverage)
Ping @DRMacIver as this should un-break the build.  Note that the build is only broken by the linting error *after* the changelog is integrated, so 3.56.1 went out OK but further work will be broken.
> Fix build - recent issues in the docs

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/cover/test_given_error_conditions.py
- hypothesis-python/tests/cover/test_statistical_events.py
- hypothesis-python/tests/cover/test_testdecorators.py
- hypothesis-python/tests/cover/test_timeout.py
- hypothesis-python/tests/cover/test_unusual_settings_configs.py
- hypothesis-python/tests/pytest/test_capture.py
There was an off-by-one error in the logic in #1211 which meant that `max_examples=1` no longer worked. This fixes that.
> Handle small max_examples correctly.

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/tests/common/setup.py
- hypothesis-python/tests/cover/test_settings.py
Calculating the database default location at setting import time subtly broke our test suite by making it so that the example database was no longer isolated between runs. This might have affected other people as well, but the APIs for this were not currently documented (but I know some people are using them unofficially).
The fix for this a mess, and I think signposts that we really need to figure out how this all should work, but this at least gets us back to the previous behaviour.
> Fix database location

- hypothesis-python/docs/changes.rst
- hypothesis-python/docs/details.rst
- hypothesis-python/docs/examples.rst
- hypothesis-python/docs/settings.rst
- hypothesis-python/docs/support.rst
Shortly after #1244 was merged, I discovered that `settings.verbosity` was not documented with all the other attributes.  Now it is, and I've changed from a members whitelist to a wildcard+blacklist to prevent the problem coming back next time we change a setting.
I then did a general sweep for anything else I left out - missing links, confusing language or code examples, weird formatting, etc. and fixed the obvious bits.  Obviously this isn't comprehensive, but it helps :smile:
> Further documentation tweaks

- .gitignore
- .travis.yml
- hypothesis-python/RELEASE.rst
- hypothesis-python/setup.py
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/database.py
- hypothesis-python/src/hypothesis/internal/charmap.py
- hypothesis-python/src/hypothesis/internal/compat.py
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/src/hypothesis/internal/coverage.py
- hypothesis-python/src/hypothesis/internal/escalation.py
- hypothesis-python/src/hypothesis/internal/reflection.py
- hypothesis-python/src/hypothesis/searchstrategy/collections.py
- hypothesis-python/src/hypothesis/searchstrategy/lazy.py
- hypothesis-python/src/hypothesis/searchstrategy/strategies.py
- hypothesis-python/src/hypothesis/searchstrategy/types.py
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/src/hypothesis/strategies.py
- mypy.ini
- requirements/tools.in
- requirements/tools.txt
- tooling/src/hypothesistooling/__main__.py
This is the first batch of work toward #200.  I suggest reviewing the commits separately:
- Configuration, including marking the package as supporting type checking
- Changes to make the new `check-types` job pass in Travis
- Add basic type hints to `find`, `@given`, and most of `hypothesis.strategies`
By "basic" hints, I mean that they are correct but not particularly specific.   The obvious chunks of future work are to make `SearchStrategy` generic in the type of the examples it generates, and to annotate the rest of the API.
> Add basic static typing to the Hypothesis API

- .flake8
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/src/hypothesis/control.py
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/extra/django/models.py
- hypothesis-python/src/hypothesis/extra/numpy.py
- hypothesis-python/src/hypothesis/extra/pandas/impl.py
- hypothesis-python/src/hypothesis/extra/pytz.py
- hypothesis-python/src/hypothesis/internal/renaming.py
- hypothesis-python/src/hypothesis/searchstrategy/strategies.py
- hypothesis-python/src/hypothesis/strategies.py
- hypothesis-python/src/hypothesis/utils/conventions.py
- mypy.ini
Does not *quite* close #200 (next time though! :tada:)
I won't recite the whole motivation here - suffice to say that at least some people like static typing, and so I'd like to let the type-checker find some of their obvious misuses of Hypothesis.
Things not obvious from review:
- Mypy doesn't support arity-specific overloads, which would be useful for `tuples`.
- The `disallow_untyped_decorators` option is indispensable if you don't want a a decorator to erase the type hints on a function.
I would also like to write some tests using `reveal_type` to check that Mypy does in fact infer the expected type for various expressions.  This may go in a later PR, to keep things reviewable - I've confirmed most of this manually, so automated tests would really be for tooling or code regressions.
> Add type hints to the public API, with generic Strategy type

- hypothesis-python/RELEASE.rst
- tooling/src/hypothesistooling/__init__.py
This changes our tagging scheme for releasing Hypothesis for Python to prefix the tags with `hypothesis-python`, in line with #1224.
I originally started with a much deeper refactoring of this that tried to make this more generic and it rather got away from me, so this is instead a minimal viable change that just moves over our existing tagging.
> Prefix tags of Python releases

- hypothesis-python/RELEASE.rst
- tooling/src/hypothesistooling/__init__.py
The sequel to #1273. This now makes tags starting with `hypothesis-python` the only valid releases for versions of Hypothesis for Python (as you may have seen, we now also have backdated versions for all of the previous releases with a numeric tag name. I haven't bothered doing the same for ones that were on the old vX.Y.Z scheme).
> Only use tags whose name start with hypothesis-python for versions

- .travis.yml
This implements @alexwlchan's suggestion of using build stages in our Travis build. Continuing to use env vars as those actually show up in the build jobs (which has been working well for Hypothesis Ruby: https://travis-ci.org/HypothesisWorks/hypothesis-ruby/).
This splits the build up into four stages:
1. "Prechecks" - stuff that runs very little in the way of actual testing. Linting, formatting, type checking, etc. The idea is that anything where the likely outcome is that you go "Doh!" and immediately repush should get caught in a precheck.
2. "Main" which runs the bulk of our tests.
3. "Extra" which is primarily for checking compatibility with a number of different versions.
4. "Deploy", which does the obvious thing and just runs the deploy job.
Given that we're typically manually …
> Another attempt at using build stages

- tooling/src/hypothesistooling/__init__.py
- tooling/src/hypothesistooling/__main__.py
More work on plan "Get build times down when we start having multiple projects in the repo".
This adds more fine grained annotations to the tasks that generalises the previous `should_run_ci_task` logic, so tasks will only run if the part of the repo they depend on has changed.
This is still pretty coarse grained - e.g. changing any source file or any test will run all the tests - but should handle the use case of e.g. not building hypothesis-python for hypothesis-ruby tests.
> More fine grained checking of whether we need to run a task

- guides/review.rst
Maybe it would be better if this were more unified with the `Engine Changes` section (a single coherent "what needs to be reviewed by whom?" section), but I didn't bother doing that.
> drmaciver's hypothesis-ruby changes don't require review

- .travis.yml
- tooling/src/hypothesistooling/__init__.py
- tooling/src/hypothesistooling/__main__.py
- whole-repo-tests/test_pyup_yml.py
- whole-repo-tests/test_release_files.py
- whole-repo-tests/test_rst_is_valid.py
- whole-repo-tests/test_secrets.py
- whole-repo-tests/test_shellcheck.py
(Built on top of #1274 so that the build actually works. History will be much cleaner once that's merged and this is rebased, so you may want to hold off on reviewing until then).
One of @alexwlchan's suggestions for build time improvements in #1224 was that we should have fewer small build jobs. This PR adopts the principle that most of these little build jobs are basically tests, and we have this perfectly serviceable test runner right here...
We will go full galaxy brain when we start decorating some of these tests with `@given`, but thankfully we're not there yet.
>  Move a lot of small build jobs into tests

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/tests/cover/test_settings.py
This serves the purpose of hiding the method from Sphinx
when building the documentation.
Closes #1269
> Make settings.define_setting a private method

- hypothesis-python/tests/pandas/helpers.py
Fixes #1289.
I'm not sure why we suddenly started seeing this. I'd guess something changed in pandas that meant that a case where they were previously not converting the byte order they now were, but the check was always wrong.
> Always reject non-native byte order in pandas tests

- .travis.yml
- hypothesis-python/tox.ini
- tooling/src/hypothesistooling/__main__.py
Turns out that we have had a defined `check-pandas23` task for a month before [Pandas 0.23 was released](https://pandas.pydata.org/pandas-docs/version/0.23.0/whatsnew.html#v0-23-0)!
> Test Pandas 23 on Travis

- hypothesis-python/docs/conf.py
The url pattern https://github.com/HypothesisWorks/hypothesis/pulls/154 should be https://github.com/HypothesisWorks/hypothesis/pull/154 . The former goes to a pull request search page and queries for PRs with an author named '154'. See for example https://hypothesis.readthedocs.io/en/latest/development.html
I'm not sure whether this counts as a doc change, and doesn't need release.rst, or if it will trigger the check for release.rst. Creating the PR now in order to get this feedback from the build.
> Typo in macro for pull request link

- .travis.yml
- hypothesis-python/setup.py
Adding the trove classifier will signal that Hypthesis also acts as a pytest plugin. This will help https://plugincompat.herokuapp.com/ to find hypothesis, list it as a plugin and do regular installation checks.
> Add pytest framework trove classifier

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/minimizer.py
- hypothesis-python/tests/cover/test_conjecture_minimizer.py
Re-order input bytes without otherwise changing the input, from lowest to highest.
This is step 1 of https://github.com/HypothesisWorks/hypothesis/issues/1096 , which is also the source of the new test.
> Add a sort pass to the minimizer

- hypothesis-python/tests/common/debug.py
- hypothesis-python/tests/common/utils.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/cover/test_database_usage.py
- hypothesis-python/tests/cover/test_flakiness.py
- hypothesis-python/tests/cover/test_health_checks.py
- hypothesis-python/tests/cover/test_integer_ranges.py
- hypothesis-python/tests/cover/test_interleaving.py
- hypothesis-python/tests/cover/test_nesting.py
- hypothesis-python/tests/cover/test_randomization.py
- hypothesis-python/tests/cover/test_reproduce_failure.py
- hypothesis-python/tests/cover/test_settings.py
- hypothesis-python/tests/cover/test_testdecorators.py
- hypothesis-python/tests/nocover/test_boundary_exploration.py
- hypothesis-python/tests/nocover/test_collective_minimization.py
- hypothesis-python/tests/nocover/test_conjecture_engine.py
- hypothesis-python/tests/nocover/test_deferred_strategies.py
- hypothesis-python/tests/quality/test_discovery_ability.py
- hypothesis-python/tests/quality/test_poisoned_lists.py
- hypothesis-python/tests/quality/test_poisoned_trees.py
- hypothesis-python/tests/quality/test_zig_zagging.py
This pull is step one of a two-stage plan to deal with the `max_shrinks` setting (see #1235):
1. Do the easy part, by substantially reducing the use of `max_shrinks` in our own test suite.
2. Leave the hard parts for ~~someone else~~ later!  At least it will be a smaller job after this.
> Replace max_shrinks=0 with Phase setting in our tests

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/minimizer.py
- hypothesis-python/tests/cover/test_conjecture_minimizer.py
When a test case is generated and cannot be fully ordered, attempt to
still impose some order within it.
This is step 2 of https://github.com/HypothesisWorks/hypothesis/issues/1096
> Partially order a test case

- build.sh
- hypothesis-python/RELEASE.rst
- tooling/src/hypothesistooling/__init__.py
- tooling/src/hypothesistooling/__main__.py
- tooling/src/hypothesistooling/projects/__init__.py
- tooling/src/hypothesistooling/projects/hypothesispython.py
- whole-repo-tests/test_deploy.py
- whole-repo-tests/test_rst_is_valid.py
This is a refactoring of some of the build system to move the Python build components out into their own file, as a precursor to making the build multi-language.
The general intended approach here is to have each project we want to build be a module in `hypothesistooling.projects`, with a common interface. It *might* make sense to make these objects rather than modules at some point, but the module approach I think works pretty well as a first pass.
Bonus features:
* We now test our deploy code (kinda).
* Better handling of failed installs of the tooling (which we're getting a lot of right now due to some network flakiness)
> Factor out Python specific build components

- .circleci/config.yml
- .travis.yml
We have two tasks in the extras build stage in our Travis config that take *vastly* longer than everything else. Meanwhile CircleCI's machines seem to generically be much faster, and we're running less on them. This moves those tasks over there. Hopefully this should make our builds significantly faster and more reliable.
One minor downside of this is that our Travis deploy does not currently check if *other* CIs have passed before deploying. I think this is OK. These are only the extras jobs, and they had to pass in order to get a merge. In many ways I'd be more worried about the status quo (what we could in theory introduce a windows or OSX bug and have it missed this way) than that these are missing from the deploy pre-checks.
> Move slower tasks over to Circle

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/django.rst
- hypothesis-python/src/hypothesis/extra/django/models.py
- hypothesis-python/tests/django/toystore/models.py
- hypothesis-python/tests/django/toystore/test_given_models.py
If the primary key value is specified as part of the strategy, then
using get_or_create() doesn't do the right thing, since it will not
match existing rows that have the same primary key field but different
values in other fields.
This fixes #1307
> Correct the way that django models are instantiated

- tooling/scripts/ensure-rustup.sh
- tooling/src/hypothesistooling/__main__.py
- tooling/src/hypothesistooling/junkdrawer.py
- tooling/src/hypothesistooling/projects/hypothesisruby.py
~Two~ Three problems were occurring:
1. Silly error on my part where I wrote `os.path.unlink` instead of `os.link`. @alexwlchan based on your suggestion in #1339 I've ended up extracting a function to the junk drawer for safe unlinking as part of this.
2. Due to hilarious comedy, the change I made in #1332 for more robust checking for an install of the build environment meant that (on Travis only) we reran all failing jobs, because the `TASK` environment variable was overriding the `check-installed` command we were explicitly passing.
3. Our build was depending on rust nightly and thus hitting https://github.com/rust-lang/rust/issues/51699. I'm not sure why I went with nightly rather than stable (the library is definitely meant to work on stable!) so I've just switched this over to …
> Fix building of rubygems

- tooling/src/hypothesistooling/projects/hypothesispython.py
- tooling/src/hypothesistooling/projects/hypothesisruby.py
This is causing failing tests in branches, e.g. https://travis-ci.org/HypothesisWorks/hypothesis/jobs/395525489
```
_______________ test_release_file_exists_and_is_valid[project0] ________________
Traceback (most recent call last):
File "/home/travis/build/HypothesisWorks/hypothesis/whole-repo-tests/test_release_files.py", line 31, in test_release_file_exists_and_is_valid
project.parse_release_file()
TypeError: parse_release_file() missing 1 required positional argument: 'filename'
========================== slowest 20 test durations ===========================
```
> Add a project-specific parse_release_file for Python + Ruby

- tooling/src/hypothesistooling/__main__.py
This fixes a trivial issue where `build.sh format` would fail if there weren't actually any files to format (because it would call `pyformat` with an empty list of files).
> Return early if there are no files to format

- hypothesis-python/tests/pandas/test_indexes.py
As part of the entropy-pocalypse from #1295 we now have flaky coverage - line 60 in impl.py isn't being reliably hit. This adds a test that reliably hits it.
> Add test that reliably triggers dtype from elements detection

- hypothesis-ruby/RELEASE.md
- tooling/src/hypothesistooling/projects/hypothesisruby.py
Apparently I'd forgotten (and missed when porting the code over from Ruby) that we need to manually set a release date in the gemspec rather than it being calculated on upload. This fixes that.
> Fix release dates for rubygems

- conjecture-rust/RELEASE.md
- conjecture-rust/src/engine.rs
- hypothesis-ruby/RELEASE.md
> Fix failure when shrinking tests with duplicates in hypothesis-ruby tests

- hypothesis-python/.coveragerc
- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/conf.py
- hypothesis-python/src/hypothesis/internal/compat.py
- hypothesis-python/src/hypothesis/searchstrategy/attrs.py
- hypothesis-python/src/hypothesis/searchstrategy/types.py
- hypothesis-python/src/hypothesis/strategies.py
- hypothesis-python/tests/cover/test_attrs_inference.py
- hypothesis-python/tests/py2/test_from_type.py
- hypothesis-python/tests/py3/test_annotations.py
Closes #954.  If you have well-behaved classes defined using attrs, and use the various validation, typing, and conversion features without abusing them too badly, Hypothesis will be a little more magical :sparkles:  
The trick for users - as usual - is to handle everything that static analysis thinks might be a valid input!  It's a good habit in general, and I actually kinda like the tooling pushing me that way :smile: 
(as an implementer, I now remember why I haven't touched inference in a while...)
> Improve inference in builds() and from_type() for attrs classes

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/changes.rst
- hypothesis-python/docs/details.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/tests/cover/test_modify_inner_test.py
- hypothesis-python/tests/numpy/test_sampled_from.py
Closes #1257 - see that issue for motivation and discussion, along with python-trio/pytest-trio#42.  
I also have a working patch for pytest-trio (https://github.com/python-trio/pytest-trio/compare/master...Zac-HD:hypothesis-experiment), which enables the following example to work exactly as you'd hope:
```python
from functools import wraps
import pytest
from hypothesis import given, strategies as st
def decorator(f):
return wraps(f)(lambda *a, **k: f(*a, **k))
@pytest.mark.parametrize('x', [3, 1, 2])
@decorator  # just to be nasty...
@given(n=st.integers())
@pytest.mark.trio
async def test(n, x):
assert n // x < 50  # fails, obviously, but passes with integers(max_value=49)
```
The patch on our end is quite small, and should be generally applicable to other extensions for asyncio, Curio, …
> Add mechanism to replace wrapped test

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/nocover/test_conjecture_engine.py
- hypothesis-python/tests/nocover/test_explore_arbitrary_languages.py
In searching for #1299 I thought I'd write some tests that target the conjecture runner more directly 
(I also improved the repr for Status because that made the test output much easier to deal with. This isn't user facing because Status is non-public API).
Well I didn't find #1299, but I did find another bug in the same code.
I think one of the lessons from this is that there are actually a lot of very subtle, entirely implicit, and thoroughly undocumented invariants to maintain while shrinking that need to be clearer before other people can do much work on the shrinker. 😢
> Add more tests for shrinker and fix internal assertion error

- hypothesis-python/scripts/basic-test.sh
- hypothesis-python/tests/py3/test_annotations.py
- tooling/src/hypothesistooling/__main__.py
Fixes #1366 (cc @jochym), fixes #1367, closes #1368 by including a1c124ef99f63938294c047f8bc6cb8980b8dbee.
The "solution" here is to note that inferring strategies from types is always best-effort, and skipping those tests because the Python 3.5 `typing` module is not up for the task :sob:
> Fix attrs tests on Python <3.6; run Py3 tests in all Py3 jobs, run tests if test scripts change

- CITATION
- hypothesis-python/docs/changes.rst
- hypothesis-python/docs/community.rst
- hypothesis-python/docs/data.rst
- hypothesis-python/docs/details.rst
- hypothesis-python/docs/reproducing.rst
- hypothesis-python/docs/stateful.rst
- Closes #1315 by suggesting [![](https://img.shields.io/badge/hypothesis-tested-brightgreen.svg)](http://hypothesis.readthedocs.io/) for those who like badges.
- Closes #1338 by clarifing the documentation for `@composite` - including explicit comparison to `st.data()`.
- Closes #1356 by linking to our CITATION file.  We'll update again if or when we have a formal publication in e.g. [JOSS](https://joss.theoj.org/).
- Adds note suggested by @lennax on #1300 that `@rule` and `@pytest.mark.parametrize` do not work well together.
- Handles documentation portion of #1238, leaving the implementation of a verbosity option.
> Lots of small documentation improvements

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/statistics.py
- hypothesis-python/tests/cover/test_statistical_events.py
Closes #1346.  
It wasn't timezones, or system clock resets.  
It was (as far as I can tell) floating-point imprecision flipping the least significant bit of an intermediate value in `math.fsum`, which is in turn thanks to the system C libraries (but only on "some non-Windows platforms using **extended precision** arithmetic" [my emphasis]).  :sob: 
Anyway, it's now handled and has a regression test providing full coverage :sparkles:
> Fix zero-division, display in draw time stats

- tooling/scripts/ensure-rustup.sh
This doesn't matter much for our CI, but it's annoying when running locally if you have nightly installed in your toolchain as well.
> Change ensure-rustup.sh to only update rustup stable rather than all versions

- conjecture-rust/RELEASE.md
- conjecture-rust/src/data.rs
- conjecture-rust/src/engine.rs
- hypothesis-ruby/.rubocop.yml
- hypothesis-ruby/Gemfile.lock
- hypothesis-ruby/RELEASE.md
- hypothesis-ruby/lib/hypothesis.rb
- hypothesis-ruby/lib/hypothesis/engine.rb
- hypothesis-ruby/lib/hypothesis/errors.rb
- hypothesis-ruby/lib/hypothesis/junkdrawer.rb
- hypothesis-ruby/minitests/test_multiple_failures.rb
- hypothesis-ruby/spec/backtrace_spec.rb
- hypothesis-ruby/spec/multiple_failures_spec.rb
- hypothesis-ruby/spec/spec_helper.rb
- hypothesis-ruby/src/lib.rs
This adds the feature (already found in Hypothesis for Python) that when there are multiple exceptions triggered during shrinking, Hypothesis will report them all.
Notable oddities: 
* This involved some somewhat interesting shenanigans with the exception reporting. We use RSpec's native support for this if running on RSpec and create an exception with a custom message for use when running anywhere else.
* We have to do some exception backtrace mangling ourself because unlike in python land, assert is a function and so the backtrace always starts somewhere boring.
Otherwise, fairly straightforward port of the logic from Python land.
> Report multiple failures in Hypothesis for Ruby

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
This improves Hypothesis's ability to shrink examples which depend on the sum of two values.
The motivating example for this is the following:
```python
import numpy as np
import hypothesis.strategies as st
import hypothesis.extra.numpy as nps
from hypothesis import given
int16s = nps.from_dtype(np.dtype('int16'))
bounded_lists = st.lists(int16s, max_size=1).filter(lambda x: sum(x) < 256)
problems = st.tuples(
bounded_lists,
bounded_lists,
bounded_lists,
bounded_lists,
bounded_lists,
)
@given(problems)
def test_sum_does_not_overflow(p):
assert sum([x for sub in p for x in sub], np.int16(0)) < 5 * 256
```
This fails because you can get an overflow if the sum is large and negative. The ideal minimum example for it in Hypothesis's ordering is `([], [], [], [-1], [-32768])`, but previously we …
> Improve Hypothesis's ability to shrink sums

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/compat.py
- hypothesis-python/src/hypothesis/internal/reflection.py
- hypothesis-python/src/hypothesis/strategies.py
- hypothesis-python/tests/py3/test_lookup.py
@jbu reported that `builds()` did not infer arguments to NamedTuple instances and, noticing that the `__init__` method is a wrapper of `object.__init__`, started work on a patch.  Unfortunately his workaround did not resolve the issue.
This PR uses a different workaround for the `__init__` problem which is specific to `typing.NamedTuple`, adds a similar workaround to correctly calculate their required arguments, and (now that `builds()` works) removes the special case in `from_type()` in favor of the general fallback.
Closes #1309.
> Fix builds() argument inference for typing.NamedTuple

- tooling/scripts/ensure-rustup.sh
Apparently more recent versions of shellcheck don't like the use of `which`. This replaces our one use of it with its suggested replacement of `command -v`
> Make shellcheck happy about our rustup check

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
We're still seeing an AssertionError every now and then in shrinking - it seems to happen pretty reliably on hard to shrink tests, but I've yet to get a good reproducible test case for its current incarnation.
In the interests of a) Not spending time tracking this down and b) Making the shrinker easier to work on, I figured why not just relax the condition: Instead of erroring when given a non-shrink, why not just reject it?
So, that's what this PR does. It creates the possibility of silently ignoring slightly silly things, but I think we've demonstrated that this sort of incredibly hard to trigger condition around subtle invariants in the shrinker is a recipe for pain, so this seems like a good trade-off.
> Handle assertion error by making it not an error

- .travis.yml
- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/packaging.rst
- hypothesis-python/docs/strategies.rst
- hypothesis-python/docs/supported.rst
- hypothesis-python/docs/usage.rst
- hypothesis-python/setup.py
- hypothesis-python/tests/pytest/test_statistics.py
- hypothesis-python/tox.ini
- tooling/src/hypothesistooling/__main__.py
Closes #863, which was getting positively *venerable* for such a small fix.  It turns out that we haven't been compatible with Pytest 2.8 for some time (though with no complaints apparently this hasn't been a problem), so I've bumped the version and we should actually run the test now.
Also updated various small version-related things in the docs as I spotted them.
> Correct required version of pytest, actually test it, and bump version-related docs.

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/nocover/test_debug_information.py
The debug information we get out of shrink passes is a bit ad-hoc. Some have a debug at the beginning, some doesn't.
This was annoying me when trying to debug some stuff, so this adds a `@shrink_pass` decorator which adds some uniform logging around the passes to report both when the pass starts and stops and also what effect it had.
> Add common debug reporting mechanism for shrink passes

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
We have this neat trick in the shrinker where it looks out for areas of the byte stream that have been marked as discarded and automatically prunes it for you when doing other things.
This trick is so neat in fact that it resembles time travel!
A really helpful property for reasoning about the behaviour of the shrinker is that the example you are working on remains mostly stable up to the point where you're working - changes made to the byte stream can only affect things that happen after those bytes have already been read. This is true, but if you have automatic discarding it often looks like it's not! The problem is that if you make a change to an example that causes it to be discarded, the example you're working on can disappear out from under you.
This PR makes automatic discarding …
> Make automatic discarding less automatic

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/cover/test_stateful.py
The way that we were selecting rules in `RuleBasedStateMachine` was almost pessimal for the shrinker. The problem was that unrelated changes to the structure could completely change the interpretation of subsequent rules - if an earlier rule is useless but puts something into a bundle, you've now changed the number of rules that can be run, which means that everything that comes afterwards has its interpretation changed if you try to remove that!
Solution: Don't do that then. This changes the way we handle bundles and preconditions to just filter for validity. As a bonus that means we can construct the strategy up front and it should be faster during generation as well.
> Use a more stable strategy for selecting rules

- .travis.yml
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/utils.py
This changes how we group together values using the `many` helper from conjecture utils. The main effect of this is that now every step in stateful testing will show up as one example rather than two, which means that they are much easier to delete.
> Group example around whole loop iteration.

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/common/debug.py
- hypothesis-python/tests/common/setup.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
This adds a new deletion pass that should reliably shrink that flaky test we've been seeing, which I'm pretty sure is the result of 3.66.12 - the two blocks that were being deleted were no longer showing up as adjacent to the shrinker.
It also makes some minor improvements to the test suite.
> Add new block oriented deletion pass

- tooling/src/hypothesistooling/__main__.py
We just found ourselves in a state where we'd uploaded to pypi but lost the tag because it happened after the upload and had to recreate the release. This was non-ideal.
This changes it so we always try to push the tag first, leading to the less bad failure mode of having a tag with no release if something goes wrong.
Something else fishy is going on here which merits investigation, but I'm not sure exactly what and this fix at least seems a uniform improvement regardless.
> Push the tag immediately rather than after upload

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/changes.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/common/utils.py
- hypothesis-python/tests/cover/test_timeout.py
It turns out that aw hole bunch of mysterious shrink failures I've been seeing are because we never deprecated timeout in find, and the tests were triggering the timeout if they executed more than 1000 function calls. Argh.
This expands the deprecation by moving it into the engine.
~This is WIP because I expect a tonne of tests to fail as a result of it~. I forgot the obvious solution: Just turn timeouts off in `minimal`!
> Timeout is also deprecated in find

- hypothesis-python/tests/common/debug.py
- hypothesis-python/tests/cover/test_composite.py
- hypothesis-python/tests/cover/test_direct_strategies.py
- hypothesis-python/tests/cover/test_find.py
- hypothesis-python/tests/cover/test_flatmap.py
- hypothesis-python/tests/cover/test_float_nastiness.py
- hypothesis-python/tests/cover/test_integer_ranges.py
- hypothesis-python/tests/cover/test_nothing.py
- hypothesis-python/tests/cover/test_permutations.py
- hypothesis-python/tests/cover/test_recursive.py
- hypothesis-python/tests/cover/test_sets.py
- hypothesis-python/tests/cover/test_sharing.py
- hypothesis-python/tests/cover/test_simple_characters.py
- hypothesis-python/tests/cover/test_simple_collections.py
- hypothesis-python/tests/cover/test_simple_strings.py
- hypothesis-python/tests/datetime/test_datetime.py
- hypothesis-python/tests/nocover/test_boundary_exploration.py
- hypothesis-python/tests/nocover/test_collective_minimization.py
- hypothesis-python/tests/nocover/test_deferred_strategies.py
- hypothesis-python/tests/nocover/test_recursive.py
- hypothesis-python/tests/py3/test_lookup.py
- hypothesis-python/tests/quality/test_shrink_quality.py
We have a bunch of slightly flaky tests that use find. I'm 80% sure this is them hitting the timeout and us not having merged #1428 yet (at which point they'll become flaky in a different way). 
This PR moves almost (there are some that are tests of e.g error behaviour rather than the generated example) all tests using find over to one of `minimal` or `find_any`. It also updates `find_any` to also set `timeout=unlimited` so that that actually helps.
Methodology for most of this: `grep` for `find(` in our tests and manually inspect and fix the files to determine what the test was doing. Fix all the tests that CI complained about. This was as boring as it sounds.
> Move over use of find in tests to standard debug helpers

- .circleci/config.yml
- .travis.yml
- hypothesis-python/tox.ini
I noticed that our CircleCI build times had gone sky high. I think a lot of the problem is that although it is faster, it's sequential, and we'd moved two very expensive jobs over there.
This PR does a couple of things:
* It moves `check-coverage` and `check-pure-tracer` back to Travis
* It significantly reduces the size of `check-pure-tracer` because they're not very useful tests and they were taking 15 (!) minutes to run.
* It moves a bunch of tasks out of main and into extra so that they don't run needlessly.
Hopefully that should help our slightly monstrous build queue.
> Do less stuff in each build

- tooling/scripts/common.sh
Have you noticed that a) Our CI caches are > 2GB each and b) CircleCI currently takes 7 minutes to fetch the cache and 15 minutes to upload it?
Yikes, right?
Anyway it turns out that more than two thirds of that is virtualenvs. We're already caching the built Pythons and wheels, so building a virtualenv is *relatively* cheap, as long as disk is faster than network which is sure seems to be on these CI setups.
> Avoid caching virtualenvs

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
This is a teeny tiny refactoring that exists mostly in support of the evaluations I'll be running (but I think it's a net improvement in its own right), where it's useful to be able to run the greedy shrink loop body on its own.
> Extract greedy shrink loop body into its own method

- .circleci/config.yml
Having just slimmed down our CircleCI caches, this fattens them up again!
Specifically, I noticed that a) We weren't caching pip's downloaded and built wheels, which is unfortunate given that we're no longer caching our virtualenvs and b) We weren't caching homebrew, which takes a considerable time to update. This fixes both of those things.
> Improve our CircleCI caching

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
In the course of working on #1423 I managed to trigger a weird error inside the shrinker during about 1 in 20 runs of the quality tests.
```python-traceback
Traceback (most recent call last):
File "/home/david/hypothesis/hypothesis-python/tests/quality/test_shrink_quality.py", line 156, in test_dictionary
lambda t: len(t) >= 3)
File "/home/david/hypothesis/hypothesis-python/tests/common/debug.py", line 66, in minimal
random=random,
File "/home/david/hypothesis/hypothesis-python/src/hypothesis/core.py", line 1194, in find
runner.run()
File "/home/david/hypothesis/hypothesis-python/src/hypothesis/internal/conjecture/engine.py", line 444, in run
self._run()
File "/home/david/hypothesis/hypothesis-python/src/hypothesis/internal/conjecture/engine.py", line 790, in _run …
```
> Handle block losses in try_shrinking_blocks

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
In tracking down some tests that had become flaky as a result of the move over to `minimal` (where they would now error instead of silently timing out) I found the culprit was the random backtracking code, which basically meant they were doing triple the work they needed to.
So I wondered... is that code actually doing anything for us any more? The shrinker has improved a lot since it was introduced, and it was never very good in the first place.
Based on some sampling of the tests it was originally designed to support, it looks like the answer is no. CI will tell us if I'm missing anything I guess.
> Remove random backtracking

- hypothesis-python/RELEASE.rst
- hypothesis-python/tests/pytest/test_fixtures.py
- requirements/test.txt
- requirements/tools.txt
Closes #1448, with a version bump so @jochym has a target to build.
> Make tests pass under pytest 3.7.0

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/src/hypothesis/internal/conjecture/floats.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinking/__init__.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinking/common.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinking/integer.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinking/lexical.py
- hypothesis-python/tests/cover/test_conjecture_float_encoding.py
- hypothesis-python/tests/cover/test_conjecture_minimizer.py
- hypothesis-python/tests/cover/test_simple_collections.py
- hypothesis-python/tests/nocover/test_conjecture_engine.py
As part of #1423 we're going to start to have other sorts of shrinkers around, not just the lexical minimizer. This creates a common shrinking interface that currently only has one implementation but will very soon have more.
NB. the main shrinker in conjecture is not an implementation of this interface. The reason for that is that while these ones shrink concrete values, the main conjecture shrinker operates on conjecture data objects, which are a bit weirder. This could probably still be made to work, but it's not totally obvious how yet.
> Extract out a common shrinking interface

- .travis.yml
- hypothesis-python/tests/cover/test_pretty.py
- hypothesis-python/tox.ini
- tooling/src/hypothesistooling/__main__.py
Fixes #1451 (bad regex test) and closes #1454, testing against Django 2.1.  Not a release, because we've had quite a few lately and there are no code or docs changes here.
> Minor build updates

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinking/__init__.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinking/common.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinking/length.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
This updates our "adaptive delete" pass to be better at adapting to large tests, especially stateful testing.
It mostly does this by bringing it closer to [the adaptive algorithm as I originally proposed it](https://www.drmaciver.com/2017/06/adaptive-delta-debugging/). The version we were using is a bit weird and strange. This basically does hierarchical debugging, applying the algorithm to the children of each draw call.
One slightly interesting point which is something I only discovered in the course of the current work is that this now goes from the right rather than the left.
* The reason for this is basically that a) Deleting on the right is more likely to work because less depends on stuff on the right
* If we can delete either A or B but B is to the right of A, we want to delete B, …
> New version of the adaptive deletion pass

- hypothesis-python/tests/cover/test_conjecture_engine.py
We are apparently covering https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/internal/conjecture/engine.py#L1700 unreliably now since the change in `max_examples` when running under coverage. This adds a specific unit test to hit that line.
> Add a test for block loss during reoffsetting of pairs

- hypothesis-python/tests/quality/test_shrink_quality.py
This test appears to have become slightly flaky since its move over to minimal. This makes it less flaky by simplifying it slightly.
> Make test easier to satisfy

- hypothesis-python/tests/quality/test_shrink_quality.py
- tooling/src/hypothesistooling/__main__.py
A new battle in the ongoing war on build times.
TLDR: There should be no material differences between these tests on different Python versions. Where there are that's a bug we should find with other tests (and also due to the gradual decline of how much we care about Python 2, meh if there are).
> Don't bother running quality tests on 2.7

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinking/length.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/cover/test_conjecture_test_data.py
- hypothesis-python/tests/nocover/test_conjecture_length_shrinking.py
- hypothesis-python/tests/quality/test_poisoned_lists.py
Somewhat impressively, the new adaptive deletion pass was literally 100% broken but the tests we had for the pass specifically happened to work given that it now attempted to zero examples, and all of the quality tests the rest of the shrinker was able to pick up the slack.
Um, oops?
> Make new adaptive deletion pass actually work

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/cover/test_debug_information.py
This adds a useful debug report at the end of shrinking to help people (in this case me) debug WTF is going on and what bits of the shrinker cost a lot / don't work that well.
Example output:
```
---------------------
Shrink pass profiling
---------------------
Shrinking made a total of 254 calls of which 37 shrank.
Individual breakdown:
* adaptive_example_deletion made 85 calls of which 8 shrank.
* minimize_individual_blocks made 44 calls of which 15 shrank.
* interval_deletion_with_block_lowering made 39 calls of which 0 shrank.
* adaptive_zero made 35 calls of which 12 shrank.
* reorder_examples made 14 calls of which 0 shrank.
* block_deletion made 12 calls of which 0 shrank.
* pass_to_descendant made 9 calls of which 0 shrank.
* minimize_block_pairs_retaining_sum made 8 calls of …
```
> Better debug information for profiling shrink passes

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
In accordance with my recent observation that we should actually prioritise shrinking towards the end rather than the beginning because it's more likely to work, this makes the same change to lexicographic minimization: Shrink later blocks earlier.
This also has the advantage that when there are multiple candidate examples earlier in the test case that an index could be pointing to, this is likely to move them to the earlier one, which can help deletion later.
(There's not much in the way of testing for this as it's just a heuristic change, and I'm not really sure how to test that behaves correctly without overfitting in a way that would just cause the test to break the next time we wanted to change the heuristic)
> Run lexicographic minimization from the last block backwards

- hypothesis-python/docs/django.rst
Closes #1458.  There's no good way to tweak this to reference a different set of models without totally rewriting it, so instead I've just added a link to the models we're talking about.  The "total rewrite" school of docs improvement is still on the table for later, but not in this pull request.
> Link to the noted Django project

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/strategies.py
The second argument of `register_type_strategy` should accept either a strategy, or a callable which returns a strategy.
> Update type hints for `example`, `seed` and `register_type_strategy`

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies.py
- hypothesis-python/tests/cover/test_direct_strategies.py
Resolves #1476. Turns out when we recursively call `floats()`, we weren't always passing it in correctly.
The NaN test isn't fixing a bug; I just couldn't convince myself we were doing the right thing without writing a test first, and once I'd written it I figured it would be a useful counterpart.
> Make sure we always pass around the allow_infinite parameter

- guides/internals.rst
The issue links seem to have been redirecting successfully, but the source directory links were just broken.
> Fix old pre-monorepo links in internals.rst

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/tests/cover/test_conjecture_test_data.py
I was poking around in Conjecture, and noticed that `self.level` is manually maintaining a value that is always equal to the length of the example stack.
Since the depth is always read through a property accessor anyway, getting rid of the explicit level field seems like a net improvement.
> Track example depth implicitly, via the length of the example stack

- hypothesis-python/tests/cover/test_conjecture_test_data.py
In Python 2.7, `bytes(5)` is the string `'5'`, rather than five 0 bytes.
In this particular test, that doesn't matter much, because the draw still overflows as intended. But it shouldn't be testing subtly different things across Python versions.
(I ran into this in #1488, because I copied the `bytes` call into a new test where the difference actually mattered, so my test failed on 2.7.)
> Fix a latent Python 2.7 test bug: bytes(5) should be hbytes(5)

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/changes.rst
- hypothesis-python/docs/numpy.rst
- hypothesis-python/src/hypothesis/extra/numpy.py
- hypothesis-python/tests/numpy/test_gen_data.py
Closes #1385.  `npst.arrays` now checks whether generated array elements will overflow when placed in the output array, and issues a warning if they would.
The patch to *generate* single- and half-precision floats has been expanded and moved to #1432.  ~~Merge the other pull before this one, or we'll be giving users a new error without a ready solution.~~ Update: done.
> Improve Numpy strategies with small dtypes

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/numpy.py
- hypothesis-python/tests/numpy/test_argument_validation.py
I actually thought this was already public API - and mentioned it at conferences - but apparently not!  I've therefore added a brief docstring and some validation so it can be used downstream, by e.g. Pandas when they're generating data with related dtypes.  Closes #1485.
> Add npst.from_dtype to public API

- hypothesis-python/scripts/basic-test.sh
- hypothesis-python/tox.ini
This makes it possible to easily run the full test suite on a Mac developer machine (via the CI scripts), while still running a reduced set of tests on CircleCI.
(From <https://github.com/HypothesisWorks/hypothesis/pull/1494#discussion_r211073125>.)
> Stop assuming that macOS means we're running on CircleCI

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/nocover/test_conjecture_engine.py
I was reading through the tree traversal in `prescreen_buffer`, and made some observations:
- When we encounter a forced node, we pretend the buffer has that value, because that's what the test would end up doing.
- When we encounter a capped node, we pretend the buffer's value is saturated, because that's what the test would end up doing ...
... except that the latter isn't true! In reality, `draw_bits` will mask its raw byte value, not saturate it.
This results in situations where the prescreen rejects a novel buffer, or accepts a buffer that's equivalent to a past one.
----
I'm fairly confident this is a real bug, but not entirely. So a second opinion would be very welcome.
Also note that the first patch in the PR is a test that fails on master, followed by a patch that fixes it. That …
> Prescreen capped bytes by masking, not by saturating

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/changes.rst
- hypothesis-python/src/hypothesis/strategies.py
- whole-repo-tests/test_rst_is_valid.py
Plus a new test (using, uh, `grep`) to catch one of the more persistent typos.
This was originally meant to just fix my markup in the latest patch note, but I eventually stopped pulling on the string :stuck_out_tongue:
> Fix some markup in the changelog

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/cover/test_stateful.py
This release improves argument validation for stateful testing, closing #1457.
- If the target or targets of an `@rule` are invalid, we now raise a validation error rather than an internal exception.
- Passing both the `target` and `targets` arguments is deprecated.
- Passing the name of a Bundle rather than the Bundle itself is also deprecated.
> Stronger validation in stateful rules

- .circleci/config.yml
- appveyor.yml
This patch has two parts:
1. Bumping the CircleCI cache key, which is the only way to clear a broken cache.  I'm leaving #1507 open as it would be nice to have a systematic fix at some point, but we need to unblock everything else so this is OK for now.
2. Improving the wheel upload condition fixes #1508, which was showing up as test failures for every release when no tests are failing.  This annoys me because our build *should* be green :fire: 
Merging this will allow CI to pass for all of @Zalathar's PRs, and set us up for the PyCon AU sprints this weekend.
> The really quick CI patch

- CONTRIBUTING.rst
Despite my earlier objections, I ended up writing a moderately-quick PR which fixes #1501.
I ended up having to rewrite a few paragraphs to keep making sense, and I hoisted the actual test invocations above the less-immediately-important commands like `format`.
> Remove obsolete references to Makefiles from CONTRIBUTING.rst

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
The original comment started by trying to describe a trivial example, but then listed the characteristics of a non-trivial example.
> Fix description of when an Example is "trivial"

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/nocover/test_conjecture_engine.py
This adds support for `self.capped` to `cached_test_function`, to bring it in line with `prescreen_buffer`.
> Check for capped bytes in cached_test_function

- hypothesis-python/docs/changes.rst
- hypothesis-python/docs/extras.rst
which is making all the builds fail.  See #1515 for source; forthcoming issue for underlying problem.
> Fix trailing whitespace in changelog

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/nocover/test_conjecture_engine.py
~~(Depends on #1505; don't merge this until that has been merged and this has been rebased.)~~
This is a follow-up to the observation in https://github.com/HypothesisWorks/hypothesis/pull/1494#discussion_r211069136 that “capped” isn't a very accurate description of these values, which are primarily byte masks.
This PR first adds assertions in the places where we use a mask as something other than a mask. Then it renames `capped` to `masks`, and `capped_indices` to `masked_indices`.
> Rename 'capped' to 'masks' in ConjectureRunner and ConjectureData

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/charmap.py
- hypothesis-python/tests/cover/test_charmap.py
While reviewing #1522, I noticed some low-hanging coverage fruit. This adds a test for that branch.
> Add a test that an error thrown when caching `charmap()` isn't shown to the user

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/charmap.py
This PR replaces pickle with json and tuple in charmap.py - closes #1512 
Issue addressed during PyCon AU 2018 sprints.
> Replace pickle with json in charmap.py

- requirements/tools.in
- requirements/tools.txt
- tooling/src/hypothesistooling/projects/hypothesisruby.py
- whole-repo-tests/test_version_sync.py
Uses the toml library to parse the Cargo.toml file properly, then just uses a string compare to check that the corresponding string exists in the Gemfile.lock file.  Closes #1337.
> Check that the Cargo.toml and Gemfile.lock files have matching helix versions

- hypothesis-python/docs/changes.rst
- hypothesis-python/tests/cover/test_control.py
Closes #1543, where a test added in #1535 needed to run without the database.
> Fix failing test, changelog formatting

- .gitignore
Now that #1541 has made some tests run with `PYTHONOPTIMIZE=2`, we should tell Git to ignore the `.pyo` files that can be produced by a test run.
> Ignore *.pyo files in .gitignore

- CONTRIBUTING.rst
- hypothesis-ruby/RELEASE.md
- hypothesis-ruby/lib/hypothesis.rb
- hypothesis-ruby/lib/hypothesis/possible.rb
- hypothesis-ruby/src/lib.rs
I was reading through the code for the ruby bindings to figure out if I want to have a play with it and noticed a couple minor issues in the documentation. Figured I may as well fix them while I was there. The only change I'm not sure about is for `lib.rs` but given that file is alone in its directory, I'm guessing that change has already happened.
> Minor improvements to hypothesis-ruby documentation

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/searchstrategy/regex.py
- hypothesis-python/src/hypothesis/strategies.py
- hypothesis-python/tests/cover/test_regex.py
- hypothesis-python/tests/cover/test_slippage.py
This release adds a `fullmatch` flag to `hypothesis.strategies.from_regex`. When set, the whole generated example will match the regular expression pattern. This mirrors the functionality of Python's `python:re.fullmatch`. Fixes #840.
> Add fullmatch flag to strategies.from_regex

- hypothesis-python/tests/cover/test_health_checks.py
While the inconsistency of this filter doesn't seem to affect its surrounding test, it does corrupt the input-cache tree in `ConjectureRunner`.
> Fix a flaky filter in test_suppressing_filtering_health_check

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
These are my notes from reading through the tree traversals in `engine.py`.
I've tried pretty hard to make sure they are actually accurate, but there is still potential for error.
> Add comments to all tree traversals in ConjectureRunner

- hypothesis-python/tests/cover/test_health_checks.py
This test could occasionally fail, because it would manage to generate 10 valid examples (the empty list) before generating 20 overflowing examples.
The engine's tree cache was unable to prevent these redundant valid examples, because its mechanism for encouraging diversity interacts poorly with `biased_coin`.
Fixes #1492.
> Fix a flaky test for HealthCheck.data_too_large

- .gitignore
- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/changes.rst
- hypothesis-python/docs/details.rst
- hypothesis-python/docs/django.rst
- hypothesis-python/docs/healthchecks.rst
- hypothesis-python/docs/numpy.rst
- hypothesis-python/docs/settings.rst
- hypothesis-python/src/hypothesis/errors.py
- hypothesis-python/src/hypothesis/extra/django/models.py
- hypothesis-python/src/hypothesis/extra/numpy.py
- hypothesis-python/src/hypothesis/strategies.py
- requirements/tools.txt
- tooling/src/hypothesistooling/__main__.py
- whole-repo-tests/test_rst_is_valid.py
With enough hyperlinks, the structure of our docs matters much less - users can easily jump around until they find what they need, or simply open the reference to something interesting in another tab for later.  That requires our cross-references to actually work though, and hence this pull.
With thanks to Trio, where I spotted the `-n` flag.  The CI trade is bidirectional!
> Run Sphinx in nitpick mode, fix broken cross-references

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/cover/test_simple_collections.py
- hypothesis-python/tests/nocover/test_conjecture_engine.py
(Fixes #1299, fixes #1581.)
This PR adds a regression test for the existing bug (together with a handy new test helper), and then fixes the bug by dropping `current` entirely, and reading block information directly from `self.shrink_target` instead.
While I was in the neighbourhood, I also tweaked the docstring for the affected shrink pass. And I added a note to the suspicious-looking test that sent me chasing after #1581 in the first place.
> Fix a rare IndexError in shrink_offset_pairs

- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/nocover/test_conjecture_engine.py
It turns out that my new shrinking test helper in #1585 was such a great idea that it already existed (via #1470 and #1478).
So I removed my "new" helper, and changed my test to use the existing `@shrink` helper instead.
> Remove the new shrinking test helper, and use the existing one instead

- hypothesis-python/RELEASE.rst
Turns out that the new nitpicky mode from #1575 had not yet been merged when #1584 had its most recent build, so when the latter was merged to master the tests failed.  Fixing this cross-reference will therefore finish the stalled release process that is currently blocking any other PRs from building.
CC @Zalathar, @HypothesisWorks/hypothesis-python-contributors with my apologies :disappointed_relieved:
> [Urgent - failed release] Fix Sphinx cross-reference

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/nocover/test_conjecture_engine.py
This change introduces `Shrinker.for_each_pair_of_blocks`, and updates shrinker passes `shrink_offset_pairs` and `minimize_block_pairs_retaining_sum` to use it instead of manually iterating over block pairs.
Along the way it introduces a `Block` class that `ConjectureData` now uses to record its block information, instead of keeping a list of `(start, end)` pairs.
> Factor out iteration over pairs of blocks

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/tests/cover/test_settings.py
I've now seen a couple of places have to debug timeout or healthcheck (etc) problems where their settings were having no effect... because they were assigning them on the *class* `hypothesis.settings`, and thus missing the explicit error from trying to mutate a settings *instance*.  Since [errors should never pass silently](https://www.python.org/dev/peps/pep-0020/#the-zen-of-python), trying this now raises an `AttributeError` too.
> Make assigning attributes of the settings class an error

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/data.rst
- hypothesis-python/docs/settings.rst
- hypothesis-python/src/hypothesis/searchstrategy/strategies.py
- hypothesis-python/tests/cover/test_recursive.py
I tracked this down to a bug in OneOfStrategy, where if `bias is not None` the sampler might be operating off the pre-flattened list of strategies.  In the case where two strategies are identical, this can be shortened by flattening and thus trigger an IndexError.  The fix is simply to calculate the biased sampler values *after* flattening the strategies list, if we're using it at all.  Closes #1502.
> Fix internal error in recursive()

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
This PR fixes three unrelated problems in the docstring for `reorder_examples`:
- The introduction refers to label-matching, which the current implementation no longer appears to do.
- The name of the example test function doesn't match what it's testing.
- There is a missing \`\` after ``x=""``.
> Fix errors in the docstring for reorder_examples

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies.py
The extra `draw` function for composite strategies has been a no-op since `data.mark_bind()` was removed a few years ago.  Removing it has slight performance gains, but mostly it shortens the stack - good for avoiding overflows, and user happiness (even if #1582 means that will only apply in debug mode).
I also noticed (while fixing a typo in a comment) that the shuffle for `permutations` would always finish with a no-op, so I cut that out too.
> Minor refactorings for composite and permutations strategies

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/tests/nocover/test_regressions.py
`stacklevel=3` used to point at the call site in user code, but now points into the lazy reification machinery.  Changing that to `stacklevel=2` points it back at the call to `note_deprecation`, which is still useful.
Closes #652.
> Fix deprecation warning stacklevel

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/tests/cover/test_settings.py
Specifying a boolean value is now deprecated, and specifying True will now have the expected effect instead of silently suppressing the blob.
Specifying any other value is now an error.
Closes #1612.
> Check that the print_blob setting is a PrintSettings value

- requirements/tools.txt
3.0 was incompatible with pip 18.1, which has been making our `check-requirements` test fail.  So this is a tiny patch to get the fixes from jazzband/pip-tools#689
CC @HypothesisWorks/hypothesis-python-contributors - every build will fail until we merge this!
> Fix pip-tools version

- .flake8
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/extra/fakefactory.py
- hypothesis-python/src/hypothesis/reporting.py
- hypothesis-python/src/hypothesis/searchstrategy/types.py
- hypothesis-python/tests/cover/test_conjecture_test_data.py
- hypothesis-python/tests/numpy/test_gen_data.py
- requirements/tools.in
- requirements/tools.txt
Inspired by #1491, this adds a lint pass that detects uses of `bytes`, and suggests using our compatibility wrappers `hbytes` or `binary_type` instead.
~~There are a few existing places that appear to truly need the real `bytes` (on Python 2.7), which are now marked with `# noqa: B1`.~~
Some caveats:
- This kind of change to the build infrastructure is new territory for me.
- I have no idea if `flake8-alfred` is any good; it's simply the first plugin I found that detects this sort of thing.
- ~~The locations marked with `# noqa: B1` could use some inspection to double-check that `bytes` is truly necessary.~~
- ~~It's possible that some of those ignored locations could be fixed by switching to a *different* compatibility wrapper instead.~~
- If this works well, there are a few other …
>  Use flake8-alfred to forbid use of bytes()

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/django/models.py
- hypothesis-python/src/hypothesis/internal/validation.py
- hypothesis-python/src/hypothesis/strategies.py
- hypothesis-python/tests/cover/test_validation.py
- hypothesis-python/tests/nocover/test_pretty_repr.py
Sets default `min_size=0` instead of `min_size=None`.
Closes #1618.
> min_size arguments default to 0

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/tests/nocover/test_cacheable.py
For equivalent effect but better behaviour around memory use and garbage collection.  Fixes #493.
> Avoid caching internal strategy that has a reference to the test class

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
As suggested by https://github.com/HypothesisWorks/hypothesis/pull/1594#discussion_r219732109.
Let me know if anything seems unclear or misleading.
> Add docstrings and comments for Example and Block

- hypothesis-python/tests/common/setup.py
I basically copied the code by @Zac-HD in #1630 with a slight change of the module argument.
Closes #1630
> Tests no longer fail with a DeprecationWarning for users of pluggy<0.6.

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/shrinking/length.py
- hypothesis-python/tests/nocover/test_conjecture_length_shrinking.py
This PR (hopefully) makes it easier to understand how `Length.run_step` works.
First it replaces `j` and `i + 1` with more meaningful variable names, based on my interpretation of what's happening.
Then it adds an overall description of the shrinking process, step-by-step comments, and a diagram to put each variable and slice into context.
----
This is a stand-alone change that doesn't fix or change any behaviour, so there's no particular hurry to get it merged.
I recommend looking the variable-renaming commit on its own, because the combined diff makes it a bit harder to see that the new version is equivalent.
> Explain how Length.run_step works

- hypothesis-python/docs/stateful.rst
Hello again! I noticed this small mistake in the stateful docs: the docs suggest `settings` can be set at `FiniteStateMachine.settings` when it is actually at `FiniteStateMachine.TestCase.settings`.
I realize that this is a pretty light PR. If that is a problem, I'd be happy to flesh this PR out with additional doc improvements. I could add some notes on using `@settings(...)` with state machines (... which I probably should have done in my last PR). I'm open to other suggestions too :smile:
> Fix code example error in stateful docs

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/src/hypothesis/internal/escalation.py
- hypothesis-python/src/hypothesis/internal/reflection.py
- hypothesis-python/tests/cover/test_escalation.py
Closes #848, with [an approach adapted from `trio`](https://vorpus.org/blog/beautiful-tracebacks-in-trio-v070/).
Basically we just strip frames off the traceback until we reach one that did not come from a Hypothesis file, attach the shortened traceback to the exception, and raise it.  Then our `@proxies` decorator overwrites the frame location so it doesn't look like a Hypothesis file... so there's a cute trick where we inject an entry into the frame globals and check for that too when unwinding.
<details><summary> comparison of old and new output from pytest</summary>
Here's a very simple test suite:
```python
from hypothesis import given
from hypothesis.strategies import integers
@given(integers())
def test_simple(x):
assert x
@given(integers())
def test_multiple_failures(x):
if x > …
```
> Elide internal frames from tracebacks, to focus on user code

- conjecture-rust/Cargo.toml
- conjecture-rust/RELEASE.md
- conjecture-rust/src/database.rs
- conjecture-rust/src/engine.rs
- conjecture-rust/src/lib.rs
- hypothesis-ruby/Gemfile.lock
- hypothesis-ruby/RELEASE.md
- hypothesis-ruby/lib/hypothesis.rb
- hypothesis-ruby/lib/hypothesis/engine.rb
- hypothesis-ruby/spec/database_spec.rb
- hypothesis-ruby/spec/multiple_failures_spec.rb
- hypothesis-ruby/spec/spec_helper.rb
- hypothesis-ruby/src/lib.rs
Long overdue feature addition: This adds support for the example database to Hypothesis for Ruby.
I'm not *super* happy with some bits of it - there's a lot of places where it will just panic if bad things happen filesystem wise, but I think that's OK- generally the correct things to do there are fix the problem or disable the database, so there's not much else we can really do.
As per usual rules for Hypothesis for Ruby, this doesn't need a full review, just a green build, but feel free to look over it.
> Add example database functionality to Hypothesis for Ruby

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/tests/cover/test_core.py
Extracted from #1609 to match the behavior added to stateful testing in #1373, without the multiple-user-facing-feature 🔊klaxon🔊 going off.
> Shrink errors from pytest.fail() in given, not just stateful testing

- CONTRIBUTING.rst
- guides/internals.rst
This method was renamed in 1dd3fe212a5fa18a56f.
> Update pass name in internal docs

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/cover/test_settings.py
This PR adds an explicit error to help prevent users from mistakenly assigning settings to the settings attribute of their state machine class. Ex:
```python
class Machine(GenericStateMachine):
pass
Machine.settings = settings(...)  # will now raise an error
```
I'm getting a strange error on when I run `./build.sh check-coverage` locally. I'm interested to see if this error shows up in CI.
Closes #1643.
> Add explicit error for assigning to settings attribute of state machine

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/changes.rst
- hypothesis-python/src/hypothesis/searchstrategy/strings.py
- hypothesis-python/src/hypothesis/strategies.py
- hypothesis-python/tests/cover/test_simple_strings.py
- whole-repo-tests/test_doctests.py
Extracted from #1621, because we have a one-feature-per-release policy and because the deeper internals changes there are taking a long time to get right.
- Expands documentation of `text()`, because Unicode is hard!
- Makes the default alphabet explicit, because that's better than implicit.
- Kills a bunch of dead code, some dating to Hypothesis 1!
> Clarify the API and docs for st.text()

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/reflection.py
- hypothesis-python/src/hypothesis/strategies.py
- hypothesis-python/tests/cover/test_type_lookup.py
- hypothesis-python/tests/py2/test_from_type.py
```python
class C(object): pass
from_type(C).example()
```
Thanks to @ccxcz for reporting that this was broken on Python 2, because `required_args` returns None for non-callable types - such as the slot wrapper on `object.__init__`.  Closes #1655, closes #1656.
> Fix from_type on Python 2

- CONTRIBUTING.rst
- hypothesis-python/docs/examples.rst
Updated the voting example to use permutations.
Decisions made:
- Used strings containing the letters A, B and C instead of numbers, to stay closer to the presentation of the problem
- Used 3 candidates instead of an arbitrary amount of candidates between 1 and 5, to simplify and stay closer to the presentation of the problem
> Change the voting example to use permutations

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/strategies.rst
- hypothesis-python/setup.py
As follow-up to #1661, I asked for a new trove classifier as described in [the PyPI FAQ](https://pypi.org/help/#new-classifier) (pypa/warehouse#4973).  They quickly created `Framework :: Hypothesis`, which can be used by all Hypothesis-related packages to make it easy for users to find them.  Thanks to @fkromer for prompting me to ask PyPA for this!
Next steps: contact all our featured extensions and encourage them to add the classifier.  After that, we can rely on natural growth :rocket:
> Use new Hypothesis trove classifier!

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/pytestplugin.py
- hypothesis-python/src/hypothesis/statistics.py
- hypothesis-python/tests/pytest/test_statistics.py
Closes #700.  
I moved some reporting code to `Statistics.get_description()`, because `xdist` can move lists of strings between processes but not arbitrary objects.  Hopefully this will be useful for future work on #437.
> Fix statistics reporting when running under pytest-xdist

- .isort.cfg
- .travis.yml
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/internal/reflection.py
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/src/hypothesis/strategies.py
- hypothesis-python/tests/cover/test_stateful.py
Which allows more settings to apply to stateful tests, including deadlines and healthchecks.  `@seed` and `@reproduce_failure` are now supported for stateful tests.  `pytest.fail()` is now supported for all tests with `@given` (previously special-cased for stateful tests; see #1372).
Closes #164, closes #1213, closes #1300.
The basic logic is obvious - just use `@given` and `st.data()` to drive the state machine - and after that it's just a matter of bookkeeping to ensure that all the auxiliary features work as expected.
After merging, I'll open an issue to deprecate `find()` and `GenericStateMachine`.
> New given-based backend for stateful tests

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/database.py
- hypothesis-python/src/hypothesis/extra/datetime.py
- hypothesis-python/src/hypothesis/extra/fakefactory.py
- hypothesis-python/src/hypothesis/extra/numpy.py
- hypothesis-python/src/hypothesis/extra/pytestplugin.py
- hypothesis-python/src/hypothesis/internal/charmap.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/src/hypothesis/internal/conjecture/utils.py
- hypothesis-python/src/hypothesis/internal/renaming.py
- hypothesis-python/src/hypothesis/internal/validation.py
- hypothesis-python/src/hypothesis/searchstrategy/collections.py
- hypothesis-python/src/hypothesis/searchstrategy/strategies.py
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/src/hypothesis/strategies.py
- hypothesis-python/tests/common/utils.py
- hypothesis-python/tests/cover/test_renaming.py
- hypothesis-python/tests/cover/test_settings.py
- hypothesis-python/tests/nocover/test_regressions.py
This adds the initial "since=" argument to note_deprecation, as described in #1697, but currently we don't act upon it.
I made it a required argument immediately because:
1. It's not part of the public API
2. I had a way to guess when most deprecations were introduced (see script below)
3. It saves us extra work later
```python
#!/usr/bin/env python
import subprocess
for line in subprocess.check_output(
"grep -rnI note_deprecation hypothesis-python --exclude-dir=.tox | tr ':' ' ' |  grep -v def | grep -v import",
shell=True
).decode("utf8").splitlines():
filename, lineno, *_ = line.split()
diff_output = subprocess.check_output(
f"git log --pretty=format:'%ai' -L {lineno},{lineno}:{filename}", shell=True
).decode("utf8")
date_str = diff_output.splitlines()[0].split()[0] …
```
> Track deprecation information with 'since' internally

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/utils.py
- hypothesis-python/src/hypothesis/searchstrategy/datetime.py
- hypothesis-python/src/hypothesis/searchstrategy/numbers.py
- hypothesis-python/src/hypothesis/strategies.py
- hypothesis-python/tests/cover/test_conjecture_utils.py
- hypothesis-python/tests/cover/test_slippage.py
> The root of the [many test timeouts] is the `geometric` helper in conjecture utils, which ends up mapping quite complicated values to quite simple integers. We should change that format, and generally avoid things that look like the `geometric` helper.
This patch removes the `geometric` helper, which was only ever used for `integers()` with one bound, and thus closes #1452.
It also ensures that such integers shrink to `0` as documented rather than shrinking to the bound, and cleans up some minor dead code related to integer generation.
> Improve shrinking of integers() with one bound

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/pytestplugin.py
Closes #1708 
Python 2.8.0 switched from pytest.mark to pytest.hookimpl / pytest.hookspec "for setting impl/spec specific parameters."
Please let me know if there is anything I've overlooked or if I have missed anything important documentation wise!
> Replacing depreciated decorator

- .travis.yml
- hypothesis-python/tox.ini
Closes #1702 
#1699 updated `pytest-xdist` to version 1.25.0 which depreciated versions of pytest<3.6.0
By running pytest30 in an environment with pytest-xdist==1.24 we are able to use versions of pytest>=3.0.0
I'm aware that the information in RELEASE.rst might be wrong or too verbose, so if you have a suggestion please do not hesitate to share!
> Re-enabling pytest30 using pytest-xdist

- hypothesis-python/tests/cover/test_lambda_formatting.py
- tooling/src/hypothesistooling/__main__.py
This restores the intelligent file selection that the previous formatter was set up to use.
(From https://github.com/HypothesisWorks/hypothesis/commit/71489455c9b62abf1de813c468094ddf63c279af#r31775407 in #1692.)
> Only run Black on modified files

- tooling/src/hypothesistooling/__main__.py
This is a minor cleanup of some seemingly-unnecessary build system code that I noticed while working on #1715.
It seems that at some point the Python file header template was stored in a `scripts/header.py`, which was then excluded from formatting. But there is currently no such file, since the header is stored inline in `hypothesistooling/__main__.py`.
> Remove old references to "header.py" from the build system

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/coverage.py
- hypothesis-python/tests/cover/test_validation.py
- hypothesis-python/tox.ini
Closes #1718.
~~This is a WIP because we still need to fix (or suppress) the existing coverage holes that were unmasked by this fix.~~
(I also took the liberty of borrowing Zac's shorter-path patch from #1712, since it will make that cleanup more pleasant.)
> Don't truncate "branch-check" multiple times during coverage tests

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/reflection.py
- hypothesis-python/tests/cover/test_lambda_formatting.py
- hypothesis-python/tests/cover/test_reflection.py
- hypothesis-python/tests/py3/test_unicode_identifiers.py
Closes #1700.
@lucaswiman’s guess is correct:
> This seems to be an off-by-two error with this example (source is 'mbda x: abs(x) > 1e-5))'), so I'm guessing it's probably that col_offset is computed on the bytes of the original file (UTF-8 encoded in this case)
The `inspect` module gives you source code as Unicode strings, but computes the index with the raw bytes. Doing a quick round-trip to bytes and back (using the same encoding detection as inspect is using) seems to fix this particular issue.
Fun little bug to dig into.
> Don't error on a Lambda in a line with Unicode identifiers

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/tests/cover/test_error_in_draw.py
- hypothesis-python/tests/cover/test_intervalset.py
Turns out that the reason that #1729's build is failing is because of a bug that has been latent for a *long* time. Essentially, errors in finally blocks are not handled correctly by `given`. @Zac-HD's port of the stateful testing to be given based meant that we could now also trigger this bug in stateful testing, it's just that we'd been lucky enough not to before now.
Basically the problem is that if in the course of shrinking or generation we do something that causes the data to be frozen, but we do so in such a way that user code can raise an error after that happened, we would try to call `mark_interesting` on an already frozen data object, which is forbidden.
The fix is to not do that and instead to raise a new `StopTest` to replace the one that was suppressed by the user error.
> Handle errors that occur once a data object is already frozen

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/shrinking/common.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinking/length.py
- hypothesis-python/tests/common/costbounds.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/nocover/test_conjecture_length_shrinking.py
When deleting (or making sequence manipulations in general) there's a tension between which order we want to go in. Changes early in the sequence are less likely to work, changes later in the sequence are more likely to produce tiny effects.
Previously we've chosen to do this from right to left in order to get the more likely to work effect. This works reasonably but has the problem that when the example is very large and slow we end up doing a lot of teeny tiny shrinks that don't get us to the small and fast examples that we'd like to have. 
This PR changes the algorithm to proceed in random order. This should help us strike a good happy medium - sometimes we'll try large changes which might work, sometimes we'll try small changes that probably will work. The result should be a shrinker …
> New randomized algorithm for length shrinking

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/django/models.py
- hypothesis-python/src/hypothesis/provisional.py
- hypothesis-python/tests/cover/test_provisional_strategies.py
- hypothesis-python/tests/django/toystore/models.py
Add an HTTP/HTTPS URL strategy.
Work toward solving issue #1388 
> #### What I have added:
> * path generation
> * port generation
> 
> #### What I haven't done:
> * utf-8 support (only ASCII URLs for now)
> * query support (the part after the `?`)
> * using an IP address in lieu of a domain
> * using mixed (upper and lowercase) case hexadecimal for escaping
> * percent encoding random safe characters
> 
> For the hosts, I'm reusing the `domains()` strategy.
> For the path, non safe characters get [percent-encoded](https://en.wikipedia.org/wiki/Percent-encoding) according to [RFC 1738](https://tools.ietf.org/html/rfc1738#section-5).
> Right now I am encoding `;`, `:`, `@`, `&`, `=`, even though they are technically valid for HTTP URLs.
> 
> #### Things I am not sure about
> * I am unsure …
> Add url strategy

- hypothesis-python/docs/packaging.rst
- hypothesis-python/docs/quickstart.rst
- hypothesis-python/docs/usage.rst
As spelled on https://pypi.org/.
> Correct capitalization of PyPI

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/nocover/test_conjecture_engine.py
This fixes a long-standing issue that we would often uselessly re-execute
the test function in cases where we knew full well it couldn't possibly succeed.
We do this by returning a dummy standin object for a full ConjectureData instance.
This allows us to unify prescreen_buffer and cached_test_function because the
former only existed to handle cases that are now correctly handled by the latter.
> Detect potential overflows in cached_test_function

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/changes.rst
- hypothesis-python/docs/django.rst
- hypothesis-python/src/hypothesis/extra/django/__init__.py
- hypothesis-python/src/hypothesis/extra/django/_fields.py
- hypothesis-python/src/hypothesis/extra/django/_impl.py
- hypothesis-python/src/hypothesis/extra/django/models.py
- hypothesis-python/src/hypothesis/internal/compat.py
- hypothesis-python/tests/django/toystore/test_given_models.py
- ``hypothesis.extra.django.models.models()`` is deprecated in favor of `hypothesis.extra.django.from_model`.
- ``hypothesis.extra.django.models.add_default_field_mapping()`` is deprecated in favor of `hypothesis.extra.django.register_field_strategy`.
- `hypothesis.extra.django.from_model` does not infer a strategy for nullable fields or fields with a default unless passed ``infer``, like `hypothesis.strategies.builds`.  ``models.models()`` would usually but not always infer, and a special ``default_value`` marker object was required to disable inference.
TLDR: closes #1695 by moving two functions and making them more consistent with core strategies.
> Clean up extra.django namespace and improve consistency with core

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/stateful.rst
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/cover/test_stateful.py
Enable rules to add multiple results to their target bundle(s), or to add no result at all. Please review and tell me what to think of this approach, and if the public functions should be named differently. 
Closes #321.
> Add multiple items to a bundle

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/datatree.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/nocover/test_conjecture_engine.py
This extracts the logic for managing a tree of ConjectureData objects into its own class. It builds on #1745 because it touches the same code, so don't bother reviewing this until that's merged and I've rebased this PR.
The reasoning for doing this is that I want to start doing some major surgery on this logic to make it less memory hungry, and getting it self contained seemed like the best place to start.
> Factor out tree logic from ConjectureRunner

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/tests/nocover/test_conjecture_engine.py
I noticed that this was a better iteration order for pairs in another context.
The idea is that rather than iterating based on a nested for loop over indices we should iterate over the gap size and the start index. So say we had three blocks, our iteration order should be:
```
(0, 1)
(1, 2)
(0, 2)
```
Where previously it would have been
```
(0, 1)
(0, 2)
(1, 2)
```
The reasoning for this is twofold:
* Blocks closer together are more likely to be related and thus if we want to make progress early on should run those sooner than blocks that are further apart.
* If there is some block that we actually can't change at all, we spread out the attempts on that block and so don't spend a long time "stalled"
It's unfortunately difficult to demonstrate that things like this are an improvement, but …
> Iterate over block pairs in a different order.

- hypothesis-python/tox.ini
- tooling/src/hypothesistooling/__main__.py
And ensure that changing pinned requirements or `tox.ini` triggers a full build.  Closes #1762.
> Fix pytest30 compat build

- hypothesis-python/README.rst
Currently [master](https://hypothesis.readthedocs.io/en/master/changes.html) and [lastest](https://hypothesis.readthedocs.io/en/latest/changes.html) builds are different about 4.0+ things. 
RTD [guarantee](https://docs.readthedocs.io/en/latest/versions.html#how-we-envision-versions-working) that the `lastest`  will always point to the most up to date code version. With Hypothesis CD strategy that also means that the `latest` version is always the latest release.
Probably, there are some hooks on RTD side which keeps `latest` always up to date, while `master` one get triggered by some other ways.
> Point to latest RTD docs instead of master one

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/src/hypothesis/internal/cathetus.py
- hypothesis-python/tests/cover/test_cathetus.py
Closes #1748.  In short:
- When `cathetus` was passed an extremely large hypotenuse and relatively small side length, it could calculate the remaining side as slightly longer than the hypotenuse.  In rarer circumstances still, this could return infinity for finite inputs.
- `complex_numbers` calculates the bounds on the real part of each example based on the imaginary part.  If `allow_infinity=False` is passed, all bounds should be finite.  However, by the above bug it was possible to get an intermediate infinity which is also a bug.
- `floats` now raises `InvalidArgument` if passed `min_value=inf, allow_infinity=False` because there is no legal value.  This bubbled out of `complex_numbers`, instead of both strategies silently generating disallowed values.
So we now clip the side length …
> Patch cathetus floating-point imprecision which broke complex_numbers

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/cache.py
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/datatree.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/tests/cover/test_cache_implementation.py
- hypothesis-python/tests/cover/test_conjecture_data_tree.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/nocover/test_cache_implementation.py
This limits the scope of the `DataTree` to only store enough information to recreate the buffer and status of the stored `ConjectureData` objects. We then use a standard cache to map the rewritten buffers to the generated `ConjectureData` objects so that the shrinker still has access to them during shrinking, but eviction is now possible.
The reasoning is that `ConjectureData` objects are really large and memory hungry, and for the overwhelming majority of our tree usage we don't actually need them, so by avoiding storing them for that we can significantly reduce the memory profile.
> Don't store the entire ConjectureData object in the tree

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/reflection.py
This hopefully fixes the warnings that hypothesis currently generates:
```
ResourceWarning: unclosed file <_io.BufferedReader name='…/lib/python3.7/site-packages/hypothesis/provisional.py'>
```
> Don't leak open files

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/errors.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
A couple of times now I've tried to track down the precise location that actually catches and discards a `StopTest` after it has stopped its test.
Unfortunately it's quite tricky to find, because the special-case handling for re-raising a `StopTest` draws attention and makes the normal code path easy to miss.
This PR aims to fix this by creating a helper method that is clearly responsible for intercepting stops, and has an explicit code path for doing so that won't be concealed by the special-case path.
---
A side benefit of introducing this method is that the path for re-raising a `StopTest` no longer needs its own separate `self.save_buffer(data.buffer)` call, because that is now handled uniformly by the `except` block out in `test_function`.
> Clarify where StopTest gets caught and discarded

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/numpy.py
- hypothesis-python/tests/numpy/test_gen_data.py
Fixes bug in `hypothesis.extra.numpy.arrays` on Python2 where `long` type dimensions are not allowed in the shape.
See https://github.com/HypothesisWorks/hypothesis/pull/1784#discussion_r253251114.
> Allow long type dimension for arrays on python 2

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/changes.rst
- hypothesis-python/src/hypothesis/extra/numpy.py
- hypothesis-python/tests/numpy/test_argument_validation.py
I spent a few hours tracing #1798 yesterday, and couldn't trigger it *or* see any code that I thought could cause it - but clearly it does happen!
This patch therefore inserts a `print()` call to show us the problematic value and strategy before re-raising the error, so we can get it next time :boot::bug:.
> Emit more information when triggering dtype bug

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/lark.py
- hypothesis-python/tests/lark/test_grammar.py
As part of the paper I'm working on I'm generating Python 3 code for testing autoformatters. I was curious if I could use the new Lark support to do this.
Verdict: No, there's quite a way to go before this is possible, and I decided to stop digging myself down that rabbit hole, but along the way I ended up doing one of the precursor refactorings that I would need to do so, and it seemed like a nice general improvement, so here is that refactoring on its own.
The high level motivation is that I needed some state object to track indentation level on. I didn't get as far as actually implement tracking the indentation level, but I felt having the state object was still life improving.
This PR:
* Moves ``from_lark`` over to use an explicit `SearchStrategy` subclass.
* Reduces the number of …
> Refactor Lark implementation to use internal API and be more explicit about parse state

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
Sometimes `blocks` will end up empty in `try_shrinking_blocks` and we'll get an `IndexError` as a result. Unfortunately I don't understand exactly *why* this happens, but I've seen it once in the wild.
There may be some deeper issue at play here, but I don't have time to debug it in depth right now, and it's fairly reasonable for `try_shrinking_blocks` to want to handle this correctly, so this PR just fixes the symptom rather than the root cause. 😞
> Fix occasional IndexError in shrinking

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
This was originally going to be just for `__test_function_cache` from #1767, but then I noticed a few other fields that had also been left behind from other changes.
> Remove unused attributes from Shrinker

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/tests/nocover/test_emails.py
[RFC 5321](https://tools.ietf.org/html/rfc5321) states that “The maximum total length of a reverse-path or forward-path is 256 octets (including the punctuation and element separators).”, hence, as path has to contain two angle brackets, it limits email length to 254 characters.
See https://stackoverflow.com/a/574698 for more details.
> Limit generated emails to 254 characters

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/tests/cover/test_random_module.py
Fixes #1813, which was caused by restoring the random state before we ever ran the body of the test.
> Run data generation and test body with the same deterministic PRNG

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/numpy.py
- hypothesis-python/tests/numpy/test_argument_validation.py
- hypothesis-python/tests/numpy/test_gen_data.py
Fixes bug in `hypothesis.extra.numpy.arrays` where the desired data type is not always returned when a scalar array is requested. This change also ensures that a numpy `ndarray` is always returned from the `arrays` strategy. See discussion in pull request #1784.  For example,
```
>>> S=arrays('int32',(),elements=booleans())
>>> x=S.example()
>>> x
True
```
and
```
>>> S=arrays('>i2',())
>>> x=S.example()
>>> x
-31543
>>> x.dtype
dtype('int16')
>>> x.dtype == '>i2'
False
```
> Return correct dtypes for zero dimensional arrays

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
OK, this looks like a ridiculously pointless little micro-optimisation that can't *possibly* help anything.
Instead it's a ridiculous little micro-optimisation that helps a really annoying amount. It doesn't help *speed* much because we're doing too many slow things right now so this is lost in the noise, but what it helps a lot is memory usage. The problem is that unless our buffers are short enough to fit in the small integer cache, we're allocating a new integer object each time index is called. These end up as the endpoints for examples and buffers, so we end up keeping many copies of the same integer object spread all around the place. This adds up surprisingly rapidly in my (admittedly fairly imprecise) benchmarking.
(As it happens I have plans that will make us want to be able to …
> Save index rather than recalculating it each time we use it

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/datatree.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/tests/quality/test_poisoned_trees.py
The main motivation for doing this was memory usage, but I think it actually makes the API much cleaner to have a logical distinction between its data and its result, and it's something I've vaguely felt I should do for a while but never got around to.
> Use a dedicated TestResult object instead of keeping ConjectureData around

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/cover/test_conjecture_test_data.py
- hypothesis-python/tests/py3/test_traceback_elision.py
Note: This is just me reopening #1825 but I'm not allowed to reopen it and have to recreate it because the branch has been force pushed. 🙄 I decided that the clever solution I was going to implement needs more thought and I'll take the big win now even without the longer term cleverness.
This changes the way we calculate the examples list to happen lazily on first usage. The reasoning for this is:
* it's a _huge_ memory saving. These example trees are by far the biggest part of our memory profile during shrinking, and most of the time we don't need them (most of the time we need them _for the current shrink target_, but if most shrinks fail then we will rarely need the resulting Example object).
* I haven't benchmarked it but I expect not allocating a giant tonne of data on the hot path …
> Compute examples lazily on demand

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/tests/nocover/test_skipping.py
It turns out that importing `pytest` is surprisingly slow, to the point that it shows up as a significant cost when running Hypothesis under a profiler.
This PR changes our imports that we use to determine skip and failure exceptions to only happen when we first catch an exception. We still have to pay the cost (if you're not using the internal API, which I am), but this makes the initial import a lot faster, which can also be relevant for interactive usage.
> Don't calculate exception lists until we first need them.

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/community.rst
- hypothesis-python/docs/extras.rst
- hypothesis-python/src/hypothesis/extra/lark.py
- we have [a StackOverflow tag](https://stackoverflow.com/questions/tagged/python-hypothesis)
- we do in fact depend on `attrs`, but it's still worth having extras packages
- Lark is still at 0.x, so our integration may break API if needed to support latest upstream
> Minor docs updates about our dependencies

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
It's rare right now that our block programs do anything at all, but I've seen a couple of cases in my recent experimentation where a block program is wildly successful. Unfortunately currently "wildly successfuly" means "makes many teeny tiny shrinks". This PR changes that failure mode by making all block programs *adaptive* - when they would make `k` consecutive shrinks they instead make `O(log(k))` larger shrinks.
> Make all block programs adaptive

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/quality/test_integers.py
After #1801 removed most of this method's body, calling it from tests no longer had any useful effect.
As a result, some shrinker tests were accidentally running the entire pass suite, instead of just a specific pass as intended.
Fortunately those tests all still seem to pass after restoring the intended behaviour.
> Remove Shrinker.clear_passes

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
The current `reorder_examples` implementation is pretty expensive. There are two proximate causes for this:
* It rarely works
* It often tries running the `Ordering` shrinker on fairly large collections.
This PR attempts to mitigate that (I wouldn't say it wholly fixes it, but it's at least *better*) by not attempting to swap examples with different labels. This a) Prioritise swaps that are likely to work over ones that are unlikely to work and b) Reduces the size of the collections it runs on, potentially considerably.
This will be particularly useful when you have things like, say, `tuples(integers(), text())` - there's absolutely no point trying to swap the elements of this tuple, but the previous implementation would and the new implementation wouldn't.
* This also adds parentage …
> Only attempt to reorder examples with the same label

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/changes.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/cover/test_datetimes.py
- hypothesis-python/tests/pytest/test_skipping.py
#1781 keeps causing odd problems, so I'd like to reduce the diff a bit - if nothing else rebasing will be easier.  So we have an independent pull, to:
- remove the now-pointless tracking of `covering_examples` on the engine
- skip a test for skipping behaviour under pytest 3.0, where it only passes by coincidence
- fix a bad link in the changelog
- increase the timeout in  `minimal` for a slow test
In unrelated news, `git grep " - 2019-" -- hypothesis-python/docs/changes.rst | wc -l` informs me that we have made 52 releases over the 54 days of the year to date.  Not bad!
> Various minor cleanups

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/tests/common/utils.py
- hypothesis-python/tests/nocover/test_conjecture_engine.py
I belatedly noticed that #1789 actually runs the block program *twice* during each unsuccessful step: first at `i - 1`, and then again at `i`.
The cache should mostly bail us out here, but it's still better to not have the extra cache pressure or bookkeeping, and the fix is very simple.
> Make sure that unsuccessful block progam steps don't do too much work

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/src/hypothesis/internal/conjecture/floats.py
- hypothesis-python/src/hypothesis/internal/conjecture/utils.py
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/cover/test_conjecture_test_data.py
- hypothesis-python/tests/cover/test_conjecture_utils.py
This pulls out most of the `ConjectureData` changes from #1819 - `draw_bits` is now the central API of `ConjectureData` and `draw_bytes` and `write` are now just specialised calls to it.
`draw_bytes` and `write` are now *mostly* vestigial. There's a fair bit of usage of them in the test suite, and one remaining use of `draw_bytes` in the main code base that is I think legitimate (it's literally for a strategy for drawing fixed size blocks of bytes).
> Commonize API on draw_bits

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
This makes two related changes to the shrinker that are designed to speed up `remove_discarded`. We run this a *lot* so it's worth the effort (it was showing up as a couple % of the runtime for an experiment I was running where the test function was quite slow and also never discarded anything!).
The two changes are:
* We add a single boolean flag that lets us skip it entirely if we never called `stop_example` with `discard=True`. Because we might discard empty examples it's still possible that this flag can be True and `remove_discarded` can be useless but that shouldn't happen too often and we can detect when it does.
* We cache length on `Example`. Turns out that subtracting two numbers can easily become a bottleneck in Python if you do it enough times. 😢
> Some micro-optimisations for shrinking

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
I noticed that `zero_examples` will often make a lot of small changes. This attempts to offset that by adding an adaptive step to it.
It doesn't help *that* much (it saves about 20% of the calls on the example I was trying, which was largish), but the implementation is cautious enough that it should almost never hurt and it has the possibility of winning big.
> Make zero_examples adaptive

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/shrinking/ordering.py
- hypothesis-python/tests/cover/test_conjecture_order_shrinking.py
The `reorder_examples` pass was almost comically inefficient due to how much work it was doing. 😢 
This changes it to be fully adaptive, based on the idea of sorting entire regions, possibly with one element left as a gap to work around awkward boundaries.
~~It also changes how we group items for reordering slightly. Particularly with the new algorithm, it's better to run these on *slightly* larger groups, so we now group by label and depth. Grouping by depth means that we don't have to worry about the case where one example is nested inside each other, but it also seems to be slightly faster than more sophisticated ways of achieving that.~~ This resulted in a weird failure in the quality tests that I've not been able to successfully debug and was a sufficiently marginal gain compared to …
> Making reordering examples adaptive

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
In the new system every shrink pass generates a series of arguments to its step function. This leads to the question of what you do when running arguments that were generated with an old version of the shrink target.
The current approach is to try to ensure that that doesn't happen by only storing indices and recalculating the collection each time we run a step if it's changed since then. This was clever but turns out to be a very bad idea for two main reasons:
* When the shrink target is large calculating these collections is expensive.
* The indices very rapidly get out of sync to the point where they're essentially just point to an arbitrary member of the collection.
This changes the process by using the arguments collection directly, with shrink pass steps now updated so that they do …
> Don't recalculate shrink pass argument on usage

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/compat.py
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/cover/test_conjecture_test_data.py
Hey, psst, buddy, would you like to see some really weird code? Then boy do I have the PR for you.
Following on from #1828 where we calculated `examples` on first use, this also allows us to calculate `Block` objects on first usage.
Unfortunately the big differences between `Example` and `Block` are that a) We use blocks a lot more and b) We need them during generation time. This means that the `Example` approach of just deferring until we first access the collection is a non-starter.
So this does uh something else. The basic idea is that we can create a collection that only _looks_ like a list of blocks but actually only stores the endpoints until we first ask it for each block object.
Important features:
* If we only ask for a small number of blocks then we only build a small number of …
> Also calculate blocks lazily

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
Previously we were interleaving all shrink pass steps and then running them. This was a fairly huge improvement over running each sequentially, because it avoids stalls where one pass is just completely not working, but it has a fairly major problem: When the test case is large, the step collections are *huge*, and computing them all up front ends up being slow and memory hungry.
Additionally, it's not always a very sensible ordering - if we have some steps that reduce the size and some that don't, we really want to run the ones that reduce the size of the example first.
This PR solves both these problems by adding an initial phase to `fixate_shrink_passes` where it doesn't really try to get to any sort of fixed point, it just really aggressively chews the shrink target down to size, by …
> Change how we run shrink pass steps

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
tracemalloc informs me that lots of allocation is happening at this line. I side eyed it a lot and then decided to just sigh and deal with it.
> Tiny micro-optimisation to reduce allocation in start_example

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/numpy.py
By removing the overhead of composite when it's not needed (I did say small!).
This also makes it very easy to deprecate passing a strategy for shape and/or dtype later, which I find seriously tempting.  Looking at new shape-dependent strategies from #1829 and #1784, I think we might want to push users in the direction of "either use a constant shape, or use `@composite` or `data()` to combine several shape-dependent things".
But it's not clear when that might land or whether we want deprecate passing a strategy for dtype too, and we have until midyear to finalise any deprecations for 5.0, so I'm holding off for now.
> Small performance patch for Numpy arrays

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/tests/cover/test_conjecture_intlist.py
When we update the shrink target we check which blocks have changed. The way we previously did this did a lot of unneccessary work. This mainly shows up as a large pile of unneccessary allocations, but it's a non-trivial time cost too.
This reduces that work in the following two ways:
* Don't allocate a bunch of useless block boundaries just to check if they're equal - this will return true if and only if the endpoint lists are equal
* Rather than doing a linear scan of the full list of blocks, we use a binary search to narrow down to a hopefully much smaller list of blocks that have changed (due to needing to check the whole prefix/suffix in that search this doesn't actually improve the time complexity, but it involves a cheaper per block check).
> Speed up checks for structural changes in the shrink target

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/src/hypothesis/internal/validation.py
- hypothesis-python/tests/cover/test_conjecture_utils.py
- hypothesis-python/tests/cover/test_explicit_examples.py
- hypothesis-python/tests/cover/test_flakiness.py
- hypothesis-python/tests/cover/test_settings.py
Per our style guide, validation is good... so now we validate *all* the arguments to `settings`, not just some.  It's a minor release because of the new warnings, but it's also conceivable that someone was doing something very strange with a setting that we just ignored and now error on - IMO those cases were never part of the supported public API.
I've also deprecated `max_examples=0` in favor of the `phases` setting, which is generally a cleaner way to turn off generation.  This has already turned up a few cases in our own tests!
> Tighten validation of several settings

- .travis.yml
We live in a post-#1854 world now (thanks @Kavec!) where almost all of the jobs we run on Travis run on Azure as well, only much faster. I've marked it as required on our pull requests.
If and when we've got deploys working from Azure we can retire our Travis config entirely, but until then there's no reason we have to suffer from slow builds.
This pares back our Travis build down to a much smaller set. The reasoning behind the remaining set is that everything on this list is basically it sure would be embarrassing if we shipped something that fails these tests, and if the other tests passed prior to merge and these ones passed post merge we've probably covered most of our bases.
Note that it merges the extras and main category - there aren't enough extras left in this build set to be …
> Remove a large number of jobs from Travis

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/numpy.py
- hypothesis-python/tests/numpy/test_argument_validation.py
- hypothesis-python/tests/numpy/test_gen_data.py
Users can leverage this strategy to generate all permissible tuple-valued inputs to  `axis` argument in [NumPy's sequential functions](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/VectorizedOperations.html#Sequential-Functions), e.g. `numpy.sum`.
Ultimately, this does the real heavy lifting needed to exhaust the permissible values for axis arguments. Specifically,
```python
from hypothesis.strategies import integers, none
from hypothesis.extra import valid_tuple_axes
def valid_axes(ndim):
return integers(-ndim, ndim - 1) | valid_tuple_axes(ndim) | none()
```
can generate all permissible values `Optional[int, Tuple[int, ...]]`, including negative axis-indices.
> Add strategy for generating values for the numpy-axis argument

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/compat.py
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/datatree.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py
- hypothesis-python/tests/cover/test_conjecture_data_tree.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/cover/test_conjecture_float_encoding.py
- hypothesis-python/tests/cover/test_conjecture_test_data.py
- hypothesis-python/tests/cover/test_float_nastiness.py
- hypothesis-python/tests/nocover/test_conjecture_engine.py
- hypothesis-python/tests/nocover/test_conjecture_int_list.py
- hypothesis-python/tests/quality/test_integers.py
- hypothesis-python/tests/quality/test_poisoned_lists.py
- hypothesis-python/tests/quality/test_poisoned_trees.py
- hypothesis-python/tests/quality/test_zig_zagging.py
- mypy.ini
The successor PR to #1819. This implements a new caching data structure based on a [Patricia trie](https://en.wikipedia.org/wiki/Radix_tree) with block values as keys instead of a pure trie with bytes as keys.
From a user perspective this is a feature PR that improves our ability to detect flaky tests (the user will probably not say "improves" they will say "whines at me about things that worked before hand" because if they have this problem and haven't noticed it it's because their tests are silently doing the wrong thing).
If the user is *really* paying attention they will notice that their Hypothesis usage is significantly less memory hungry and moderately faster, because the new data structure is hilariously memory efficient compared to the old one (this is less a function of how good …
> New Patricia trie based example cache

- guides/api-style.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/src/hypothesis/extra/lark.py
- hypothesis-python/tests/cover/test_nothing.py
- hypothesis-python/tests/cover/test_reusable_values.py
- hypothesis-python/tests/cover/test_sampled_from.py
- hypothesis-python/tests/cover/test_type_lookup.py
As discussed on #1860, returning `nothing()` instead of raising an error makes it easy to lose parts of a composed strategy.  Since we only do that in one place currently, it's pretty easy to deprecate it and add a note in our API style guide not to do this again!
For the three internal uses where we want this behaviour, we convert `sampled_from(a)` to `sampled_from(a) if a else nothing()`.  For the two cases where we don't, we can improve clarity and efficiency by passing `min_size=1` to prevent generation of the empty list we tried to sample.
> Deprecate sampled_from([])

- azure-pipelines.yml
- tooling/src/hypothesistooling/__main__.py
An experiment in pursuit of #1571.  Results so far:
- Installing a specific Python on the build agent is hard, but using the provided Python version selectors is both easy and a *lot* faster given the caching situation.
- upstream UX issue for @vtbassmatt: if the config is invalid, github will show "Waiting for status to be reported" indefinitely instead of an error state.  Not a big problem, but it's usually worth removing any friction in onboarding.
- For some reason installing Numpy gets me `AttributeError`s in `searchstrategy.types`.  No idea why, but numpy-on-win-x86 is one of the jobs we really can't give up.  Still working on this one.
> Move Windows, OSX builds to Pipelines

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
See title.
Usage of this field went away in #1846 but the field itself did not. The field itself is potentially quite big, and updating it potentially happens quite often (in my Csmith experiments all `draw_bits` calls are with `n_bits=31`. So this was getting populated on every single call. This was a poor life choice)
> Don't bother calculating the giant table of masks that we never use

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/datatree.py
Another "oh this is one of the the allocation hotspots and there's no good reason for it to be" PR which is unlikely to have a huge impact in and of its own right but is small enough that it's worth doing anyway.
When we look up a buffer we rewrite it to see if it corresponds to something we've previously run, but if there's a novel behaviour then we definitely *haven't* run it before, so there's no point in rewriting it. When the buffer is large, doing so can involve a bunch of useless allocations.
> Don't rewrite novel buffers

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
Turns out that as well as lazily allocating `Block` objects as of #1830 we're *also* allocating them on the hot path. 🙄 This removes that code.
I think this must have got screwed up in a rebase as I had a bunch of branches in flight at the time.
> Remove lingering Block allocation

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/src/hypothesis/reporting.py
I was moderately surprised to discover that of all things `_settings.py` was now one of the allocation hotspots. This turns out to be because we are calling `local_settings` on every `debug` call in the engine, which is a bit hungrier than I thought it would be. 😳 
Anyway, this PR fixes that. It's unlikely to have a *huge* impact, but it should have a small one, and gets this method out of the allocation reports which makes it easier to notice what's going on with other things.
> Don't use a fresh context manager on every debug call

- guides/strategies-that-shrink.rst
Closes #1705.
I'd appreciate lots of feedback on this as I certainly don't think it's perfect - but hope it's better than nothing.
> Add guide to designing strategies for good shrinking behaviour.

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
This PR unfortunately combines a couple of things, in particular #1871 and #1870, because they both triggered the same problem (failing pandas tests) and needed the same solution. However each commit should be independently reviewable.
The main motivators for this are:
* Replacing the stable identifiers with just using integer indices. The stable identifiers are probably *better* but they're very expensive in terms of memory usage, especially for large and deeply nested test cases.
* Moving shrink passes that can have purely lexical steps later in the process. The shrinker tends to get a bit distracted by these early on and do a lot of needless work.
The problem this runs into is that some of the pandas tests start failing if you introduce *either* of these changes. This is because these …
> Improve memory usage and speed of long-running shrinks

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/cover/test_conjecture_test_data.py
This eliminates the one call site that was causing `Block` allocation during generation, after #1830.
(It was originally a part of #1862, but I pulled it out here because it's a perfectly fine incremental improvement on its own.)
In theory this could enable some simplifications of the lazy block management code, but in practice I haven't actually investigated any of those yet.
> Obtain the last block's length without having to create it

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/cover/test_conjecture_intlist.py
- hypothesis-python/tests/cover/test_conjecture_test_data.py
This follows on from the work in #1830 of making the example collection *even lazier*.
The basic design principle here is to make `Example` just a thin shim indexing into a more compact representation. This representation stores a compact record of the set of `start_example/stop_example/draw_bits` call and compact representations of any property that has been accessed on an `Example` object for the current collection.
The code involves is... a bit weird. However I genuinely think a decorator that transforms a nested class into a method *is* the nicest way to represent this.
Note that there is now a certain amount of logical redundancy in the code which really should be merged. In particular `Examples` and `Blocks` work quite differently, and `ExampleRecord` and `DataObserver` are fairly …
> Build example objects lazily

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/src/hypothesis/internal/floats.py
- hypothesis-python/tests/cover/test_float_nastiness.py
- hypothesis-python/tests/nocover/test_pretty_repr.py
Because there's nothing we can possibly generate in those cases.  Closes #1859.
> Error on excluded infinite endpoints

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/supported.rst
- hypothesis-python/setup.py
- hypothesis-python/src/hypothesis/searchstrategy/regex.py
- hypothesis-python/tests/cover/test_regex.py
- hypothesis-python/tox.ini
- scripts/install.ps1
- tooling/scripts/install-python.sh
- tooling/src/hypothesistooling/__main__.py
With [the release of 3.4.10](https://www.python.org/downloads/release/python-3410/), Python 3.4 is end-of-life upstream and that means it's time for us to drop (free) support too.  Just [nine months to go](https://pythonclock.org/) before Python 2!
The diff is mostly cleaning up install commands we no longer need, but there's also a nice clarification to regex handling where certain inconsistent treatment of unicode digits is now "just" another 2/3 difference.
> Drop support for Python 3.4

- guides/testing-hypothesis.rst
There are some tests in the test suite that require `mock`, and will fail with import errors if that library isn't present.
> Add "mock" to the virtualenv setup instructions

- hypothesis-python/tests/cover/test_reusable_values.py
Fixes #1892.
It's slightly annoying that this won't automatically detect when `HypothesisDeprecationWarning` is no longer necessary (when #1860 becomes a hard error), but I don't know of a reasonable way to make that happen.
> Fix flaky test_reusable_strategies_are_all_reusable

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/tests/pandas/test_data_frame.py
I was staring at a long running shrink wondering why it took so long for a while before I figured out what was happening: It had successfully got to the point where the emergency passes were running, and something about that had unlocked `minimize_individual_blocks`. The result was that it was no longer at a fixed point for that pass, but *was* for every other (or possible almost every other? I didn't check that carefully) pass.
Unfortunately, this meant that every time it ran a loop to make progress on  `minimize_individual_blocks`, it had to run every other shrink pass as well, none of which did any good. This was expensive, obviously.
The solution is this: When we call `fixate_shrink_passes` and have run all of the shrink passes, we check if only some of them worked. If that is the …
> Run useful shrink passes to completion before resuming others

- hypothesis-python/tests/cover/test_slippage.py
I noticed a flaky failure in `test_can_disable_multiple_error_reporting` at https://dev.azure.com/HypothesisWorks/Hypothesis/_build/results?buildId=1871 (via #1905).
My guess is that this test occasionally generates `i=1` and stops more-or-less immediately without finding a second bug, violating the expectations of the test. Derandomizing the test should make this edge-case impossible.
Potentially obsolete if #1781 gets merged, though I haven't tested the interaction.
> Derandomize test_can_disable_multiple_error_reporting to hopefully make it non-flaky

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/searchstrategy/flatmapped.py
- hypothesis-python/tests/cover/test_searchstrategy.py
This improves the error message if the `flatmap` function doesn't return a `SeachStrategy`
> Improve error message if flatmap function doesn't return a strategy

- azure-pipelines.yml
- hypothesis-python/tests/cover/test_stateful.py
- hypothesis-python/tests/cover/test_verbosity.py
- hypothesis-python/tests/django/toys/settings.py
- hypothesis-python/tests/django/toystore/test_basic_configuration.py
- hypothesis-python/tox.ini
- tooling/src/hypothesistooling/__main__.py
Fixes #1909, by updating the settings for our Django app and adding Django 2.2 to our CI config.  I also fixed the leaked printing of a seed report from an expected-failing test.
Subsumes and thus closes #1910 because the tests would fail otherwise - thanks @Zalathar for working that one out!
> Get our CI working again

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/searchstrategy/lazy.py
- hypothesis-python/src/hypothesis/searchstrategy/misc.py
- hypothesis-python/src/hypothesis/searchstrategy/strategies.py
- hypothesis-python/tests/cover/test_sampled_from.py
- hypothesis-python/tests/nocover/test_sampled_from.py
Closes #1885. Follow-up to my #1862 and Zac's #1890.
I abandoned most of my earlier work, and instead focused on taking #1890 and replacing its hard-coded special case in `FilteredStrategy` with a more general hook mechanism.
Some things that are specifically *not* in this PR:
- Updating `RuleStrategy.do_draw` to use `sampled_from(...).filter(...)` internally
- Adding special-case handling for `integers(a, b)`
- Extending special-case handling to chained `filter` calls (#1894)
> Add special-case filtering for SampledFromStrategy

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/cover/test_core.py
- hypothesis-python/tests/cover/test_random_module.py
The `random_module()` strategy sets global RNG state, and arranges for `BuildContext` to restore the original state afterwards.
However, when `deterministic_PRNG` is nested inside `BuildContext`, this causes the outer state-restoring hook to accidentally restore the deterministic state, instead of the original state.
The solution is to reverse the nesting, so that each context manager restores the intended state.
----
Fixes #1907, in conjunction with the changes to `test_one_dead_branch`.
> Correctly restore global RNG state after using random_module()

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/searchstrategy/strategies.py
- hypothesis-python/tests/nocover/test_filtering.py
- hypothesis-python/tests/nocover/test_sampled_from.py
This PR causes chained calls to `.filter(...)` to create a single flat `FilteredStrategy` with multiple conditions, instead of a nested sequence of `FilteredStrategy`.
By itself this doesn't make much difference, but when combined with #1904 it causes the special-case handling of `sampled_from(items).filter(f)` to also apply to `sampled_from(items).filter(f).filter(g)`, and to longer filter chains. That's especially helpful when later filters are the ones that cause the sampling to become sparse.
I've written the release notes under the assumption that #1904 gets merged first, ~~and I would also like to go back and add some tests to explicitly check that sample-filter chains actually work properly.~~
> Flatten .filter(...) chains into a single FilteredStrategy

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/searchstrategy/misc.py
- hypothesis-python/tests/cover/test_sampled_from.py
This bug was accidentally introduced in #1904.
This fix was originally part of #1891 and #1921, but has been isolated into its own PR for a standalone release.
> Fix assertion failure in sampled_from(...).filter(...) when there are few elements and all are rejected

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/cover/test_flakiness.py
- hypothesis-python/tests/cover/test_slippage.py
- hypothesis-python/tests/cover/test_testdecorators.py
Closes #847.
It turns out that this is basically an update of #1589, with two important changes: I have a better idea of where to put the change, and I realized that we have to go by `call_count` because there may be a very small number of possible `valid_examples` (and so the latter may loop until timing out).
In practice I doubt we'll find multiple bugs much more often, since the "reducers are fuzzers" effect of shrinking was already fairly effective for large or complex examples and we don't try very hard for subsequent bugs in generation.  
This really shines where the simplest input causes one error and other simple inputs cause another (e.g. the "mean of list of floats" test), which is likely to be noticed when potential users are running evaluations, and hence the lower bound on …
> Multi-bug discovery during generation

- azure-pipelines.yml
Further work on consolidating our CI, per #1571.  This PR is a fairly direct continuation of work started in #1858, with the goal of allowing us to drop Appveyor.
> Run most tests under Windows on Pipelines

- hypothesis-python/tests/common/debug.py
- hypothesis-python/tests/cover/test_regex.py
- hypothesis-python/tests/cover/test_simple_strings.py
- hypothesis-python/tests/django/toystore/test_given_models.py
- hypothesis-python/tests/numpy/test_gen_data.py
- hypothesis-python/tests/quality/test_poisoned_trees.py
- requirements/tools.in
- requirements/tools.txt
- tooling/src/hypothesistooling/__main__.py
Tests are often developed by a copy-paste-modify method - but we forget to change the function (or method) name, the earlier test is silently redefined and can never be run.  This is obviously bad.
Since it turns out that the redefinition problem does actually happen, this PR adds Pylint to our CI *just* to run the `function-redefined` check.  It also fixes the several test suite bugs that this detects, and restructures the false-positives to make this check as useful as possible.
I'm *not* running it over the source in CI, but did check each location by hand - there are multiple places where we really do want to redefine the function, and the remainder are due to PyCQA/pylint#2239 (`@typing.overload` needs but does not yet have special handling).
> Check for shadowed tests with Pylint

- hypothesis-python/tests/cover/test_simple_collections.py
- hypothesis-python/tests/cover/test_slippage.py
- hypothesis-python/tests/numpy/test_gen_data.py
This PR makes some tweaks to our Numpy tests:
- "unwraps" a few so that Pytest can call them directly, in some cases using our `@fails_with(exception_type)` decorator.
- Caps the side length in `test_broadcastable_shape_has_good_default_values`, where I once saw a `MemoryError` for a large shape.
- Add a dtype to `np.zeros(shape, dtype="uint8")` for efficient memory allocation and smaller size (the default is `float32`).
- Reduce the `max_examples` on tests that have a `minimal(...)` internally, since we would not usually wrap that in `@given` at all.  Making this change to the seven slowest cases cuts over a third from the total runtime of our Numpy tests.
- Retry [this (non-Numpy) test](https://dev.azure.com/HypothesisWorks/Hypothesis/_build/results?buildId=1953&view=logs&jobId=c3892b1c- …
> Speed and stability improvements for our Numpy tests

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/src/hypothesis/internal/reflection.py
- hypothesis-python/src/hypothesis/searchstrategy/functions.py
- hypothesis-python/src/hypothesis/searchstrategy/types.py
- hypothesis-python/src/hypothesis/strategies.py
- hypothesis-python/tests/cover/test_composite.py
- hypothesis-python/tests/cover/test_functions.py
- hypothesis-python/tests/cover/test_lambda_formatting.py
- hypothesis-python/tests/cover/test_reflection.py
- hypothesis-python/tests/py3/test_functions.py
- hypothesis-python/tests/py3/test_lookup.py
- requirements/tools.txt
It's the simplest possible thing that closes #167.
`functions(like=lambda: None, returns=none())` takes two arguments; the first must be a callable and the second must be a strategy, both are optional.  The generated function will pretend to be `like`, and return a value drawn from `returns` each time it is called.  This strategy supports `.example()`.
There are multiple ways that this could be improved, such as simulating pure functions or inferring a return strategy from the return type hint of `like`, but nothing that I can think of would break this API.  I therefore decided to get a MVP out first, and leave the harder parts for after someone actually asks for them.
> A new strategy for generating functions

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/reflection.py
- hypothesis-python/src/hypothesis/searchstrategy/collections.py
- hypothesis-python/src/hypothesis/searchstrategy/misc.py
- hypothesis-python/tests/cover/test_slippage.py
- hypothesis-python/tests/nocover/test_sampled_from.py
The "make your own luck" trick from our shrinking guide can make `lists(sampled_from(...), unique=True)` practical even when the list is of around the same length as the sampled sequence.  That closes #1115, by optimising the implementation of a naive `sets(sampled_from(elements))` strategy - though it used to be a common cause of the filtered-too-much HealthCheck.
> Efficient unique collections with elements from a sampled_from 

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/compat.py
PEP 570 adds "positional only" arguments to Python, which changes the
code object constructor. This adds support for Python 3.8.
I assume this is covered by existing tests, but it would be good to add a "nightly" build to the CI matrix.
Fixes #1943
> Add support for positional only arguments

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/searchstrategy/types.py
The `from_type` strategy now supports `range` objects.
Closes #1927.
> added range/xrange to from_type

- hypothesis-python/docs/changes.rst
Hi @HypothesisWorks/hypothesis-python-contributors - turns out that using the same link target like this requires *two* underscores, so this PR un-breaks our CI so that the deploy can finish.  Merging ASAP would be very much appreciated!
> Fix 'duplicate link target' error

- guides/README.rst
- guides/internals.rst
- guides/review.rst
- hypothesis-python/docs/changes.rst
With the PyCon sprints increasingly close, I did a last pass through the docs and found a few places where the guide was out of date and one where the behaviour of `lists()` was mis-described (this is relevant if you have a bunch of equal numbers of different types!).
> Minor tweaks to contributor/maintainer guides

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/searchstrategy/recursive.py
- hypothesis-python/src/hypothesis/searchstrategy/strategies.py
Solves issue #1600 by removing `bias` and logic depending on it.
`bias` was removed in `recursive` and tests still seem to pass
> Remove bias argument from OneOfStrategy

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/numpy.py
Fixes #1798.  Paraphrasing my comment there: it's triggered by a *weird* behaviour of `np.dtype` that can be rarely found by `npst.array_dtypes()`, where:
`np.dtype([("f1", int), ("", int)])` fails, as does anything where the name `"f{index}"` exists elsewhere but the name at the index is `""` (e.g. `dtype([('', int), ('f0', int)])`) - the empty name defaults to the `f{index}` name even if it exists elsewhere, but obviously the `unique_by` doesn't catch that.  We can ensuring that all field names are non-empty is a decent workaround until I can talk it over with upstream.
> Work around weird behavior of np.dtype

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/cache.py
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinking/common.py
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/cover/test_unittest.py
- hypothesis-python/tests/nocover/test_modify_inner_test.py
- requirements/tools.in
- requirements/tools.txt
- tooling/src/hypothesistooling/__main__.py
This patch adds [`autoflake`](https://pypi.org/project/autoflake/) to our formatting job, so that unused imports are removed automatically instead of causing a lint error.  It also handles unused variables, and - most relevantly as this actually causes a diff - removes pointless `pass` statements.  Hurrah for canonical forms!
> Add autoflake fixer

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
This internal method presumably served a useful purpose at some point.
But ever since #1052 overhauled novelty-generation, it has just delegated directly to `__zero_bound`.
> Remove ConjectureRunner.__rewrite

- hypothesis-ruby/README.markdown
This PR fixes a misspelled word in the initial code example.
Thanks for putting this preview out here.
> README: Fix a typo in code example

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/extra/django/models.py
- hypothesis-python/src/hypothesis/extra/numpy.py
- hypothesis-python/src/hypothesis/searchstrategy/collections.py
- hypothesis-python/src/hypothesis/searchstrategy/regex.py
- hypothesis-python/tests/common/utils.py
- hypothesis-python/tests/cover/test_conjecture_test_data.py
- hypothesis-python/tests/cover/test_example.py
- hypothesis-python/tests/cover/test_explicit_examples.py
- hypothesis-python/tests/cover/test_pretty.py
- hypothesis-python/tests/cover/test_regressions.py
- hypothesis-python/tests/nocover/test_collective_minimization.py
- hypothesis-python/tests/nocover/test_flatmap.py
- hypothesis-python/tests/nocover/test_pretty_repr.py
- hypothesis-python/tests/numpy/test_gen_data.py
- hypothesis-python/tests/quality/test_shrink_quality.py
- requirements/tools.in
- requirements/tools.txt
- tooling/src/hypothesistooling/__main__.py
They're slightly more efficient than creating and converting an intermediate structure.
More importantly, this is another thing where we can enforce (and automatically convert to) a canonical form for our code - this time with https://github.com/asottile/pyupgrade
(and I fixed a logic bug where "fields" was always plural in an error message)
> Consistently use dict/set literals and comprehensions

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/tests/nocover/test_testdecorators.py
Closes #1978.  
This both adds the `.is_hypothesis_test` attribute to the `invalid` stub, so you get the signature-mismatch message instead of the settings-without-given message, and expands the former to make it clear that the argument is coming from a strategy passed to `@given` (including for positional arguments).
> Clarify error message for signature mismatch

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/database.py
- hypothesis-python/src/hypothesis/internal/compat.py
This patch fixes a very rare example database issue with file permissions.
When running a test that uses both `@given` and `pytest.mark.parametrize`, using `pytest-xdist` on Windows, with failing examples in the database, two attempts to read a file could
overlap and we caught `FileNotFound` but not other `PermissionError` or other `OSError`s.
This is obviously a pretty niche case due to the timing, but I've seen it twice in a \~month while working on hypothesis-jsonschema... which has a 269-way parametrize over the entire upstream test suite and ``-n 16`` on a nice desktop 😄
(for "we should have distinct DB keys for different parametrize items", see #1996)
> Widen caught exception in rare database collision

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/stateful.rst
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/cover/test_runner_strategy.py
- hypothesis-python/tests/cover/test_stateful.py
- hypothesis-python/tests/pytest/test_statistics.py
Closes #1693.
`GenericStateMachine` has no replacement beyond the existing choices of rule-based stateful testing or `@given(data())`; and in fact the deprecation is intended to push any remaining users onto one of those alternatives.  Rule-based testing is more efficient, and direct use of given-and-data removes a few layers of indirection that no longer offer useful features.
> Deprecate GenericStateMachine

- hypothesis-python/tests/cover/test_conjecture_engine.py
As seen in https://github.com/HypothesisWorks/hypothesis/pull/2000#issuecomment-498007405, we apparently don't have reliable coverage of the branch in `reorder_examples` that rejects example identifiers that are no longer valid (due to intervening shrinks).
This PR aims to remove that flakiness by explicitly triggering that path, and similar paths in other shrink passes.
> Reliably cover the handling of stale example identifiers while shrinking

- CONTRIBUTING.rst
- RELEASE.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/django/models.py
Because otherwise, all I get by default is:
```
asauseriwant/tests/test_models.py::TestModels::test_userstory_str
/home/circleci/.local/share/virtualenvs/project-zxI9dQ-Q/lib/python3.7/site-packages/hypothesis/extra/django/models.py:81: HypothesisDeprecationWarning: This function is deprecated; use `hypothesis.extra.django.from_model` instead.
since="2019-01-10",
```
and I have to source-dive to find out what it is I'm using that I shouldn't
> Explicitly name deprecated methods in note

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/compat.py
- hypothesis-python/tests/pandas/test_indexes.py
Added via https://bugs.python.org/issue37032.
> Use CodeType.replace in Python 3.8

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/compat.py
- requirements/typing.txt
Closes #2014.
I have checked that this still works on the previous version of the `typing` backport, but did not add an "older backport" environment to our CI matrix - we explicitly document that we only support the latest version of the `typing` ecosystem, and will be dropping Python 2 support at the end of this year anyway.
> Support newer typing backport too

- azure-pipelines.yml
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/src/hypothesis/searchstrategy/strategies.py
One thing I've noticed a couple of times in workshops recently is that the tracebacks emitted from broken strategies are more complicated than they need to be, because there are a few caches where we use `KeyError` for control flow.  This is of course a reasonably technique, but unfortunately doesn't interact well with Python 3's traceback chaining as the sequence of "while handling..." can get pretty long.
So this PR converts the three main causes to use if-statements for control flow instead.
> Cleaner tracebacks for broken strategies

- .gitattributes
This was an incidental finding from PR #2018, and is intended so that image files (binary files) are not rewritten during `git push`.
> Preclude .jpg, .png, .gif being rewritten on git push

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/searchstrategy/datetime.py
- hypothesis-python/tests/cover/test_datetimes.py
- hypothesis-python/tests/cover/test_verbosity.py
Some months have fewer than 31 days!  And not trying to call datetime with an invalid month/day combination makes our can-overflow test impossible.
> Fix day-of-month overflow in datetimes()

- hypothesis-python/tests/common/debug.py
- hypothesis-python/tests/cover/test_datetimes.py
- hypothesis-python/tests/cover/test_numerics.py
- hypothesis-python/tests/cover/test_regex.py
- hypothesis-python/tests/cover/test_simple_strings.py
- hypothesis-python/tests/cover/test_slices.py
- hypothesis-python/tests/cover/test_verbosity.py
- hypothesis-python/tests/nocover/test_collective_minimization.py
- hypothesis-python/tests/nocover/test_flatmap.py
- hypothesis-python/tests/nocover/test_recursive.py
- hypothesis-python/tests/nocover/test_sets.py
- hypothesis-python/tests/numpy/test_gen_data.py
- hypothesis-python/tests/pandas/test_data_frame.py
- hypothesis-python/tests/quality/test_float_shrinking.py
- hypothesis-python/tests/quality/test_shrink_quality.py
- hypothesis-python/tox.ini
This PR reduces our internal use of `find()`, to make it easier to deprecate it in future (#1694), by re-implementing `minimal()` and associated test helpers on top of `@given` instead.
~~This is pretty easy to do, with one exception: `test_can_shrink_through_a_binding` and `test_can_delete_in_middle_of_a_binding` are now failing.  @DRMacIver - it looks like this shrinking logic doesn't work properly under `@given`??~~
> Port `minimal()` test helper from `find()` to `@given`

- tooling/src/hypothesistooling/installers.py
- whole-repo-tests/test_shellcheck.py
Since it's pre-installed on Travis (though also cached), and apt-get installable on Azure Pipelines.
This reduces the `check-whole-repo-tests` from `18:29` to `4:39` - including setup!  We were previously spending a full fourteen additional minutes installing `shellcheck` :astonished:
> Make shellcheck install much faster

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/changes.rst
- hypothesis-python/docs/settings.rst
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/cover/test_health_checks.py
- hypothesis-python/tests/cover/test_settings.py
- hypothesis-python/tests/nocover/test_explore_arbitrary_languages.py
- hypothesis-python/tests/numpy/test_gen_data.py
- hypothesis-python/tests/quality/test_poisoned_trees.py
From the vaguely-on-the-todo-list-for-ages department, we expose the `buffer_size` setting to users... even though it's deeply entwined with implementation details and basically impossible to set beyond "more than the default" (and doing so is *usually* unhelpful).
So this PR closes #1233 by deprecating the setting and ignoring it in favour of an internal constant.
> Deprecate the buffer_size setting

- .travis.yml
- azure-pipelines.yml
- tooling/src/hypothesistooling/installers.py
The recent changes to how we install shellcheck in #2026 mean that the whole repo tests can only be run as root (and attempt to install things globally), which isn't ideal in general and prevents local usage. This PR changes it so that the build will still use the old method to install shellcheck if it's not found, but will use a system one if present, and updates our build config to install shellcheck before the tests are run.
> Don't run apt-get commands from the whole repo test suite

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
This function was only used for testing, and was about to become more awkward to support in some changes I have planned, so this removes it entirely and makes it an error to call a shrink pass directly.
> Remove the ability to run a single shrink pass

- hypothesis-python/tests/numpy/test_gen_data.py
The coverage job is currently flaky because https://github.com/HypothesisWorks/hypothesis/blob/c3c28220d6b4ca53957a63979665d1d9d6d3b685/hypothesis-python/src/hypothesis/extra/numpy.py#L241-L242 are not being reliably covered. This PR adds a test that reliably hits them.
> Add test to reliably cover handling of collisions in unique arrays

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py
- hypothesis-python/src/hypothesis/searchstrategy/collections.py
- hypothesis-python/src/hypothesis/searchstrategy/lazy.py
- hypothesis-python/tests/cover/test_conjecture_junkdrawer.py
- hypothesis-python/tests/cover/test_direct_strategies.py
- hypothesis-python/tests/cover/test_sampled_from.py
- hypothesis-python/tests/nocover/test_sampled_from.py
Failures in  #2030 demonstrated that the current approach for this is still filtering out a lot of data. This replaces our special casing with the other approach I suggested, which uses a lazy fisher-yates shuffle to get better behaviour for this sampling.
WIP because I expect this to fail the test suite in a bunch of places and leave some code uncovered, and I'm being lazy and letting CI find that out for me.
> Improve performance of unique lists with `elements=sampled_from(...)`

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/src/hypothesis/extra/numpy.py
- hypothesis-python/tests/numpy/test_argument_validation.py
- hypothesis-python/tests/numpy/test_gen_data.py
- tooling/src/hypothesistooling/projects/hypothesispython.py
> Adds strategy for advanced indexing with integer-arrays

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/tests/cover/test_conjecture_test_data.py
- hypothesis-python/tests/cover/test_simple_characters.py
Fixes #1864.
I think this problem must *always* have been latent in Hypothesis but the previous implementation of the tree had a bug which masked it somehow, because the issue is actually intrinsic to what we were doing: The rejection sampling on small state spaces forces the necessary novel prefix to be progressively longer and longer, creating an accidentally quadratic problem where generating the Nth example takes O(N) time.
This PR fixes it by implicitly capping *all* rejection sampling loops to 20 iterations by building logic for marking longer sequences of consecutive discards as invalid into `ConjectureData`.
Earlier versions of this PR had an independent performance improvement to `generate_novel_prefix` which turned out to change the distribution enough that I decided to pull it …
> Improve performance of small tests that use rejection sampling

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/datatree.py
- hypothesis-python/tests/common/debug.py
- hypothesis-python/tests/cover/test_conjecture_data_tree.py
- hypothesis-python/tests/cover/test_slippage.py
- hypothesis-python/tests/datetime/test_pytz_timezones.py
- hypothesis-python/tests/nocover/test_regressions.py
Fixes #2027 
This is the performance patch I pulled from #2030 because it didn't seem necessary and changes the data distribution for some reason caused us to lose coverage.
I decided that the reason we lost coverage was mostly accidental - the previous tests couldn't reliably guarantee that coverage, they just happened to work - so I also added some tests for datetimes in this PR in order to get back to 100% coverage. I've also upped the `max_examples` count on one test that had become flaky, so I think there's some chance that this has made the data distribution slightly worse, but I think it's worth it for the performance gain.
> Improve performance of generate_novel_prefix

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/pandas/impl.py
The [`collections` module will remove the top-level aliases](https://docs.python.org/3/library/collections.html#module-collections) for the classes that now belong in `collections.abc`.
We have a redirect in `compat.py`, and this PR simply uses it from our Pandas extra.
I also investigated enabling `-Werror` for the Pandas extra, but was quickly foiled by the volume of warnings about Numpy/Pandas/Cython versions and deprecation pathways etc.  It's certainly possible to make this work, but not across every version of Pandas we test against!
> Fix warnings in Pandas extra

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/changes.rst
- hypothesis-python/docs/data.rst
- hypothesis-python/docs/details.rst
- hypothesis-python/docs/settings.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/tests/cover/test_arbitrary_data.py
- hypothesis-python/tests/cover/test_core.py
- hypothesis-python/tests/cover/test_random_module.py
- hypothesis-python/tests/cover/test_runner_strategy.py
- hypothesis-python/tests/cover/test_validation.py
- hypothesis-python/tests/cover/test_verbosity.py
- hypothesis-python/tests/nocover/test_boundary_exploration.py
- hypothesis-python/tests/nocover/test_database_usage.py
- hypothesis-python/tests/nocover/test_deferred_errors.py
- hypothesis-python/tests/nocover/test_find.py
- hypothesis-python/tests/nocover/test_imports.py
- hypothesis-python/tests/nocover/test_randomization.py
- hypothesis-python/tests/py2/test_generate_ints.py
This PR *finally* closes #1694, after other PRs ported our internal uses of `find()` over to `@given`.
In particular, this consists mostly of documentation changes and our `@checks_deprecated_behaviour` test helper - there were only a few tests left using `find()` without specifically existing *to* test `find()`.  And one important call to `note_deprecation`, of course!
> Deprecate find()

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/tests/cover/test_direct_strategies.py
- hypothesis-python/tests/cover/test_simple_strings.py
We can treat `text("abc")` as `text(characters(whitelist_characters="abc"))` instead of `text(sampled_from("abc"))`.  This allows for non-sequence alphabets such as sets, as well as allowing common strategies like `text(string.printable)` to share the distribution and shrinking behaviour of the more advanced `characters()` strategy.
I've split this out from my WIP refresh of #1621, because it's independently useful and the smaller that gnarly PR gets the better :smile:
> Pass alphabet through to characters()

- hypothesis-python/tests/pandas/test_data_frame.py
- hypothesis-python/tests/pandas/test_series.py
Our build is currently failing (most of the time) due to https://github.com/pandas-dev/pandas/issues/27484 causing an error when it tries to display the data frame generated.
This works around that bug by suppressing printing of the repr in the test for now.
> Work around a bug in pandas's repr handling

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/changes.rst
- hypothesis-python/docs/reproducing.rst
- hypothesis-python/src/hypothesis/__init__.py
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/version.py
- hypothesis-python/tests/cover/test_reproduce_failure.py
- hypothesis-python/tests/cover/test_settings.py
- hypothesis-python/tests/cover/test_stateful.py
- whole-repo-tests/test_requirements.py
This removes the `PrintSettings.INFER` option and as a result lets us delete some slightly strange logic where we try to reparse our falsifying example messages as valid Python code.
The motivation here is that I was looking in to improving the quality of our messages and this got in the way. I'm not yet sure I'm going to finish that work, but this logic is weird and counterintuitive and doesn't serve much useful purpose, so I thought I'd remove it anyway while I'm in the area
> Simplify logic for when to print the reproduce_failure blob

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/changes.rst
- hypothesis-python/src/hypothesis/internal/conjecture/utils.py
MD5 is cryptographically broken. Of course, this function doesn't really need cryptographic strength (it's slicing down to 8 bytes, so it hardly matters). However, when OpenSSL is used in FIPS mode (conforming to the US Government's FIPS-140 standard), MD5 is entirely disabled. While I generally have a pretty low opinion of FIPS, and I'm loath to ask projects to do actual work to support FIPS deployments, in this case I think the balance of equities is in favor:
- The match is tiny, and should not bring any ongoing maintenance burden
- FIPS's efforts to burn MD5 with fire are legitimately useful
- I'd expect the performance difference to be minimal, on my machine it's ~0.5 usecs per MD5 (of a 12 byte string) vs. ~0.6 usecs per SHA384 (same string)
> Removed usage of MD5 from calc_label_from_name

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/numpy.py
- hypothesis-python/tests/cover/test_numerics.py
- hypothesis-python/tests/numpy/test_gen_data.py
- hypothesis-python/tests/numpy/test_narrow_floats.py
Closes #1899.  Some users will probably find this pretty annoying, but we *do* have a `width` argument to `floats()` for exactly this reason, and it's used by our inferred strategies.  Unfortunately - and to my surprise - `numpy.can_cast(..., "safe")` does allow lossy downcasting.  So now we just compare exactly.
> Detect and warn on float truncation in arrays

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/choicetree.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/tests/common/debug.py
- hypothesis-python/tests/cover/test_conjecture_choice_tree.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
TLDR version: Changes to the shrinker that a) Should dramatically reduce memory usage for large starting points and b) Will in the long run hopefully produce much faster shrinking but right now are merely not noticeably worse than the status qo.
This changes the logic of shrink passes so we don't have to calculate large collections of arguments which gradually go stale up front. Its main goal is that it should significantly improve the ability of the shrinker to handle larger test cases.
The basic core of the idea is that the thing we do for non-redundant random generation also works really well for defining shrink passes: We encode steps in shrink passes as the shrinker making a series of choices (e.g. pick an example, pick a block), and the indices corresponding to the sequence of …
> New representation of shrink steps

- hypothesis-python/tests/cover/test_direct_strategies.py
When a parametrized test's parameters include sets or dicts, inconsistent values of `PYTHONHASHSEED` across `pytest-xdist` workers causes test collection to desync, because the parametrized tests end up having different names.
This file already had some manual workarounds for printing dicts consistently (85062d1), but #2044 added a set as a parameter value, which caused inconsistencies to start appearing again.
> Restore stable reprs across multiple processes in test_direct_strategies.py

- azure-pipelines.yml
- build.sh
- tooling/src/hypothesistooling/__main__.py
We can skip install of our "tool Python" by having Pipelines supply that, which makes the install step of _every_ task take one instead of three minutes.  That's pretty handy when the rest of a slow task takes ~6 minutes, and a fast one takes 20 seconds!
> Faster build on Azure Pipelines

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/healthchecks.rst
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/src/hypothesis/statistics.py
- hypothesis-python/tests/cover/test_phases.py
I went to look something up in the settings docs, and ended up doing a bunch of minor refactoring, improved a few reprs and error messages, and added some better markup in a few places.
It's individually-minor stuff, but the little things add up for users - or for contributors!
> Clarify settings reprs and refactor decoration logic

- hypothesis-python/RELEASE.rst
- hypothesis-python/scripts/basic-test.sh
- hypothesis-python/src/hypothesis/extra/lark.py
- requirements/coverage.txt
Turns out that Lark added [a required argument in the latest patch version](https://github.com/lark-parser/lark/compare/0.7.1..0.7.2), which made the tests fail for our in-progress release :sob: 
So this PR makes the fix, and ensures that we test against both the old and the new versions.
> Fix for newest Lark parser

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/tests/py3/test_lookup.py
Another enhancement PR prompted by my [Hypothesmith](https://github.com/Zac-HD/hypothesmith/) project, this time to support the lovely [libCST](https://libcst.readthedocs.io/en/latest/why_libcst.html).
Concrete syntax tree?  Just what I wanted... and every node is a dataclass with type annotations, so it only takes a little massaging for `from_type` to cheerfully construct a whole tree for me.  Well, once it handles abstract base classes anyway!
(I don't actually *need* this for Hypothesmith since I'm going to register a strategy for every concrete node type anyway, but it's a small enough change and the only downside I can see is that we might end up walking down a tree that doesn't have any concrete subclasses after all.)
> Support `from_type` for abstract classes with unknown concrete subclasses

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/lark.py
- hypothesis-python/tests/lark/test_grammar.py
Closes #1806, in that it turns out to make supporting `@declare`d indents possible for [hypothesmith](https://github.com/Zac-HD/hypothesmith) *without* weird hacks, and handling of identifiers a *lot* more efficient.
> Explicit terminal strategies for Lark

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/numpy.py
- hypothesis-python/src/hypothesis/internal/coverage.py
- hypothesis-python/src/hypothesis/internal/validation.py
- hypothesis-python/tests/cover/test_validation.py
A couple of minor improvements have been made:
- The check_type function now tests for lists of length 1 so the
returned mesaging is better.
- check_valid_size() now passes the name variable into check_type
as this is a required argument.
This fixes #2083.
> Improved the check_type and check_valid_size validation functions

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/numpy.py
- hypothesis-python/tests/numpy/test_argument_validation.py
- hypothesis-python/tests/numpy/test_gen_data.py
From discussion with @Zac-HD at Euroscipy. Generating arrays with string dtypes with `min_len=0` issues warnings like:
> properties/test_pandas_roundtrip.py::test_roundtrip_pandas_dataframe
>  /home/takluyver/miniconda3/envs/hypothesise-xarray/lib/python3.7/site-packages/hypothesis/extra/numpy.py:147: HypothesisDeprecationWarning: Generated array element b'\xff\xc00\xff\xc8\xff\xb2\xff)\x00\xd6\xff\xff\xcb\xff' from binary().filter(lambda b: b[-1:] != b"\0").map(bytes_).map(convert_element) cannot be represented as dtype dtype('S') - instead it becomes b'\xff' (type <class 'numpy.bytes_'>).  Consider using a more precise strategy, for example passing the `width` argument to `floats()`, as this will be an error in a future version.
This is because the value generation from `from_dtype` …
> Deprecate generating string dtypes with unspecified length

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/internal/compat.py
- hypothesis-python/src/hypothesis/searchstrategy/attrs.py
- hypothesis-python/tests/cover/test_attrs_inference.py
- requirements/py2.txt
Fix for #2091 
Changed the attrs strategy to fallback to `from_type` if the attribute type if from `typing`
in python < 3.6 (including 2.7), `typing.Union` is a subclass of `typing._FinalTypingBase`
> Test and fix attrs type inference when using the typing module

- hypothesis-python/docs/data.rst
`draw` doesn't take a parameter `min_size` but `text` does.
> Fix a typo in a composite example

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/errors.py
- hypothesis-python/src/hypothesis/searchstrategy/strategies.py
- hypothesis-python/tests/common/setup.py
- hypothesis-python/tests/cover/test_example.py
- requirements/py2.txt
- requirements/test.in
- requirements/test.txt
The `.example()` method on strategies is great for interactive exploration.
Unfortunately, it's not (yet) as clear as it should be that `.example()` should not be used in tests - it's built on top of `@given`, but: slower, more prone to duplicates, less configurable, doesn't support minimal examples, and *doesn't save or replay failures*.
So this PR adds a warning, which will only trigger if the code is not running in an interactive session.
> Warn on non-interactive `s.example()`

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/details.rst
- hypothesis-python/src/hypothesis/__init__.py
- hypothesis-python/src/hypothesis/control.py
- hypothesis-python/src/hypothesis/internal/compat.py
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/cover/test_targeting.py
This is the minimum releasable implementation that closes #1779:
- One new user-facing API (the `hypothesis.target()` function)
- Engine upgrades, mainly around `TargetSelector`.
- Plenty of documentation warning that this is experimental.
I've also been careful to leave as much flexibility as possible for future changes, where that didn't prematurely complicate the code.  
Thoughts?  Feedback on the implementation and API would be great, but I'm especially interested in how we could evaluate and tune the various constants for better performance :smile:
> Implement targeted PBT

- hypothesis-python/RELEASE.rst
- hypothesis-python/setup.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/src/hypothesis/searchstrategy/attrs.py
- requirements/py2.txt
Use of `cmp=` is deprecated, and the workaround is a lot clumsier than our one-line `getattr` for pre-17 attr versions.  So given `attrs` excellent compatibility policy, I thought that the best option was to simply increase the minimum version.
Closes #2110.
> Update attrs dependency to >= 19.2

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/configuration.py
- hypothesis-python/src/hypothesis/database.py
- hypothesis-python/src/hypothesis/internal/charmap.py
- hypothesis-python/src/hypothesis/internal/reflection.py
- hypothesis-python/tests/cover/test_filestorage.py
- hypothesis-python/tests/cover/test_reflection.py
- hypothesis-python/tests/nocover/test_database_usage.py
This PR aims to delay creation of the `.hypothesis/examples` directory until it is actually needed. This is done by shifting responsibility for creation from `configuration.py` to `DirectoryBasedExampleDatabase.save`.
Be sure to let me know if anything else is needed from my side :)
And please point me to another issue I could pick up so I can keep working towards my hacktoberfest t-shirt!
Fixes #2106
> Fix #2106. Defer directory creation to DirectoryBasedExampleDatabase

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/numpy.py
- hypothesis-python/tests/numpy/test_argument_validation.py
- hypothesis-python/tests/numpy/test_gen_data.py
It's (un?)surprisingly tricky to get all the subtle things right here: for example, `np.shares_memory` returns `False` for views that are of size zero!  Anyway, thanks to a lot of feedback from Hypothesis I think I've got it all right now :grin: 
Closes #1930.
> Numpy `basic_indexes(shape)` strategy

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/src/hypothesis/searchstrategy/misc.py
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/cover/test_simple_collections.py
We have some fancy handling lately for generating unique collections from some small known sequence of elements, i.e. `UniqueSampledListStrategy` and the related filtering improvements.
Now we take advantage of that logic for the common case that a strategy can only generate one (or perhaps two) elements.  It's only a little more efficient on a per-case basis, but I was prompted by a `FilteringTooMuch` while mucking around so here it is.
> Implement `booleans()` and `just()` as `sampled_from()` for better collections

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/src/hypothesis/extra/django/_fields.py
- hypothesis-python/src/hypothesis/extra/pandas/impl.py
- hypothesis-python/src/hypothesis/searchstrategy/strategies.py
- whole-repo-tests/test_type_hints.py
Closes #2071, with a slight change of plans - I've just gone through some manual inspection without writing automated tests, since it turns out that mypy still has trouble expressing Hypothesis' types.
So IMO this is patch is a nice improvement, but it's not worth doing much more with static typing at the moment.
> More precise strategy type-hints

- azure-pipelines.yml
- hypothesis-python/RELEASE.rst
- hypothesis-python/setup.py
- hypothesis-python/src/hypothesis/extra/pytestplugin.py
- hypothesis-python/tests/pytest/test_compat.py
- hypothesis-python/tests/pytest/test_parametrized_db_keys.py
- hypothesis-python/tox.ini
- tooling/src/hypothesistooling/__main__.py
Detecting whether a pytest Item is parametrized turned out to be deceptively simple. However, I have trouble figuring out how to test this code. I can make a (parametrized) test that uses an InMemoryExampleDatabase, and look into it's state in a different test, but this does not seem to be a nice way forward.
Secondly, doing `item.obj.hypothesis.inner_test._hypothesis_internal_add_digest = item.nodeid.encode("utf-8")` as proposed in the issue doesn't seem to produce the desired behaviour for some reason. 
I'll dig a bit further through the internals tomorrow.
Fixes #1996
> Implement pytest.mark.parametrize detection. Fix #1996

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/reflection.py
I was in the area and noticed the code for `is_mock` was generating an awful lot of UUIDs for checking whether a mock object was really a mock object. This seems unneccessary and while it's probably not particularly important this code *is* on the hot path, so I thought I'd patch it to use a simpler check.
> Simplify checking for mock objects

- build.sh
- requirements/tools.txt
The build on master is currently broken: https://travis-ci.org/HypothesisWorks/hypothesis/jobs/597671659#L649
This appears to be a mismatch between pip-tools (which uses internal pip APIs) and pip.
This PR does two things:
1. Manually bump the pip-tools to the latest version
2. Ensure when building our tools virtualenv we always use the latest pip
Hopefully that should both fix this mismatch and make them less likely in future.
> Attempt to unbreak build by using latest pip and pip-tools

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/reflection.py
- hypothesis-python/tests/cover/test_reflection.py
Turns out some of our reflection tests fail if you run them first. Why? Because we mess with `tokenize.detect_encoding` for our own sakes, but it turns out that the standard library *most unreasonably* expects to be able to call that function too. If the tests run later then the line cache is already populated and it's not needed, but if the tests run first then the `inspect` module needs to be able to `detect_encoding` and we can't.
This fixes that by giving us a copy of `detect_encoding` local to the reflection module that we can mess with without stepping on the standard library's toes.
(The things you find when you run the Hypothesis build with `-n40`...)
> Don't attempt to mess with tokenize.detect_encoding

- .travis.yml
Travis is now very much the bottleneck on our pull requests, and all of its tasks are also runnning on Azure. Currently we only really care about it because it still manages our releases.
This PR guts our Travis build in two ways:
* It removes a bunch of tasks we don't really need to run on Travis (and unifies the main and precheck stages as a result)
* It restricts the rest to only run on master builds rather than pull requests. 
This should significantly speed up our PR workflows.
> Remove many of our Travis build tasks

- .travis.yml
Apparently #2140 broke master builds (or Travis is being flaky): https://github.com/HypothesisWorks/hypothesis/pull/2140#discussion_r335457825
This PR removes the condition on our prechecks so they always run. This *shouldn't* be necessary, but maybe it will help? I've already unmarked Travis as required for merge so we'll still get most of the benefits.
> Remove if check on Travis

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/cover/test_statistical_events.py
I noticed that this could be a problem while noodling on #2078 a while ago, but seeing this [near-kiloline stats dump](https://github.com/aparnasbose/hypothesis/blob/master/flaky%20test#L6493-L7412) made me give up on [the associated StackOverflow question](https://stackoverflow.com/questions/58320032/how-to-debug-when-hypothesis-produces-flaky-test-error).
So while this makes the reprs expose a bit *less* for a change, I think the overall effect is that it's much easier to tell what's happening!
- `Rule` still reports which method it's wrapping, but without the memory address
- `Bundle` reports the name, but not it's (varying) contents
- `RuleStrategy` reports the machine it's attached to, but not that machine's current state.
(see the repr of the machine for that, which hasn't changed)
> Better stats reporting for state machines

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/database.py
- hypothesis-python/src/hypothesis/internal/reflection.py
- hypothesis-python/tests/numpy/test_gen_data.py
- whole-repo-tests/test_security.py
FIPS 140-2 is an obnoxious mistress, but SHA384 is a fine replacement for an MD5 even in circumstances where you don't hugely care about cryptographic security.
> Remove one final use of md5

- hypothesis-python/tests/conftest.py
Closes #1919, by adding a pytest hook to our test suite derived from #2129.
> Check for PRNG state leaks

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/searchstrategy/types.py
- hypothesis-python/tests/py3/test_lookup.py
> Add support for `SupportsIndex` in Python 3.8

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/searchstrategy/recursive.py
- hypothesis-python/tests/cover/test_recursive.py
- hypothesis-python/tests/cover/test_reproduce_failure.py
- hypothesis-python/tests/quality/test_integers.py
Some flaky tests are blocking #2153. Initially I thought these were caused by #2137 but apparently not! Possibly they were exposed by it, but they're actually two latent longstanding bugs in our test suite:
* We genuinely don't have any examples that guarantee covering invalid base 64, because (on Python 3?) whitespace is stripped from decode
* We were potentially catching a `StopTest` that we shouldn't.
Additionally in investigating and improving the testing of the `recursive` strategy to improve some missing coverage that I got there when I pushed the first set of changes, I discovered that our logic for how many branches we needed in `recursive` was wrong and we were stopping adding child strategies too soon, so I fixed that while I was there.
> Fix some flaky tests and fix a longstanding bug in recursive

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/extra/pytestplugin.py
- hypothesis-python/tests/cover/test_debug_information.py
- hypothesis-python/tests/cover/test_settings.py
Closes #2160 
In the case where `@settings` is applied before `@given`, we set up a shim test function in case `@given` is not called. We then update this shim with attributes created by other decorators. When `@given` is applied, we replace the shim test function with the real test function.
This PR also copies any `hypothesis` attributes from the shim test function onto the real test function, preserving settings that have been applied by other decorators.
The test case added specifically reflects #2160, and checks that the examples added via the `hypothesis_explicit_examples` attribute.
> Warn on settings without given at pytest_runtest_call

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/utils.py
- hypothesis-python/tests/pandas/test_indexes.py
Originally - I think - a typo in 5df039ff, this caused @rsokl and I some confusion as we worked on #2153; it's a separate PR because I don't want to inflict *that* review on anyone else.
> Fix biased_coin doc

- guides/testing-hypothesis.rst
- hypothesis-python/tests/cover/test_example.py
Closes #2167, by adding a comment to explain why this test might mysteriously fail, with advice on how to fix it.
> Explain why launching "python -Werror" might mysteriously fail

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/charmap.py
- hypothesis-python/tests/cover/test_charmap.py
- hypothesis-python/tests/cover/test_deadline.py
Loading the cached charmap from disk always failed because the
`GzipFile` was passed to `json.loads`, which expects a string. Use
`json.load` instead, which accepts a file.
This fixes an issue where the first test in a test run that used the
charmap would be unexpectedly slow.
For context, see https://github.com/HypothesisWorks/hypothesis/issues/2108#issuecomment-548579704.
> Fix loading of charmap from cache file

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/cover/test_stateful.py
If a rule returns MultipleResults then when a step using that rule
is printed the return value should be expanded into multiple
variables. Currently this is not the case
Fixes #2139.
> Make stateful assign to multiple variables when printing steps that return MultipleResults

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/pytestplugin.py
- hypothesis-python/tests/cover/test_setup_teardown.py
- hypothesis-python/tests/pytest/test_profiles.py
Currently, we unconditionally add profile information to the pytest report header.  This PR changes to only adding the information if pytest (*or* Hypothesis) is in verbose mode, which matches the behaviour of pytest's builtin cache plugin.  
Closes #2155.
> Only add profile info to pytest header if in verbose mode

- azure-pipelines.yml
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/src/hypothesis/searchstrategy/types.py
- hypothesis-python/tests/py3/test_lookup.py
If your `TypeVar` has a bound that is treated as a union, it wasn't actually treated as a typevar... *until now*.  If you had two typevars with the same constraints, they werent' distinguished... *until now*.  (if you wanted bare typevars not to always be text, uh, that's a lot harder than it sounds)
Closes #2094.
> Improved handling of typevars

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/searchstrategy/types.py
- hypothesis-python/tests/py3/test_lookup.py
> Add support for `typing.Literal` in Python 3.8 

- .flake8
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py
- hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/src/hypothesis/searchstrategy/lazy.py
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/src/hypothesis/utils/dynamicvariables.py
- hypothesis-python/tests/cover/test_conjecture_utils.py
- hypothesis-python/tests/cover/test_pretty.py
- hypothesis-python/tests/quality/test_shrink_quality.py
- requirements/tools.in
- requirements/tools.txt
- tooling/src/hypothesistooling/releasemanagement.py
https://pypi.org/project/flake8-bugbear/ adds a useful set of more-subjective style warnings to `flake8`.  The main ones of interest to us are checks for unused loop variables, use of `setattr()` with a static name, and constant `assert False` where an exception is always expected.
Since the checks are easy, why not use them?  In particular this found some over-elaborate code relating to fractions, so it definitely catches a few things that nothing else did.
(plus some fixes for documentation formatting, because there's no change in behaviour there either)
> Add `flake8-bugbear` to our CI

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/tests/cover/test_direct_strategies.py
This would almost always raise an internal error, though if you're carefully sneaky you could cause a silent failure instead.  Closes #2178.
> Check that `strategy` argument to `data.draw()` is actually a strategy

- .readthedocs.yml
- .rtfd-reqs.txt
This PR updates our readthedocs configuration to build using Python 3 rather than Python 2.
As well as getting ahead of the game for January 2020, we can inline the "install hypothesis[all]" requirements file, and users might appreciate seeing the `*` indicating a keyword-only argument over the `__reserved` argument that we convert.  ([before](https://hypothesis.readthedocs.io/en/latest/numpy.html#hypothesis.extra.numpy.mutually_broadcastable_shapes), [after](https://hypothesis.readthedocs.io/en/py3-for-rtfd/numpy.html#hypothesis.extra.numpy.mutually_broadcastable_shapes))
[config file schema](https://docs.readthedocs.io/en/stable/config-file/v2.html), [build logs](https://readthedocs.org/projects/hypothesis/builds/9917470/)
> Update readthedocs config

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/searchstrategy/functions.py
This flag was previously used in the logic for deciding whether to print a `@reproduce_failure` blob, but that logic was simplified in #2054, and so the flag became unused.
This PR removes the remaining code that was creating or updating the unused flag.
> Remove unused flag data.can_reproduce_example_from_repr

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/src/hypothesis/searchstrategy/numbers.py
- hypothesis-python/tests/cover/test_direct_strategies.py
- hypothesis-python/tests/cover/test_float_nastiness.py
This reduces the number of recursive calls and of `.map()` and `.filter()` layers in many `floats()` strategies, which in many cases gives us a small but noticable performance improvement.
Once this is merged, I'll have a follow-up PR for #1704; I thought that this would be worth doing separately and much easier to review this way :smile:
> Handle `floats()` width further down the stack

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/datatree.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/cover/test_conjecture_data_tree.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/cover/test_regex.py
- hypothesis-python/tests/nocover/test_recursive.py
Key Idea: If we've discarded an example then everything below that point in the tree necessarily contains discards and thus is redundant and so we might as well prune it out of the tree, encouraging us to pursue parts of the tree that just skip out on the discarded bits altogether in future.
I've been thinking about how to do this for a while and all of the attempts I've thought about have been awful, and then ~I realised this morning that it's fairly easy to do by using the first completed discarded example as the point after which we know that going deeper into the tree is redundant.
The big big win here is on `integer_range` which no longer creates huge redundant sequences on small ranges that aren't a multiple of two. e.g. `@given(integers(0, 2))` used to produce a lot of examples …
> Prune parts of the data tree that have discards in them

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/tests/cover/test_core.py
Due to the absence of a pass-through implementation of `WithRunner.do_validate`, strategies supplied to a test method (in a test class) were not being properly validated before running the test.
> Properly validate strategies used with test methods

- hypothesis-python/tests/cover/test_example.py
If you do a clean install of hypothesis with an older version of virtualenv, `tests/cover/test_example.py::test_interactive_example_does_not_emit_warning` will fail because `python -Werror` fails in `site.py`. With this PR, this condition is detected - that is, if `python -Werror` itself fails for some reason - the test is simply skipped. If just running python succeeds, then the actual test code is run (through `pexpect`) and the test will succeed or fail as per normal.
> Skip the interactive test if -Werror fails

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/tests/cover/test_health_checks.py
> Count `charmap()` towards `text()` drawtime

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/conf.py
- hypothesis-python/src/hypothesis/extra/numpy.py
- hypothesis-python/tests/numpy/test_argument_validation.py
- hypothesis-python/tests/numpy/test_gufunc.py
Closes #2174.  
This is a smaller API than [`hypothesis-gufunc`](https://github.com/uber/hypothesis-gufunc), but should have significantly better shrinking performance.  @rdturnermtl, you might want to port over to use this!
I'm implicitly pushing advanced users onto `@st.composite` to define their own gufunc-arrays strategy, as everyone will want something a little different - and Hypothesis is a library full of things for them to compose, not a my-way-or-highway framework.
> Upgrade `mutually_broadcastable_shapes()` to handle gufunc signatures

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/internal/escalation.py
- hypothesis-python/src/hypothesis/provisional.py
such as `zipapp` or `PyOxidizer`.
- `is_hypothesis_file` will always return `False`, because `hypothesis.__file__` is not defined.  This weakens our traceback elision somewhat; it's clearly better than a crash but if we get a non-trivial user base on these platforms it's probably possible to do better.
- Provisional strategies require one of Python 3.7+, `__file__`, or the `importlib_resources` backport to load the list of TLDs.  Anyone in the third category is encouraged to contact us, because I'm *not* adding a conditional dependency without any evidence that it would actually be useful.
Closes #2196.
> Suport platforms where `__file__` is not defined

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/tests/py3/test_annotations.py
While looking into `is_invalid_test` for #2199, I noticed that most `@given` usage errors are reported lazily, but "Missing required kwarg" is reported eagerly.
After investigating #625, I couldn't find any reason to think that this was a deliberate choice, so it's probably just a minor oversight that slipped through.
I've therefore switched those errors over to use lazy reporting, to match the other argument usage errors.
> Make @given raise "Missing required kwarg" errors lazily

- paper.bib
- paper.md
[JOSS](https://joss.theoj.org/) is a journal specifically for advertising the research benefits of your open source project. @Zac-HD suggested ages ago that we should have a paper there and then, for reasons that are entirely my fault, we err didn't. This is is step one of my attempting to fix this.
Unfortunately we cannot currently easily preview the resulting paper without merging to master (see https://github.com/openjournals/joss/issues/617), but this pull request is an opportunity for people to comment on content, form, etc. Also @Zac-HD do you have an orcid I can include for you as the author?
Currently Zac and I are listed as the coauthors. This isn't due to any particular desire to exclude people so much as the result of there being a *lot* of contributors and having to cut it …
> Write a JOSS paper for Hypothesis

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/internal/conjecture/utils.py
- hypothesis-python/src/hypothesis/internal/entropy.py
- hypothesis-python/src/hypothesis/internal/floats.py
- hypothesis-python/tests/cover/test_lazy_import.py
- hypothesis-python/tests/nocover/test_skipping.py
- hypothesis-python/tests/numpy/test_lazy_import.py
Via https://github.com/astropy/astropy/pull/9532#issuecomment-552346683, our attempted import of `nose` (to get its `SkipTest` exception) can cause problems in some setups.
So I've adapted [this trick](https://twitter.com/jakevdp/status/1130987263301627904) to ensure that we only import test runner packages (and numpy) if someone else did so first.  If it's never imported, we don't need to integrate with it!
Caveats: `st.from_type()` still does optimistic imports, and if you're on Python <= 3.5 `numpy` will be imported to support 16-bit floats.  Otherwise we should be a bit lighter than before 😄
> Avoid being the first to import large packages

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/pytestplugin.py
This ensures that, if you're using a version of pytest which is older than our plugin supports - which is itself older than the pytest developers support - we just disable the plugin instead of throwing an internal error.  You won't get e.g. statistics support, but can still run the tests!
This means you get a warning and graceful degredation in old environments, and in particular that being unable to upgrade pytest won't stop you upgrading Hypothesis.
> Disable pytest plugin if pytest is too old

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/src/hypothesis/searchstrategy/types.py
- hypothesis-python/tests/conftest.py
- hypothesis-python/tests/cover/test_statistical_events.py
- hypothesis-python/tests/py3/test_async_def.py
- hypothesis-python/tests/py3/test_asyncio.py
- hypothesis-python/tests/py3/test_lookup.py
- hypothesis-python/tests/py3/test_lookup_py38.py
i.e. `typing.Final` and `typing.TypedDict`, closing #2116, and fixes a new asyncio warning.
The support for optional keys in `typing.TypedDict` won't do anything until python/cpython#17214 is released, but until then it's valid to just assume that everything is required.
> Support new-in-3.8 typing module types

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/tests/cover/test_float_nastiness.py
Closes #2201.  
This does technically break `floats(min_value=-0.0, max_value=0.0, exclude_max=True)` (i.e. `just(-0.0)`) and `floats(min_value=-0.0, max_value=0.0, exclude_min=True)` (i.e. `just(0.0)`).  I sincerely doubt that anyone at all was doing this, but could turn it into a deprecation warning if requested.
> Stop `floats(max_value=0.0, exclude_max=True)` generating `-0.0`

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/control.py
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/tests/cover/test_explicit_examples.py
I was trying to improve our example output a bit and the way we duplicate it between explicit examples and generated examples made that hard to deal with. This attempts to commonise that logic by running explicit examples through the same code path as generated examples (with a dummy version of the conjecture data object)
> Commonise logic between explicit examples and generation

- README.rst
While most of the changes in #2222 were subjective, I noticed that one of them was fixing a clear error in the current text.
So I took the original patch and cut it down to just this one change (preserving the original author credit), so that the improvement isn't lost.
Thanks to @Thethaa for spotting this problem!
> Add missing word in README.rst

- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/cover/test_core.py
- hypothesis-python/tests/cover/test_intervalset.py
- hypothesis-python/tests/cover/test_provisional_strategies.py
- hypothesis-python/tests/cover/test_reproduce_failure.py
- hypothesis-python/tests/cover/test_slippage.py
- hypothesis-python/tests/cover/test_stateful.py
- hypothesis-python/tests/cover/test_statistical_events.py
- hypothesis-python/tests/cover/test_verbosity.py
- hypothesis-python/tests/numpy/test_gen_data.py
- hypothesis-python/tests/pytest/test_seeding.py
This pulls out a lot of the test suite related changes from #2219. Once it's merged I'll rebase on top of it.
The main thing this does is add a lot of special cases where we're currently relying on a `@given` to provide coverage. It also adds a few cases where we want to test with a higher `max_examples` than is default for `check-coverage`. 
I've been running `check-coverage` under autoclave for a while on this and I think this catches all the flakiness for `check-coverage` on master. It may not catch all other flakiness we've been seeing.
> Improve reliability of test suite under check-coverage
