- docs/community.rst
> Capitalise bullet point

- docs/community.rst
Hacker School is now the Recurse Center: https://www.recurse.com/blog/77-hacker-school-is-now-the-recurse-center
> update HS/RC link

- docs/supported.rst
PyPy (not pypy): http://pypy.org/features.html
OS X (not OSX): https://www.apple.com/osx/
> minor typos / casing

- docs/community.rst
While self-deprecation can be a source of humour, I think the world, community & individuals are better without it and would like to humbly suggest that given your writing and the work you've put into this project that you more than meet the level required to be considered "excellent". :)
> Remove self-deprecation

- docs/stateful.rst
Sorry for the nitpick, I just found those when reading through the docs and thought I might flag them up.
> Small fixes to sentences/wording.

- docs/endorsements.rst
I would like to endorse Hypothesis for the use in my open source projects
"natsort" and "fastnumbers".
> Add endorsement for natsort and fastnumbers.

- docs/endorsements.rst
(I endorse Hypothesis, having been involved in its usage at LaterPay)
> Disambiguate personal / company confusion

- src/hypothesis/strategies.py
This makes it appear in the online docs.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/drmaciver/hypothesis/132)
> Add recursive to __all__ in strategies

- docs/internals.rst
> Correct indentation in code example

- src/hypothesis/settings.py
- tests/cover/test_testdecorators.py
There aren't any tests for this yet, although I have some other code that uses Hypothesis across multiple threads that I used to check that this implementation isn't completely broken. I'll write some real tests when it's not 1am. :-)
> Create and cache example databases per-thread

- docs/details.rst
> Grammar improved

- CONTRIBUTING.rst
- src/hypothesis/strategies.py
- tests/cover/test_basic_strategy.py
- tests/cover/test_sets.py
- tests/cover/test_simple_collections.py
- tests/cover/test_validation.py
See GitHub issue #193 for more information.
> Uniquify lists() based on direct object equality when unique=True

- docs/endorsements.rst
:+1: :chart_with_upwards_trend:
> Add endorsement by adamchainz

- docs/details.rst
Hi,
just a very small typo. :-)
Best regards,
Patrick Kanzler
> DOC fixed small typo

- docs/usage.rst
Priority uses Hypothesis the best of all my projects, and it's finally released, so here we are!
> Add Priority to the users list.

- docs/usage.rst
It just looks so wrong to me with a capital Q :wink:
> Fix spelling of qutebrowser

- docs/endorsements.rst
> I am a very important man, and will testify on Hypothesis' behalf.

- CONTRIBUTING.rst
- src/hypothesis/searchstrategy/numbers.py
- src/hypothesis/strategies.py
- tests/cover/test_float_nastiness.py
- tests/nocover/test_floating.py
Added infinity/nan filtering for nasty_floats
Added nan filter to FullRangeFloats
This a partial solution to issue 186.
> Added infinity/nan filtering for floats

- docs/data.rst
Just simple doc addition, to show examples on choice and sample_from. stolen from issue #243
> Update docs (data.rst) to show choice and sample from.

- src/hypothesis/strategies.py
Added private functions check_valid_integer(), check_valid_bound(), &
check_valid_interval().
Moved bounds & type checking in integers() and floats() to pre-condition
checks, separated from strategy implementation logic.
> Factored bound checking out of integers() & floats()

- src/hypothesis/core.py
Found these whilst upgrading some tests to 2.0 seeing a health check failure.
> Fix some typos

- docs/usage.rst
Axelrod is available on pypi and has some hypothesis testing implemented with a view to adding more.
This commit b2050322f0ec4f4f1fa86211dc48b148c54c0cb3 implements the tests.
Awesome library :) Feels like doing magic. :tophat:
> Adding axelrod to usage.rst.

- docs/changes.rst
Easy to guess what you meant from the surrounding context.
> Fix typo in changelog

- CONTRIBUTING.rst
- docs/extras.rst
- docs/healthchecks.rst
- docs/settings.rst
I was updating projects using hypothesis today and noticed a couple of issues in the documentation. This pull request has my attempt at fixing those issues.
I hope this helps.
> Documentation updates for v3

- README.rst
> Update README regarding Python 2.6 and 3.3

- CONTRIBUTING.rst
- docs/django.rst
- src/hypothesis/extra/django/models.py
- tests/django/toystore/models.py
- tests/django/toystore/test_given_models.py
> Django model default values

- CONTRIBUTING.rst
- docs/examples.rst
I'm guessing the existing code was an older version of hypothesis syntax, and never got updated.  This gets it working again.
> Update the rest api fuzzing example in the docs

- CITATION
This is based on this article
http://www.software.ac.uk/blog/2013-09-02-encouraging-citation-software-introducing-citation-files
Note that there is no specific style, this is a set of instructions but
I have based it on the GAP style file
<https://github.com/gap-system/gap/blob/master/CITATION>, although I
have simplified it somewhat (to have a bare set of requirements).
Also: there are two points in which the version should be
> Adding a CITATION file.

- src/hypothesis/internal/charmap.py
At least, that’s the theory.
Fixes #302.
> Calculate the Unicode table atomically

- docs/settings.rst
> Update settings.rst to use the new settings syntax

- docs/healthchecks.rst
- docs/settings.rst
It comes up in error messages.
> Mention the suppress_health_check settings parameter in docs.

- src/hypothesis/strategies.py
Total pedantry, but I saw it [on this docs page](http://hypothesis.readthedocs.io/en/latest/data.html), so I thought I'd fix.
> Minor punctuation fix

- docs/endorsements.rst
Adding my name to the list of Hypothesis users via a GitHub pull request as requested. Hopefully my gramar and spelling are good, if not plese feel free to get me to change the test.
> Add Russel Winder to the list of endorsers.

- src/hypothesis/strategies.py
- tests/cover/test_direct_strategies.py
- tests/nocover/test_example_quality.py
> Add additional parameters to fractions and decimals strategies.

- docs/usage.rst
> Add another Hypothesis using package to the list.

- docs/usage.rst
> Add another hypothesis user to the list.

- docs/stateful.rst
> Fixed typo

- scripts/basic-test.sh
- setup.py
Builds on #362, experimental fix for #394. Let's run this in CI and see what happens.
> Experiment with switching from fake-factory to faker

- docs/index.rst
- docs/strategies.rst
> Add a new listing for external strategies.

- CONTRIBUTING.rst
> Add myself to the list of contributors.

- docs/changes.rst
- setup.py
- src/hypothesis/version.py
Provides change log and version bump and nothing else, but I need to do a pull request because protected branches. :-)
> Release pull request for Hypothesis 3.6.1

- .travis.yml
- Makefile
- scripts/install.sh
- tox.ini
To my extreme confusion, all the tests pass without any modification
required.
> Add Python 3.6 to the build matrix

- docs/usage.rst
Thanks for the great software!
> Add PyCEbox to list of open source projects using hypothesis

- src/hypothesis/strategies.py
This is the reverse of the normal order of Fisher-Yates because
this shrinks "correctly" (or at least more consistently with the
usual way Hypothesis does things, and the way permutations shrank
historically): Smaller is lexicographically closer to the identity
permutation.
Unlike the old implementation, this one isn't quadratic in the
size of the list. This fixes issue #438.
> Fisher-Yates style implementation of permutations

- tests/common/__init__.py
- tests/conftest.py
- tests/cover/test_conjecture_engine.py
- tests/cover/test_integer_ranges.py
- tests/datetime/test_datetime.py
- tests/nocover/test_example_quality.py
- tests/nocover/test_fixtures.py
This PR makes time in our build run 100x faster.
This causes a few tests to start failing, so it also relaxes the timeouts so they can have a bit more time to run.
(I don't expect I've caught them all and am going to use Travis to catch the rest, so I'm expecting a failed build initially).
> If we want faster builds, why don't we just speed up time?

- docs/supported.rst
Rebased version of #353. Hopefully this should trigger some working CI, and we can get this merged.
> Rebased version of "Add link for CI and show nose supported"

- docs/changes.rst
- src/hypothesis/version.py
This updates the version and the changelog to reflect the changes.
Once this is merged and the master build passes I will tag it and do a release.
> Hypothesis 3.7.0 release

- CONTRIBUTING.rst
- Makefile
- src/hypothesis/internal/reflection.py
- tests/cover/test_lambda_formatting.py
Just a small thing I noticed while browsing the code.
> Fix typo in regex

- setup.py
Addressing @Zac-HD’s comment [on 57416dc](https://github.com/HypothesisWorks/hypothesis-python/commit/57416dc9a3464ce6ed5735bf1115fc3e93279b7a#commitcomment-21685504).
> Add Python 3.6 support to setup.py

- setup.py
Resolves @Zac-HD’s comment here: https://github.com/HypothesisWorks/hypothesis-python/pull/489#discussion_r110558177
> Correct the supported Django versions

- docs/numpy.rst
- src/hypothesis/extra/numpy.py
- src/hypothesis/strategies.py
Basically just passing around more attributes so that Sphinx's introspection works as expected.  Closes #474.
> Improved Sphinx compatibility

- docs/changes.rst
Apparently I forgot to thank @inglesp when writing this changelog entry. :-( This fixes that.
> Add missing thanks to changelog

- .travis.yml
- CONTRIBUTING.rst
- Makefile
- requirements/tools.txt
For real this time.  #500 was meant to do this, but I forgot to update the base branch and it's easier to just create a new pull request than try to undo this mess.
> Add RST linting to our build process

- docs/endorsements.rst
> Add endorsement from Wellfire Interactive

- requirements/benchmark.txt
> Maybe we shouldn't install Hypothesis from pypi

- Makefile
- scripts/benchmarks.py
- scripts/check-changelog.py
- scripts/check-untagged.py
- scripts/check_encoding_header.py
- scripts/deploy.py
- scripts/enforce_header.py
- scripts/hypothesistooling.py
- scripts/tool-hash.py
- scripts/unicodechecker.py
As observed in #540, scripts are not currently being autoformatted. As an increasingly large number of our scripts are written in Python rather than bash (yay!) this seems like an unfortunate oversight. This PR fixes that oversight.
> Autoformat scripts too

- docs/changes.rst
- src/hypothesis/core.py
- src/hypothesis/version.py
This is a pure refactoring change that tears given apart and breaks it up into smaller functions, which is long overdue.
The result isn't *much* easier to work with, but is at least better demarcated into distinct sections. More improvement could be used here, but this is a decent starting point.
This pull request is based off #498 ~~as an incentive to get that one reviewed faster~~ because I made some changes to given in there and trying to merge changes across this refactor would be awful. I'll reset the base to master once that one has been merged.
> Break up given into smaller chunks

- .travis.yml
- Makefile
- scripts/basic-test.sh
- scripts/check-ancient-pip.sh
- scripts/install.sh
- scripts/retry.sh
Supersedes #578 by actually fixing the issues raised by shellcheck. Of course this may have broken something, because shell script hilarity. All the proposed fixes _look_ sensible, but I’d like the CI to have a crack at it first.
> Correct issues raised by shellcheck

- scripts/check-changelog.py
Closes #592, and avoids a possible bad day with many releases (or malformed changelog, I guess).
> More precise check for version and date

- docs/changes.rst
- docs/community.rst
- docs/conf.py
- docs/data.rst
- docs/development.rst
- docs/endorsements.rst
- docs/examples.rst
- docs/packaging.rst
- docs/quickstart.rst
- docs/support.rst
- docs/supported.rst
- docs/usage.rst
- setup.py
Closes #532, replaces #603.
If it's not obvious what this changes, I should probably revise it 😜
> Updates to docs, clarifying supported versions

- docs/endorsements.rst
Hey cuz!
Here's a testimonial - we've been using Hypothesis for a few months now and it kicks ass. Let me know if there's anything else we can do to help out.
> Add Stripe to endorsements.rst

- CONTRIBUTING.rst
- Makefile
- guides/README.rst
- guides/review.rst
This is an attempt at solving #505 - it adds a section to the CONTRIBUTING.rst outlining what we should be looking for in review.
Critiques and suggested additions *extremely* welcome, both from Hypothesis maintainers and externally.
> Draft review guidelines proposal

- docs/changes.rst
Ping @DRMacIver; I've cancelled the other build.
> Correct date in changelog

- docs/changes.rst
- scripts/basic-test.sh
- src/hypothesis/extra/django/models.py
- src/hypothesis/version.py
- tests/django/toys/settings.py
- tests/django/toystore/test_given_models.py
Closes #439.  Extracted from #621 as it's only related by implementation.
> Respect Django's USE_TZ setting in the Django extra

- docs/strategies.rst
For appearance and convenience.
> Add a description to hs-dbus-signature entry

- docs/changes.rst
- scripts/hypothesistooling.py
- src/hypothesis/core.py
- src/hypothesis/version.py
- tests/cover/test_explicit_examples.py
Closes #313.  Not much else to say when the changelog is longer than the diff.
> Print explicit examples in verbose mode

- scripts/benchmarks.py
Currently our benchmarks are using ttest\_ind to test for a difference in mean sizes, but they don't really satisfy the distributional requirements for a t-test (they are not normally distributed).
In fact our distributions are potentially arbitrarily complicated and don't necessarily follow *any* sensible distribution. So the correct thing to do is switch to a non-parametric test that doesn't depend on the distribution.
This switches us to a [permutation test](https://en.wikipedia.org/wiki/Resampling_(statistics)#Permutation_tests). The way this works is this:
* Under the null hypothesis that the old and new have the same distribution, we can just randomly reassign the data points labels saying whether they come from the old or the new distribution.
* We can now calculate the probability …
> Switch benchmarks to a permutation test for difference in means

- CONTRIBUTING.rst
- docs/changes.rst
- docs/conf.py
- docs/details.rst
- docs/examples.rst
- docs/settings.rst
- docs/stateful.rst
- docs/strategies.rst
- docs/supported.rst
- guides/documentation.rst
The commits should all speak for themselves - this is really a collection of smaller things.
- I really like Sphinx cross-references.  I especially think they're important in the changelog, so readers can immediately jump to more detail when a new thing is introduced.  I wrote a small docs guide mostly to point out how nice they are 😜 
- I dislike deprecated code examples, outdated references, and defaulting to Python 2.
> Various docs updates

- requirements/test.txt
- requirements/tools.txt
Closes #738, closes #743, closes #745.
> Manually bump our dependencies

- docs/changes.rst
- src/hypothesis/internal/charmap.py
- src/hypothesis/searchstrategy/strings.py
- src/hypothesis/strategies.py
- src/hypothesis/version.py
- tests/cover/test_charmap.py
- tests/cover/test_simple_characters.py
> Add whitelist_characters argument to characters() strategy

- guides/api-style.rst
- guides/review.rst
As part of the recent numpy and pandas work I've been thinking about API style and what I'd like Hypothesis's API to look like. In particular I found myself writing some APIs I wasn't happy about, and running into some existing ones.
So I thought it might be helpful to write up a style guide outlining some of my thoughts on this (and where we deviate from them) to help codify this into a set of guidelines for what a Hypothesis API should look like.
Feedback and pushback very welcome.
> [WIP] Add API style guide

- CONTRIBUTING.rst
- RELEASE.rst
- docs/conf.py
- docs/data.rst
- docs/numpy.rst
- src/hypothesis/extra/numpy.py
- src/hypothesis/strategies.py
This includes some changes to the inline documentation at src/hypothesis/strategies.py.
> Various small typos and fixes to 'data' doc.

- CONTRIBUTING.rst
- RELEASE.rst
- src/hypothesis/extra/pandas/impl.py
I made a little change, in the Pandas documentation.
> DOCS: Fixing missing s in pandas documentation - #866

- RELEASE.rst
- docs/details.rst
- src/hypothesis/control.py
- src/hypothesis/core.py
Various very small issues on the 'details' page.
> Some more copy-editing of documentation.

- docs/conf.py
- docs/extras.rst
- docs/packaging.rst
- docs/quickstart.rst
- docs/usage.rst
Replaces #722.  And includes some other tweaks while I was there 😉
> Minor docs updates and cross-references

- RELEASE.rst
- src/hypothesis/core.py
This improves #914 but isn't a full solution, it's just a bunch of low hanging fruit I noticed while looking at the problem just now.
In my testing of this it took the runtime of the example from that issue from ~0.8s to ~0.2s, which is a reasonably large improvement, but it would be nice to get some more of the way there.
> Performance micro-optimizations to our use of coverage

- scripts/install.sh
> Install non-portable pypy on OSX

- docs/settings.rst
So you can directly copy the example into conftest.py and it work.
> Include Verbosity in import for conftest.py.

- .pyup.yml
- .travis.yml
- Makefile
- requirements/tools.in
- requirements/tools.txt
- scripts/validate_pyup.py
Hey, you know what would be really funny? If our pyup config had always been completely broken and we were just relying on default pyup behaviour.
¬_¬
I don't know why I mention that. Obviously that's not the case. That would be really embarrassing if it were true.
But uh on a totally unrelated note I happened to notice that we had an invalid yaml file in the repo that probably isn't for anything important, so I fixed the syntax and added a build task to validate it.
> Fix pyup config

- docs/packaging.rst
> Add a note about Hypothesis's mandatory dependencies

- docs/usage.rst
Closes webyneter/python-humble-utils#98.
> Mention python-humble-utils in docs/usage.rst

- CONTRIBUTING.rst
- RELEASE.rst
- guides/documentation.rst
- src/hypothesis/strategies.py
Clarifies a point from #940; closes #910.
> Tweaks to user and contributor docs

- docs/usage.rst
> Add attrs & argon2_cffi

- scripts/hypothesistooling.py
> Skip running CI on an autocommit for a new version

- docs/usage.rst
Notes:
* I‘m a maintainer on Loris, and I was the one who added it to the test suite. Still counts! 😂 
* Loris is written and Python but not available on PyPI; I claim it’s still okay because it’s an application, not a library.
* I’ll be watching CI closely as a first test of #1014.
> Add Loris to the list of users

- RELEASE.rst
- src/hypothesis/internal/conjecture/engine.py
- tests/cover/test_conjecture_engine.py
Note: This pull request is based off #1029, that should be reviewed and merged first.
This pull request fixes #1027.
(For those keeping track at home, this is a pull request fixing a bug that was found during work on tests that was done to track down a bug that was introduced in a refactoring. Does anyone want a yak hair sweater?)
> Fix key management for examples found during shrinking

- .travis.yml
- examples/test_rle.py
- scripts/basic-test.sh
- tox.ini
> Re-enable examples builds in Travis and make them work

- RELEASE.rst
- src/hypothesis/internal/conjecture/engine.py
- tests/cover/test_conjecture_engine.py
> Skip debug_data when verbosity < debug

- RELEASE.rst
- src/hypothesis/internal/conjecture/data.py
- src/hypothesis/internal/conjecture/engine.py
- tests/cover/test_conjecture_engine.py
#1046 was a nice idea, unfortunately the implementation was totally wrong in the presence of nested intervals. This makes it not totally wrong.
> Correctly handle nested discards

- CONTRIBUTING.rst
- RELEASE.rst
- src/hypothesis/internal/conjecture/engine.py
> Fix typo in docstring

- tests/cover/test_float_nastiness.py
- tests/quality/test_shrink_quality.py
A quality test I'd noticed was flaky plus fixes #1066.
> Fix some flaky tests

- CONTRIBUTING.rst
- RELEASE.rst
- docs/database.rst
- docs/quickstart.rst
- guides/documentation.rst
- guides/review.rst
- src/hypothesis/internal/validation.py
- src/hypothesis/searchstrategy/strategies.py
- src/hypothesis/searchstrategy/strings.py
This pull has been extracted from #1129.
It consists of a variety of improvements to documentation, mostly but not exclusively for contributors (closes #1109 and closes #750).
I have also included some incidental refactoring here, so that #1131 can focus entirely on the `characters()` changes.
> Documentation improvements and incidental refactoring

- RELEASE.rst
- docs/conf.py
- docs/django.rst
- requirements/tools.in
- requirements/tools.txt
- src/hypothesis/extra/django/models.py
- tests/django/toystore/test_given_models.py
- tox.ini
*Just* enough work towards #1116 that it closes #1112.
CC @DRMacIver, @MrGreenTea
> Minimum viable Django validator introspection

- CONTRIBUTING.rst
- RELEASE.rst
- src/hypothesis/internal/conjecture/data.py
.stop_example() is a noop in case data is frozen
> ConjectureData: unconditionally call .stop_example()

- RELEASE.rst
- src/hypothesis/internal/compat.py
> Fix internal error in Django check

- _RELEASE.rst
- docs/database.rst
- docs/settings.rst
- src/hypothesis/_settings.py
- src/hypothesis/core.py
- src/hypothesis/database.py
- src/hypothesis/errors.py
- src/hypothesis/internal/charmap.py
- src/hypothesis/internal/conjecture/utils.py
- src/hypothesis/internal/validation.py
- src/hypothesis/searchstrategy/misc.py
- src/hypothesis/searchstrategy/strategies.py
- src/hypothesis/strategies.py
- tests/cover/test_database_backend.py
- tests/cover/test_direct_strategies.py
- tests/cover/test_example.py
- tests/cover/test_given_error_conditions.py
- tests/cover/test_sampled_from.py
- tests/cover/test_settings.py
- tests/cover/test_simple_characters.py
- tests/nocover/test_database_agreement.py
- tests/numpy/test_sampled_from.py
There are dozens of relatively minor deprecations scattered through our code - from changes to settings, to tighter validation, or new checks for problematic conditions - saying something like "X is bad.  In a future version, [X will be an error | Hypothesis will Y]."
This is the PR that does the future thing.  I strongly recommend reviewing each commit individually, as they're self-contained and seeing how the edits are grouped is pretty useful.
> Implement many minor deprecations in v4.0

- circle.yml
> [WIP] Fix Python installation in CircleCI

- RELEASE.rst
- src/hypothesis/_settings.py
- src/hypothesis/core.py
- tests/cover/test_health_checks.py
- tests/cover/test_settings.py
- tests/pytest/test_capture.py
Closes https://github.com/HypothesisWorks/hypothesis-python/issues/1135.
> warn on @settings without @given

- docs/examples.rst
I’m not 100% sure that my change is correct. I’m only starting to look at Hypothesis. But if it’s not correct, I’m not sure where `Nodes would get its args from
> Use correct strategy

- docs/stateful.rst
Apparently I didn't fully update the example in response to review suggestions!
> Fix stale reference to in_memory_example_db

- .travis.yml
- Makefile
- scripts/check_secrets.py
- scripts/deploy.py
- scripts/hypothesistooling.py
As expected, #1210 didn't entirely work on merge. This hopefully fixes that. I was going to push straight to master but it ended up a bit larger than I intended (though still not large), so PR after all.
Unfortunately very hard to test without actually running it. We definitely need some testing of our build. :-(
> Hopefully fix directory assumptions of deploy script

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/changes.rst
- hypothesis-python/docs/conf.py
- hypothesis-python/docs/database.rst
- hypothesis-python/docs/endorsements.rst
- hypothesis-python/docs/examples.rst
- hypothesis-python/docs/extras.rst
- hypothesis-python/docs/packaging.rst
- hypothesis-python/docs/strategies.rst
- hypothesis-python/docs/usage.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/strategies.py
- hypothesis-python/tests/cover/test_complex_numbers.py
- scripts/basic-test.sh
- scripts/check-release-file.py
- scripts/hypothesistooling.py
Fixes #1225, closes #1219, closes #1142, steals parts of #1156.
> Misc fixes to docs, links, error messages, formatting, etc.

- .readthedocs.yml
- .rtfd-reqs.txt
attention of @DRMacIver
I've confirmed this works in a fork, so I'd suggest just pushing the commit directly to master.
> Fix readthedocs build

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/details.rst
- hypothesis-python/src/hypothesis/core.py
> Speculative fix for settings.derandomize

- hypothesis-python/tests/cover/test_arbitrary_data.py
> Allow rare failure of output capturing

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/utils.py
- hypothesis-python/src/hypothesis/searchstrategy/misc.py
- hypothesis-python/src/hypothesis/strategies.py
- hypothesis-python/tests/cover/test_permutations.py
> Deprecate use of non-sequence types as permutations

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/django/models.py
- hypothesis-python/src/hypothesis/provisional.py
- hypothesis-python/src/hypothesis/strategies.py
- hypothesis-python/tests/cover/test_emails.py
- hypothesis-python/tests/cover/test_provisional_strategies.py
move emails strategy from provisional to strategies.py.
add entry to CONTRIBUTING.rst
fixes #162
> move emails strategy to public API.

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/settings.rst
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/cover/test_datetimes.py
- hypothesis-python/tests/cover/test_flatmap.py
- hypothesis-python/tests/cover/test_health_checks.py
- hypothesis-python/tests/cover/test_integer_ranges.py
- hypothesis-python/tests/cover/test_reporting.py
- hypothesis-python/tests/cover/test_settings.py
- hypothesis-python/tests/cover/test_stateful.py
- hypothesis-python/tests/cover/test_testdecorators.py
- hypothesis-python/tests/cover/test_verbosity.py
- whole-repo-tests/test_deploy.py
> [WIP] Deprecate settings as context manager

- hypothesis-python/RELEASE.rst
- tooling/src/hypothesistooling/releasemanagement.py
> Fix release file management

- hypothesis-python/tests/nocover/test_recursive.py
I stared at this test for a bit and couldn't for the life of me figure out what it was supposed to be testing, so I decided to just kill it. It looks over-complicated and slow. My suspicion is that it is a relic of these things having a much more complicated implementation pre-conjecture but I haven't confirmed.
> Remove flaky test

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/vendor/pretty.py
- mypy.ini
Closes #1359.  CC @pjdelport, if you want to review this :smile:
> Ignore vendored type issues for downstream

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/cover/test_skipping.py
- hypothesis-python/tests/cover/test_stateful.py
Closes #1372.  CC @jacg - this should fix the problem you asked about.
> Always report steps from stateful tests

- hypothesis-python/RELEASE.rst
- hypothesis-python/setup.py
> Fix our version bound for coverage

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/nocover/test_explore_arbitrary_languages.py
Fixes #1380, and also improves the quality of failures we get from that test to be a bit more comprehensible.
> Fix hard to trigger bug in test-case generation

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies.py
- hypothesis-python/tests/cover/test_simple_strings.py
> Add checks for alphabet/char strategy for text.

- CONTRIBUTING.rst
- hypothesis-python/docs/examples.rst
i tried running the examples and found the doctests in example.rst wouldn't run because of a missing import.
Here's the command:  (from the hypothesis-python/docs directory)
`py.test examples.rst`
I also found a code snippet that wouldn't run until I changed the import from `strategy` to `strategies`
This pull request tries to fix these specific issues.
> Example.rst

- hypothesis-python/docs/endorsements.rst
> just a little thx

- .rtfd-reqs.txt
- hypothesis-python/RELEASE.rst
Closes #1326... obvious in hindsight!
> Fix RTFD build for Numpy, Pandas, dateutil

- .travis.yml
> Disable doctests until we fix the script

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
Another extract from #1423 to try and get the size of that pull request under control a bit.
> Improve shrink pass debugging format and extract context manager

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/changes.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/tests/nocover/test_coverage.py
> Pass through the return value from wrapped collector.save_data()

- tooling/src/hypothesistooling/projects/hypothesispython.py
- tooling/src/hypothesistooling/releasemanagement.py
- whole-repo-tests/test_release_management.py
This is a copy of #1539 (fixes #1526), separated into its own PR without the unrelated changes.
> Strip trailing whitespace when reading RELEASE.rst

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/control.py
- hypothesis-python/tests/cover/test_explicit_examples.py
- hypothesis-python/tests/cover/test_logging.py
> Hide nonfinal logging

- hypothesis-python/scripts/basic-test.sh
>  Test with PYTHONOPTIMIZE=2 in CI

- requirements/tools.in
- requirements/tools.txt
- whole-repo-tests/test_security.py
> Run bandit in CI

- CONTRIBUTING.rst
- hypothesis-python/tests/cover/test_given_error_conditions.py
- hypothesis-python/tests/cover/test_simple_strings.py
- hypothesis-python/tests/cover/test_testdecorators.py
- hypothesis-python/tests/cover/test_verbosity.py
- hypothesis-python/tests/nocover/test_given_error_conditions.py
- hypothesis-python/tests/nocover/test_simple_strings.py
- hypothesis-python/tests/nocover/test_testdecorators.py
> refactor(tests): Move slow moving tests to tests/nocover

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/tests/cover/test_reproduce_failure.py
> Do not print blob in quiet mode

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
> fix(core): HypothesisDeprecationWarning now gives indication of slow tests

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/utils.py
- hypothesis-python/src/hypothesis/strategies.py
- tooling/src/hypothesistooling/projects/hypothesispython.py
@Zac-HD This fixes #1576 . I also ran the test suite against CPython master and I couldn't see any failures. Attached the log below for reference. English is not my first language and I hope my tone is right. Feel free to edit the message or suggest improvements if necessary.
Thanks
<details><summary>Python 3.8 pytest log</summary>
```
======================================== test session starts ========================================
platform linux -- Python 3.8.0a0, pytest-3.8.0, py-1.6.0, pluggy-0.7.1
hypothesis profile 'default' -> timeout=-1, database=DirectoryBasedExampleDatabase('/tmp/tmp8hupgrj3/examples')
rootdir: /home/karthi/hypothesis, inifile: pytest.ini
plugins: xdist-1.23.0, forked-0.2, flaky-3.4.0, hypothesis-3.71.3
collected 1727 items …
```
> Fix import related warnings in Python 3.8

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/tests/cover/test_seed_printing.py
- hypothesis-python/tests/cover/test_settings.py
- hypothesis-python/tests/cover/test_simple_strings.py
> Fix reporting verbosity, explicit examples settings bugs

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/searchstrategy/types.py
- hypothesis-python/tests/numpy/test_gen_data.py
- hypothesis-python/tests/py3/test_lookup.py
> Support from_type(Tuple[()])

- .travis.yml
- tooling/src/hypothesistooling/__main__.py
- whole-repo-tests/test_documentation.py
- whole-repo-tests/test_requirements.py
> Consolidate prechecks for faster Travis runs

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/stateful.rst
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/tests/cover/test_settings.py
- hypothesis-python/tests/cover/test_verbosity.py
This PR extends `hypothesis.settings.__call__` to apply settings to `RulesBasedStateMachine`. 
I believe this closes https://github.com/HypothesisWorks/hypothesis/issues/455
> Add settings decorator for RuleBasedStateMachine

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/searchstrategy/types.py
- hypothesis-python/src/hypothesis/strategies.py
Fixes https://github.com/HypothesisWorks/hypothesis/issues/1636
Also added `numbers.Rational`, `typing.Iterable`,`typing.Sequence`,`typing.Collection`,`typing.Sized`
> Added more types to that can be detected hypothesis.infer

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/numpy.py
- hypothesis-python/tests/numpy/test_gen_data.py
Closes #1591 - I had tagged it `good first issue`, but the Numpy details were fiddly enough that I decided to do it myself anyway.
> Check that numpy can represent complex64/unicode/bytestring elements

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/compat.py
- hypothesis-python/src/hypothesis/strategies.py
- hypothesis-python/tests/numpy/test_narrow_floats.py
> Fix ceil and floor for Numpy ints on Py3

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/pytestplugin.py
- hypothesis-python/src/hypothesis/strategies.py
- hypothesis-python/tests/pytest/test_capture.py
> Warn on strategies collected as tests

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/stateful.rst
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/cover/test_stateful.py
Implement the `consumes()` function proposed by @DRMacIver for this purpose.
Closes #136
> Add API to remove items from stateful.Bundle

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/compat.py
- hypothesis-python/tests/py2/test_generate_ints.py
> floor and ceil should return ints, not longs

- hypothesis-python/docs/database.rst
- hypothesis-python/docs/development.rst
- hypothesis-python/docs/examples.rst
- hypothesis-python/docs/packaging.rst
- hypothesis-python/docs/strategies.rst
- hypothesis-python/docs/supported.rst
No associated issue, just a pile of small cleanups I've had accumulating for a while.
> Misc docs cleanup

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/utils.py
- hypothesis-python/tests/nocover/test_integer_ranges.py
- hypothesis-python/tests/numpy/test_gen_data.py
Even for bounded integers with a very wide interval.  Closes #1387.
> Consistent distribution of integers()

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
This adds some docstrings and comments to explain some of the internal design reasoning in the shrinker.
> Improve internal shrinker documentation

- whole-repo-tests/test_requirements.py
To fix our [currently broken build on master](https://travis-ci.org/HypothesisWorks/hypothesis/builds/483167698), which will make any other PRs fail - not a good experience for our contributors!
> Fix broken build (check_requirements) on master

- .isort.cfg
- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/extras.rst
- hypothesis-python/scripts/basic-test.sh
- hypothesis-python/setup.py
- hypothesis-python/src/hypothesis/extra/lark.py
- hypothesis-python/src/hypothesis/internal/validation.py
- hypothesis-python/tests/README.rst
- hypothesis-python/tests/lark/__init__.py
- hypothesis-python/tests/lark/test_grammar.py
- hypothesis-python/tests/py2/test_validation.py
- hypothesis-python/tox.ini
- requirements/coverage.in
- requirements/coverage.txt
- requirements/tools.in
- requirements/tools.txt
Being an initial implementation of #170, based on the [Lark parser package](https://github.com/lark-parser/lark/).
> Create strategies for strings matching Lark (EBNF) context-free grammars

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/cover/test_deadline.py
- hypothesis-python/tests/cover/test_health_checks.py
> Deprecate and disable hung_test healthcheck

- .gitignore
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/pytestplugin.py
- hypothesis-python/src/hypothesis/searchstrategy/regex.py
- hypothesis-python/tests/cover/test_regex.py
- hypothesis-python/tests/nocover/test_regex.py
> Fix IGNORECASE bug in st.from_regex

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/tests/cover/test_direct_strategies.py
- hypothesis-python/tests/cover/test_float_nastiness.py
> Allow floats() to generate open intervals

- requirements/tools.txt
For some reason the existence of a new black version is breaking our build. This updates the black version rather than figuring out what that reason is.
> Update black version

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/cover/test_slippage.py
As discussed with @DRMacIver on #1781.
> Add setting to disable multi-bug reporting

- hypothesis-python/tests/cover/test_complex_numbers.py
- hypothesis-python/tests/nocover/test_strategy_state.py
Fixes #1884, and another flaky floats test I found, with tests extracted from #1781 for quicker merging.
> Flaky test fixes

- hypothesis-python/docs/strategies.rst
Hi,
this should add my hypothesis-networkx project to your documentation.
Cheers!
> Add hypothesis-networkx to strategies.rst

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/src/hypothesis/searchstrategy/types.py
- hypothesis-python/tests/cover/test_type_lookup.py
- hypothesis-python/tests/py3/test_lookup.py
This is mostly by @PJCampi (🎉), and closes #1911.
It's basically a tidied-up version of #1914, but there were some GitHub issues when I pushed a maintainer commit to the `master` branch of a fork and resetting it didn't fix things, so here we are.
> Support registered strategies for NewTypes in from_type (previously ignored)

- guides/strategies-that-shrink.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/stateful.py
> Use new sampled_from implementation in stateful rule choice

- guides/testing-hypothesis.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/changes.rst
- hypothesis-python/docs/numpy.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
> Continue with unbiased generation while TargetSelector is empty

- hypothesis-python/docs/database.rst
> Typo database.rst

- hypothesis-python/docs/reproducing.rst
with with -> with
Super cool project!
> typo reproducing.rst

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/changes.rst
- hypothesis-python/src/hypothesis/searchstrategy/types.py
> support slice in from_type

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/searchstrategy/types.py
> Fix rare bug in `from_type(range)`

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/src/hypothesis/strategies.py
- whole-repo-tests/test_type_hints.py
I'd vaguely wanted this to work for a while, but talking to @rsokl pushed me to work out how to test it... and here we are!
> Expose DataObject for type hints

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/compat.py
> Fix typing issue under Python 3.5.0

- azure-pipelines.yml
- hypothesis-python/tests/cover/test_regex.py
- hypothesis-python/tests/py3/test_asyncio.py
- hypothesis-python/tests/pytest/test_capture.py
- hypothesis-python/tox.ini
- tooling/src/hypothesistooling/__main__.py
> Test more new Pythons

- hypothesis-python/docs/strategies.rst
I'm not completely sure about grammar, tho
Resolves #2119
> Add `Schemathesis` to the "Projects extending Hypothesis" list.

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_strategies.py
- hypothesis-python/src/hypothesis/extra/lark.py
- hypothesis-python/src/hypothesis/searchstrategy/deferred.py
- hypothesis-python/src/hypothesis/searchstrategy/strategies.py
This is basically me cherry-picking a couple of random little cleanups that I've accreted over a weekend of poking at various issues.  The unifying factor is that they're *very small*.
> Four tiny cleanups

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py
- hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/tests/common/debug.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/cover/test_core.py
- hypothesis-python/tests/cover/test_slippage.py
- hypothesis-python/tests/cover/test_stateful.py
- hypothesis-python/tests/cover/test_statistical_events.py
- hypothesis-python/tests/cover/test_targeting.py
- hypothesis-python/tests/cover/test_verbosity.py
- hypothesis-python/tests/datetime/test_pytz_timezones.py
- hypothesis-python/tests/nocover/test_flatmap.py
- hypothesis-python/tests/numpy/test_gen_data.py
- hypothesis-python/tests/pytest/test_statistics.py
- hypothesis-python/tests/quality/test_discovery_ability.py
I've been thinking about ways to improve our test case generation recently, and as a result I wanted to find out how many of the current weird heuristics we have are remotely useful (I've suspected for a while that the answer is "not many").
So I started deleting code to see what it would do to our test suite and got... quite far. In the end our weird mutator algorithm *does* end up being more useful than pure random generation, but not that much more useful, and by biasing the random generation using an old algorithm for an earlier incarnation of Hypothesis we end up being able to more or less satisfy the test suite - there are a few minor regressions where things now take a bit longer to find things, and a few weird quirks, as you can see from the test diffs.
The reason for this patch …
> Clean up core test case generation logic

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/numpy.py
- hypothesis-python/src/hypothesis/searchstrategy/attrs.py
- hypothesis-python/tests/common/__init__.py
- hypothesis-python/tests/cover/test_conjecture_engine.py
- hypothesis-python/tests/cover/test_conjecture_float_encoding.py
- hypothesis-python/tests/cover/test_phases.py
- hypothesis-python/tests/nocover/test_regressions.py
- hypothesis-python/tests/nocover/test_simple_numbers.py
- hypothesis-python/tests/quality/test_integers.py
- hypothesis-python/tests/quality/test_poisoned_lists.py
- hypothesis-python/tests/quality/test_poisoned_trees.py
- hypothesis-python/tests/quality/test_zig_zagging.py
- requirements/tools.txt
This upgrades us to the (just released) new black. Mostly minor changes around use of brackets when unpacking.
> Upgrade to the latest black

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/numpy.py
- hypothesis-python/tests/numpy/test_gen_data.py
One part of the monster PR at #2153
> Broadcastable shapes health

- .travis.yml
- azure-pipelines.yml
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/numpy.py
- hypothesis-python/tests/cover/test_statistical_events.py
- hypothesis-python/tests/numpy/test_argument_validation.py
- hypothesis-python/tests/numpy/test_gen_data.py
Closes #1969 and replaces the mammoth #2153
> New strategy: mutually broadcastable shapes

- CODEOWNERS
- paper.md
Closes #2210 (thanks @djmitche!).  
Cross-ref openjournals/joss-reviews#1891.
> Clarify wording from JOSS paper review

- paper.md
Some minor wording tweaks to the JOSS paper.
> Improve wording of paper

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
In the past I've had some trouble navigating the control flow in `given` and `StateForActualGivenExecution`, so this time I wrote up some of my notes as comments.
Hopefully this will save others (and my future self) some confusion.
---
Most of the changes are comments and docstrings, but I also made a few small code changes to make things clearer in key places. There shouldn't be any functional changes.
---
All of these comments are based on my own reading of the code, so while I've tried to be accurate, mistakes are certainly possible.
> Describe and clarify some of the control flow in core.py

- paper.bib
sorry, should have caught these in the previous PR
> more bib fixes, in paper titles

- paper.bib
hopefully the last change needed for https://github.com/openjournals/joss-reviews/issues/1891
> fixing missing letter

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
This seems to have been left over from an earlier draft of #2137.
> Remove unused enum DataClassification

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
> Enforce BUFFER_SIZE

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/tests/cover/test_arbitrary_data.py
- hypothesis-python/tests/cover/test_core.py
- hypothesis-python/tests/cover/test_random_module.py
- hypothesis-python/tests/cover/test_runner_strategy.py
- hypothesis-python/tests/cover/test_validation.py
- hypothesis-python/tests/cover/test_verbosity.py
- hypothesis-python/tests/nocover/test_database_usage.py
- hypothesis-python/tests/nocover/test_deferred_errors.py
- hypothesis-python/tests/nocover/test_find.py
- hypothesis-python/tests/nocover/test_randomization.py
Closes #2236 
(#2235 needs to be merged first, but we're just waiting on a green build for that)
> Undeprecate find

- hypothesis-python/tests/quality/test_discovery_ability.py
This test has a hard-to-satisfy filter condition that has a small chance of triggering `HealthCheck.filter_too_much`, causing flaky failures if not suppressed.
Spotted in <https://dev.azure.com/HypothesisWorks/Hypothesis/_build/results?buildId=3118>.
> Suppress flaky health check in test_mixing_is_sometimes_distorted

- hypothesis-python/tests/cover/test_testdecorators.py
We would, very occasionally, see this test failing. That's because it was wrong - the heuristics for whether to continue trying to generate examples do allow us to try more than `MIN_TEST_CALLS` valid examples, and very occasionally that would result in us generating more examples than this test claims were allowed.
This fixes the test by making it clear that it only applies to single example mode (which was the only mode that existed when it was first written I think, and the adaptation to multiple examples was flawed).
> Fix flaky test in test_testdecorators.py

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/src/hypothesis/internal/conjecture/pareto.py
- hypothesis-python/tests/conjecture/test_engine.py
- hypothesis-python/tests/conjecture/test_pareto.py
This adds a *really* basic (it's just the shrinker with a fancy hat on) optimiser for the Pareto front, as a prelude to more advanced work.
> Optimise the pareto front

- guides/testing-hypothesis.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/conf.py
- hypothesis-python/docs/django.rst
- hypothesis-python/src/hypothesis/extra/django/_fields.py
- hypothesis-python/tests/cover/test_direct_strategies.py
- hypothesis-python/tests/nocover/test_regex.py
I just proposed that https://github.com/HypothesisWorks/hypothesis/pull/2282#issuecomment-569464683 would be the next PR we merge, but... while drafting the follow-up PR(s) I noticed a couple of small fixes that are not related to the big upgrade - including a flaky test.
If any @HypothesisWorks/hypothesis-python-contributors are available for a quick review, it would be much appreciated - and much easier than the other PRs :joy:
> Tiny cleanups before 5.0.x

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/cover/test_stateful.py
> Make MultipleResults an iterable

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies/_internal/types.py
- hypothesis-python/tests/cover/test_lookup.py
> Ensure generic set elems can be hashed

- hypothesis-python/docs/settings.rst
> Remove stray closing parenthesis (settings docs)

- hypothesis-python/docs/strategies.rst
> Complete "External Strategies" list

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/compat.py
> Fix typing issue in python 3.5.2

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/cover/test_stateful.py
Fixes #2341, after considerably more frustrated debugging than the diff might suggest :sweat_smile:
> Ensure stateful vars are defined before use

- hypothesis-python/docs/strategies.rst
Hi! we are building a package that generates GraphQL schemas and queries for schemas :) It is on alpha stage now, but can produce valid queries that already can find some issues in GraphQL-based apps
> Add hypothesis-graphql

- hypothesis-python/docs/usage.rst
Hi @Zac-HD :wave: finally that short chat at EuroScipy paid off :)
See https://github.com/poliastro/poliastro/pull/926.
> Add poliastro to list of projects using Hypothesis

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/tests/cover/test_explicit_examples.py
Fixes #2125, which turned out to be a lot easier than I expected :smile:
> Fix assume-example-parametrize interaction

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/internal/compat.py
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/src/hypothesis/statistics.py
- hypothesis-python/tests/conftest.py
- hypothesis-python/tests/conjecture/test_engine.py
Closes #2340 by adding the shrink-phase timeout logic discussed on that issue.
> Cap wall-time duration of shrink phase

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies/_internal/core.py
- hypothesis-python/tests/cover/test_cache_implementation.py
Resolves #2433 
Based on the discussion there. This approach implements a per-thread cache instance, rather than a single cache instance with storage inside.
Posting it for initial review, will a test & notes later. @Zac-HD @DRMacIver please take a look
> Implement thread-local strategy cache

- CONTRIBUTING.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/compat.py
- hypothesis-python/src/hypothesis/strategies/_internal/core.py
- hypothesis-python/tests/cover/test_functions.py
@Zac-HD I got started on making the changes. Just wanted to check, if I am making the code changes in the right direction. 
Disclaimer - A few test cases are failing. I will fix them.
(edit for magic comment: resolves #2425)
> WIP: Smarter return type for st.functions()

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/tests/cover/test_explicit_examples.py
> Improve explicit example reporting

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_settings.py
Extracted from #2467, because it really is an unrelated change.
> Improve `derandomize` docs

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py
- hypothesis-python/tests/conjecture/test_engine.py
- hypothesis-python/tests/conjecture/test_junkdrawer.py
> We could potentially do something with fiddling around with getting and setting the recursion limit but that sounds a bit yikes.
...yep.  Fixes #2494 though, so here we are :sweat_smile:
> De-flake RecursionErrors

- hypothesis-python/tests/cover/test_ghostwriter.py
> Deflake ghostwriter test

- hypothesis-python/tests/django/manage.py
- hypothesis-python/tests/django/toys/urls.py
Fixes #2531 
Also contains an unrelated weird change that suppresses a deprecation warning in our manage script - no idea what's up with that and why it's failing on my local install and not on CI, but the suppression is harmless on CI I think so I decided to leave it in.
> Fix Django build

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/changes.rst
- hypothesis-python/docs/extras.rst
- hypothesis-python/docs/ghostwriter.rst
- hypothesis-python/docs/index.rst
- hypothesis-python/setup.py
- hypothesis-python/src/hypothesis/extra/cli.py
- hypothesis-python/src/hypothesis/extra/ghostwriter.py
- hypothesis-python/tests/ghostwriter/recorded/base64_magic.txt
- hypothesis-python/tests/ghostwriter/recorded/eval_equivalent.txt
- hypothesis-python/tests/ghostwriter/recorded/sorted_idempotent.txt
- hypothesis-python/tests/ghostwriter/recorded/sorted_self_equivalent.txt
- hypothesis-python/tests/ghostwriter/recorded/timsort_idempotent.txt
- hypothesis-python/tests/ghostwriter/test_expected_output.py
- hypothesis-python/tests/ghostwriter/test_ghostwriter.py
- hypothesis-python/tests/ghostwriter/test_ghostwriter_cli.py
Black magic for the benefit of new users, or anyone else unsure of where to start.  Closes #2118.
*If you want to try this out before release, you can `pip install -U "hypothesis[cli] @ git+https://github.com/Zac-HD/hypothesis.git@ghostwriter#subdirectory=hypothesis-python"` to get `hypothesis write` early:*
```shell
$ hypothesis write re.compile --except re.error
```
```python
import re
from hypothesis import given, reject, strategies as st
@given(pattern=st.nothing(), flags=st.just(0))
def test_fuzz_compile(pattern, flags):
try:
re.compile(pattern=pattern, flags=flags)
except re.error:
reject()
```
<details>
<summary><code>hypothesis write gzip</code></summary>
Inferring the roundtrips for https://docs.python.org/3/library/gzip.html and fuzzing the rest.
```python
import gzip
from …
```
> Ghostwriter: writes tests for you

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies/_internal/core.py
- hypothesis-python/src/hypothesis/strategies/_internal/types.py
- hypothesis-python/tests/common/utils.py
- hypothesis-python/tests/cover/test_lookup.py
- hypothesis-python/tests/cover/test_type_lookup.py
I have added a few tests to illustrate the it works correctly.
But, I guess I didn't add all the required tests. So, let's think about what else is needed! 🤔 
Closes #2537 and closes #2544.
> Adds origin handling

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/numpy.py
- hypothesis-python/tests/numpy/test_gen_data.py
> ensure array from arrays() owns its memory

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/tests/cover/test_falsifying_example_output.py
> More verbose message for failures from @example marked tests

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/cli.py
- hypothesis-python/src/hypothesis/extra/ghostwriter.py
> Makes black optional during the import time

- hypothesis-python/docs/community.rst
- hypothesis-python/docs/details.rst
- hypothesis-python/docs/django.rst
- hypothesis-python/docs/examples.rst
- hypothesis-python/docs/quickstart.rst
- hypothesis-python/docs/settings.rst
- notebooks/Designing a better simplifier.ipynb
Bundle of four sets of trivial corrections to documentation.
> Copy edits to documentation

- CONTRIBUTING.rst
Updated the instructions in CONTRIBUTING.rst on adding name to author list that was missed
> updated author reference in contributing.rst

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/compat.py
- hypothesis-python/tests/cover/test_lookup.py
- hypothesis-python/tests/cover/test_lookup_py36.py
Closes #2603 
@Zac-HD I have followed your idea. It seems to be the easiest way. Hacky, but working! 👍
> Fixes how annotations are fetched from annotated types

- AUTHORS.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/control.py
- hypothesis-python/tests/cover/test_targeting.py
Fixes #2562 (done as part of PyConAu 2020 sprints!)
> target() now works with integers in addition to floats

- azure-pipelines.yml
- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/strategies.rst
- hypothesis-python/examples/example_hypothesis_entrypoint/example_hypothesis_entrypoint.py
- hypothesis-python/examples/example_hypothesis_entrypoint/setup.py
- hypothesis-python/examples/example_hypothesis_entrypoint/test_entrypoint.py
- hypothesis-python/src/hypothesis/entry_points.py
- hypothesis-python/tox.ini
Fixes #2564, where apparently all my tests only covered import-time side effects :grimacing: 
Also fixes #2571 by trying various ways to get entry points from most to least performant.
> Fix callable entry points

- AUTHORS.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/provisional.py
- hypothesis-python/tests/cover/test_provisional_strategies.py
> provisional.urls strategy fix

- guides/review.rst
> Code Review Handbook: Missing "if"

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/django/_fields.py
- hypothesis-python/tests/django/toystore/forms.py
- hypothesis-python/tests/django/toystore/test_given_forms.py
Follow-up to #1743 which closes #1116.
> Use Django field validators to infer more precise strategies

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies/_internal/datetime.py
- hypothesis-python/tests/cover/test_datetimes.py
- pytest.ini
> Naive datetimes are never imaginary

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/tests/cover/test_verbosity.py
> Fix indexing bug with explicit `@example` and `verbosity=quiet`

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies/_internal/collections.py
- hypothesis-python/src/hypothesis/strategies/_internal/core.py
- hypothesis-python/src/hypothesis/strategies/_internal/misc.py
- hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
- hypothesis-python/tests/cover/test_fuzz_one_input.py
- hypothesis-python/tests/cover/test_sampled_from.py
Closes #2036.  It's a little fiddly but there's nothing fundamentally strange here :slightly_smiling_face:
> Special-case `sampled_from(...).filter(...).map(...)` in unique collections

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies/_internal/core.py
- hypothesis-python/tests/cover/test_lookup.py
- hypothesis-python/tests/nocover/test_build_signature.py
> Distinguish `from_type()` from `builds()` by inferring strategies for parameters with default values

- .github/workflows/main.yml
Interest points:
- I found out that I am not familiar with how Windows works
- The commit is not signed (if that's important), because I was testing out #2735 I verify that it is still me 🙂 
Closes #2729
> Initial cache implementation

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/strategies.rst
- hypothesis-python/src/hypothesis/__init__.py
- hypothesis-python/src/hypothesis/control.py
- hypothesis-python/tests/cover/test_control.py
Fixes #2581, taking the approach that @PiDelport suggested in #2675.
> Add `currently_in_test_context()` to check if you can call `assume()`, `target()`, etc.

- .github/workflows/main.yml
- hypothesis-python/tox.ini
- tooling/src/hypothesistooling/__main__.py
> Test PyPy 3.7 in CI

- conjecture-rust/src/data.rs
- conjecture-rust/src/database.rs
- conjecture-rust/src/distributions.rs
- conjecture-rust/src/engine.rs
I'm about to make a modification to `conjecture-rust` and there are currently lots of linter errors. This doesn't fix all of them, but is a start.
> Fix some clippy errors.

- CONTRIBUTING.rst
> Fix link rendering in CONTRIBUTING.rst

- .gitignore
- build.sh
- guides/documentation.rst
- guides/review.rst
- hypothesis-python/docs/conf.py
- hypothesis-python/docs/details.rst
- hypothesis-python/docs/strategies.rst
- requirements/tools.in
- requirements/tools.txt
- tooling/src/hypothesistooling/__main__.py
Closes #2719, or it will once https://www.githubstatus.com/incidents/tf9v5jjmq2lg is resolved and Actions runs.
> Update release guide and document our thread-safety policy 

- hypothesis-python/docs/data.rst
- hypothesis-python/docs/details.rst
- hypothesis-python/docs/reproducing.rst
- hypothesis-python/docs/settings.rst
- requirements/coverage.txt
- requirements/test.txt
- requirements/tools.txt
Automatically update pinned dependencies
> Update pinned dependencies

- .github/workflows/main.yml
It was recently released as a native feature: https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
And Hypothesis was the first project I thought of! 😃
> Removes skip check from CI

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/cover/test_stateful.py
> Check multiple preconditions

- build.sh
- tooling/src/hypothesistooling/__main__.py
It is time to update the tooling with new security releases 🔐
> Updates Python versions to newer ones

- .github/workflows/main.yml
- hypothesis-python/scripts/basic-test.sh
- hypothesis-python/tests/cover/test_annotations.py
- hypothesis-python/tests/cover/test_lookup.py
- hypothesis-python/tests/cover/test_lookup_py38.py
- hypothesis-python/tests/cover/test_pretty.py
- hypothesis-python/tests/cover/test_randoms.py
- hypothesis-python/tox.ini
- tooling/src/hypothesistooling/__main__.py
Follow-up for #2767, on the basis that we should probably just work around https://bugs.python.org/issue43006 since it hasn't been fixed in alpha5 or alpha6.
> Test with CPython 3.10-dev

- AUTHORS.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/src/hypothesis/core.py
- whole-repo-tests/test_type_hints.py
> Fix missing type annotation for settings.__call__

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies/_internal/core.py
- hypothesis-python/tests/cover/test_sampled_from.py
Closes #2923.  @HypothesisWorks/hypothesis-python-contributors for a quick review?
(plus a small documentation update following #2915)
> Improve error message for certain empty enums

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies/_internal/core.py
- hypothesis-python/tests/cover/test_lookup.py
> New error message for `builds(Optional[x])` suggesting `from_type()`

- hypothesis-python/RELEASE.rst
- hypothesis-python/setup.py
- hypothesis-python/src/hypothesis/entry_points.py
> Use new importlib API

- AUTHORS.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/provisional.py
- hypothesis-python/tests/cover/test_provisional_strategies.py
All tests under `hypothesis-python/tests/cover/test_provisional_strategies.py` currently pass.
Still thinking about allowing non-encoded "/" and "?" for fragments.
Fixes https://github.com/HypothesisWorks/hypothesis/issues/2908
> Generate URL fragments

- hypothesis-python/tests/quality/test_discovery_ability.py
Tests in `quality/test_discovery_ability.py` currently perform all `RUNS = 100` attempts before reporting failure, even if the number of successes so far is so low that we can't possibly hit the probability target.
This PR makes the loop stop early and report failure as soon as success becomes 100% impossible.
> Make example-discovery tests give up early if they can't hit their target

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies/_internal/types.py
> Changes how we treat newtypes

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies/_internal/attrs.py
- hypothesis-python/tests/ghostwriter/test_expected_output.py
- hypothesis-python/tests/ghostwriter/test_ghostwriter.py
> Fix attrs+ghostwriter bug

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/reflection.py
- hypothesis-python/src/hypothesis/strategies/_internal/types.py
- hypothesis-python/tests/cover/test_lookup_py37.py
- hypothesis-python/tests/cover/test_type_lookup.py
Fixes #2951.  @mristin, I'd really appreciate your review - this seems to fix the problem in your issue, but if you have more complex examples it would be great to check those too.
> Improve `try_issubclass`

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/details.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/extra/array_api.py
- hypothesis-python/src/hypothesis/extra/pandas/impl.py
- hypothesis-python/src/hypothesis/internal/compat.py
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/src/hypothesis/internal/healthcheck.py
- hypothesis-python/src/hypothesis/internal/reflection.py
- hypothesis-python/src/hypothesis/internal/validation.py
- hypothesis-python/src/hypothesis/strategies/_internal/collections.py
- hypothesis-python/src/hypothesis/strategies/_internal/core.py
- hypothesis-python/tests/common/utils.py
- hypothesis-python/tests/cover/test_annotations.py
- hypothesis-python/tests/cover/test_lambda_formatting.py
- hypothesis-python/tests/cover/test_lookup.py
- hypothesis-python/tests/cover/test_lookup_py38.py
- hypothesis-python/tests/cover/test_reflection.py
- hypothesis-python/tests/cover/test_seed_printing.py
- hypothesis-python/tests/ghostwriter/recorded/hypothesis_module_magic.txt
- hypothesis-python/tests/numpy/test_gufunc.py
- hypothesis-python/tests/pytest/test_capture.py
- tooling/setup.py
- tooling/src/hypothesistooling/projects/hypothesispython.py
Following #3088, this PR fixes #2495 and fixes #3029.
> Improved handling of required args via `inspect.signature()`

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/details.rst
- hypothesis-python/src/hypothesis/control.py
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
Fixes #3147.
> Update note description

- .github/workflows/main.yml
- hypothesis-python/tests/common/setup.py
- hypothesis-python/tox.ini
- tooling/src/hypothesistooling/__main__.py
> Add CI jobs - Pyjion JIT, new Pandas

- .github/workflows/main.yml
- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/supported.rst
- hypothesis-python/setup.py
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/src/hypothesis/extra/django/_fields.py
- hypothesis-python/src/hypothesis/strategies/_internal/types.py
- hypothesis-python/tests/common/setup.py
- hypothesis-python/tests/conftest.py
- hypothesis-python/tests/django/manage.py
- hypothesis-python/tests/django/toys/urls.py
- hypothesis-python/tox.ini
- requirements/coverage.in
- requirements/coverage.txt
- tooling/src/hypothesistooling/__main__.py
Being various fixes to our CI, and consequently also to Django 4.0 timezone handling (closes #3187).
Also cherry-picks and therefore fixes #3183, with thanks to @tserg 😍
> Misc CI updates

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/cover/test_stateful.py
> Fix stateful _print_step for invariants

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
> Representative examples

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/cache.py
- hypothesis-python/tests/cover/test_cache_implementation.py
> Fix LR-reused cache bug

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/cover/test_stateful.py
> Fix single-return stateful printing

- hypothesis-python/docs/details.rst
Code did not match text and expected output of code
> Fix typo in assume example

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies/_internal/numbers.py
Closes #3092.  I'd like to be able to just handle all such cases, but this is one of those awful messes where kicking a clear explanation back to the user is the best we can do.
> Error if denormals-are-zero

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies/_internal/core.py
- hypothesis-python/src/hypothesis/strategies/_internal/numbers.py
- hypothesis-python/tests/cover/test_lookup.py
- hypothesis-python/tests/cover/test_numerics.py
> Clarify `floats()` and `builds()` error messages

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/changes.rst
- hypothesis-python/docs/settings.rst
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/conjecture/test_engine.py
- hypothesis-python/tests/cover/test_slippage.py
> Shrinking disabled -> early stopping

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/extra/cli.py
- hypothesis-python/src/hypothesis/extra/ghostwriter.py
- hypothesis-python/tests/cover/test_explicit_examples.py
- hypothesis-python/tests/cover/test_given_error_conditions.py
Closes #3266, closes #3268, closes #3269.
> Quality-of-life ghostwriter patches

- .github/workflows/main.yml
- AUTHORS.rst
- CONTRIBUTING.rst
- guides/testing-hypothesis.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/_hypothesis_pytestplugin.py
- hypothesis-python/tests/pytest/test_junit.py
- hypothesis-python/tox.ini
- tooling/src/hypothesistooling/__main__.py
Entirely thanks to @brandon-leapyear, new PR so that I can include some final config commits before merging.  Closes #3277.
> Fix `junit-xml` support

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies/_internal/core.py
> Error out on unhandlable psudeo-generics from Pydantic

- AUTHORS.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/ghostwriter.py
- hypothesis-python/tests/ghostwriter/test_ghostwriter.py
Fixes https://github.com/HypothesisWorks/hypothesis/issues/3316
> Revise Hypothesis Ghostwriter to include nested imports in python classes

- AUTHORS.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/tests/cover/test_explicit_examples.py
first ever commit for open source
Fixes #3319.
> Hypothesis 3319

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/extra/django/_fields.py
- hypothesis-python/src/hypothesis/extra/ghostwriter.py
- hypothesis-python/src/hypothesis/internal/charmap.py
- hypothesis-python/src/hypothesis/internal/compat.py
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/reflection.py
- hypothesis-python/src/hypothesis/strategies/_internal/core.py
- hypothesis-python/tests/cover/test_reflection.py
- hypothesis-python/tests/ghostwriter/recorded/magic_builtins.txt
Closes #3317, following https://github.com/python/cpython/pull/92065.
Plus a few tiny internal cleanups, deleting unused attributes and fixing type comments.
> Check for keywords in param names

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/ghostwriter.py
- hypothesis-python/src/hypothesis/extra/numpy.py
- hypothesis-python/tests/ghostwriter/recorded/magic_gufunc.txt
- hypothesis-python/tests/numpy/test_from_dtype.py
Plus some related fixes for ghostwriting Numpy tests.
> Fix `from_dtype(np.dtype("g"))`, float128

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/src/hypothesis/strategies/_internal/collections.py
- hypothesis-python/src/hypothesis/strategies/_internal/core.py
- hypothesis-python/src/hypothesis/strategies/_internal/misc.py
- hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
- whole-repo-tests/test_mypy.py
- whole-repo-tests/test_pyright.py
Closes #3348 
Also closes #3347 by cherry-picking.
> Improve annotations for pyright users

- hypothesis-python/docs/details.rst
> Fix bullet-point typo

- hypothesis-python/RELEASE.rst
- hypothesis-python/setup.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/common/utils.py
- hypothesis-python/tests/cover/test_control.py
- hypothesis-python/tests/cover/test_health_checks.py
- hypothesis-python/tests/nocover/test_interesting_origin.py
- hypothesis-python/tests/nocover/test_targeting.py
Closes #3367 and closes #3374.
> Fix pipenv install issue and sometimes-too-short draw time healthcheck

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies/_internal/types.py
🤞 compatibility fix after https://github.com/python/cpython/pull/93754
> Support 3.11 GenericAlias again

- HypothesisWorks.github.io/_posts/2016-08-09-hypothesis-pytest-fixtures.md
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/internal/reflection.py
- hypothesis-python/tests/common/utils.py
- hypothesis-python/tests/cover/test_annotations.py
- hypothesis-python/tests/cover/test_falsifying_example_output.py
- hypothesis-python/tests/cover/test_lookup.py
- hypothesis-python/tests/cover/test_lookup_py38.py
- hypothesis-python/tests/cover/test_unicode_identifiers.py
- hypothesis-python/tests/django/toystore/test_given_models.py
> Fix `@example()`/`@given()` argument-handling inconsistencies

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/internal/reflection.py
- hypothesis-python/tests/cover/test_lookup_py38.py
> Better `@example()` argument validation

- hypothesis-python/RELEASE.rst
- hypothesis-python/scripts/basic-test.sh
- hypothesis-python/src/hypothesis/internal/conjecture/utils.py
- hypothesis-python/src/hypothesis/strategies/_internal/numbers.py
- hypothesis-python/tests/array_api/test_arrays.py
- hypothesis-python/tests/cover/test_filtered_strategy.py
- hypothesis-python/tests/quality/test_integers.py
> Generate integer bounds more often

- AUTHORS.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/cli.py
- hypothesis-python/tests/ghostwriter/test_ghostwriter.py
> Better error messages on ghostwriter filename

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/errors.py
- hypothesis-python/src/hypothesis/internal/healthcheck.py
- hypothesis-python/tests/conjecture/test_engine.py
- hypothesis-python/tests/cover/test_health_checks.py
- hypothesis-python/tests/cover/test_regressions.py
> Fix pickle errors for exceptions

- hypothesis-python/tests/cover/test_lookup_py38.py
> Test from_type() resolution and error message for non-runtime-checkable Protocols

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/ghostwriter.py
- hypothesis-python/src/hypothesis/internal/reflection.py
- hypothesis-python/tests/ghostwriter/test_ghostwriter.py
This fixes `hypothesis write mygrad.matmul`, cc @rsokl.
Also fixes #3438, or at least works around it in all the cases I saw 🤷‍♂️
> Improve ghostwritten locations

- build.sh
- hypothesis-python/.coveragerc
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/extra/codemods.py
- hypothesis-python/tests/pytest/test_skipping.py
- requirements/tools.txt
- tooling/src/hypothesistooling/__main__.py
> Consistent skipping from explicit examples

- hypothesis-python/.coveragerc
- hypothesis-python/RELEASE.rst
- hypothesis-python/setup.py
- hypothesis-python/src/_hypothesis_ftz_detector.py
- hypothesis-python/src/hypothesis/strategies/_internal/numbers.py
Closes #3458 the *complete overkill* way, because once I got started each incremental part wasn't *that* hard to add... and if you're trying to understand what's going on here I'd like to help as much as possible.
cc @catherio FYI.
> Identify FTZ-causing library

- hypothesis-python/docs/usage.rst
Added Ivy ML framework to projects using Hypothesis
> Add Ivy to open source projects using Hypothesis

- hypothesis-python/docs/usage.rst
Added array-api-tests to projects using Hypothesis
> Update open source projects using Hypothesis

- AUTHORS.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/examples/test_basic.py
Add a basic usage example to enable easy onboarding.
See discussion on #3544.
> Add a basic Python example (fixes #3544)

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/data.rst
- hypothesis-python/src/hypothesis/control.py
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/internal/scrutineer.py
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/src/hypothesis/strategies/_internal/core.py
- hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
- hypothesis-python/src/hypothesis/vendor/pretty.py
- hypothesis-python/tests/cover/test_custom_reprs.py
- hypothesis-python/tests/cover/test_pretty.py
- hypothesis-python/tests/quality/test_discovery_ability.py
- hypothesis-python/tests/quality/test_normalization.py
Fixes #3529.  
This is also a big chunk of the pretty-printing groundwork for #3411, which should be coming along in the next week or so...
> Represent objects by the call that made them

- AUTHORS.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/numpy.py
Thanks for maintaining this great project! This is a trivial patch to fix some docstring.
> Fix the docstring of hypothesis.extra.numpy.arrays

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/vendor/pretty.py
- hypothesis-python/tests/cover/test_slippage.py
- hypothesis-python/tests/numpy/test_gen_data.py
> Fix pprint recursion error

- AUTHORS.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/ghostwriter.py
- hypothesis-python/tests/ghostwriter/test_ghostwriter.py
> Add handling for from_regex and test for change

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/settings.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/tests/cover/test_database_backend.py
- requirements/coverage.txt
- requirements/test.txt
- requirements/tools.txt
https://github.com/HypothesisWorks/hypothesis/pull/3555 is too big, so I'm pulling out parts which can be merged separately.
> Separable parts of Inquisitor

- AUTHORS.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/control.py
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/internal/compat.py
- hypothesis-python/src/hypothesis/provisional.py
- hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
- hypothesis-python/tests/array_api/test_arrays.py
- hypothesis-python/tests/common/debug.py
- hypothesis-python/tests/common/utils.py
- hypothesis-python/tests/cover/test_pretty.py
- hypothesis-python/tests/cover/test_randoms.py
- hypothesis-python/tests/django/toys/settings.py
- hypothesis-python/tests/django/toystore/test_given_models.py
- hypothesis-python/tests/ghostwriter/test_ghostwriter.py
- hypothesis-python/tests/nocover/test_regex.py
- requirements/coverage.txt
- requirements/tools.txt
Mostly extracted from #3555, to make that as small and simple as possible.
> Internal refactorings

- .github/workflows/fuzz.yml
- requirements/fuzzing.in
- requirements/fuzzing.txt
- requirements/test.in
- requirements/test.txt
- requirements/tools.txt
Because we should really be dogfooding https://github.com/Zac-HD/hypofuzz/issues/14 and [`GitHubArtifactDatabase`](https://hypothesis.readthedocs.io/en/latest/database.html#hypothesis.database.GitHubArtifactDatabase) 😁 
Once we've seen this running for a few weeks, we can look at how to pull the results into the rest of our workflow - there are going to be a bunch of ergonomics challenges around how to get sharding working nicely, and probably also performance issues when downloading artifacts induces latency before the first test function starts running.  Those are problems for _after_ it's running, though.
> Set up fuzzing cronjob

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies/_internal/regex.py
- hypothesis-python/tests/nocover/test_regex.py
Adding support for Python 3.11 new regex as described here: https://docs.python.org/3/whatsnew/3.11.html#re
solve part of #3684
> Adding support for Python 3.11 new regex

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/vendor/pretty.py
- hypothesis-python/tests/cover/test_pretty.py
Via https://github.com/HypothesisWorks/hypothesis/pull/3710#discussion_r1285467133, with thanks to @jobh
> pprint empty flag combinations

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/_hypothesis_pytestplugin.py
- hypothesis-python/tests/pytest/test_parametrized_db_keys.py
Fixes https://github.com/HypothesisWorks/hypothesis/issues/3733
> Fix parametrize false-alarm healthchecks

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/src/hypothesis/statistics.py
- hypothesis-python/tests/cover/test_phases.py
- hypothesis-python/tests/cover/test_settings.py
- hypothesis-python/tests/cover/test_statistical_events.py
We've been dogfooding this for six months and it's been great so far, so let's share it with the world 💖
> Enable the `explain` phase by default

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies/_internal/core.py
- hypothesis-python/tests/cover/test_composite.py
Closes https://github.com/HypothesisWorks/hypothesis/issues/3786.
> Warn about composite annotation

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/nocover/test_stateful.py
Via email follow-up to https://groups.google.com/g/hypothesis-users/c/Jj9YE2_hVr0/m/9FGxvgDmAAAJ and https://hypothesis.readthedocs.io/en/latest/changes.html#v6-90-0
> Grab stateful settings off our TestCase class

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/utils.py
- hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
- hypothesis-python/tests/common/strategies.py
- hypothesis-python/tests/conjecture/common.py
- hypothesis-python/tests/conjecture/test_forced.py
- hypothesis-python/tests/cover/test_intervalset.py
- hypothesis-python/tests/nocover/test_sampled_from.py
In preparation for #3818, but includes some bug fixes as well.
I've moved the strategies for `test_forced` to `common` in preparation for their use in testing the ir ([see work in progress usage here](https://github.com/HypothesisWorks/hypothesis/blob/1b6c46aa46984c6db955cff2375475451ecb9753/hypothesis-python/tests/conjecture/test_ir.py)). Simultaneously, I've improved the coverage of these strategies, which resulted in discovering a few bugs w.r.t `forced` that this pull also fixes.
> Improvements to `forced` and forced testing

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies/_internal/utils.py
- hypothesis-python/tests/cover/test_searchstrategy.py
fix #3880 
I added a simple test to ensure it's working. I haven't done performance testing but am happy to if this is in a critical path.
> Allow dataclasses etc to have custom json formats

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/ghostwriter.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/ghostwriter/recorded/hypothesis_module_magic.txt
- hypothesis-python/tests/ghostwriter/test_ghostwriter.py
- hypothesis-python/tests/ghostwriter/test_ghostwriter_cli.py
Fixes https://github.com/HypothesisWorks/hypothesis/issues/3884.
> Improve import-detection logic in the Ghostwriter

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/schema_observations.json
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/observability.py
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/cover/test_observability.py
- hypothesis-python/tests/cover/test_stateful.py
Another part of https://github.com/HypothesisWorks/hypothesis/issues/3845.
> Observability for stateful testing: better representation and timing info

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/strategies.rst
- hypothesis-python/src/hypothesis/extra/pandas/impl.py
- hypothesis-python/tests/cover/test_database_backend.py
- hypothesis-python/tests/cover/test_filestorage.py
- hypothesis-python/tests/cover/test_settings.py
- hypothesis-python/tests/pytest/test_pytest_detection.py
- hypothesis-python/tests/pytest/test_seeding.py
- pytest.ini
- whole-repo-tests/test_mypy.py
- whole-repo-tests/test_pyright.py
- whole-repo-tests/test_release_management.py
Closes https://github.com/HypothesisWorks/hypothesis/issues/3904.
> Add type annotations

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/tests/nocover/test_regressions.py
> Fix flaky error on unique collections containing nan

- AUTHORS.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/compat.py
- hypothesis-python/src/hypothesis/internal/entropy.py
> Do not warn about possibly unreferenced RNGs on free-threaded CPython

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/datatree.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/tests/conjecture/test_data_tree.py
- hypothesis-python/tests/conjecture/test_engine.py
- hypothesis-python/tests/cover/test_simple_collections.py
split some of the easier changes from #3962.
> Shrinker-adjacent improvements

- AUTHORS.rst
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/django/_fields.py
- hypothesis-python/tests/django/toystore/forms.py
- hypothesis-python/tests/django/toystore/test_given_forms.py
- hypothesis-python/tox.ini
> Add strategies for Django's model choice fields

- .github/workflows/main.yml
- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/database.py
- hypothesis-python/src/hypothesis/internal/entropy.py
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/cover/test_stateful.py
Fixes #4003
Adds coverage or better-considered coverage exclusions for the earlier FIXMEs.
In the process, one unrelated flake is addressed; plus pyodide CI execution is parallelized.
> Full coverage

- hypothesis-python/RELEASE.rst
- hypothesis-python/tests/django/toystore/test_given_models.py
> Fix flaky django generated field test

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/ghostwriter.py
- hypothesis-python/src/hypothesis/extra/numpy.py
- hypothesis-python/src/hypothesis/vendor/pretty.py
- hypothesis-python/tests/ghostwriter/recorded/magic_class.txt
- hypothesis-python/tests/ghostwriter/recorded/magic_numpy.txt
- hypothesis-python/tests/ghostwriter/recorded/nothing_found.txt
- hypothesis-python/tests/ghostwriter/test_expected_output.py
- hypothesis-python/tests/numpy/test_from_type.py
Fixes https://github.com/HypothesisWorks/hypothesis/issues/4038.
> Improve `from_type()` and Ghostwriter on numpy dtypes

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/src/hypothesis/control.py
- hypothesis-python/src/hypothesis/extra/codemods.py
- hypothesis-python/src/hypothesis/vendor/pretty.py
- hypothesis-python/tests/codemods/test_codemods.py
- hypothesis-python/tests/cover/test_pretty.py
Closes https://github.com/HypothesisWorks/hypothesis/issues/4037 and closes https://github.com/HypothesisWorks/hypothesis/issues/4030.
> `pprint` valid syntax more often

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/internal/intervalsets.py
- hypothesis-python/src/hypothesis/strategies/_internal/core.py
- hypothesis-python/src/hypothesis/strategies/_internal/strings.py
- hypothesis-python/tests/cover/test_filter_rewriting.py
- hypothesis-python/tests/cover/test_regex.py
Closes https://github.com/HypothesisWorks/hypothesis/issues/4008.
> `st.from_regex()` alphabet improvements and `text().filter(re.compile(...).match)` bugfix

- .github/workflows/main.yml
- hypothesis-python/RELEASE.rst
- hypothesis-python/setup.py
- hypothesis-python/src/hypothesis/control.py
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/tests/cover/test_type_lookup.py
- hypothesis-python/tests/nocover/test_collective_minimization.py
- hypothesis-python/tests/nocover/test_conjecture_engine.py
- tooling/src/hypothesistooling/__main__.py
More work towards #3914, extracted from #4034.  
Closes #4044, with thanks to @tybug for working out the problems there.
> More crosshair compatibility

- hypothesis-python/RELEASE.rst
- hypothesis-python/setup.py
- hypothesis-python/src/_hypothesis_pytestplugin.py
- hypothesis-python/src/hypothesis/reporting.py
- hypothesis-python/tests/common/debug.py
- hypothesis-python/tests/common/setup.py
- hypothesis-python/tests/cover/test_randoms.py
- hypothesis-python/tests/cover/test_regex.py
- hypothesis-python/tests/cover/test_reporting.py
- hypothesis-python/tests/cover/test_sampled_from.py
- hypothesis-python/tests/cover/test_seed_printing.py
- hypothesis-python/tests/cover/test_slippage.py
- hypothesis-python/tests/nocover/test_interesting_origin.py
- hypothesis-python/tests/nocover/test_strategy_state.py
- hypothesis-python/tests/numpy/test_gen_data.py
Extracted from #4034 again, since it continues to expose me to code I haven't looked at in quite some time, and I both want to make that PR easier to work with (ie smaller) and get the independently-useful parts on master sooner.
> Various small cleanups to reporting, test settings, and a few flakes

- hypothesis-python/RELEASE.rst
- hypothesis-python/setup.py
- hypothesis-python/src/hypothesis/vendor/pretty.py
- hypothesis-python/tests/cover/test_cache_implementation.py
- hypothesis-python/tests/cover/test_explicit_examples.py
- hypothesis-python/tests/cover/test_float_nastiness.py
- hypothesis-python/tests/cover/test_health_checks.py
- hypothesis-python/tests/cover/test_pretty.py
- hypothesis-python/tests/nocover/test_recursive.py
> Improve numeric pprinting

- CONTRIBUTING.rst
`virtualenv` is very outdated :)
> Use `python3 -m venv` instead of `virtualenv` in `CONTRIBUTING.rst`

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies/_internal/core.py
- hypothesis-python/src/hypothesis/strategies/_internal/types.py
- hypothesis-python/tests/typing_extensions/test_backported_types.py
Let's see how it goes 🚄 
Closes https://github.com/HypothesisWorks/hypothesis/issues/4071
> Allow `Annotated` and `ReadOnly` types for `TypedDict` keys

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies/_internal/core.py
- hypothesis-python/src/hypothesis/strategies/_internal/types.py
- hypothesis-python/tests/typing_extensions/test_backported_types.py
Closes https://github.com/HypothesisWorks/hypothesis/issues/4074
> Support `LiteralString`

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies/_internal/types.py
- hypothesis-python/tests/nocover/test_type_lookup.py
- hypothesis-python/tests/typing_extensions/test_backported_types.py
> Include `TypeIs` to `TypeGuardTypes`

- hypothesis-python/RELEASE.rst
- hypothesis-python/setup.py
- hypothesis-python/src/hypothesis/strategies/_internal/types.py
- hypothesis-python/tests/cover/test_deadline.py
- hypothesis-python/tests/cover/test_type_lookup.py
- hypothesis-python/tests/typing_extensions/test_backported_types.py
I always have so much fun contributing to hypothesis 😊 
Because it combines two my fav things: typing and testing! 
Closes https://github.com/HypothesisWorks/hypothesis/issues/4080
> Support TypeVar defaults and `typing_extensions.TypeVar`

- .github/workflows/main.yml
- build.sh
- hypothesis-python/setup.py
- hypothesis-python/tests/cover/test_regex.py
- hypothesis-python/tests/nocover/test_complex_numbers.py
- hypothesis-python/tests/nocover/test_database_usage.py
- hypothesis-python/tests/numpy/__init__.py
- hypothesis-python/tests/numpy/test_from_dtype.py
- requirements/coverage.in
- requirements/coverage.txt
- requirements/fuzzing.txt
- requirements/test.in
- requirements/test.txt
- requirements/tools.txt
- tooling/src/hypothesistooling/__main__.py
Closes #4100, cherry-picks from #4034.
> Update dependencies + test cleanups

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/provisional.py
> Don't generate port 0 in urls strategy

- hypothesis-python/tests/conjecture/test_optimiser.py
https://github.com/HypothesisWorks/hypothesis/pull/4163#issuecomment-2466606458
> More explicit `Optimiser` coverage

- hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py
- hypothesis-python/tests/conjecture/test_junkdrawer.py
- hypothesis-python/tests/cover/test_float_utils.py
As seen in [this CI job](https://github.com/HypothesisWorks/hypothesis/actions/runs/12457398494/job/34771911765). 
Since the release CI failed, I'm leaning towards merging this without a release.rst? But up to you @Zac-HD!
> Properly clamp signed zeroes

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/_hypothesis_pytestplugin.py
- hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py
- hypothesis-python/src/hypothesis/internal/floats.py
- hypothesis-python/src/hypothesis/strategies/_internal/utils.py
- hypothesis-python/tests/conjecture/test_junkdrawer.py
- hypothesis-python/tests/cover/test_float_utils.py
- hypothesis-python/tests/nocover/test_strategy_state.py
- hypothesis-python/tests/pytest/test_collection_warning.py
Closes #4200 on our side; I'll also open a Pytest issue for their crash-on-deleted-dir race condition.
> warn on suspicious pytest-collection of `.hypothesis` directory

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/tests/conjecture/test_shrinker.py
- hypothesis-python/tests/conjecture/test_test_data.py
- hypothesis-python/tests/quality/test_shrink_quality.py
> `lower_blocks_together` -> `lower_integers_together`

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/control.py
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/internal/conjecture/choice.py
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py
- hypothesis-python/src/hypothesis/internal/conjecture/pareto.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/conjecture/common.py
- hypothesis-python/tests/conjecture/test_alt_backend.py
- hypothesis-python/tests/conjecture/test_data_tree.py
- hypothesis-python/tests/conjecture/test_engine.py
- hypothesis-python/tests/conjecture/test_ir.py
- hypothesis-python/tests/conjecture/test_optimiser.py
- hypothesis-python/tests/conjecture/test_provider_contract.py
- hypothesis-python/tests/conjecture/test_shrinker.py
- hypothesis-python/tests/conjecture/test_test_data.py
- hypothesis-python/tests/cover/test_database_backend.py
- hypothesis-python/tests/cover/test_reproduce_failure.py
- hypothesis-python/tests/nocover/test_conjecture_engine.py
- hypothesis-python/tests/nocover/test_precise_shrinking.py
- hypothesis-python/tests/quality/test_poisoned_trees.py
Still need to rename `ir_type` -> `choice_type`. Will do that in a future pull since that's a bigger change.
> Clean up some IR names

- .github/workflows/main.yml
- hypothesis-python/tox.ini
- tooling/scripts/ensure-python.sh
See https://github.com/HypothesisWorks/hypothesis/issues/4028, closes #4236.
> Enable CI jobs for free-threading mode and also python 3.14

- hypothesis-python/tests/nocover/test_conjecture_utils.py
Closes https://github.com/HypothesisWorks/hypothesis/issues/4280.  Wasn't blocking us but sure, it's easy to get working.
> Get test working on older Python

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/pandas/impl.py
- hypothesis-python/tests/pandas/test_argument_validation.py
thanks to #4291 🎊 
(and my sympathies to everyone else learning about latent bugs!)
> handle overflow in validation

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/changes.rst
- hypothesis-python/src/hypothesis/strategies/_internal/random.py
- hypothesis-python/tests/cover/test_randoms.py
Closes #4297, with some cleanup along the way.
And also fixes formatting in some old changelog entries, which I was reading through recently.
> fix bounds of `ArtificialRandom`

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/conjecture/test_alt_backend.py
- hypothesis-python/tests/conjecture/test_engine.py
- hypothesis-python/tests/crosshair/test_crosshair.py
Split from https://github.com/HypothesisWorks/hypothesis/pull/4034#issuecomment-2744965203
> Fix symbolic realization on fatal error

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/extra/ghostwriter.py
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/src/hypothesis/internal/conjecture/pareto.py
- hypothesis-python/src/hypothesis/internal/reflection.py
- hypothesis-python/src/hypothesis/strategies/_internal/core.py
- hypothesis-python/src/hypothesis/strategies/_internal/flatmapped.py
- hypothesis-python/src/hypothesis/strategies/_internal/numbers.py
- hypothesis-python/src/hypothesis/strategies/_internal/random.py
- hypothesis-python/src/hypothesis/strategies/_internal/shared.py
- hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
- hypothesis-python/src/hypothesis/strategies/_internal/strings.py
- whole_repo_tests/revealed_types.py
I don't think any of these changes are public-facing.
> Add more type hints

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/conf.py
- hypothesis-python/docs/redirect.html.template
- hypothesis-python/src/hypothesis/internal/healthcheck.py
- website/content/2018-01-08-smarkets.md
Closes https://github.com/HypothesisWorks/hypothesis/issues/4330, and improves general hash redirection.
> Add settings redirect and update health check link

- hypothesis-python/docs/strategies.rst
Add reference for [hypothesis-torch](https://hypothesis-torch.readthedocs.io/en/latest/)
> Update strategies.rst to include hypothesis-torch

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/choice.py
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/datatree.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py
- hypothesis-python/src/hypothesis/internal/conjecture/providers.py
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/src/hypothesis/internal/filtering.py
- hypothesis-python/src/hypothesis/strategies/_internal/collections.py
- hypothesis-python/src/hypothesis/strategies/_internal/numbers.py
- hypothesis-python/tests/conjecture/common.py
- hypothesis-python/tests/conjecture/test_alt_backend.py
- hypothesis-python/tests/conjecture/test_data_tree.py
- hypothesis-python/tests/conjecture/test_engine.py
- hypothesis-python/tests/conjecture/test_float_encoding.py
- hypothesis-python/tests/conjecture/test_forced.py
- hypothesis-python/tests/conjecture/test_ir.py
- hypothesis-python/tests/conjecture/test_optimiser.py
- hypothesis-python/tests/conjecture/test_provider_contract.py
- hypothesis-python/tests/conjecture/test_shrinker.py
- hypothesis-python/tests/conjecture/test_test_data.py
- hypothesis-python/tests/cover/test_float_utils.py
- hypothesis-python/tests/crosshair/test_crosshair.py
- hypothesis-python/tests/quality/test_poisoned_trees.py
Ref #4166, renames `kwargs` to `constraints`
> Rename ChoiceNode.kwargs to ChoiceNode.constraints

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
- hypothesis-python/src/hypothesis/strategies/_internal/lazy.py
- hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
- hypothesis-python/tests/nocover/test_labels.py
- hypothesis-python/tests/nocover/test_regressions.py
> Use `strategy.label` for `sampled_from` label

- requirements/crosshair.in
- requirements/crosshair.txt
Let's see how CI for this shakes out
> Unpin crosshair

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/internal/conjecture/engine.py
- hypothesis-python/tests/conjecture/test_alt_backend.py
Closes https://github.com/pschanely/hypothesis-crosshair/issues/31
> Dont report failure --> verified as unsound

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/conf.py
- hypothesis-python/docs/reference/api.rst
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/src/hypothesis/control.py
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/database.py
- hypothesis-python/src/hypothesis/internal/conjecture/providers.py
- hypothesis-python/src/hypothesis/internal/constants_ast.py
Also skips files over 200kb.
See https://github.com/HypothesisWorks/hypothesis/pull/4366#issuecomment-2877081864 (cc @zjmlianxi, and thanks for the great benchmarks!)
I have not verified/benchmarked this yet.
> Faster AST collection set union

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/changelog.rst
- hypothesis-python/docs/compatibility.rst
- hypothesis-python/docs/conf.py
- hypothesis-python/docs/how-to/suppress-healthchecks.rst
- hypothesis-python/docs/reference/api.rst
- hypothesis-python/docs/reference/integrations.rst
- hypothesis-python/docs/tutorial/settings.rst
- hypothesis-python/src/hypothesis/_settings.py
- hypothesis-python/src/hypothesis/control.py
- hypothesis-python/src/hypothesis/strategies/_internal/core.py
preview: https://hypothesis--4405.org.readthedocs.build/en/4405/
> Refactor settings docs

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/src/hypothesis/extra/django/_impl.py
- hypothesis-python/src/hypothesis/extra/ghostwriter.py
- hypothesis-python/src/hypothesis/internal/compat.py
- hypothesis-python/src/hypothesis/internal/conjecture/choice.py
- hypothesis-python/src/hypothesis/internal/conjecture/data.py
- hypothesis-python/src/hypothesis/internal/conjecture/datatree.py
- hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py
- hypothesis-python/src/hypothesis/internal/conjecture/pareto.py
- hypothesis-python/src/hypothesis/internal/observability.py
- hypothesis-python/src/hypothesis/internal/reflection.py
- hypothesis-python/src/hypothesis/strategies/_internal/attrs.py
- hypothesis-python/src/hypothesis/strategies/_internal/core.py
- hypothesis-python/tests/conjecture/test_pareto.py
- requirements/tools.in
- requirements/tools.txt
Every time I get on a plane, I seem to want to make typing changes 😄
> Add more internal type hints

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/conjecture/providers.py
- hypothesis-python/tests/conjecture/test_alt_backend.py
(cc @pschanely, though this isn't actually called anywhere yet. That'll come Hypofuzz-side in the future).
> Add `PrimitiveProvider.replay_choices`

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies/_internal/utils.py
- hypothesis-python/tests/cover/test_compat.py
- hypothesis-python/tests/cover/test_searchstrategy.py
> Support `to_json` in nested dataclasses

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/database.py
As seen in hypofuzz CI: https://github.com/Zac-HD/hypofuzz/actions/runs/15658648133/job/44113126765?pr=145#step:5:149
> Fix rare db race condition

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/tests/pytest/test__pytest.py
closes https://github.com/HypothesisWorks/hypothesis/issues/4446
> Fix conditional `_pytest` imports

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/tests/nocover/test_threading.py
Part of https://github.com/HypothesisWorks/hypothesis/issues/4451.
> Fix thread safety of `@rule` definitions

- hypothesis-python/RELEASE.rst
- hypothesis-python/docs/prolog.rst
- hypothesis-python/src/hypothesis/stateful.py
- hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
- hypothesis-python/tests/common/__init__.py
Part of https://github.com/HypothesisWorks/hypothesis/issues/4451
> Fix a race in `@initialize`

- website/theme/static/style.css
After this, the website is good to deploy on my end 👍 
to build: `./build.sh live-website`
> Tweak website styling

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/core.py
- hypothesis-python/tests/crosshair/test_crosshair.py
See https://github.com/HypothesisWorks/hypothesis/pull/4489#discussion_r2253116743
> Realize `data.events` in solver-based backends

- website/content/2018-01-08-smarkets.md
- website/content/2025-08-07-thread-safe.md
- website/theme/static/style.css
- website/theme/templates/article-card.html
Part of https://github.com/HypothesisWorks/hypothesis/issues/4451. 
(@ngoldbaum I mention you by name here, so it seems only fair to give you a courtesy ping!)
> Add "Hypothesis is now thread-safe" blog post

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/strategies/_internal/deferred.py
- hypothesis-python/tests/conjecture/test_shrinker.py
Closes https://github.com/HypothesisWorks/hypothesis/issues/4523.
> Fix a race condition in `DeferredStrategy.wrapped_strategy`

- hypothesis-python/RELEASE.rst
- hypothesis-python/src/hypothesis/internal/lambda_sources.py
- hypothesis-python/tests/cover/test_reflection.py
> Fix typo in _function_key
